### ISSUE TITLE
Create Documentation for monorepo

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#10]
The monorepo architecture is different to the original project. So documentation will be needed to make it clear how to use it.

**Comment by IanMayo** [comment]
@foxleigh81 - would wiki-pages be a suitable placeholder for the documentation?

https://github.com/serge-web/serge-web/wiki

**Comment by foxleigh81** [comment]
It's certainly not a problem for me to maintain a wiki and I agree that a knowledge base is very useful but I'd also want to ensure that vital 'getting started' documentation was captured in a README.md file in the root.

**Comment by IanMayo** [comment]
Done.
