### ISSUE TITLE
Country not shown for some regions

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1036]
Note: this issue can be reproduced by entering the `Papa Foxtrot` game as `Blue Senior`, going into the `Blue COAs` channel, and creating a new COA document.

We're using JSON-Schema `dependencies` to make one drop-down control dependent upon the value of another.

But, this is breaking when we edit an existing document:
![screencast](https://i.gyazo.com/01efa0c1d029b276bf6cfd47027441b8.gif)

It works fine for new documents:
![screencast 2](https://i.gyazo.com/99b8c0adbff6544fd9ed08aea1a52eae.gif)

Aah, note how the control moves to the right for some values.  That _may_ be down to the length of the USA country name. Will experiment.

Note: resizing the browser window makes the missing control appear:
![screencast 3](https://i.gyazo.com/6701e02da08de7703dcdc13829a18507.gif)

**Comment by lebaphi** [comment]
Hi @IanMayo, It seems the dropdown works well on my machine
https://user-images.githubusercontent.com/26705621/131655966-aaed414d-8790-43ad-b4fa-ea802cd8d7bd.mov
So this form was generate by the JSON Editor load the schema 
```
createEditor(schema)
```

sample schema 
```
LOCATION: {
          title: "*Location of activities in this turn",
          type: "object",
          properties: {
            region: {
              title: "Region",
              type: "string",
              enum: [
                "Asia Pacific",
                "Europe",
                "Americas"
              ],
              default: "Europe"
            },
            Europe: {
              title: "Country",
              type: "string",
              enum: [
                "United Kingdom",
                "Germany"
              ],
              options: {
                dependencies: {
                  region: "Europe"
                }
              }
            },
            Americas: {
              title: "Country",
              type: "string",
              enum: [
                "United State of America",
                "Brazil"
              ],
              options: {
                dependencies: {
                  region: "Americas"
                }
              }
            },
            AsiaPacific: {
              title: "Country",
              type: "string",
              enum: [
                "India",
                "China"
              ],
              options: {
                dependencies: {
                  region: "Asia Pacific"
                }
              }
            }
          }
        },
```
So can you check your schema if it matches with the schema above ?

**Comment by IanMayo** [comment]
Yes, it works when creating a new document. But, it doesn't work when editing one.

So, you will `Submit` the one you're looking at.  It will collapse. Then you will `Claim` it, and it will collapse again.  Then, you can edit the existing document - and you should see the second drop-down disappears until the window is resized.
