### ISSUE TITLE
Need flag to assign a role as `Game Control` able to step forward

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1062]
We have an `isGameControl` flag in the wargame to show which role can move the game forward.

We can't set this from the admin pages. It's `probably` another toggle on `roles`.

**Comment by IanMayo** [comment]
It's this property that we need to control:
![image](https://user-images.githubusercontent.com/1108513/132012919-acea20fe-b5df-45aa-8b77-aa5f70733537.png)

I propose we only show the toggle for roles if force has `isUmpire` ticked.

**Comment by IanMayo** [comment]
As a first step for this, we should manually insert the value for `Game Control` on `EXCON` - directly into the database

**Comment by sanjayradadiya** [comment]
> We have an `umpire` flag in the wargame to show which role can move the game forward.
> 
> We can't set this from the admin pages. It's `probably` another toggle on `roles`.

Confirm few things.
1. umpire flag no changes required for existing? or Should i remove it and move to point no. 2?
2. new umpire flag with each role which is mentioned in attachment and it will store in database.

![image](https://user-images.githubusercontent.com/16476120/132641563-1e5eb648-eb97-467b-8ff7-4f3e4724db8f.png)

**Comment by sanjayradadiya** [comment]
> As a first step for this, we should manually insert the value for `Game Control` on `EXCON` - directly into the database

isUmpire flag should be set from database for  Role `Game Control` on force `EXCON`?

**Comment by sanjayradadiya** [comment]
> It's this property that we need to control:
> ![image](https://user-images.githubusercontent.com/1108513/132012919-acea20fe-b5df-45aa-8b77-aa5f70733537.png)
> 
> I propose we only show the toggle for roles if force has `isUmpire` ticked.

this for toggle should be display only if role has isUmpire flag set.
![image](https://user-images.githubusercontent.com/16476120/132642378-1266238a-3b89-4cd2-886e-5ed677223c97.png)

**Comment by IanMayo** [comment]
Sorry if it's confusing @sanjayradadiya 

Correct - the boolean is `isGameControl`, not `umpire` - my mistake.  So we need to add a `Game Control` toggle to the `Role` if the current force has `isUmpire` ticked.

I suggest you use the `control-tower` icon from Font-Awesome, with a tooltip of `Game Control`.

**Comment by IanMayo** [comment]
> only if role has isUmpire flag set.

no, only if `force` has `isUmpire` flag set:

![image](https://user-images.githubusercontent.com/1108513/132653780-9b21db1d-d7c3-4e72-a20d-8b8e3dd2f021.png)

**Comment by IanMayo** [comment]
@sanjayradadiya  - could you update me on where you've got with this, please?
