### ISSUE TITLE
Region of chat channel not visible

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1111]
I'm playing as a White Force player who can see Blue Chat, but is not a member of it.

The period at the bottom of the channel is empty.

Steps to reproduce:
* log in as blue player
* create 6 chat message in Blue Chat
* log in as White force player
* examine Blue Chat channel - see space at bottom of channel

![image](https://user-images.githubusercontent.com/1108513/132519949-03edf349-4799-472e-ae39-022c0ea2a6bd.png)

Note: the missing area is the same dimensions as the chat controls:
![image](https://user-images.githubusercontent.com/1108513/132521408-6810b71b-3838-4aa5-9f05-10c38f4f5b0f.png)

I've just realised that as a non-member of a channel (White viewing Blue RFI), there is a missing space at the bottom of the column where the `New message` button would be:
![image](https://user-images.githubusercontent.com/1108513/132524394-c05380ac-4c16-4fca-ac6a-340506edbf40.png)

**Comment by lebaphi** [comment]
Hi @IanMayo, I found the root cause that make the chat region invisible:

`client/src/Components/ChatChannel.tsx`
```
        state.channels[channelId].observing === false &&
        <div className="new-message-creator wrap new-message-orderable" ref={chatMessageRef}>
          <div className="chat-message-container">
            <ChatEntryForm turnNumber={state.currentTurn} from={selectedForce} isUmpire={!!isUmpire} channel={channelId} role={state.selectedRole} roleName={state.selectedRoleName} postBack={messageHandler} />
          </div>
        </div>
```
in your case, the `state.channels[channelId].observing  = true` so the `ChatEntryForm` does not render. I'm not sure if it is right business 🤔

**Comment by IanMayo** [comment]
Yeah - player that is "observing" a channel can view the content, but not write messages into it.

But, in the above it's checking for `not observing`. 

It isn't an issue that the chat region is invisible. It's an issue that the space is still allocated to it.  See how the scroll bar only covers ~ 2/3 of the height of the channel.

**Comment by lebaphi** [comment]
Ahh, I see this issue is the scrollbar here, the chat area height should be full of the page, right?
![image](https://user-images.githubusercontent.com/26705621/133072439-64449dae-ffc2-4482-aa32-57a2e336cf45.png)

**Comment by IanMayo** [comment]
Yes.  In this instance, if the full height was available, we may not even need the scroll bar.

**Comment by lebaphi** [comment]
Hi @IanMayo , I think the space at the bottom is still there 🤔 
https://user-images.githubusercontent.com/26705621/133100174-5c6d709a-fee1-48c7-812c-d5173fefe8de.mov

**Comment by lebaphi** [comment]
Hi @IanMayo , for this one
```
I've just realised that as a non-member of a channel (White viewing Blue RFI), there is a missing space at the bottom of the column where the New message button would be:
```
if a non-member of the channel, the bottom should have more space where the new message would be, something like:

<img width="771" alt="Screen Shot 2021-09-13 at 9 34 45 PM" src="https://user-images.githubusercontent.com/26705621/133103245-516fb13f-361c-4f03-a62a-8358e547e539.png">

**Comment by IanMayo** [comment]
I don't think this applies to the COA or RFI channels.

Correct - if a non-member, the messages in the channel should occupy the full height. Space shouldn't be reserved for a component that isn't visible.
