### ISSUE TITLE
Force role name update create undefined

### ISSUE THREAD

**Issue by sanjayradadiya** [serge-web/serge#1144]
## 🐞 Bug description

Create Wargame > Select Force > Roles > Add Role > Select Role name > Press Delete button > Role name will be undefined

## 🖥️ Screenshots

https://user-images.githubusercontent.com/16476120/133719804-256516d0-328d-40f9-91e9-d488f3d58083.mov

## 💻 System information

 - Operating System: [e.g. iOS, Windows, etc...]
 - Browser Version [e.g. 22]
 - Browser resolution 
 - Are cookies enabled
 - Is Javascript enabled
 - Do you have an ad blocker

**Comment by IanMayo** [comment]
I _think_ it's a bug that it goes to `undefined`.  A user shouldn't see that.
