### ISSUE TITLE
As Game Control I wish all users to be using current version of Serve to ensure fixes present

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1180]
For one wargame, users are playing from Virtual Machines.

The game lasts several months, and the VMs can stay alive between turns.

Yesterday I encountered a user playing Serve version dated 24th Sept. He experienced an issue that I know was fixed on the release dated 29th Sept.  I know an F5 refresh would update his version of Serge.

This is an enduring issue that may hurt us/them in the future.

One potential solution to this is for the server to reply to heartbeat with the current version. If this is newer than the client version, then a dialog can open to ask the user to refresh.

For this to happen we'd require the build version in both the server (node) code and the client code. We're currently not incrementing the version on updates - just the build date.

The build date comes from this client-side code:
![image](https://user-images.githubusercontent.com/1108513/137897366-adebad45-9163-4d5c-87e0-db8f8a659932.png)

There is a chance that use of that code could produce different times if separately declared in `client` package build vs `server` package build steps.  So, the code needs to go into a single central repository. Maybe in `config` package?

We do have a challenge here.  The issue this week was with an old copy of Serge.  If we add this feature, these old copies of Serge will not know how to handle the version (build) data coming back from the server.

So, I propose this modification:
- change the URL used for heartbeat
- updated server won't reply to old URL. Clients will show error. They will be advised to refresh
- server will return build version from new URL

Note: I don't necessarily think this is an opportunity to move forward the `last-interaction` logic at #910

**Comment by lebaphi** [comment]
Hi @IanMayo, let me sort things out a bit:
- Change the API `/healthcheck` to `/health_check` => make the old Serge call pingServer fails
- The new API `/health_check` will return the current version which defined in the `.env` file

=> If we apply this feature, the server won't reply on the old `healthcheck` api, yes. And the client will show an error, they will be advised to refresh.

- In the new client code we'll do a little update, comparing the current version and the one coming back from the `/health_check`. If they are different, we will display an error and advise the user to refresh.

So what do you think?

**Comment by IanMayo** [comment]
We have some build issues related to this issue. The Serge version number is in multiple locations in the repo, and our release process doesn't include a step to increment the build version.

I'm going to re-assign it to @lilitkarapetyan , since she has more familiarity with the repo build structure.

**Comment by IanMayo** [comment]
This problem _Should_ go away once we move to monolith #1720
