### ISSUE TITLE
Collab editing channels - lock headers

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1184]
In the new collab-editing channels, the whole channel scrolls. This means the headings disappear, and that the user has to scroll back to the top to change a filter.

Just the list of messages should scroll.

**Comment by lebaphi** [comment]
Hi @IanMayo, so do we hold these items and do some tests with the new table, right?

**Comment by IanMayo** [comment]
yes please. it should be easier with the new component.

**Comment by lebaphi** [comment]
Can we close it since we support new table? @IanMayo
