### ISSUE TITLE
Collab edit channel filters - regenerate

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1186]
We have some collab editing channels that have filters.

The filters are generated from the list of unique values in that column.

I have 8 values for the "From" column.  I can apply a filter for "Status" to just display "Closed".  The displayed messages just come from 2 sources. So, the "From" column filter should just show these two values.

We can apply a filter on one column that reduces the number of messages shown.  When this happens, I believe we should regenerate the other lists of filters - to only show filter values for messages that are present.

**Comment by lebaphi** [comment]
Can we close it since we support new table? @IanMayo
