### ISSUE TITLE
Consider alternative table component

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1199]
The table component we use for Collaborative-Editing does a lot of hard work.

Before we extend the component, or implement fixes, I'd like us to pause & see if there is an off-the-shelf open source component that we could/short be using instead.

I guess we have these requirements:
1. able to host a collapsible child elements
2. Dynamic filtering based on column contents
3. Sortable columns
4. Responsive (to handle changing page width)
5. Fixed headers (that stay visible as user scrolls down long table)

Ideally we'd also have these featuers:
1. search/filter interface to find specific entry
2. show/hide columns
3. indicate low priority columns that get hidden as horizontal space reduces

**Comment by lebaphi** [comment]
Hi @IanMayo , after do some investigation, I think the table https://www.npmjs.com/package/react-data-table-component is best suite for your requirement. I created an example here https://codesandbox.io/s/condescending-cookies-wmlmf?file=/src/App.js.

```
I guess we have these requirements:

- Able to host a collapsible child elements: yes
- Dynamic filtering based on column contents: yes
- Sortable columns: yes
- Responsive (to handle changing page width): yes
- Fixed headers (that stay visible as user scrolls down long table): yes

Ideally we'd also have these featuers:

- Search/filter interface to find specific entry: yes, we can custom the sort function
- Show/hide columns: yes
- indicate low priority columns that get hidden as horizontal space reduces: yes
```

**Comment by lebaphi** [comment]
https://user-images.githubusercontent.com/26705621/140481635-49daaec5-395b-4d76-b581-de0adcd6049f.mov
