### ISSUE TITLE
Unread message count works incorrectly 

### ISSUE THREAD

**Issue by lebaphi** [serge-web/serge#1204]

**Comment by IanMayo** [comment]
Hello @lebaphi  - I've had a separate report for issues with the unread message count. 

Could you provide a description of what the issue is here? Then we'll know if it's a duplicate or not.  Thanks :-)

**Comment by lebaphi** [comment]
Hi @IanMayo , this issue is when we expand message in the table, the unread message count on the header minus one, but it's just a counter variable, not calculated by the total number of unread messages of the channel, refresh page the variable's value will become to the initial value, also the flag `hasBeenRead` of read message is still false.
![image](https://user-images.githubusercontent.com/26705621/142873504-37d03876-999b-45ae-a36d-548e768b11ca.png)
![image](https://user-images.githubusercontent.com/26705621/142873526-8c39580c-0a9f-4aef-b4f8-7a90379c02f9.png)
