### ISSUE TITLE
Font Size and Type Uniformity

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1215]
Throughout many pages and windows of the game, the font size and type are somewhat inconsistent. It would be nice to have font uniformity through the different pages and windows.

Here's an example of different sizes of fonts in the same window:
![Different Size-Type Fonts](https://user-images.githubusercontent.com/85491794/142914506-d9859c37-c791-430a-929f-650ca53aac4a.png)

**Comment by IanMayo** [comment]
We have `Mark all as read` in 2 different font-sizes.  I don't really mind which size we use - but they should be the same size.  The left-hand window is probably "BLUE COA".

**Comment by ShendMikullovci** [comment]
I agree. I suggest we use a slightly smaller font size than that of the "Mark all as read" on the right-hand side of the screenshot. Capitalization is great for visibility but with all the notifications and messages that will be filling up the screen, maybe it would be smoother to not have everything capitalized. 

Should I play around with some designs to see how it all looks?

**Comment by IanMayo** [comment]
@ShendMikullovci - could we go for a quick size decision, and defer the deeper analysis for the future please? I'll create a future [task](https://github.com/serge-web/serge/issues/1238) for you to investigate/consider use of fonts & font-case in Serge UI.   I'll label tasks like that as "UX - low priority", and you can work on them if/when there is nothing higher priority to do.

**Comment by ShendMikullovci** [comment]
Great. I'll go through Serge screens and collect the different font sizes and see if I can come with a mean size.

**Comment by ShendMikullovci** [comment]
I went through some of the pages of Serge. All of them have a variety of font types and sizes. 
Bold fonts should be used for titles and headers (also potentially important info in-screen, we'll see along the way).
The font I suggest we use is the following: 
![Font to Use](https://user-images.githubusercontent.com/85491794/145615300-cfd36f53-489f-49a2-820e-eba63560d3a8.png)

I would also suggest that "Show archived" and both "Mark all read" buttons (one of them is Mark All As Read and the other is Mark All Read; I suggest both should be Mark All Read) be grey. They're not crucial to gameplay and don't need to take up attentional resources. We could use the grey from the "Filter Data" tab: 
![Grey font](https://user-images.githubusercontent.com/85491794/145615683-71f7dd88-d255-4299-b744-597234ffd8da.png)

Finally, if we stick to a thin grey font, we could capitalize it all. The idea here is that the size of the font isn't superior to the channel font and that the color doesn't take up attentional resources.

**Comment by lebaphi** [comment]
Hi @IanMayo and @ShendMikullovci , I will update when you have a size decision 😄

**Comment by ShendMikullovci** [comment]
Hi guys!
I was unable to identify the size of the "MARK ALL READ" font through "inspect element". Are you guys able to look at the code directly and find out the exact size? Sorry for the trouble.

**Comment by lebaphi** [comment]
Hi @ShendMikullovci , here they are :D

<img width="269" alt="Screen Shot 2021-12-14 at 2 05 52 PM" src="https://user-images.githubusercontent.com/26705621/145949468-c970abcc-761f-4762-9b9e-bf913c165ac3.png">
 
<img width="269" alt="Screen Shot 2021-12-14 at 2 05 44 PM" src="https://user-images.githubusercontent.com/26705621/145949457-9dcd2c4f-c2b4-4dca-8be6-94fa972fea1f.png">

**Comment by IanMayo** [comment]
Hello @lebaphi - could you give @ShendMikullovci & me a quick lesson?  What tool did you use to get that extra data?

@ShendMikullovci - do you have a preferred font size?

**Comment by lebaphi** [comment]
> Hello @lebaphi - could you give @ShendMikullovci & me a quick lesson? What tool did you use to get that extra data?
> 
> @ShendMikullovci - do you have a preferred font size?

Hi @IanMayo, I just use the Chrome Dev Tool and inspect the element. When hover the mouse on the text, a small popup will appear as the screenshot above :D

**Comment by ShendMikullovci** [comment]
Hi guys! Thanks @lebaphi !
You can go ahead and use the 12px font size you found here:

<img width="269" alt="Font to Use" src="https://user-images.githubusercontent.com/85491794/146351558-90537222-8151-42a0-96ab-a30473dba9bd.png">

If you could switch it to the grey color used for the "filter data" text as well that'd be great!

**Comment by lebaphi** [comment]
okay @ShendMikullovci 👍

**Comment by ShendMikullovci** [comment]
12px has been implemented.
