### ISSUE TITLE
Browser Pop-up to be replaced

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1216]
In [this bug](https://github.com/serge-web/serge/issues/1207#issue-1060018927), I noticed that when I click on the delete button, a browser pop-up asking if I am sure I want to delete appears:

![Browser Pop-Up](https://user-images.githubusercontent.com/85491794/142915442-0015e0f6-fc0e-4ba7-a29d-a6d888eb9024.png)

It would be better if the pop-up was in-game rather than a browser pop-up. We could use the same model of the pop-up we get in the admin page when we try to delete a channel: 

![In-game delete pop-up](https://user-images.githubusercontent.com/85491794/142915558-d41a0e30-d3b2-480e-86e1-72a28fe4fec5.png)

**Comment by lebaphi** [comment]
Yep, I've seen this before, I'm not sure we can replace it since it's a builtin method in the JSON Editor library and it runs synchronously. If we want to make it work with react modal, it should be run asynchronously because it has to wait until react modal closes to get the result.
![image](https://user-images.githubusercontent.com/26705621/145424614-7583bd27-aba7-4fa8-ae8c-7f2b7a0bf828.png)

**Comment by IanMayo** [comment]
What @lebaphi was saying to @ShendMikullovci  was that it's hard to replace the form-based editor popup with our own.

But, there are two kinds of delete.
1. Shend's first screenshot is deleting a country name from a Course-of-Action
2. Shend's second screenshot is deleting a channel from the Game Admin pages.

In case (1) we can't change the popup. But, it's a very low risk delete operation.  Not a lot of effort will have been invested in adding the country.  I propose we config the editor to not display a warning before deleting a country.

In case (2) there is an investment in effort in creating the channel, so it's right to display a confirmation. Fortunately, in that location we are able to display a Serge-flavoured one.

@ShendMikullovci - do you think it's ok to remove the delete warning for array (list) elements in the form-based editor?

If one day we realise forms have got so complex that there could be lost effort in deleting an array item - then I suggest at that point we offer a fix to the JSON-Editor team, to allow their popup to be over-ridden.

**Comment by ShendMikullovci** [comment]
In that case, removing the browser pop-up entirely would work as well. You're right, adding a country is low risk and low effort operationally. Shouldn't have huge cognitive costs. The only worry with removing the pop-up would be the case where the button is accidentally clicked on and the user didn't see what they deleted (low probability of happening really, but in a loaded screen it's not impossible).

I say we go with it and follow up if the issue comes up later.

**Comment by IanMayo** [comment]
Great. In that case, @lebaphi - could you configure the editor to not show the delete warning please?
![image](https://user-images.githubusercontent.com/1108513/145431958-1a3e7bdf-290b-48b3-8b6e-ebd67a799c30.png)

**Comment by lebaphi** [comment]
okay @IanMayo 👍
