### ISSUE TITLE
Can't delete Platform from the Admin Page

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1246]
There's no delete button once a user creates a platform on the admin page.
![Can't delete platform](https://user-images.githubusercontent.com/85491794/145621384-db746e1f-af2c-496f-8a69-809ffcc99499.png)

I would assume it's important to be able to delete a platform from the game if necessary.

I suggest we stick to feature we use the channel delete feature (next to the channel title there's a delete button next to the duplicate button): 
![Channel Delete Feature](https://user-images.githubusercontent.com/85491794/145621693-63db252f-a998-4ff1-9e80-bdf8289d7e78.png)

Let me know what you all think.

**Comment by IanMayo** [comment]
Yes, good plan, thanks.
