### ISSUE TITLE
Redundant Delete Button

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1247]
In the Forces tab of the Admin Page, there are 2 Delete buttons. A little redundant:
![Forces delete feature](https://user-images.githubusercontent.com/85491794/145621824-a0af96d1-3468-414c-8fb0-deed8e2425ef.png)

I suggest we use the channel delete feature only:
![Channel Delete Feature](https://user-images.githubusercontent.com/85491794/145621866-afa106c3-c220-4925-9cb7-1a0924d17acc.png)

**Comment by IanMayo** [comment]
Good recommendation, thanks @ShendMikullovci

**Comment by lebaphi** [comment]
So let me confirm that we will remove this `Delete` button right?
<img width="1362" alt="Screen Shot 2021-12-16 at 9 08 36 PM" src="https://user-images.githubusercontent.com/26705621/146387197-3818d210-faf6-4c83-8c8e-6dd8d2ce5dd2.png">

**Comment by IanMayo** [comment]
Yes.   I understand your desire to double-check 🤣

**Comment by ShendMikullovci** [comment]
Yes, absolutely! Sorry for not communicating it better.
