### ISSUE TITLE
Delete Forces button doesn't work

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1249]
I created a new Force on the admin page. Clicked on the Delete Button in the force window and nothing happened.
![Delete Button didn't work](https://user-images.githubusercontent.com/85491794/145622753-d0e9cfa4-7e41-43d9-b9c0-c1d3ddb3bc75.png)

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci 

I propose we drop this issue, since we intend to remove the `Delete` button.

**Comment by ShendMikullovci** [comment]
I agree.
