### ISSUE TITLE
Data Table Name Uniformity

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1254]
It'd be nice to have player name uniformity for the data table. I noticed that for Senior Blue's COAs, their name is shown in 2 different ways in the data table, namely as "Senior Blue" under "From" and "BLUE-SENIOR B" under "Owner". 
![Data Tables Name Uniformity](https://user-images.githubusercontent.com/85491794/145800055-74db8b00-6fe9-4f1e-b5eb-62823447ffad.png)

I suggest we stick to "Senior Blue" for both cases. As you can see there's also a difference in font size between these two names. It'd be nice for the font size to be the same for both.

**Comment by IanMayo** [comment]
Yes - sure.  Thanks @ShendMikullovci . I'll take this one :-)

**Comment by ShendMikullovci** [comment]
This has been fixed.
