### ISSUE TITLE
Data Table Center Text

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1256]
The text within the first row of cells of the data table is not in the centered: 
![Data Tables Center Text](https://user-images.githubusercontent.com/85491794/145802748-922e3329-64f1-4c0f-bcae-ed6ec472b4cf.png)
 
It would be better to center it and align it with the data that it represents.

**Comment by IanMayo** [comment]
Sure. Nice improvement. But, for now I'll leave it unassigned as we concentrate on functional improvements.

**Comment by ShendMikullovci** [comment]
This has been fixed.
