### ISSUE TITLE
Unresponsive Chat Notification Counter

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1257]
The BLUE Chat notification counter is unresponsive. 
![Unresponsive Chat Notification Counter](https://user-images.githubusercontent.com/85491794/145830886-4c26a2cf-a46e-46e5-8294-d0417767b9d5.png)

Given that BLUE Chat is a channel presenting chat messages between the team, it would be nice to follow consensus and have the notifications disappear when the user clicks on the channel to view the messages.

The notifications disappear only when I click on "MARK ALL READ":
![Chat Notification Counter Responded after MARK ALL READ](https://user-images.githubusercontent.com/85491794/145832274-c838b0a7-cc6d-486e-be1d-942f7962bfd2.png)

**Comment by IanMayo** [comment]
Yes, @ShendMikullovci .  There isn't really the concept of marking a Chat message as read - since they don't expand/collapse.  A player indicating they're up to speed on the channel (by clicking `Mark all as Read` seems a valid solution.

Do you picture something else happening?

**Comment by ShendMikullovci** [comment]
I suggest the notification goes away as soon as the player clicks on the "Blue Chat" channel.

**Comment by IanMayo** [comment]
That's certainly one option.  But what if there is a more than a screenful of chat messages?  It _feels_ like someone monitoring a number of channels may pop into that tab to look for anything urgent, but only `Mark all as read` once they had gone through everything in detail.  But, I guess that's different users working in different ways.  IMHO it could cause a problem if accidentally opening a tab marks all the messages as read.

**Comment by ShendMikullovci** [comment]
That's very true. I'm O.K. with sticking to the Mark All Read button as long as the chat tabs are redesigned as suggested in issue #1258.

**Comment by IanMayo** [comment]
> That's very true. I'm O.K. with sticking to the Mark All Read button as long as the chat tabs are redesigned as suggested in issue #1258.

Sure, yes.
