### ISSUE TITLE
Chat Message UX

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1258]
This is our current chat message design:
![Chat Notification Counter Responded after MARK ALL READ](https://user-images.githubusercontent.com/85491794/145833778-5a7c243c-6256-4465-b0b5-272059c58568.png)

I was bug-checking the chat channels and noticed I instinctively thought the chat messages were clickable and could be interacted with. The mouse cursor changes to the clickable hand once I hover over them as well, yet they can't be clicked on. 
If it's our intention for them to remain unclickable, we should redesign them. The current design has a few small flaws as well.

First, the name of the message sender should be in the upper left corner to immediately attract attention. Currently, it sits under the chat text and given its highlighted icon, is somewhat confusing. 
The name icon also takes up valuable space within the chat window that could be used to convey a longer message. Placing the name on the upper left would solve this issue. 

The time the message is sent is currently shown in blue, and I worry it might attract attention as well. It would be better to have time be shown parallel to the name icon, on the far left-hand side of the message tab. Switching its color to grey eliminates the attentional grasp.  

Finally, the messages have a light blue outline on the right-hand side that makes them stand out from the background. The thickness of the outline led me to believe that the messages were clickable, and if it is our intention for them to remain unclickable, the outline would be better off a little thinner.

Here's a general idea: 
![Chat Message UX Design](https://user-images.githubusercontent.com/85491794/145835335-1851e21a-2d93-40d8-8a6c-b64d3c204894.png)

Let me know what you guys think.

**Comment by IanMayo** [comment]
They're all good changes, thanks @ShendMikullovci .

Could you implement the new design please @lebaphi 

I suggest you produce a solution in a StoryBook (and add `.inc` to the filename to ensure it gets built) so @ShendMikullovci can be shown different data permutations.

**Comment by ShendMikullovci** [comment]
A similar design has already been implemented.
