### ISSUE TITLE
Admin Page Step Cursor

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1259]
There's a cursor on the top right-hand side of the screen on the admin page that reacts to the user switching the pages:
![Step Cursor Admin Page](https://user-images.githubusercontent.com/85491794/145837791-c8c1274a-ef78-4e1a-b69b-82d7bd804666.png)

The "Platform Types" page is not included in the cursor. 

I also noticed that the "Forces" page is shown as a green icon on the cursor. Is there an explicit reason?

I suggest the green icon moves steps along with the pages as the user skips ahead.

**Comment by IanMayo** [comment]
Yes - good suggestion, thanks @ShendMikullovci

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , I just look into the code and found something:

> The "Platform Types" page is not included in the cursor.
<img width="355" alt="Screen Shot 2021-12-17 at 7 19 39 PM" src="https://user-images.githubusercontent.com/26705621/146543974-a6420e3f-be69-420f-9749-aa3c4accece7.png">

It's because the `wargame.data` has only 3 items, so I think the tab rendered should based on the size of the wargame data.

> I also noticed that the "Forces" page is shown as a green icon on the cursor. Is there an explicit reason?
<img width="507" alt="Screen Shot 2021-12-17 at 7 26 42 PM" src="https://user-images.githubusercontent.com/26705621/146544598-6832d914-404b-4953-96d0-05cee0c6fe2c.png">

As you can see here, each cursor we have 2 property: `active` and `complete`, so I think the green icon means `complete = true`.

How do you think?

**Comment by IanMayo** [comment]
Thanks for that @lebaphi 
I'm pretty sure we should create a default `PlatformTypes` object with a new wargame.

I'll look into it.

Yes - I agree that a green circle means there is data for that item.

**Comment by ShendMikullovci** [comment]
So, the green circle means the page has started to be filled in?

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I think the green circle means that page has sufficient data for a wargame.  But, that's a challenging test to define.  So, "page started" may be easier to define/implement.  So, we have at least one force, one channel, etc.

**Comment by ShendMikullovci** [comment]
I suggest adding another step in the cursor to include the "Forces" tab.

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , so what is the final decision for this item?

**Comment by IanMayo** [comment]
Yes, we should certainly add the 4th step to the process (my guess is that it will represent `platform types`).

We (or I) should come up with the logic to test if a tab is complete. i.e. Has enough detail to run a wargame.  I'll try to do that in here.

* **Overview**:  nothing required
* **Platform Types**:  none-required
* **Forces**: one required (note: the white/umpire force is created by default, which will make this "true")
* **Channels**:  none-required

Ok, so I don't think we have realistic tests for if a page is complete.  Maybe drop the "green" marker for a completed page @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
Yes, that sounds good. Is there a specific reason why we have selected green as the color to mark an incomplete page? Green usually has completion associations.

**Comment by IanMayo** [comment]
I _think_ the intention was that green represented a completed page.  But, since I don't think we can decide if a page is complete or not, I think we have to drop the highlight completely.

I'm quite happy to be corrected @ShendMikullovci  :-)

**Comment by ShendMikullovci** [comment]
> I _think_ the intention was that green represented a completed page. But, since I don't think we can decide if a page is complete or not, I think we have to drop the highlight completely.
> 
> I'm quite happy to be corrected @ShendMikullovci :-)

We might not be able to show a completed page, but we can show an incomplete one. If we still would like to show an incomplete page, we could show it as a red marker to attract attention. Once the page is completed, the red marker would disappear. As for orientation, we could have a thicker outline on the marker of the page the user is on (complete or not) to show where the user is among the pages.

**Comment by IanMayo** [comment]
Aah, that's a conundrum :-D. If we can't tell if a page is complete, I _don't think_ we can tell if a page is incomplete.

To be honest, I think we can remove the whole component.   We can't realistically measure progress through the process of creating a wargame there isn't much point in providing an illustration of it.  Or, do you think it still brings benefit @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
> Aah, that's a conundrum :-D. If we can't tell if a page is complete, I _don't think_ we can tell if a page is incomplete.
> 
> To be honest, I think we can remove the whole component. We can't realistically measure progress through the process of creating a wargame there isn't much point in providing an illustration of it. Or, do you think it still brings benefit @ShendMikullovci ?

Whatever you think is best. It's a rather low priority detail. Unless you think it could be a problem for an admin to get lost in data, I don't think it brings much benefit.

**Comment by IanMayo** [comment]
New action for @lebaphi :  **Delete the top-right progress cursor in admin pages**

**Comment by ShendMikullovci** [comment]
Only the green dot has been deleted, not the entire cursor. If we decide to maintain the cursor, I suggest we use a slightly bolder outline for the active steps.

**Comment by lebaphi** [comment]
Hi @IanMayo , @ShendMikullovci 
I just though if we need this progress indicator. I find we often use a progress indicator in a container or a carousel when there are many items and we don't know where we are, so we can see the indicator.

In our case this is the tab container and using it together with the progress indicator, is it superfluous?

https://user-images.githubusercontent.com/26705621/165267548-e1f01536-700a-490f-a9ad-980fa808f828.mp4

**Comment by IanMayo** [comment]
Hello @lebaphi - I don't think we need the progress indicator.  The Game Designer doesn't have to complete the pages in order, and for most of the pages, an empty page is "acceptable" for a wargame, particularly if the wargame is still being designed.

Let's delete the whole control, please.

**Comment by lebaphi** [comment]
> Hello @lebaphi - I don't think we need the progress indicator. The Game Designer doesn't have to complete the pages in order, and for most of the pages, an empty page is "acceptable" for a wargame, particularly if the wargame is still being designed.
> 
> Let's delete the whole control, please.

yep, I think we should remove this control too
