### ISSUE TITLE
Make Options Appear Clickable

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1261]
The force name, icon change tabs, and the color chart should be rendered to appear more clickable:
![Make appear clickable admin page](https://user-images.githubusercontent.com/85491794/145839420-4ef23949-749a-4fbb-b558-620d8fa967a6.png)
 
This could be done simply by underlining the force name and the "Change Icon". As for the color chart, its outline could be dimmed.

**Comment by IanMayo** [comment]
Great, yes.   Let's have underlines please @lebaphi

**Comment by lebaphi** [comment]
[Ian moved comment to PR]
