### ISSUE TITLE
Unresponsive Blue & SME Chat Channel

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1299]
I was reviewing the playable version of the new collab editor and noticed the Blue & SME Chat Channel seemed to be unresponsive?

![Unresponsive BLUE SME chat](https://user-images.githubusercontent.com/85491794/149389958-ad9273ec-4e79-4a5e-b6c2-3ce7917e43e9.png)

There's a notification appearing on the tab yet nothing inside the channel. And the NEW MESSAGE button doesn't appear.

**Comment by IanMayo** [comment]
Aah, #This is related to some re-organisation we've (well, I've) done behind the scenes.

Well spotted, thanks :-)

**Comment by ShendMikullovci** [comment]
This has been fixed.
