### ISSUE TITLE
Blue Screen of Death?

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1300]
Clicking on the RFI's and COA's sometimes leads to a blue screen that I imagine is the Blue Screen of Death you referenced to @IanMayo?
This is what it looks like: 
![Blue screen of death](https://user-images.githubusercontent.com/85491794/149390188-6eabdb06-e714-407f-98b9-1133bfa42a3b.png)

Furthermore, interacting with the RFI's and COA's is now slower and laggier.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci - is this from the Player side, or the admin pages?

(i.e. I could do with you giving me the steps to reproduce it)

**Comment by ShendMikullovci** [comment]
This is from the player's side. I logged in as Blue CO and clicked on the RFIs and COAs to see the expansion and this happened.
