### ISSUE TITLE
Insights & Intro Buttons CMDWK-HIGH DATA

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1303]
It seems the buttons for the Insights box and Intro pop-up have been glued together in the game. 

![Insights and Intro Button Bug](https://user-images.githubusercontent.com/85491794/149667978-b2f40028-bef2-4b62-8023-2780df383feb.png)
 
Could we space them out like in Papafoxtrot?

**Comment by IanMayo** [comment]
Yes, we need to provide minimum width value for these tables.

Hmm, to be honest, the limited resolution of a specific projector forced us to compress the width of the Admin panel.   If/when we restore the width of the Game Admin channel the icons will get more space again.
