### ISSUE TITLE
Icon Uniformity Mapping

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1306]
We present square icons in the asset menu on the mapping page: 

![Stick to Circles Instead of Squares for Logo Uniformity](https://user-images.githubusercontent.com/85491794/149668354-66d51fdb-20d8-4041-90ef-937f8960865b.png)

It's the only page to my knowledge where we present square icons. 
We should stick to circular icons to maintain force icon uniformity.

**Comment by IanMayo** [comment]
Sure. Can we switch to circular icons for force?
