### ISSUE TITLE
Fit to Window Button Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1307]
The Fit to Window button is inconsistent and doesn't zoom into a clicked cell, but rather on the focal point of the screen at the time. Very often, this leads to screens like this:

![Fit to Window](https://user-images.githubusercontent.com/85491794/149668453-7c0ebfa1-dde5-4a26-a83c-2aa9d5fecced.png)

Can we see to it that the button leads to a specific clicked cell or cell area? 

Also, clicking on the Fit to Window button after the zoom should zoom the screen out to its previous position.

**Comment by IanMayo** [comment]
Ian to reproduce & consider underlying issue.

**Comment by IanMayo** [comment]
Aah, I see.  This is what happens when nothing is selected. Let me investigate.
