### ISSUE TITLE
Intro Pop Up CMDKW-HIGH DATA

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1308]
Same bug on the intro pop-up as in Papafoxtrot: 

![Intro Pop Up bug on Mapping](https://user-images.githubusercontent.com/85491794/149668531-44f73934-0cb1-4d39-9dc0-952e4d0743c4.png)

I'm happy with applying the same solution as #1206

**Comment by IanMayo** [comment]
Hmm, it looks like we've lost the earlier fix for the popup dialog layout.

**Comment by lebaphi** [comment]
Hi @IanMayo, @ShendMikullovci , It seems to works on my machine, I also check the current code base and it included the fix already. Can you try to clear cache or open it in incognito browser?

<img width="505" alt="Screen Shot 2022-01-18 at 9 42 00 PM" src="https://user-images.githubusercontent.com/26705621/149958902-14a5fba4-4f05-4fa1-8465-ff9b13474348.png">

**Comment by ShendMikullovci** [comment]
Just tried. The bug is still there for me.

**Comment by IanMayo** [comment]
Ok. I used the development branch: https://serge-review.herokuapp.com/?wargame=wargame-kskl1i3t&access=rkskl59n7

It was laid out properly:
![image](https://user-images.githubusercontent.com/1108513/150128809-811c1eef-b936-4f68-926d-add748e0fbc2.png)

I'm in Chrome.

**Comment by ShendMikullovci** [comment]
Checked deployment. All good. Thanks, guys!

**Comment by lebaphi** [comment]
Can we close it? @IanMayo @ShendMikullovci

**Comment by ShendMikullovci** [comment]
> Can we close it? @IanMayo @ShendMikullovci

Good for me!
