### ISSUE TITLE
Intro Pop up or Tutorial for Mapping

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1309]
I noticed that the mapping channel has no introduction or any tutorial to show users how to use it, orientation and buttons. 
In the channel, we have two new tables that don't appear anywhere else in the game: 

![Intro for Mapping Channel](https://user-images.githubusercontent.com/85491794/149668644-6c49f830-65fa-466d-aed0-609f371f0cec.png)

I suggest we offer a short tutorial on how to use the highlighted tables above.

**Comment by IanMayo** [comment]
Sure. We need a combination of @ShendMikullovci coming up with the headings/features/descriptions for the walkthrough, and for @lebaphi to implement it.

**Comment by ShendMikullovci** [comment]
Here's an initial design for the tutorial for GC: 

![Mapping Intro Screen 1](https://user-images.githubusercontent.com/85491794/150688621-6238d469-c1cf-4a7c-be58-584f8cb5fd23.png)

![Mapping Intro Screen 2a](https://user-images.githubusercontent.com/85491794/150688648-02ce4e76-9a0b-4794-9ab1-143e82022f7f.png)

![Mapping Intro Screen 2b](https://user-images.githubusercontent.com/85491794/150688656-c3b8a0ac-75fe-4ab1-a7bb-4c97795d33ee.png)

![Mapping Intro Screen 3](https://user-images.githubusercontent.com/85491794/150688659-393ec9cb-a3f8-40b7-85e9-dd3f47db8b91.png)

![Mapping Intro Screen 4](https://user-images.githubusercontent.com/85491794/150688666-5ae7c93f-e589-4099-a239-56a55fb6de76.png)

![Mapping Intro Screen 5](https://user-images.githubusercontent.com/85491794/150688674-a8d21846-61fe-455c-818c-7c171948897e.png)

![Mapping Intro Last Screen](https://user-images.githubusercontent.com/85491794/150688681-37832837-efb9-4855-b39e-054f075fa57d.png)

The pop-up would be identical to the introduction pop-up in order to avoid confusion. Ideally, the user could activate the pop-up by clicking on the button for the introduction pop-up. Let me know if that's difficult to code.

**Comment by IanMayo** [comment]
Sure. The design seems sound.

One extension to the wording.  We mention the top-left panel for assets that the current player controls, and for non-controlled assets that are visible.  It may be worth mentioning that selecting them causes a dedicated editor panel to open at the bottom right.  We won't be able to "highlight" it in the tour, since it's only present when something is clicked. But, it will mean the player is aware of it.

**Comment by ShendMikullovci** [comment]
I think it's a great idea and a valuable step to add to the tutorial: 

![Mapping Intro Screen 2c](https://user-images.githubusercontent.com/85491794/150864633-df6edec4-bff9-47cf-b1be-eb2ad717c5c0.png)

**Comment by IanMayo** [comment]
Sorry @ShendMikullovci - by default we don't show "View asset" when the page opens, it's just when an asset is clicked.  Beyond that, I don't think we can force the "View asset" panel to open.  But, we can mention that clicking on an asset in the top-left will open a tailored panel at the bottom-left.

**Comment by ShendMikullovci** [comment]
Alright. Added the explanation to step 3 of the pop-up. 
Good with the wording? : 

![Mapping Intro Screen 2b](https://user-images.githubusercontent.com/85491794/151068715-8af9c4e2-2cc2-4d2f-ab54-1ae1c1560b4c.png)

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci 

It's a bit more generic than your wording. Clicking on an asset from the `Control` tab also pops up a panel.

Also, in the walkthrough, I don't think we can switch from the `Control` tab to the `Visibility` tab.  So, I think that step needs to cover both tabs - it can then also indicate that clicking on any tab on this panel opens a tailored form.

**Comment by ShendMikullovci** [comment]
Excellent. Here's the updated walkthrough: 

![Mapping Intro Screen 1](https://user-images.githubusercontent.com/85491794/151259518-51c221d7-c1e3-4eaa-9274-1a122e83aa2a.png)


![Mapping Intro Screen 2a](https://user-images.githubusercontent.com/85491794/151259740-3a9799ab-1292-4609-9e22-55784d50ad5a.png)


![Mapping Intro Screen 2b](https://user-images.githubusercontent.com/85491794/151259554-245ea0e5-d631-440f-8daf-8aa479951318.png)


![Mapping Intro Screen 3](https://user-images.githubusercontent.com/85491794/151259582-eb43a326-8272-4196-b8eb-14137e0378e1.png)

![Mapping Intro Screen 4](https://user-images.githubusercontent.com/85491794/151259587-85abf14c-7e3b-45db-9b7b-7a13b35e923e.png)

![Mapping Intro Screen 5](https://user-images.githubusercontent.com/85491794/151259594-1a843a6f-264a-4637-9b29-0022286bf8e2.png)

![Mapping Intro Last Screen](https://user-images.githubusercontent.com/85491794/151259622-78604eaf-dab9-40db-9e00-a3662246f757.png)

**Comment by IanMayo** [comment]
1. We can't switch to the `Visibility` tab during the walkthrough.  So, the wording will have to be "Under Visibility you will be able to view ..."
2. Minor improvement to `Globe buttons`.   Only umpire force are able to view other force's perception of map.  Since we expect umpire forces to have more experience, I guess we could remove that step.

**Comment by ShendMikullovci** [comment]
> 1. We can't switch to the `Visibility` tab during the walkthrough.  So, the wording will have to be "Under Visibility you will be able to view ..."

Yes, that is the idea. I'll change the background shortly.

> 2. Minor improvement to `Globe buttons`.   Only umpire force are able to view other force's perception of map.  Since we expect umpire forces to have more experience, I guess we could remove that step.

I was thinking of showing this step only for the White Force, hence why I logged into the game as GC for the designs. Is it possible to include it only for members of the White Force?

**Comment by ShendMikullovci** [comment]
> 1. We can't switch to the `Visibility` tab during the walkthrough.  So, the wording will have to be "Under Visibility you will be able to view ..."

Here's an idea: 

![Control Mapping](https://user-images.githubusercontent.com/85491794/151527148-0ef47cea-72df-4928-a2bc-c120dc0a86b2.png)

![Visibility Mapping](https://user-images.githubusercontent.com/85491794/151527230-1dd3649a-183b-454d-9a60-6a010d72f1e1.png)

Since we can't switch to the actual Visibility tab, we dim everything else.

**Comment by IanMayo** [comment]
> highlight the visiblity tab

Yes, great idea.

> only show globes step if logged in as umpire force

Yes, if it's possible to do that :-)

I'm happy to ask @lebaphi to start implementing this. But, @ShendMikullovci there is a chance he'll miss something in our discussions.  Could you please produce an updated/consolidated set of screenshots that capture all we've discussed?

**Comment by ShendMikullovci** [comment]
> I'm happy to ask @lebaphi to start implementing this. But, @ShendMikullovci there is a chance he'll miss something in our discussions. Could you please produce an updated/consolidated set of screenshots that capture all we've discussed?

Absolutely.

**Comment by ShendMikullovci** [comment]
To Implement: 
This is the introduction pop-up in the mapping page for CWK-HIGH DATA. Only members of the White Force see step number 6 (globe feature to alternate between perspectives). The rest of the players get the same intro pop-up, but without step number 6.

Here are the screenshots: 

![Mapping Intro Screen 1 Final](https://user-images.githubusercontent.com/85491794/151557449-8b6afd86-3b8f-4a8e-9b5c-2f92a55b1e38.png)

The entire background is dimmed and the intro pop-up appears bright on the screen.

![Mapping Intro Screen 2a Final](https://user-images.githubusercontent.com/85491794/151557508-9d02e1ab-ccc3-4261-87dd-949d081415ed.png)

The orders tab and the control button brighten as well as the pop-up.

![Mapping Intro Screen 2b Final](https://user-images.githubusercontent.com/85491794/151557533-34eff63f-9f0a-4fe2-97ff-5cacbe70a12a.png)

Here, only the Visibility tab brightens, and everything else is dimmed.

![Mapping Intro Screen 3 Final](https://user-images.githubusercontent.com/85491794/151557589-d57abc20-fd74-469f-a5ac-63177f8f82e7.png)

Bright zoom-in and zoom-out and home button.

![Mapping Intro Screen 4 Final](https://user-images.githubusercontent.com/85491794/151557637-c7cfba36-100d-4f9d-9f7d-080edb0a81f4.png)

Bright clockwise & counterclockwise buttons.

![Mapping Intro Screen 5 Final](https://user-images.githubusercontent.com/85491794/151557659-5b1dac7d-0700-4651-b21f-acece5d78d44.png)

Bright globe buttons. **This feature is only for the White Force. Other players don't have this feature so it's not included in the pop up for anyone else.**

![Mapping Intro Last Screen Final](https://user-images.githubusercontent.com/85491794/151557674-b579cfa0-bcbb-49cb-bf8a-f20bdad6897a.png)

Finally, dimmed background and bright pop-up and intro button at the top right corner.

Sorry for the length. Let me know if you have any questions.

**Comment by ShendMikullovci** [comment]
Do we plan on implementing this? Sounds like a valuable feature, especially for the upcoming game.

**Comment by IanMayo** [comment]
Yes, I do hope to. The game date has slipped though, possibly by a couple of months.

So, the priority is on fixing the broken bits, then the tutorial.

**Comment by lebaphi** [comment]
Hi @IanMayo , @ShendMikullovci ,
so in the first time we also show the tutorial to the force player, so how to solve if there are 2 types of tutorial showing at the same time?

**Comment by IanMayo** [comment]
Good question @lebaphi :-)

I _guess_ we only show the mapping walkthrough if the main walkthrough has already completed (we do that by checking the flag in the cookie data)
