### ISSUE TITLE
UI Improvement - Player Log to react table

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1316]
The current player log isn't interactive.

When there are lots of players the Game Designer may wish to sort or filter some columns.

We should switch the table to the `react-table` component.

It should include these capabilities:
- sort on all colums
- click on column headers to filter values in that column.  This should be for `force`, `role ` and `last message` columns. When new data is received, the filter should still be in place.  Plus, there should be some visual indication that a column has a filter applied.

**Comment by lebaphi** [comment]
Hi @IanMayo, `react-table` you mean the table is the same as the version we use in the `collab-status-board`?

**Comment by IanMayo** [comment]
yes @lebaphi , `react-data-table-component`
