### ISSUE TITLE
Re-merging reduced databases

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1318]
In December a volume of data was deleted from the SQLite database, to reduce the volume of data being handled by the application.

Now the wargame is complete, analysts wish to look at the whole body of data - so we wish to merge the databases back together.

We have:
1.  original.sqlite - this contains all data
2. live.sqlite - old data was deleted from this, but it has new data

So, I guess we need a process to:
* open the newer database (2)
* attach the older database (1)
* run a query to copy `by-sequence` records from (1) to (2) if they're not already present.

**Comment by rnllv** [comment]
1. Open the database files

   - via DB Browser for SQLite

     - Open **live.sqlite** file from DB Browser [**Open Database** button or **Ctrl+O** command] [Schema and table structures in the images below are indicative only]
![1_OpenLiveDB](https://user-images.githubusercontent.com/77854924/150841303-bce154de-d1da-4b76-b2c2-758a30344eea.png)

     - Attach **original.sqlite** file from DB Browser  [**Attach Database** button][Ensure to provide the database name as **original** when prompted]
![2_OpenOriginalDBasoriginal](https://user-images.githubusercontent.com/77854924/150841405-99391823-80f4-46d8-bb3d-1b770c452c79.png)
![2b_OpenOriginalDBasoriginal](https://user-images.githubusercontent.com/77854924/150841422-8b60b135-2830-49b5-9240-8b647ee8c686.png)

   - via command line

     - Execute `sqlite3 live.sqlite` at the command line prompt (**cmd**/**bash**/etc) [Ensure both **live.sqlite** and **original.sqlite** files exist at the path you're executing this command]
     - Execute `ATTACH DATABASE 'original.sqlite' AS original;` at the SQLite prompt


2. Merge deleted records (same for command line and DB Browser for SQLite)

   - Execute the below script at the SQLite prompt in the command line or inside the *Execute SQL* tab in DB Browser for SQLite tool 

```
with seq_to_copy as (
  select seq 
  from 
  original."by-sequence" 
  where seq not in (
   select seq 
   from 
   main."by-sequence")
)
insert into main."by-sequence" 
select * from original."by-sequence" o
where o.seq in 
 (select seq 
 from seq_to_copy);
```

![4_ExecuteQuery](https://user-images.githubusercontent.com/77854924/150841592-55a0f157-df7e-47d2-a2cb-b145bfa3b453.png)


3. Save writes to DB (DB Browser for SQLite, auto-saved for command line)

   - Press Ctrl+S or click on `Write Changes` from the file menu
![5_WriteChanges](https://user-images.githubusercontent.com/77854924/150841605-1babdf73-79b2-4d1d-a81b-db05774e4a73.png)

**Comment by rnllv** [comment]
### Another quick and dirty command line hack

Assuming both **live.sqlite** and **original.sqlite** files are in the same path, executing the below command in the same location will merge the **live.sqlite** file with deleted records from **original.sqlite**

```
sqlite3 live.sqlite 'attach database "original.sqlite" as original;with seq_to_copy as ( select seq from original."by-sequence" where seq not in ( select seq from main."by-sequence")) insert into main."by-sequence" select * from original."by-sequence" o where o.seq in (select seq from seq_to_copy);'
```

**Comment by IanMayo** [comment]
hi, I just tried this in `Browser for SQLite`, and it ran just fine. Thanks :-)

**Comment by IanMayo** [comment]
Task complete.
