### ISSUE TITLE
Improved editor component for design of platform speeds

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1332]
We're trying to see if we can re-design and update the tracking of asset speed. Our current design takes up too much space on the admin page and is not optimal for tracking. 

This was the initial idea:

![Speed Box](https://user-images.githubusercontent.com/85491794/151879419-1f06da63-c6e8-44a2-947e-fc4a55162228.png)
 
Here, the user can change the interval values and length. Selecting one value auto-selects the previous values: The selected speed in this design is 18KTS, which means the asset can also go at 6 & 12 KTS if necessary.

@IanMayo brought up the following ideas: _It's possible for a warship to have a maximum speed for "flying operations", that's the maximum speed the can travel at and still use their helicopter. But, an autonomous underwater vehicle (AUV) could have a "most efficient speed" - that's the speed that maximises search range and battery endurance. There is a chance that this speed could be expressed in metres/second. So the AUV could have an "Optimal search speed" with units of "m/s". The Game Designer may provide different "optimal search speeds" for different instances of AUV._

The following questions arise: 
- Why would the most efficient speed be measured in m/s and not KTS? 
- Have we discussed this with the client? 
- Can they provide details on the most efficient speed per asset type based on real-life scenarios?

**Comment by ShendMikullovci** [comment]
Adding "Optimal Search Speed" to the speed box clutters the design and could be redundant. Can we show optimal search speed in equivalent KTS? That way, the appropriate KTS speed would be highlighted and selected by default, with a small question mark to explain the selection.

**Comment by IanMayo** [comment]
> Why would the most efficient speed be measured in m/s and not KTS?

It's an illustration of a scenario when the units of speed could be something other than knots.  Similarly, If it was a land vehicle it would be km/h or mph.

> Have we discussed this with the client?

No.  Clients require ability to specify any measurable concept as a `variable` (or `attribute`). 

> Can they provide details on the most efficient speed per asset type based on real-life scenarios?

Again, I'm just providing an example of an attribute.  They don't have a list of what attributes they wish to use in the game. If fact it's the opposite - they wish to be able to store _any_ measurable concept in game.

**Comment by IanMayo** [comment]
> Here, the user can change the interval values and length. 

The design needs to demonstrate/explain how interval values and length are edited by the game designer.

**Comment by ShendMikullovci** [comment]
Here's a walkthrough: 

The user views an empty speed box ready to be filled out.

![Speed Box Empty](https://user-images.githubusercontent.com/85491794/151969266-711ef3c0-1d1e-4a09-811c-600c01cd3cc1.png)
 
They click on "Add Speed" and the interval pops up. I noticed that in CWK-HIGH DATA, we track 0-5 speeds depending on assets, for a total of 16 platforms. That's an average of 2.6 speeds per asset, so I rounded that up to 3 and decided to show 3 default data points for the interval. The values here are also from CWK-HIGH DATA but can be changed. 

Three icons on the right of the interval also appear. 
The Plus allows the player to add data points, the dash to remove them, and the bin to delete the entire interval. 

P.S. I got rid of the interval tracker because of its use for more fluid scales; intuitively, I should be able to set the speed at whatever point between 6-12 for example, but that only renders things more complex. Let me know if you want it back.

As for the Optimal Search Speed (OSS, for quicker typing), I'm in between 2 design ideas. The one below shows OSS as a text form to be filled with a value that the user sees fit. The other idea is to present OSS as a feature on its own, where we present a default value for OSS and give the user the ability to activate and edit it. I was thinking of a checkbox or a radio button, an on/off feature, etc. 

Finally, the user can also manipulate the measurement, by changing the unit manually. I had the idea of adding a drop-down list of the units the user might want to use, and clicking on one would instantly change the values on the interval. Some of the units would also be unavailable (I guess?) depending on travel mode (meters/second for a boat? probably not). 

![Speed Box Input](https://user-images.githubusercontent.com/85491794/151969371-53d44de5-7420-4d15-ad25-747ffa96e8a4.png)

Once the input is over, the user hits enter and the interval turns pitch black:

![Speed Box Completion](https://user-images.githubusercontent.com/85491794/151971388-9b6755c5-efd4-4678-a9e5-f7c7d7cf68f7.png)

I've left the add/remove and delete buttons on here, but it would be nicer if they only appeared when hovering over the speed box after the user has hit enter.

Let me know your thoughts.

**Comment by IanMayo** [comment]
Sorry if the concept of "Optimal search speed" is a distraction.  It's an example of an `attribute` that takes units.  It wasn't intended to replace/supplement `Search` in a `Platform-Type`.

I'm happy with the general concept of moving the speed editor from a vertical list of a horizontal list.

For the `-` button to work, the player would need to select a speed before clicking it, which introduces the need for a `current speed` marker. 

There is a danger of this component becoming increasingly complex/expensive for something that only the Game Designer interacts with.

A _simpler_ interface would be to display the speeds as a horizontal (comma-separated) list.  But, with an "Edit" button that pops up the existing vertical editor component in a dialog - where they get added/edited/deleted as currently, but with a "Done" button that closes the dialog, and shows the horizontal list.  How about that?

**Comment by ShendMikullovci** [comment]
Something like this? : 

![New Speed Box](https://user-images.githubusercontent.com/85491794/153089462-f591340d-6c4f-456b-9788-b6336aa5e6a8.png)

![New Speed Box 1](https://user-images.githubusercontent.com/85491794/153089476-ac77c1b0-cef1-41d8-982f-91e878040f46.png)

**Comment by IanMayo** [comment]
> Something like this? 

Yes - spot on - though would we still need edit/cancel buttons?  (I'm pretty sure we would if it's in a popup dialog)

**Comment by ShendMikullovci** [comment]
How does this look?: 

![Speed Box Reduced 1](https://user-images.githubusercontent.com/85491794/153490392-466ad975-1b89-49d5-b66c-fd2ac7000bf0.png)

Reduced size for less space consumption. When the user clicks on Edit Speed, the pop-up appears: 

![Speed Box Reduced 2](https://user-images.githubusercontent.com/85491794/153490525-a9944531-fefc-4d1d-b01d-b587e096b1fd.png)

Added a save button and an X marker to keep it simple and straightforward. The color on the buttons is not crucial, though I believe it matches well with the aesthetics of the game.

**Comment by IanMayo** [comment]
> How does this look?
Yes, great :-)

**Comment by lebaphi** [comment]
> Reduced size for less space consumption. When the user clicks on Edit Speed, the pop-up appears:

Should we set height limit for this popup (in case the list is too long)? @IanMayo @ShendMikullovci 
or
we can do them same with the Commodities, edit each row when we focus on

**Comment by IanMayo** [comment]
Thanks @lebaphi . Yes, I guess we need a scroll bar if there are more than 5 items.

**Comment by lebaphi** [comment]
> Thanks @lebaphi . Yes, I guess we need a scroll bar if there are more than 5 items.

Thanks @IanMayo @ShendMikullovci , I just wonder why do we need a popup while its UI/UX is almost the same with current component?

Current component:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/26705621/153747274-d52743b2-4364-452c-96b6-17e808cf1bc5.png">

Popup:
![image](https://user-images.githubusercontent.com/26705621/153747287-267d523b-3e9d-43fc-a58b-a8d8b83fc425.png)

IMO with the popup, I think the `Add Speed` button should not scroll with the list items and it should have the same line and the same style as the `Save` button.

**Comment by IanMayo** [comment]
Good question @lebaphi 

When in "read-only" view the values will be displayed as a horizontal list - using very little vertical space.  But, it makes sense to edit them in a vertical list.  So, in "edit mode" the dialog show them as a vertical list.  On "Save" the new versions are shown as a horizontal list.

**Comment by ShendMikullovci** [comment]
> I just wonder why do we need a popup while its UI/UX is almost the same with current component?

It's because we think it best to show the speed variables in a horizontal bar to limit space usage in the admin page as well as to reinforce known behavior: we have a tendency to go left for lower variables and right for higher ones.

**Comment by lebaphi** [comment]
Hi @IanMayo @SendMikullovci, while implementing this feature I realized one thing:

https://user-images.githubusercontent.com/26705621/154216251-b0666110-d282-484e-8759-961fd24850e8.mov

First thing, I want to confirm that all new edit data in settings platform type tab will be stored in local state and it will be lost when we reload the page until we click the ` Save platform type` button.

So I think we don't need the `Save` button in the popup (because it also saves the data to the local state), I think the edited data will update immediately to the horizontal list like the video above. For this approach, I think UI is cleaner and UX is still the same as the way we edit data in horizontal list and we can also reuse the `sortable-list` component.

What do you think?

**Comment by ShendMikullovci** [comment]
> Hi @IanMayo @SendMikullovci, while implementing this feature I realized one thing:
> 
>  Screen.Recording.2022-02-16.at.2.23.48.PM.mov 

Nicely spotted. I think that every time a speed is added, it should be a rounded value as well, but this is fairly low priority.

> First thing, I want to confirm that all new edit data in settings platform type tab will be stored in local state and it will be lost when we reload the page until we click the ` Save platform type` button.
> 
> So I think we don't need the `Save` button in the popup (because it also saves the data to the local state), I think the edited data will update immediately to the horizontal list like the video above. For this approach, I think UI is cleaner and UX is still the same as the way we edit data in horizontal list and we can also reuse the `sortable-list` component.
> 
> What do you think?

I agree that it's cleaner that way. I added the save button as a way out from the pop-up and to not have to click on SAVE PLATFORM to save the speed. It's cleaner to simply click outside of the pop-up or hit the X button and have the speeds added instantly. It's also not uncommon among games to have to save the entire page in order to save one feature of the page. A good way around it though is to have a "Save Changes?" pop-up if we want the user to be sure.

**Comment by IanMayo** [comment]
I agree with @ShendMikullovci  :-)

Yes, we don't need a `Save` button on the popup.

Hmm, I don't think we should round the value. There could be circumstances when a set of speeds is used that seems weird to us. Some kind of fast boats either go very slow (around harbour) or one of a few very fast speeds (once they are [planing](https://en.wikipedia.org/wiki/Planing_(boat)))

**Comment by lebaphi** [comment]
thanks, any updates for the UI/UX in the above video? @IanMayo @ShendMikullovci

**Comment by IanMayo** [comment]
Thanks @lebaphi  - I'm quite happy with the video :-D

**Comment by lebaphi** [comment]
> Thanks @lebaphi - I'm quite happy with the video :-D

How to make you extremely happy @IanMayo ? 🤣

**Comment by ShendMikullovci** [comment]
> thanks, any updates for the UI/UX in the above video? @IanMayo @ShendMikullovci

Also very happy. It looks really neat!
