### ISSUE TITLE
Two issues with Platform-Types in Game Admin page

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1333]
We have two issues with the Platform-Types editor page.

The first is that a platform-type can't be deleted until it has been saved/modified (as illustrated [here](https://github.com/serge-web/serge/pull/1323#issuecomment-1024248765) )

The second is that if we create several platform-types, deleting one deletes all of them - as illustrated here.

![screencast](https://camo.githubusercontent.com/478507df66651891a2f781904b8d69f1c00f4c6e0ed2089b5e4c07693a9dcbde/68747470733a2f2f692e6779617a6f2e636f6d2f36366461656633616437663138393938323866386261623434343565343434312e676966)

**Comment by ShendMikullovci** [comment]
I encounter this issue frequently but with various manifestations. Today, I couldn't delete a platform before nor after saving. Then, after closing the tab and restarting a game, the platforms were immediately saved after creation, making their deletion possible.

**Comment by IanMayo** [comment]
Could you look at this too, please @lilitkarapetyan ?

**Comment by IanMayo** [comment]
Tested on `serge-review`, working.
