### ISSUE TITLE
14. Information Markers

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1339]
As a **Game Controller** I wish to be able to **put marker pins on the map** to **highlight the location of significant events**

More thoughts [here](https://docs.google.com/presentation/d/1AOGfEQuSYsRyvAYUe4_x3E_bvu15KJ8KpzqDyDAMh-Q/edit?usp=sharing)

At the end of an adjudication phase the Game Controller has a volume of information to convey to each player force.  The information is currently passed in these ways:
1. updated state of world (via mapping channel)
2. in-channel messages from umpire-force to players 
3. notes taken by an observer during adjudication which are conveyed orally when they return to the force room

Option (3.) brings the most versatility, but, it allows for mistakes in the location where things happened.

Conveying information through map markers would ease this challenge.  A suite of icons for the markers could convey part of the message, with a text label for more detail.

So, the following capability would be useful:
1. Game Control able to add markers to the map during adjudication (or force laydown) phases, via drag/drop
2. Game Control can also control who can see the marker, plus specify the icon and text for the label
3. The marker is annotated with the turn when it was dropped (to show age). 
4. Game Control can delete markers in later turns.
5. If different icons or labels are required for different forces, then these must be created as separate labels.
6. The text label for markers would only be displayed if they are selected, or at a sufficient zoom level
7. A new tab will be present in the "World State" (top-left) panel listing markers. This is where Game Control/Player clicks on a marker to edit/view more data resp.  Clicking on a marker from this panel will both open it in the bottom-left panel, and pan/zoom onto it on the map.
8. Just like any modified/accepted planned routes, the markers would stay on the Game Control PC until the Game Control clicks on "New State of World" and they are sent to the players with their updated vessel locations.

* [x] Create data type for markers & markers collection
* [x] Modify wargame data to allow markers
* [x] Modify sample wargame to include information marker
* [x] Render information marker (icon)
* [x] Render information marker (polygon ring)
* [x] Render just text label
* [x] Provide popup with extra description
* [x] Introduce control-bar button to add info-marker at current centre of plot
* [x] Make marker draggable if Game Control, and marker selected.
* [x] New world-bar panel for info markers (if any are present)
* [x] Edit dialog for selected info-marker if Game-Control.  Marker only draggable if currently selected. 
* [x] View dialog for selected info-marker if non Game-Control
* [x] New Game Admin panel to let Game Designer add/specify new icons.  Needs to support icon name plus `upload` of new icons

**Comment by ShendMikullovci** [comment]
Great addition. Instantly thought of the pin icon: 

![Pin Icon Black Grey Background](https://user-images.githubusercontent.com/85491794/156385062-c1f5da29-34da-448e-9724-a9ee872530bc.png)

Tilting it to the right to occupy a more diagonal space and appear more like a detail. 

A few issues we would probably encounter with it: 

1. Markers can clutter the mapping page: We could try an outlined icon with a dim color like we have previously.
2. New and old markers: The GD should be able to not only delete but also archive older markers, as well as view all/select number of markers on the map to maintain awareness. 
3. Color: I suggest we color according to force if the pins are necessary for multiple forces. If it's a feature that will only be used for subject force (Blue), then we stick to a regular icon.

**Comment by IanMayo** [comment]
Sure. I guess we have UX requirements for:
- new tab in top-left window, labelled "Markers"
- new tab at bottom-left for when umpire clicks on marker to edit it
- new tab at bottom-left for players?  Maybe not - they can see the icon/color/label, and hover/click to see more details

**Comment by ShendMikullovci** [comment]
After some thought and playing around with the icon, I realized that the location pin used for most mapping services (including Google Maps) feels more appropriate. So, I came up with this design (this would be a pin for Blue-2):

![Location Pin Edited Blue](https://user-images.githubusercontent.com/85491794/156572210-96ddb09a-7122-4575-9a7b-d72edc8ff0d3.png)
 
Here's how it would look on the mapping page: 

![Markers Mapping   Window](https://user-images.githubusercontent.com/85491794/156572378-b8684a08-a72f-48d8-8a77-97af8ca55c05.png)

I also added numbers next to the icons in order to maintain awareness (without them, the user would have to click on random icons in the top left window to know which one they want to edit). 

I was thinking we make the markers editable directly on the top left window since they only represent textual information. That way, we limit space consumption and cluttering. 

Let me know your thoughts.

**Comment by IanMayo** [comment]
Thanks for that @ShendMikullovci .

The Game Designers wish to have a range of icons for the markers.  So, one could be fire - to represent the player being able to see that something is on fire. Another could be an "ear" (or something similar) to say the sonar had heard something coming from that area.  The designers will come up with their set of icons.

I also think the marker could have a short label plus a description.  The short label would be displayed when sufficiently zoomed in - but now when viewing the full map. The description would be available by clicking on the marker.

Yes, we _could_ allow editing in the top-left panel, but we don't do that for anything else.  If we keep the top-left for selecting which one to edit, we'll be consistent with other features, and we won't need much of a software change (if at all).

Aah, so the umpire will need to edit:
- icon (from drop-down list showing icons & names)
- label
- description
- which forces can see this marker

**Comment by ShendMikullovci** [comment]
That's great! The game is getting richer and richer. I'll see what we can come up with.

**Comment by ShendMikullovci** [comment]
Here's how that could look: 

![Markers 1](https://user-images.githubusercontent.com/85491794/156602760-36c6bd56-944b-4b3b-be45-e15d29c3add8.png)

A list of icons provided by the client on the top left can be dragged and dropped into the mapping page. 

Dropping one into the page would instantly open the lower tab where the user would fill in the necessary details:

![Markers 2](https://user-images.githubusercontent.com/85491794/156603076-1ba2fee0-b8a4-4397-ba85-58ea8384e993.png)

The label and description are text boxes that can be edited. The user also selects who they want this feature to be visible for by selecting the appropriate force. 

Let me know your thoughts!
