### ISSUE TITLE
Component for "More info available" text span

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1345]
There are lots of occasions when we need to provide supporting/background information to a player (or even Game Designer in the admin pages).

We currently support this via tooltips, but it's cumbersome for a player to hover over all screen elements in the hope of finding tooltips.

I don't know if this is possible, but it would be great if we could have a modified span control that includes a small info marker (fa-circle-info) at the top-right.   Clicking on the question mark pops up the explanatory guidance.  I guess we should allow for up to 30 words.

I'm thinking of a span control since the text is currently just displayed as plain text - so switching to a `span` shouldn't cause any layout problems.

I guess the control would also have these props:
- icon color (so it can stand out from background)
- description text

We should develop this a StoryBook component that has a range of values for the above, including short and long descriptions.

Aah, hold on. There are also occasions when we wish to indicate that an icon has "more info" available.  So, I guess we also need an extended font-awesome icon that can have its own more-info icon at the top-right.

So, we'd be able to provide `more-info` for the `Password` and `Game control` column headers.

![image](https://user-images.githubusercontent.com/1108513/153577940-7faf5dcb-dfb4-4825-8656-d32c4503e820.png)

An early use of this would be the

**Comment by lebaphi** [comment]
I just done the initial demo of this component. How do you think @IanMayo @ShendMikullovci 

https://user-images.githubusercontent.com/26705621/153699366-b75475ed-cc4a-47ca-aabc-e616a5cb623d.mov

**Comment by IanMayo** [comment]
Thanks @lebaphi  - but we need to apply "more info" to the three column header icons.  So, to be in proportion with them, I think we need to have a smaller icon.
