### ISSUE TITLE
Problems with orientation marker

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1358]
I'm working on a marker to show which way a ship is facing, as described here:
https://docs.google.com/presentation/d/15E55FU_1thskbCgPN1KdzZaEmspEeE-IU3j2PuiQT5Q/edit?usp=sharing

My work is in PR #1359 

I have found an SVG shape with a point.  I'm putting it under the ship marker.  It will point in the correct direction.

![image](https://user-images.githubusercontent.com/1108513/155496998-40f1f33d-7bb2-4def-836b-29f7d194e745.png)

The above example is from `http://localhost:6611/?path=/story/local-localmapping--natural-earth`

But, I have two challenges:
- I need to be able to specify any color for the shape, so it matches the ship/force color
- I need to correct a small offset, so that it aligns with the ship shape

I'm pretty sure the changes go in `asset-icon\index.tsx` and `asset-icon\styles.module.scss`

**Comment by lebaphi** [comment]
Hi @IanMayo , now we can custom the color of the marker by change the css 😄 

<img width="251" alt="image" src="https://user-images.githubusercontent.com/26705621/155516862-f6037bbc-fd77-4ab4-b00d-c89a11473184.png">

**Comment by IanMayo** [comment]
Fixed in #1359
