### ISSUE TITLE
Two features missing in `attributes`

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1362]
I've just realised we are missing two capabilities related to `attributes`. They are both in the admin pages.

![image](https://user-images.githubusercontent.com/1108513/156004067-a3655fad-5dcc-45f2-9e76-67e9169893c9.png)

1. When adding a new `asset` to a `force`, lookup the `attributes` for that `platform-type` and add the relevant `attributes` to the new `asset`. An `asset` is added to a force by dragging one of the platform-type icons into the `List of assets` section.
2. Before allowing a `SAVE FORCE`, do a check that the `attributes` are correct for each asset. Specifically, do this:
    a. Find the platform-type for the asset
    b. Check that each attribute is present on the asset
    c. Check that no extra attributes are present on the asset
    d. Popup a warning if anything is wrong.  The dialog should include the asset name(s) and what the problem is.

**Comment by ShendMikullovci** [comment]
Great idea!

**Comment by lebaphi** [comment]
Hi @IanMayo , I pushed a new PR for this issue 1, we can save force with the asset attributes. I just wonder about the issue 2.
How can the user can save force with extra asset attributes, I see we allow the user to edit the current attribute value, not to add more attribute 🤔

**Comment by IanMayo** [comment]
It's if the Game Designer changes the attributes for that `platform type` while still designing the game.  The may remove an attribute for `fishing vessel`, but he has already created some instances of `fishing vessel` - so we do some tidying up for him.
