### ISSUE TITLE
Support turning circles in planned routes

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1364]
For close-in wargames, the turning circles of ships becomes a significant factor.

* [x] Introduce data-type for turning circle in platform-type
* [x] If turning circle present for platform use "unwind-rope" algorithm to determine extent of achievable positions
* [x] If extent of achievable positions is present, restrict allowable hexes to the current one, plus any cells with a centre in the set of achievable positions
* [x] When player is planning route, exclude those not in the allowable hexes
* [x] When marker is dropped (and turn has been planned), see if it matches the direct route.  If it does, just store ends, otherwise store all cells
* [ ] Respect terrain data - don't allow ships on land, or land assets on sea
* [x] For partial leg plans, ensure correct amount of distance is removed (reflect complex path if present)
* [x] Don't show blue line if it passes through no-go area, and don't process turn if dropped in no-go area.
* [ ] Handle issue when immediately dropping pin into no-go area (see video below)

![scrreencast](https://user-images.githubusercontent.com/1108513/158978081-edf9803a-2898-4848-9020-f96b966e97c3.gif)

**Comment by IanMayo** [comment]
I realise we still need to allow `Turning Circle` to be specified for a `PlatformType` in the admin page/

Here is the field:
![image](https://user-images.githubusercontent.com/1108513/160238954-e764b65d-38d4-45d8-8fd7-7701231bdb04.png)

Here is the editor page for platform-types:
![image](https://user-images.githubusercontent.com/1108513/160239063-963ea44e-cb44-4a52-934f-22ec045e39d8.png)
 
I _guess_ we could introduce a second block in the top row.  It would be titled `Turning circle (optional)`  and  have a single text field, followed by a `m` label to indicate its in units.  On `Save`, if the value is a non-zero number, we store that, else the field is omitted.

Does that sound ok @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
Good idea! Here's how that could look:

![Turning Circles](https://user-images.githubusercontent.com/85491794/160296283-d39d917c-ab7d-49ba-ae82-b27e1b5bfb4f.png)

![Turning Circles 2](https://user-images.githubusercontent.com/85491794/160296289-edb29925-2eb4-4d37-9546-340b08eae80c.png)

I added the unit text box and measurement icon to maintain uniformity.

> It would be titled Turning circle (optional) and have a single text field, followed by a m label to indicate its in units.

Why the letter "m"?

**Comment by IanMayo** [comment]
The value is always in metres.  So, we just show the "m" to the right of the value to remind the Game Designer about this.

There won't be a `trash` icon - since it isn't a list of values.  It's a plain text box, I believe.

**Comment by ShendMikullovci** [comment]
Can the user delete if they change their mind?

**Comment by ShendMikullovci** [comment]
> The value is always in metres. So, we just show the "m" to the right of the value to remind the Game Designer about this.
> 
> There won't be a `trash` icon - since it isn't a list of values. It's a plain text box, I believe.

Something like this?:

![Turning Circles 2a](https://user-images.githubusercontent.com/85491794/160400310-4f64c799-c504-425d-a8f2-4b5c92a2ad82.png)

**Comment by IanMayo** [comment]
Yes - that's fine. The user will use `delete` key if they change their mind.
