### ISSUE TITLE
MoreInfo component is overridden after dialog

### ISSUE THREAD

**Issue by lebaphi** [serge-web/serge#1368]
We can see the MoreInfo component displays behind the dialog

![image](https://user-images.githubusercontent.com/26705621/156752115-7baa3fc4-6322-489f-8f1a-2071e8cc62b4.png)

**Comment by ShendMikullovci** [comment]
Are you also referring to this: 

https://user-images.githubusercontent.com/85491794/156879095-c9c02693-a187-46cf-adb9-ea5efe927d37.mp4

**Comment by lebaphi** [comment]
Yep, it is @ShendMikullovci 👍
