### ISSUE TITLE
Can't add elements to a platform on Papafoxtrot

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1372]
Can't seem to be adding elements to a platform on Papafoxtrot. Is there a reason for this?

https://user-images.githubusercontent.com/85491794/156805076-5e858a4c-a9d7-4c57-9249-3c45fb5a5ab6.mp4

**Comment by IanMayo** [comment]
Good find. Possibly related to #1369

**Comment by ShendMikullovci** [comment]
The issue is also relevant for "Small Wargame": 

https://user-images.githubusercontent.com/85491794/156879846-16c2e97e-fa57-4e6c-acb6-93134bd12485.mp4

**Comment by ShendMikullovci** [comment]
Everything works fine in "Local Wargame" in already present platforms but not on New Platforms.

**Comment by ShendMikullovci** [comment]
It appears Papafoxtrot, Small Wargame, Tall MSG all have this issue from the jump, whereas Local Wargame, CMDWK and CMDWK High Data only have this issue on newly created platforms. Is there something that comes to mind that could explain this for you guys?

**Comment by IanMayo** [comment]
Hmm, can you look at this please @lebaphi ?
