### ISSUE TITLE
Reactive Edit Button Attributes

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1375]
The edit button reacts when the mouse hovers over the attributes same as when the mouse hovers over itself:

https://user-images.githubusercontent.com/85491794/156879391-a04db27e-86ba-4ff3-b11b-f3390422698c.mp4

Can we turn that off?

Also, it could be beneficial to have the attribute chip be deletable: as the mouse hovers over it, an X button appears next to the attribute label. Somewhat like this: 

![Deletable Chip](https://user-images.githubusercontent.com/85491794/156879445-ada7850b-c2c6-4c19-8728-de92097ec37b.png)

This would prevent us from adding a delete button entirely and would also resolve part of #1369.

**Comment by IanMayo** [comment]
Drop, as we drop legacy mapping.
