### ISSUE TITLE
Attribute Chip Size

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1376]
The larger attribute chips end up scooting the "Edit" button far off to the right, eating up half of its display: 

![Attribute Chip Size Issue](https://user-images.githubusercontent.com/85491794/156879533-b772363d-2026-4f13-9bcd-8dee1b29d156.png)

A good solution would be to have the edit button under the attribute chips at all times: we would avoid this issue and maintain uniformity with the rest of the buttons.

**Comment by ShendMikullovci** [comment]
It appears our edit button has gone entirely outside of the screen: 

https://user-images.githubusercontent.com/85491794/162994349-613879bc-688f-4c52-b349-47e2b9799de5.mp4

It'd be nice to have it under the attributes, in a navy blue color since it's an actionable button.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci
