### ISSUE TITLE
Drag & Drop Not Intuitive 

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1377]
As a user, it might not be intuitive for me to have to drag back an asset into the asset list if I mistakenly added it:

![Not Intuitive Drag And Drop](https://user-images.githubusercontent.com/85491794/156879677-48332e2c-bf8f-43f3-8937-938d13302cb8.png)
 
Could we provide a small X on the right of the asset like with deletable chips?

**Comment by IanMayo** [comment]
@lilitkarapetyan - could you have a think about the options for deleting an asset from the list of assets?

Is it possible to have a small `x` at the top-right of the asset icon, to delete it?

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan - but I think we need a `confirm` dialog to delete the asset after clicking the red `x`, please.

**Comment by ShendMikullovci** [comment]
This has been implemented.
