### ISSUE TITLE
New Platform UX issues

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1378]
Multiple things here: 

https://user-images.githubusercontent.com/85491794/156880045-6baf8503-d52c-45c0-953a-0484e1da9611.mp4

1. The issue with adding elements (#1372) persists with New Platforms as well.

2. When I create a New Platform, it pops up at the bottom of the screen. Could we have it pop up at the top? In a wargame with plenty of platforms, it adds another step of scrolling down to find the newly created platform for the user that is unnecessary. 

3. If I accidentally hit Delete on the New Platform, the element display page behaves like I confirmed the deletion. Once I hit cancel, the elements don't reappear, and I'm forced to click on New Platform again to view the elements. These are all extra steps that prolong the game creation process. If we could have the screen stay still behind the "Are you sure?" pop-up and only disappear once the deletion is confirmed, that'd be great.

**Comment by IanMayo** [comment]
Some for you, please @lebaphi

**Comment by ShendMikullovci** [comment]
> 2. When I create a New Platform, it pops up at the bottom of the screen. Could we have it pop up at the top? In a wargame with plenty of platforms, it adds another step of scrolling down to find the newly created platform for the user that is unnecessary.

https://user-images.githubusercontent.com/85491794/157425186-215d5f61-c44b-427f-95f5-9480b00a3cc3.mp4

I noticed that creating a platform or force, pops up the new element under the previous one. On the other hand, creating a channel pops the new channel on top. Essentially, if we could make platform and force creation behave like channel creation, that'd be great!

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , on fixing some ux issues, I found another one:

https://user-images.githubusercontent.com/26705621/157471136-d248110a-73b1-4424-ab20-220081e2fbbf.mov

As you can see when adding multiple channels without saving, on clicking the button Save Channel, only the last channel was saved.
So do you think we should do the same behavior like platform types, force (save item after adding) or keep the current adding behavior but fix the issue of saving channels ?

**Comment by IanMayo** [comment]
> So do you think we should do the same behavior like platform types, force (save item after adding) or keep the current adding behavior but fix the issue of saving channels ?

I don't like the force-safe.  I'd like the save to just happen on `Save channel`.  But, we do need to remember other saved channels.

Aah, I've got it.  This should be `Save channels`.  It's the full set of channels that we save.  Similarly, it should be `Save platform types` - since the contents of the whole tab that are being saved.

**Comment by ShendMikullovci** [comment]
> Hi @IanMayo @ShendMikullovci , on fixing some ux issues, I found another one:

Nicely spotted! I think "logically" this bug makes sense because essentially, the user is saving the channel that they are on. 
However, what if they wanted to keep multiple channels and edit them as they go? This is solved by having the channel automatically saved after adding. 

Another way to go here would be forcing the user to save the first New Channel before being able to create newer ones. This, however, would probably slow element creation down a little.

**Comment by lebaphi** [comment]
> Another way to go here would be forcing the user to save the first New Channel before being able to create newer ones

I'm prefer this one 😄

**Comment by ShendMikullovci** [comment]
Essentially, it depends on the cost of accidentally forgetting an unedited "New Channel". How much does it impact the game if GC accidentally adds this to the game:

![New Channel](https://user-images.githubusercontent.com/85491794/157475692-339f5860-bd62-4cd7-a990-ba976fd76d09.png)
 
If it has little to no impact, then should we bother restricting the user to save every new channel and add extra work for you guys? 

From a UX perspective, I do have to say it's neater.

**Comment by IanMayo** [comment]
Here's my understanding/position:

Our tabs are `Channels`, `Platform types`, etc.  So, it does seem like we have the `Channels` tab open until we finish editing channels. At that point the player can choose to commit their changes (`Save channels`) or drop the changes and switch to another tab.  Along the way, the user may wish to save channel changes "so far".

So, I believe for each tab, we need to start off by taking a copy of the relevant collection of data (`channels`).  It's that copy that is modified with the tab. When the user clicks on `Save channels` we update (_store_) the whole set of channels into the wargame.

But, if the user clicks to another tab, we let them choose whether to save the copy (commit it), or drop the changed copy (lose changes).
