### ISSUE TITLE
Messages Sent Twice on Local Wargame

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1382]
Messages are sent twice on Local Wargame:

**Note from Ian**: they aren't actually sent twice, they are just displayed twice locally. If you do a page refresh, you'll see there is actually just one instance of each message.

https://user-images.githubusercontent.com/85491794/156931951-689b30f2-4bd3-4dd8-b796-5927ad99c820.mp4

**Comment by ShendMikullovci** [comment]
It turns out they are received as singular messages by Blue CO: 

![Messages Sent Twice on Local Wargame Received Once](https://user-images.githubusercontent.com/85491794/156932134-fe334a9b-b0c3-4dbb-b2ac-6af557b72bf5.png)

They only appear as singular messages once the page is refreshed (as GC): 

![Messages Sent Twice on Local Wargame Received Once After Refresh](https://user-images.githubusercontent.com/85491794/156932101-0e93dc2f-ce7c-487a-bbba-fd3f31f4cba7.png)

**Comment by ShendMikullovci** [comment]
Blue & Red also sent out messages twice for some reason: 

![Messages Sent Twice Blue](https://user-images.githubusercontent.com/85491794/156932339-5d30316c-625a-4140-aae9-f881f7202f86.png)
![Messages Sent Twice Red](https://user-images.githubusercontent.com/85491794/156932341-6db299b4-4254-4b92-b20c-37fc8954ff7f.png)

Received as singular messages from GC: 

![Messages From Blue and Red Received Singular](https://user-images.githubusercontent.com/85491794/156932401-914aa0db-e89e-4903-a75f-e8b9040d4a96.png)

**Comment by IanMayo** [comment]
This is a recurring issue.  In the past it has been resolved by the player just clicking "Refresh page" button.  But, that's a poor workaround.

It would be useful to understand, and to overcome this please @lilitkarapetyan 

Note: if it can't be resolved through identifying a problem in registering database listeners, then I suspect the workaround is to reduce the local list of messages to the unique ones by `_id`.  That will remove the apparent duplcates.

**Comment by ShendMikullovci** [comment]
Same issue for the general chat as well: 

![Message Sent Twice General Chat Local Wargame](https://user-images.githubusercontent.com/85491794/157082505-c8777c24-69db-4edf-94db-caaeece0502e.png)

**Comment by IanMayo** [comment]
@lilitkarapetyan - this either hasn't been fixed, or has come back :-(

**Comment by IanMayo** [comment]
Fixed in #1384
