### ISSUE TITLE
Messages displayed on the same side for every player of the same force

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1383]
I just noticed that messages sent from BLUE CO appear on the right of the window for other Blue players (same for RED CO and other Red players): 

![Message Displayed On The Side for Blue Players](https://user-images.githubusercontent.com/85491794/156932787-01f1470b-f8f7-45eb-bfd9-19c598c620ae.png)

Was this on purpose? I suppose this would associate the right-handed side to the force rather than to the individual player, but general consensus is that I only view my own messages on the right-hand side of the window. I suggest we follow that since we can clearly distinguish between forces due to colors.

**Comment by IanMayo** [comment]
Sure, ok. Good suggestion.  We should check if `selectedRole` matches `details.from.roleId`.

**Comment by ShendMikullovci** [comment]
We should apply the same logic for the general chat as well. Same issue there (this time in "Small Wargame"):

![Message Side from my own Force](https://user-images.githubusercontent.com/85491794/157081316-34adc5b9-e608-4a34-a72c-9ec7c5ab0df9.png)

**Comment by IanMayo** [comment]
Yes, agreed.  @lebaphi - we can probably fix this in `storybook` first.  Please ping me if you need different dummy data.

**Comment by IanMayo** [comment]
Closing. Fixed  in #1383
