### ISSUE TITLE
Message Display Inconsistency

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1385]
Couple of things I wanted to mention: 

![Chat Window Incongruity](https://user-images.githubusercontent.com/85491794/157084387-17d1e90d-01ac-43b3-ac86-0805f9532ce5.png)

There's inconsistency in how we display messages on channels vs general chat. In the message channels, older messages move higher up and newer messages occupy immediate lower spaces. This is a general consensus among messaging apps accross the board and I think we should apply it for the general chat as well. Currently, the general chat displays the opposite: old messages down, new messages up.

Also, in the general chat as you can see in the screenshot above, it's difficult to visually discern between teams simply based on the 2 colored small squares next to the message. Furthermore, unless the user is viewing their own messages where they see this message cloud type of icon below: ...

![Own Message General Chat](https://user-images.githubusercontent.com/85491794/157085400-0f130d17-833b-4e87-95b4-187cb4555bd8.png)

... then the message is indistinguishable from the white background. 

I suggest we grab the same design from the channel messages and apply for the general chat. The grey would help distinguish the messages and the colored sidebar would stand out more than a small colored square. It would look something like this: 

![New General Chat UX](https://user-images.githubusercontent.com/85491794/157088846-7f97c45a-a5f3-4ec5-88ef-6f4831495fec.png)

Let me know your thoughts.

**Comment by IanMayo** [comment]
Yes, I'm happy with both impovements.
