### ISSUE TITLE
Deleting a new channel deletes other channel too

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1386]
I just created a new channel.

When I went to delete it, it deleted another channel too:
![recording](https://i.gyazo.com/7f2b536344553e85f470515bd7c6bbc1.gif)

**Comment by ShendMikullovci** [comment]
Just noticed this. It happens in Small Wargame, Local Wargame and Tall MSG only.

**Comment by IanMayo** [comment]
Fixed in #1392
