### ISSUE TITLE
Reactive Online Marker 

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1389]
The online/offline marker is reactive to the text box next to it. It squeezes or expands depending on if the text box says "a few seconds ago" or "X minutes ago".

![A Few Seconds Ago Bug](https://user-images.githubusercontent.com/85491794/157252613-31e51ad2-f81b-4c2c-b04f-d9c9caae55eb.png)

![A Minute Ago Bug](https://user-images.githubusercontent.com/85491794/157252640-e707434e-1749-4d58-90da-3c7f072f07eb.png)

Could we make the text box a two-liner so it doesn't impact the marker?

**Comment by ShendMikullovci** [comment]
Wondering whether it's a font issue? I noticed that the Role and Last Active fonts might not be the same:

![Role Font Message Channel](https://user-images.githubusercontent.com/85491794/157254456-54ff1ba9-5d49-4c90-a9d9-69790958d4ee.png)

![Last Active Font Message Channel](https://user-images.githubusercontent.com/85491794/157254491-c93b3caf-ef09-4fad-8068-47538f7863d7.png)

Also, apparently, Chrome considers the offline marker as the same element as the text box. Maybe they need to be separate?

**Comment by IanMayo** [comment]
Another solution is to take more control of the column widths.  I'm sure we can reduce `Force` and `Sent at`. Hmm, or we make the dialog 50px (approx) wider. Then the `Last active` column will fit without squashing the icon.

**Comment by lebaphi** [comment]
I think the simple solution is set the min-width for the marker, it does not touch too much on the component code based 🤔

**Comment by lebaphi** [comment]
the marker works well but the text seems to be cut off. we can increase the column width a bit but I wonder if other columns has the long text, so we should support responsive column width here 🤔 

<img width="146" alt="image" src="https://user-images.githubusercontent.com/26705621/158001644-4cd72764-50ee-4433-b1da-abb2023f3c4d.png">

**Comment by ShendMikullovci** [comment]
I was playing around with the deployment in #1407 and I noticed that the Message column has the smallest text box info. I thought maybe we could shrink that one, but then I noticed this: 

I sent a message with BLUE 1 CO on the Message Channel (VHF C16):

![Message Channel Blue 1 CO](https://user-images.githubusercontent.com/85491794/158013886-dbbb2301-7b1f-4818-bdc8-4c6e50301cae.png)

The player log seems to show that a message has been sent in "Chat", the same as when a message is sent in the general chat:

![Player Log Message Column Shows Chat instead of VHF C16](https://user-images.githubusercontent.com/85491794/158013898-c0d51061-773d-49d5-b56a-94fe036618eb.png)

I would assume that when a player sends a message in the channels, it's a different item than the general chat message? 
In this example, should we show "VHF C16" in the message column in the player log?

**Comment by IanMayo** [comment]
I understand the confusion @ShendMikullovci 

We are displaying the message-type rather than the channel.  So, the game you're looking at has the `VHF C16` and `Admin` both configured to send `Chat` messages.  We _could_ switch to showing the channel name instead, but right now I don't think there is a right answer.  I suggest we live with it for a while and see.
