### ISSUE TITLE
Player Log Questions

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1390]
A couple of things I noticed and wanted to discuss with you all: 

1. Should the user have to see their own activity on the player log?

![GC sees themselves in the player log](https://user-images.githubusercontent.com/85491794/157258851-37b0437f-68f8-4b79-93f7-eb5eac91e4b4.png)
 
Here, GC sees themselves in the player log. What benefits does this have? To view whether their account/game is active? 
If it's unintentional, I suggest we change this and free up that row of space. 

2. Sorting Last Active Ascending/Descending might not be fully functional:
I sent out a message with RED HHQ in order to see whether they would appear as Last Active, and played around with the Asc/Dsc sorting order. RED HHQ wouldn't go on the top (or bottom) of the list and always remain somewhere in the middle: 

![RED HHQ Last Active Bug](https://user-images.githubusercontent.com/85491794/157259650-ca2e495a-0f9d-4b91-8cc2-32955ee612af.png)

![RED HHQ Last Active Descending Bug](https://user-images.githubusercontent.com/85491794/157259714-ee32656f-6b22-4397-90fd-e688c74e6162.png)

**Comment by IanMayo** [comment]
1. Don't show own log.  Sure, let's filter what gets displayed please @lebaphi 
2. Sort order for new messages. Yes, could you investigate this please @lebaphi

**Comment by ShendMikullovci** [comment]
I've referred to this issue in #1389 as well @lebaphi so I'd like to know your thoughts.

**Comment by lebaphi** [comment]
> * Don't show own log.  Sure, let's filter what gets displayed please @lebaphi
> * Sort order for new messages. Yes, could you investigate this please @lebaphi

@IanMayo @ShendMikullovci  I have a MR to fix the marker width #1407 but does not include ☝️, let me update 😄

**Comment by lebaphi** [comment]
I pushed the fix 👍

**Comment by ShendMikullovci** [comment]
This has also been fixed and implemented. Thanks guys!
