### ISSUE TITLE
Admin Page Entry Display

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1397]
This is our current Admin Page Entry Display: 

![Current Admin Page Entry Page](https://user-images.githubusercontent.com/85491794/157692188-8c792923-e2d1-4d9c-a6fa-5dec22463c73.png)

It displays no situational clues for the user to identify what page they are on. "Password" is shown twice on the page, which is a little redundant, and with the lack of clues, the user might not know what password we are referring to. 

I suggest the following additions: 

![New Admin Page Entry](https://user-images.githubusercontent.com/85491794/157692574-2b8009ea-d2a2-4a2c-8e83-e618cc964025.png)

The SERGE logo with the title below, as well as the name of the page the user is on. The password title is removed and the password text box is aligned to the center of the screen, along with the logo and the two titles below it. I am also considering a small, introduction (most likely one to two sentences) similar to our Welcome Screen. 

Also, the ENTER button has been turned navy blue since it's an executive button.

What do you guys think?

**Comment by IanMayo** [comment]
It has been left a little, since it's only used by the Game Admin - but sure, good suggestions :-)
