### ISSUE TITLE
Message Library Save Buttons

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1398]
I noticed that our message library shows 2 save buttons when editing: 

![Message Library 2 Save Buttons](https://user-images.githubusercontent.com/85491794/157694317-f6c4a5ff-db07-4bbb-b8cd-8f45068f7d40.png)

Do these buttons serve 2 different purposes? Or just a bug?

Side Question: I kinda like the floppy disk icon next to SAVE MESSAGE. Intuitive. What do you guys think about generalizing it throughout the game? It would allow us to only use the icon in tighter spaces.

**Comment by IanMayo** [comment]
Yes - the floppy icon is a useful addition.

The `Message Library` can probably be archived, to be honest.  It didn't make it into actual usage.

**Comment by ShendMikullovci** [comment]
Since the Message Library is not going to be used, closing this issue.
