### ISSUE TITLE
SERGE Entry Page

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1399]
Here's our current SERGE Entry Page: 

![Current SERGE Entry Page](https://user-images.githubusercontent.com/85491794/157707592-51698792-d530-4f2d-88ce-595d91374ae3.png)

I suggest a few improvements: 

![New SERGE Entry Page](https://user-images.githubusercontent.com/85491794/157707726-ec278068-b0e4-4f40-8d60-247d2d021b89.png)

The icon is still firmly present, though it occupies less space, allowing for a better display of our text. A "SERGE" title under the icon with the Welcome message below. The text box has also been largened, to eliminate the scrollbar and fit everything in one page. 
I added the actual insights button icon to the text to illustrate what users should be looking for in case they need to. 

Finally, the PLAY button, now navy blue, is centered alongside everything else in the page. 

Let me know your thoughts.

**Comment by IanMayo** [comment]
Sure.

This is ok, but the text & logo have been replaced for each past wargame - so our text would be lost.

**Comment by ShendMikullovci** [comment]
Essentially, I'd like to implement a softer display and give a smoother visual welcome to the user. The current one looks a little glitchy with the text vertically aligned to the left of the text box.

**Comment by IanMayo** [comment]
Another for you, please @lebaphi
