### ISSUE TITLE
Can't Save Force Name

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1403]
In the wargame created for issue #1400, I can't seem to be able to save the name for New Forces:

https://user-images.githubusercontent.com/85491794/157919412-d7be9f6b-50d1-4c49-8098-cb4c6d911851.mp4

As you can see, the "FORCE SAVED" notification doesn't appear when I actually click "SAVE FORCE" but when I create a new force. As the Force is saved, it automatically goes back to its default name. What do you guys think is causing this?

**Comment by ShendMikullovci** [comment]
Can't seem to be able to save Force color either: 

https://user-images.githubusercontent.com/85491794/157921565-0cb4f68d-105b-4fbc-aae7-aef63bb1b44d.mp4

**Comment by IanMayo** [comment]
Today this is working ok for me:
![image](https://user-images.githubusercontent.com/1108513/159904405-1bad2492-bad8-4372-8db8-c61042e481e2.png)

It worked for editing an existing force, and adding forces to a newly created wargame.

Will re-open if the problem re-occurs.

**Comment by ShendMikullovci** [comment]
This is also a recurring, inconsistent bug. Couldn't save on a couple of new test forces for the first trial, then it saved after I deleted forces and added them back in.
