### ISSUE TITLE
Linked Forces and Deletion Issue

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1405]
I noticed while creating Forces that they can sometimes get linked between each other and end up not being deleted properly: 

https://user-images.githubusercontent.com/85491794/157923264-63875cc3-428e-4ca3-b9d5-2515f24f3059.mp4

**Comment by IanMayo** [comment]
This is working reliably today.  Channels still temperamental.

Closing, until issue returns.

**Comment by ShendMikullovci** [comment]
> This is working reliably today. Channels still temperamental.
> 
> Closing, until issue returns.

Just added two test forces, tried to delete one, the White Force (at the bottom of the list) got deleted instead. This was in New Test - Lots of Forces.

**Comment by ShendMikullovci** [comment]
> > This is working reliably today. Channels still temperamental.
> > Closing, until issue returns.
> 
> Just added two test forces, tried to delete one, the White Force (at the bottom of the list) got deleted instead. This was in New Test - Lots of Forces.

Update: Now I've unwantedly deleted White, Blue 1, Blue 2 by trying to delete Test Forces 1 & 2.

**Comment by ShendMikullovci** [comment]
I noticed something. I think elements are reacting to the order of establishment. I noticed this with the deletion of the forces (going from the 1st added force to the last), but apparently, they also react to the order of addition for platforms: 

https://user-images.githubusercontent.com/85491794/159987893-8ad7a37a-3de9-4762-8f10-35e92317dc2c.mp4

As you can see, Platform 2 can only be saved on Test Force 2 once it has been successfully added to Test Force 1 (its predecessor).

**Comment by IanMayo** [comment]
Re-open. Requires further investigation/

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci - it was a bug, in code that we wrote some time ago. Thanks for catching it.

You should be able to correctly delete forces in serge-review now.

**Comment by ShendMikullovci** [comment]
Got hit with a blue screen as I was testing this out.

**Comment by ShendMikullovci** [comment]
> I noticed something. I think elements are reacting to the order of establishment. I noticed this with the deletion of the forces (going from the 1st added force to the last), but apparently, they also react to the order of addition for platforms:
> 
>  Order.Bug.mp4 
> As you can see, Platform 2 can only be saved on Test Force 2 once it has been successfully added to Test Force 1 (its predecessor).

I was trying this again since I didn't get hit with the blue screen and noticed the addition doesn't react to the order of establishment of forces today. I tried out different ways to add Test Platform to Test Forces 1 and 2. Didn't work.

https://user-images.githubusercontent.com/85491794/160396498-8c3740b1-bc97-49c9-86fd-17bf5aab89d7.mp4

**Comment by ShendMikullovci** [comment]
This has been fixed.
