### ISSUE TITLE
Element Selection Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1406]
When adding conditions, states and attributes to a platform, the selection underline remains active on the last elements of each category even after it has been added: 

https://user-images.githubusercontent.com/85491794/157925433-122813bd-9b3f-452b-8211-931717da192d.mp4

**Comment by ShendMikullovci** [comment]
Also, the attribute text boxes might be a little too small: 

![Small Text Box Attributes](https://user-images.githubusercontent.com/85491794/157925900-f4936f28-6f82-4ff4-98e7-451e5752e701.png)

For example, the one previewing the formats can't even fully contain the word "format". What if the user wants to add a long format? Unit is also quite tight.

**Comment by IanMayo** [comment]
Thanks for that @ShendMikullovci 

The `format` field will probably only normally be one of `0`, `0.0`, `0.00`.   So, the values will almost alway be shorter than the word `format`. 

Units are also typically short `m`, `kg`, `tons`, `secs`.  On the rare occasion that it's a longer word it seems acceptable for the user to have to drag the cursor.  

I think it's right to give the most sapce to `Atrtribute` and `Description`.  I _guess_ we could use smaller fonts in some places, but that may just distract.

Hmm, If we give `format` just a couple more pixels of width it would solve the `format` issue.

What do you think @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
> The `format` field will probably only normally be one of `0`, `0.0`, `0.00`. So, the values will almost alway be shorter than the word `format`.
> 
> Units are also typically short `m`, `kg`, `tons`, `secs`. On the rare occasion that it's a longer word it seems acceptable for the user to have to drag the cursor.

If you're sure those are the formats and units most likely to be used then we can stick to what we got. I was just being cautious. 

> I think it's right to give the most sapce to `Atrtribute` and `Description`. I _guess_ we could use smaller fonts in some places, but that may just distract.

What kind of descriptions would the user usually have for the attributes? I would imagine a short sentence would suffice?

**Comment by IanMayo** [comment]
> If you're sure those are the formats and units most likely to be used then we can stick to what we got. I was just being cautious.

Sure.  It seems a pretty rare occurrence to have a units for format more than 4 chars long. If there is, the Game Designer can still drag their mouse to read the text.

> What kind of descriptions would the user usually have for the attributes? I would imagine a short sentence would suffice?

I'm afraid this is the `unknown unknowns` - the users don't know the range of attributes they will come up with for a wargame, they just know they want freedom to specify any kind of attribute.

**Comment by ShendMikullovci** [comment]
> I'm afraid this is the `unknown unknowns` - the users don't know the range of attributes they will come up with for a wargame, they just know they want freedom to specify any kind of attribute.

In that case, we could allow for the description to display only a word or two, sort of like a title, and give an option to enter more data in a pop-up window. Once that data is added, it is applied to an info marker, where the user would click the info marker to see the entire description.

**Comment by IanMayo** [comment]
Really, the "Attribute" is the element that is a word or two long, and the "description" is the amplifying text.

Let's see how we get on with this next wargame. As the Game Designer is developing it, he can ask us to give more space if necessary.

**Comment by IanMayo** [comment]
The underline for `state` and `condition` is a valid bug.

But, right now it's just cosmetic, and it only affects the Game Designer. Marking as low priority.
