### ISSUE TITLE
Insights/Game Admin Tab Notification Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1409]
Insights/Game Admin tabs don't show any notifications when new messages are received: 

https://user-images.githubusercontent.com/85491794/158014534-85516316-3f3a-4e05-b5a9-717b3204d391.mp4

It'd be nice to have a simple notification counter on both tabs that disappear once the user hits "MARK ALL AS READ".

**Comment by IanMayo** [comment]
Yes, good suggestion @ShendMikullovci
