### ISSUE TITLE
Insight Box Send Issue

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1410]
The user doesn't get any feedback that the "SEND" button is functional and their message has been sent: 

https://user-images.githubusercontent.com/85491794/158014625-97f82d33-d83e-40de-bf29-aa71720e15ab.mp4

It would be nice if they would get a message confirming the insight has been sent, or have the insights box disappear once the message has been sent.

**Comment by IanMayo** [comment]
Yes, good one.  I think that the "send feedback" used to disappear when `Send` was clicked.

Could you fix it please @lebaphi :-)

**Comment by lebaphi** [comment]
Hi @ShendMikullovci , @IanMayo , it seems the `send feedback` form always disappear when Send was clicked

https://user-images.githubusercontent.com/26705621/158833026-7e6a8969-04db-4a6d-8446-f818f475ca67.mov

**Comment by IanMayo** [comment]
Aah, so it's not broken. That's good :-)
