### ISSUE TITLE
Channel Creation & Deletion Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1413]
When I create a new channel and save it, a new one is instantly created without me clicking on the button.
Furthermore, deleting the newly unsolicited channel actually ends up deleting the one I intentionally created. 

https://user-images.githubusercontent.com/85491794/158082311-8ee3c691-9346-4763-b993-5e18033cbbcb.mp4

**Comment by ShendMikullovci** [comment]
It turns out the unsolicited channels are linked to the intentional ones. Check out how they're both selected simultaneously: 

![Linked Mapping Channel](https://user-images.githubusercontent.com/85491794/158082418-5729ba04-094e-451e-b5be-4c4e32b90e41.png)

![Linked Channel](https://user-images.githubusercontent.com/85491794/158082422-cc93e7ac-b99a-4833-a645-48cb08b5f3c4.png)

**Comment by IanMayo** [comment]
One for you, please @lilitkarapetyan  - this looks like a recurring issue.

**Comment by ShendMikullovci** [comment]
Another deletion bug I came accross is that the channel I hit delete on, doesn't get deleted. Rather, the 1st created one does, and the deletion proceeds in that order: 

https://user-images.githubusercontent.com/85491794/159074636-7884010b-5671-4ff9-a3d8-94a911981bc2.mp4

**Comment by IanMayo** [comment]
This is a proper bug, where duplicate channels (with the same id) are created.  That also explains why the "wrong" channel is deleted.

**Comment by ShendMikullovci** [comment]
This has been fixed.
