### ISSUE TITLE
Mark All Read Bug General Chat

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1417]
As previously noted by @lebaphi in #1401, the Mark All Read button doesn't seem to be functional in the general chat. 
Furthermore, there's a small rectangle of empty space eating up chat space: 

![White Rectangle Bug General Chat](https://user-images.githubusercontent.com/85491794/158194239-4f0f2495-5628-40d7-b0a0-8783592f3d8c.png)

This rectangle is not apparent on every screen in the same way. As you can see below, it's smaller in GC's screen: 

![Smaller White Rectangle Bug General Chat](https://user-images.githubusercontent.com/85491794/158194626-99764dd9-3025-46fe-9702-efad8b47bef1.png)

**Comment by IanMayo** [comment]
Good points, thanks @ShendMikullovci

**Comment by ShendMikullovci** [comment]
Good work guys. However, the "MARK ALL READ" button is still dysfunctional on my end for some reason.
