### ISSUE TITLE
Delete Role Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1420]
It appears roles can't be deleted once they are added to the list on a new wargame: 

![Delete Role Bug](https://user-images.githubusercontent.com/85491794/158413628-ee4f5117-c613-4e04-a7eb-48986afcf3dc.png)

This issue is also present in already existing wargames: 

![Delete Role Bug Small Wargame](https://user-images.githubusercontent.com/85491794/158413685-d0d13a3f-5386-4f9d-b8a1-f191a757c16a.png)

**Comment by IanMayo** [comment]
Another for you, please @lilitkarapetyan . Maybe this is related to the other instances of the issue.

**Comment by IanMayo** [comment]
Fixed in #1423

**Comment by ShendMikullovci** [comment]
I think we agreed for the bin to be on the left, next to the name, before closing?

![Bin on the right](https://user-images.githubusercontent.com/85491794/159977764-c0bff25f-9afb-4e77-bdc7-a4b7d8db7ba4.png)

It's still on the right.

**Comment by IanMayo** [comment]
Oops, well spotted.

@lebaphi - could you move the `trash` icon next to the `Roles` entry please?

**Comment by ShendMikullovci** [comment]
Unfortunately, this bug has reappeared: 

https://user-images.githubusercontent.com/85491794/162999890-8e654e76-602f-4a9d-906a-6892b6fcdd0f.mp4

**Comment by ShendMikullovci** [comment]
This has been fixed.
