### ISSUE TITLE
New Overview Display

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1425]
Here's our current Overview Screen : 

![Current Overview Page](https://user-images.githubusercontent.com/85491794/158631650-555f1ab5-c149-417e-ad0b-f9720bb17bd0.png)

There are a few things I'd like to address here: 

1. The screen can't fit all of the elements without scrolling, while relatively little space is actually being occupied. As you can see, the screen itself is not at all cluttered and contains a relatively small amount of elements to be edited. However, our current layout of these elements, forces the user to scroll down in order to find the "Initiate Wargame" button, which is arguably one of the most important buttons of the game. 
2. The current layout of the overview places a much bigger emphasis and importance on the Game Description & Objectives text box, rather than the settings. While I understand the importance of the description, the settings hold a more important place in the creation of the wargame itself. 
3. Reading through "Don't Make Me Think" by Steve Krug, I realized that our clickable and editable areas might not be as intuitive as we think, especially titles/names.

With all of this in mind, I thought of redesigning this page and came up with this: 

![New Overview](https://user-images.githubusercontent.com/85491794/158633170-55f95213-5549-4db4-89c2-e789b0281f80.png)

Here, all of the elements fit the same screen, eliminating the need for the user to scroll down to find the Initiate Wargame button. The latter has also been made light blue, to match SERGE's theme colors as well as attract attention. To maintain uniformity, the save and cancel buttons stay navy blue and grey, as they do throughout the game. 

The description box remains overhead, however slightly smaller and rounder. Right underneath, we present the settings with the editable section in a white rectangle. The choice behind the white rectangle was made to follow the same logic as the description box (since the white rectangle in the description box is the editable one). This dichotomy between grey and white creates a design that could be implemented throughout the game that I believe would condition the user to identify these white areas as editable vs grey areas as fixed. You can also notice that I put the title in a white rectangle as well, to further emphasize this. 

I went through the screens of the game and overall, I think this way of designing the editable areas would fit well, with little work to be done on my part. If you guys like the idea, I can get on it.

Let me know your thoughts.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - sorry for the late reply.  You are right that we waste a lot of space on the `objectives block`, particularly since it hasn't been used yet.   But, I'm not a fan of the new layout. We waste quite a lot of horizontal space, and in `Settings` there is too much white space between the labels and their controls - which makes it more challenging to know which label is for which control.

Maybe it's an option to switch to a 3-column layout:  [objectives] [time variables] [others]

The `others` block would be turn-type and show access codes.

In the fairly near future we'll have to let the game designer specify some map constraints.  This panel _may_ be the correct destination for that set of controls..

**Comment by ShendMikullovci** [comment]
>Hello @ShendMikullovci - sorry for the late reply.

No worries.

>We waste quite a lot of horizontal space, and in Settings there is too much white space between the labels and their controls - which makes it more challenging to know which label is for which control. Maybe it's an option to switch to a 3-column layout: [objectives] [time variables] [others]. The others block would be turn-type and show access codes.

Sure. Here's an idea: 

![Column Overview Design](https://user-images.githubusercontent.com/85491794/161102607-0bd3533f-be2e-4123-8bfc-48ba5726bd44.png)
 
Depending on what those mapping constraints could be, that tab could be displayed differently. 
Another motivation behind this initiative is to render the display smoother and more approachable. It's been shown that smoother design not only provides a better experience for the user but also allows them to better learn and interact with the application.

Let me know your thoughts.

**Comment by ShendMikullovci** [comment]
A new design has been suggested.
