### ISSUE TITLE
Role Selection

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1427]
As we know, the user can select multiple roles from a force in a permissions tab in collab edit, giving them access to documents and permission to interact with them. This manifests visually as a dropdown multiple-choice list where the user clicks on as many roles as they want: 

https://user-images.githubusercontent.com/85491794/158642992-ea78469e-e97f-45f2-b202-4e47f974fa5e.mp4

However, in the case of a single-role force, this feature is not needed and forces the user to click outside the dropdown unnecessarily: 

https://user-images.githubusercontent.com/85491794/158643297-63a0bd59-1867-4cef-ac2e-12795c9c1b79.mp4

Is there a way to make the dropdown disappear once the role has been clicked on, for forces containing only 1 role?

**Comment by IanMayo** [comment]
@ShendMikullovci - if there is a force with a single role, then the drop-down can be left blank - so all roles in that force participate in that way, right?

**Comment by ShendMikullovci** [comment]
> @ShendMikullovci - if there is a force with a single role, then the drop-down can be left blank - so all roles in that force participate in that way, right?

Sounds like that could work. Do you think we should only present the role itself, without access to a dropdown at all? That way the user doesn't have to click on it at all either.

**Comment by IanMayo** [comment]
I don't think it's worth introducing more functionality for this minor inconvenience.   Whilst it may offer a time saving, it's something that doesn't happen very often, so cost cost of effort is low overall.

**Comment by IanMayo** [comment]
Closing, but thanks for proposing it @ShendMikullovci
