### ISSUE TITLE
Off VS Disabled Toggles

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1428]
We should be able to distinguish between toggles that have been turned OFF versus toggles that are DISABLED.

For example: 

https://user-images.githubusercontent.com/85491794/158644620-3f4b5156-b8ba-4baa-b606-e253ad12b2a7.mp4

The toggles before clicking on the edit pen, should be dimmed grey and unresponsive to mouse hovers to emphasize their disabled quality, irrespective of their OFF/ON status. Once the edit pen has been clicked on, they regain their color.

Here's some examples: 

TOGGLE OFF/ON ENABLED:

![Toggle Off](https://user-images.githubusercontent.com/85491794/158645230-c38e9382-0332-4f1e-a132-907eba064de6.png)
![Toggle On](https://user-images.githubusercontent.com/85491794/158645245-b72789e9-2e73-4091-9842-e25d535e05a6.png)

TOGGLE OFF/ON DISABLED: 

![Disabled Toggle Off](https://user-images.githubusercontent.com/85491794/158645294-d48c6ee6-5ae1-457a-aea9-8e5b807355a4.png)
![Disabled Toggle On](https://user-images.githubusercontent.com/85491794/158645310-1714eaa0-5f4b-42e0-98d4-fb483f2869f8.png)

**Comment by IanMayo** [comment]
Nicely spotted @ShendMikullovci . Can you fix it please @lebaphi  ?
