### ISSUE TITLE
"Are You Sure" pop-up Permissions

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1429]
![Physical Proximity Edit Pen Garbage Bin](https://user-images.githubusercontent.com/85491794/158646238-62205a57-1f72-4b38-8c8a-40f3ec8907b3.png)

Considering the physical proximity of the edit pen to the garbage bin, we should add an "Are you sure you want to permanently delete this role?" pop-up when clicking on the garbage bin.

I've already accidentally deleted a force trying to edit it.

**Comment by IanMayo** [comment]
One for you, please @lebaphi
