### ISSUE TITLE
"Blue Screen of Death" on Newly Initiated Wargame

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1433]
I logged in to find out the initial 1400 wargame that I had created, saved and initiated had been deleted. So I created a new one, but encountered the blue screen after launching and trying to log in as a user:

![Blue Screen of Death](https://user-images.githubusercontent.com/85491794/158904737-81233686-c27b-4921-bd81-c3aaee0e7ffd.png)

**Comment by IanMayo** [comment]
Hey, @lebaphi  - could you give Shend the steps to get the console trace please?

**Comment by IanMayo** [comment]
It's really valuable to catch bugs like that @ShendMikullovci 

Based on the `serge-review` version, could you give us the exact steps to reproduce this please?

**Comment by lebaphi** [comment]
> Hey, @lebaphi - could you give Shend the steps to get the console trace please?

I think you just need to open the dev tool or press F12 button, open the `Console` tab and the logs was there

**Comment by ShendMikullovci** [comment]
> It's really valuable to catch bugs like that @ShendMikullovci
> 
> Based on the `serge-review` version, could you give us the exact steps to reproduce this please?

So, it turns out the bug doesn't happen when I log in through White Force. However, as soon as I add other forces, I can't access the game.

**Comment by ShendMikullovci** [comment]
> I think you just need to open the dev tool or press F12 button, open the `Console` tab and the logs was there

This is what I got: 

![Dev Tool Errors](https://user-images.githubusercontent.com/85491794/159073947-16d8a709-b5b8-495a-9ff2-e3df43314b3b.png)

**Comment by IanMayo** [comment]
Hello @ShendMikullovci  - I've implemented a workaround for this bug.

The underlying bug is that a problem with `Save channel` meant that we ended up with multiple channels with the same `id`.  Serge was falling over when trying to display multiple channels with the same id.  So now, when Serge loads, it removes channels with a duplicate id.

Clearly the correct fix is to stop saving duplicate channels, but my workaround (now in `develop` branch, which all other branches come from) - so you shouldn't see it again.

**Comment by ShendMikullovci** [comment]
It appears that now I can't access the game at all: 

https://user-images.githubusercontent.com/85491794/159704403-99f92282-2531-4b99-af99-1b05f6401c41.mp4

Neither the admin page nor the player page allow me to log in.

**Comment by IanMayo** [comment]
Sorry @ShendMikullovci - I'm on it.

**Comment by ShendMikullovci** [comment]
> Sorry @ShendMikullovci - I'm on it.

No worries. Take your time.

**Comment by IanMayo** [comment]
Sadly this seems an intermittent issue.  `serge-review` is working properly now @ShendMikullovci .  Will keep an eye on it.

**Comment by ShendMikullovci** [comment]
I've encountered the infamous blue screen on a few other occasions so far. Here's a couple I managed to record: 

https://user-images.githubusercontent.com/85491794/160181739-d015de3b-7d7c-4a95-9d08-dab28a0ec7f6.mp4

As you can see, no issue with Cloud-One.

I also encountered the blue screen while testing out @IanMayo's improvements in #1405 but it's not consistent so I couldn't record it yet.

**Comment by ShendMikullovci** [comment]
Another encounter just now: 

https://user-images.githubusercontent.com/85491794/160397503-e5c6c025-9839-4f45-b773-3e15e2c0faa6.mp4

**Comment by ShendMikullovci** [comment]
https://user-images.githubusercontent.com/85491794/160398325-8cc09802-d926-49b2-a87e-3a4dd408c637.mp4
