### ISSUE TITLE
5.0 Provide orders

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#145]
As a < player >, I want < to give orders for my platforms > so that < I can drive the wargame >.

The blue/red players should be able to provide orders for their platforms for multiple steps.

# Acceptance criteria

- [ ] Game `MWARC Initialized`, logged in as `Red CO`
- [ ] Game in `Planning` phase
- [ ] Player sees red assets.  Any of them can be clicked on.  The assets are not currently draggable. Clicking on an asset opens the `Control popup`.  
- [ ] Cancel closes the control popup
- [ ] With the popup open, a list of planned states are provided as radio buttons.  Selecting a mobile state enables the speed controls.  Clicking on a speed radio button enables the 'Plan Route' button.  Clicking on that collapses the form. but shows a maximum distance ring plotted around the platform.  Clicking on the platform again opens the 'Route Planning' form.  It contains buttons to 'Cancel planning route' and 'Continue'.  
- [ ] The platform can be dragged in multiple legs. Each time the platform is dropped, the range remaining will shrink.
- [ ] Once the available range has been consumed, the new platform location can be clicked on, to re-open the `Control Popup`. It has buttons for `Plan another turn`, `Cancel planned legs` and `Submit planned turns`.
- [ ] Initially, the instructions provided above will just be submitted to the console. Eventually they will update the "Orders" panel.

# UX

_May_ need more UX.

# Notes

**Comment by clenoble** [comment]
@IanMayo This follows the general flow of the prototype, except for a number of clicks on buttons like Cancel, Plan route, etc. I think we can avoid having so many buttons and clicks with the following (if possible technically): 

- [ ] Close the popup by clicking anywhere outside it, including on the marker itself (no "cancel" button). 
- [ ] No "Plan route" button: as soon as a speed has been set, the marker becomes draggable to plan a route. The range circle appears on mouse down, as soon as the user starts dragging. It disappears on mouse up when the user places the marker in a new location.
- [ ] I don't think we need a specific button to "Plan another turn" either (unless it's necessary technically). When at the end of the range for 1st turn, the user can continue to drag the marker for another turn if they want to keep the same state and speed (which will be the majority of cases I imagine). If not, they can click on the marker to change state and condition (if they click on the marker within one turn, the state and condition are visible but disabled, they can't be changed).

We might need a button to "End current turn": what if a platform reached its destination in the middle of a turn and it needs to stop there. Currently, they are not able to change state to moored or speed to zero within the turn.

**Comment by IanMayo** [comment]
Morning, good questions.  

> range circle appears on mouse down

That was my initial implementation. But, while playing with the logic yesterday, I grew to like the idea of pre-shading that area.  I think this "leads" the user through the next step in the process.

Also, as distance is _consumed_, we're already showing the achievable locations, rather than only showing them at the start of the next drag operation.

**Comment by IanMayo** [comment]
Done.
