### ISSUE TITLE
Messages Not Sent Until Page is Refreshed

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1451]
Messages are not being sent until the page is refreshed: 

https://user-images.githubusercontent.com/85491794/159981688-6c3507e1-816e-401e-99a7-0bef9371c850.mp4

**Comment by IanMayo** [comment]
Fixed in #1446

**Comment by ShendMikullovci** [comment]
Sadly, I've encountered this again. I was trying to see if I could at least receive the message on other user logins, but the blue screen wouldn't let me: 

https://user-images.githubusercontent.com/85491794/160182812-d58f9062-6c05-42ec-a9e8-e3a478eaae2b.mp4

**Comment by ShendMikullovci** [comment]
This seems to have been fixed: 

https://user-images.githubusercontent.com/85491794/162791202-6fbc8c14-ddf4-499c-b758-1e6861c56100.mp4

However, as you can see, the message is still being sent twice (refer to #1382). 

Closing this.
