### ISSUE TITLE
Control/Visibility Tab Disappears when Minimized

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1452]
The top left tab containing user assets disappears when minimized in New Test - Lots of Forces:

https://user-images.githubusercontent.com/85491794/159982980-d22e0b9d-97db-4c9c-9b55-302d9f54eaf9.mp4

**Comment by IanMayo** [comment]
Aah, ok. This may be a long-term issue. in real games the tab is revealed by clicking on an asset on the map.

@lebaphi  - can we change the `world-state` panel at the top-left so when it is collapsed, we still see the vertical tabs please?

**Comment by ShendMikullovci** [comment]
Hey guys! Just reviewed this. Works great, the tab doesn't disappear once minimized. 
However, I noticed that the user can only maximize the window by clicking on the closed tab: 

https://user-images.githubusercontent.com/85491794/160863656-4ded1c6b-e0f6-4750-b52d-6bd35fe6b5bf.mp4

As you can see, if I minimize by clicking Visibility, I can only maximize by clicking Control (and vice versa). The user should be able to open the window by clicking on either tab (Visibility or Control).
