### ISSUE TITLE
Can't View Own Assets

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1453]
I can't seem to be able to view my own assets on the mapping page (map or top left tab): 

https://user-images.githubusercontent.com/85491794/159984358-3f74f188-9420-4451-87d6-49ef8e56ece8.mp4

Am I missing something on the admin page?

**Comment by IanMayo** [comment]
This is still in development.

An Asset won't be visible on the map until it has a hex location.  The mapping for this game is a little mangled.  I think this is one for me to work on.

**Comment by ShendMikullovci** [comment]
I believe this has been fixed.
