### ISSUE TITLE
Mapping Channel Participant Issue

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1454]
So far, the main issue that is not allowing me to advance with #1400 lies in the mapping channel in the admin page: 

https://user-images.githubusercontent.com/85491794/160002518-35b32ad9-86e3-474f-bb55-2aa02d1624cb.mp4

As you can see, adding the forces onto the mapping channel doesn't work. I've tried a variety of methods to see if I can bypass the bug but so far I don't have anything.

**Comment by ShendMikullovci** [comment]
This bug seems to only be relevant for the mapping page so far. I can add permissions/participations with no problem for collab editing and chat channels.

**Comment by ShendMikullovci** [comment]
Just reviewed. Works great! Thanks, @IanMayo!

**Comment by ShendMikullovci** [comment]
Update: The bug has reappeared

https://user-images.githubusercontent.com/85491794/160862633-77bd2e83-607d-43df-b02d-2c33fc333f31.mp4

**Comment by IanMayo** [comment]
Oops.

**Comment by ShendMikullovci** [comment]
This seems to have been fixed. Thanks!
