### ISSUE TITLE
Message Templates Chips

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1458]
We currently present Message Templates (alongside Response Templates) as chips. However, the chip feature is usually used to indicate 1 or more choices for a feature, sort of like a tick button for different options in a feature. In our case, we're currently only allowing 1 Message Template per channel: 

https://user-images.githubusercontent.com/85491794/160185436-fffa96b4-0083-4dba-a42e-52eb5fa39e6e.mp4

Is it possible within the thought frame of the next games for the users to have the possibility of including multiple Message Templates within the same channel? If so, we should enable that and keep the chip feature. 

If not, I suggest we use a dropdown list, similar to the Roles drop-down: 

![Drop Down List](https://user-images.githubusercontent.com/85491794/160185515-02c8590f-6f1e-40f1-9047-2c67424862d3.png)

That way, we emphasize the idea that this feature only allows one option to be selected.

**Comment by IanMayo** [comment]
In _other_ channels we do allow multiple message template types to be provided.  The collab-edit channels are for a single business process - and just only one template has been required so far, for collab-editing channels (either `Request for Information channel`, or `Plan Course of Action channel`).

I'm happy leave this until we have a client that both requires it, and is willing to fund it.
