### ISSUE TITLE
Message Templates Chips Too Large For Text Box

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1459]
Some of the longer text chips are too large for the text box: 

![Request for Information Cut off](https://user-images.githubusercontent.com/85491794/160186164-51a7bf95-69e9-4880-b1cb-e0246d8e57e5.png)

![Request for Support Cut off](https://user-images.githubusercontent.com/85491794/160186191-8ae4f511-2b6a-4ccc-a537-31cf549f9415.png)

![Weather Forecast tight chip](https://user-images.githubusercontent.com/85491794/160186223-9d7feea1-dd66-4259-acbb-1d21611b89ef.png)

Lengthening the text box for just a couple of more pixels should do it. Also, the word "information" can be abbreviated to "info".

**Comment by ShendMikullovci** [comment]
Another solution could be expandable chips. Found this online: 

https://user-images.githubusercontent.com/85491794/160186898-7d71fe6b-7e09-41df-9bff-850bd5ea31e0.mp4

This could be useful since we use chips not only for message templates (where we present the available options) but also for our Add-Terms (Request Changes, Approve, Release). Similarly, the user can't view the entirety of the terms in those features: 

https://user-images.githubusercontent.com/85491794/160187316-e65c63c0-9858-4e71-ad21-4a2be638459a.mp4

Even abbreviated terms end up being quite spacious if they contain more than 1 word.

**Comment by IanMayo** [comment]
@lebaphi - are you able to check that we assign tooltip for the message template names?

That may help when the badge is wider than the space available.

**Comment by lebaphi** [comment]
sure @IanMayo

**Comment by lebaphi** [comment]
We can place the more-info icon on the top right of the name (as default) but:
-  We need to increase the chip height then we have more space to display the icon 
-  If the name it too long, the icon may be cut off so we need to handle the max name width based on the chip width. I think it's unnecessary.
So I found another solution to put the more-info icon as the video below, how do you think @IanMayo @ShendMikullovci ?

https://user-images.githubusercontent.com/26705621/162180584-eb694384-6442-4cdf-b913-005722998177.mp4
