### ISSUE TITLE
Platform Deletion Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1462]
When deleting a platform from Platform Types, it should disappear from the asset dropdown in Forces. Currently, it doesn't:

https://user-images.githubusercontent.com/85491794/160401458-8125bfdd-d268-4a46-bee7-667af4d88030.mp4

Also, you'll notice at the end I encountered a blue screen when clicking on the platform that should have been deleted in the asset dropdown.

Refer to #1433 for other encounters of blue screens.

**Comment by IanMayo** [comment]
Fixed in #1467
