### ISSUE TITLE
Clickable Force Field 

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1463]
Currently, the text boxes for Forces in the admin page react as the mouse hovers over them by showing the garbage bin. This is a great feature since it allows the user to delete a Force without having to click on it. However, the animation makes the user think that the entire field is clickable. Unfortunately, the user can only open the force when they click on the actual force title. 

https://user-images.githubusercontent.com/85491794/160403297-b90afd39-fb40-40d5-90fb-3f2033e85de7.mp4

It would be more intuitive for the force to open up wherever the user clicks inside the text box.

**Comment by IanMayo** [comment]
One for you please, @lebaphi

**Comment by IanMayo** [comment]
Hello @lebaphi - actually @ShendMikullovci wanted something different.

He wanted the whole of the list item to be the click-target, not just the text value.

So, could you switch back the cursor please, and change the UI so that the whole row is the click-target please?

**Comment by ShendMikullovci** [comment]
I guess the cursor can stay, since the entire row will be clickable?

**Comment by lebaphi** [comment]
sure, I will update as this way 😄
