### ISSUE TITLE
Forces List Reacts to Collapsible Elements

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1472]
As you can see below, the collapsible elements shrink the list width on the left. 

https://user-images.githubusercontent.com/85491794/160870278-1bb08dd5-0ed7-43dd-86b9-d049cbe3670c.mp4

I suppose this is because of the scrollbar on the right-hand side being introduced by the collapsible elements. 
Fairly low-priority, but it'd be smoother to have the screen stay still while the user is interacting with the elements.

**Comment by lebaphi** [comment]
it seems only occurs on windows, I will check it 🤔 

https://user-images.githubusercontent.com/26705621/161884984-052f5954-6694-4abc-9df4-bdc7d8a225e4.mov

and I think should apply the fix for platform types and channels tab.
