### ISSUE TITLE
Blue Screen Trigger

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1492]
I think I might have spotted a trigger for the Blue Screen. I was trying to do a review of one of the issues regarding the admin page quickly, so I went to https://serge-review.herokuapp.com/ and clicked on the admin page button before the page fully loaded (before the logo appeared). This significantly slowed the pages down and eventually led to the blue screen. I shut it down then tried to open it again, and everything is still slow: 

https://user-images.githubusercontent.com/85491794/162230583-766cd5ec-d93c-4087-808a-e202e1cf932a.mp4

As you can see, the logo no longer loads and the game page shows no options. The logo does load for the admin page but hitting enter triggers the blue screen. 

I'm thinking that trying to access the admin page through the admin page button before the landing page to https://serge-review.herokuapp.com/ fully loads, ends up crashing the game. This has happened to me last time I encountered a set of blue screens as well, but I wasn't sure if it was the same trigger.

Could you guys see if you can reproduce? 

Steps: 

1. Go to https://serge-review.herokuapp.com/
2. Click on the admin page logo BEFORE the SERGE logo loads.
3. Observe the time the pages need to load.

**Comment by IanMayo** [comment]
Thanks for capturing the detail @ShendMikullovci . I think you're actually suffering from the bug I captured here: #1486

Serge is failing to connect to the database every time.  @lilitkarapetyan has a fix almost ready here #1488 

Let's re-test this once that fix is merged.

**Comment by ShendMikullovci** [comment]
Update: 
Game Page: The blue screen hits before the game selection menu appears now.
Admin Page: Same so far, appears right after I hit enter.

**Comment by IanMayo** [comment]
@ShendMikullovci - this issue should be fixed now. I had failed to configure something properly.

**Comment by ShendMikullovci** [comment]
> @ShendMikullovci - this issue should be fixed now. I had failed to configure something properly.

No issues so far. Will keep you posted on Slack if anything happens.

**Comment by ShendMikullovci** [comment]
High Data froze and triggered the blue screen before launching:

https://user-images.githubusercontent.com/85491794/163254495-4220fa18-d141-43a9-944a-b7e0ac94fa0b.mp4

**Comment by IanMayo** [comment]
Working now. Just checked on `serge-review`.
