### ISSUE TITLE
Asset Tab Mapping Minimization/Maximization

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1499]
Hey guys! I noticed that the user can only maximize the asset window by clicking on the closed tab: 

https://user-images.githubusercontent.com/85491794/160863656-4ded1c6b-e0f6-4750-b52d-6bd35fe6b5bf.mp4

As you can see, if I minimize by clicking Visibility, I can only maximize by clicking Control (and vice versa). The user should be able to open the window by clicking on either tab (Visibility or Control).

_Originally posted by @ShendMikullovci in https://github.com/serge-web/serge/issues/1452#issuecomment-1083238650_

**Comment by IanMayo** [comment]
Well spotted @ShendMikullovci  :-)
