### ISSUE TITLE
Mark All Read Removal

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1502]
Given that we've added the mark all read button in most of the channels, I suggest we remove the older control: 

![Old Mark All Read](https://user-images.githubusercontent.com/85491794/163008321-d84cb68d-07fd-4c7a-a008-e2989d21d1ed.png)

And we replace it with our icons: 

![Channel Icons](https://user-images.githubusercontent.com/85491794/163008386-f344f5f8-7415-4973-9ee0-59d6d95fc854.png)

In cases where filtering and archive are not relevant, we don't include them. 

Let me know your thoughts.

**Comment by IanMayo** [comment]
Yes, sounds great.
