### ISSUE TITLE
Redundancy in COA form

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1511]
I was playing around with the COAs in Papafoxtrot and noticed how much space the countries/continents take up in the released form: 

![Europe 1 and 2](https://user-images.githubusercontent.com/85491794/163403632-b3688aa7-7953-45d3-8ace-ae08a71430f2.png)

![Asia 1 and 2](https://user-images.githubusercontent.com/85491794/163403649-0020aa04-5ff4-4371-b963-b7b40377d9e8.png)

I think it's not necessary to mention the continent names more than once, since the user should know that Germany and France are in Europe for example. And it would be more efficient to list out activities in the concerned locations rather than the Continent > Country schematic. 

Here's an idea of how it would look if we stuck to our current schematic: 

![Europe New](https://user-images.githubusercontent.com/85491794/163405490-2b14cb3a-32e5-41ec-b8b0-ecbe44973635.png)

This would save lots of space and reduce scrolling for the user.

Let me know your thoughts.

**Comment by IanMayo** [comment]
Thanks for observing and recording this @ShendMikullovci 

But, form design is down to the Game Designer - we don't have any control over it.  In this case, I think they were duplicating the layout of an existing paper form.
