### ISSUE TITLE
RFI Urgency

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1512]
These are our current RFI Urgency options:

![RFI Urgency](https://user-images.githubusercontent.com/85491794/163407204-8130d76a-9397-4de4-98e2-d8afdf027b80.png)

Once the RFI is sent out, the urgency is shown in the form here: 

![Urgency RFI](https://user-images.githubusercontent.com/85491794/163407483-4ecd75ad-8798-4fce-b3cc-a037e4580207.png)

I think it would be of value to highlight message urgency in the channel itself. That way, the user's attentional resources would be guided towards more urgent matters quicker and easier. What do you guys think?

**Comment by IanMayo** [comment]
The layout of the form is down to the game designer, it's not part of Serge software.

Aah. but the Game Designer can indicate which `Additional channels` should be displayed in the `Collab-edit` channel.  If we allowed some free-text in that field, the Game Designer could add `URGENCY`.

**Comment by ShendMikullovci** [comment]
Also, what is the difference between priority and urgency? Can an RFI have high priority but not have a response required urgently?

**Comment by IanMayo** [comment]
The design of a form is outside our responsibility.  When I'm onsite providing user support I can offer suggestions on message layout, but this isn't an issue for us,
