### ISSUE TITLE
Can't select channels in Game Admin pages

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1527]
I'm in Game Admin pages for `small wargame`.

I can select other `Forces` but I can't select other  `Channels`:

https://user-images.githubusercontent.com/1108513/165275861-65f4fdd2-fe0d-47ca-a372-7db8d42cebcf.mp4

**Comment by ShendMikullovci** [comment]
Was there just now. Bug didn't happen to me. The fix should be functional.

**Comment by IanMayo** [comment]
Fixed in #1528
