### ISSUE TITLE
Specify which roles can control which assets

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1531]
This is a big one.

Currently, we assign one role per force with the permission to plan routes for the assets.

But, for a future wargame (WATU) we wish to assign one asset per role. We can _currently_ only do that by creating a force for every asset/role.

Another way of handling this would be for the Game Designer to indicate which role can control which asset. If no asset is. specified, then that role controls all un-controlled assets for that force.  (this will accommodate our current model).

This would also allow control of a large force to be separated by environment, platform-type, or task-group commander.

So, I _think_ we would have these changes:
- [x] in the `mapping` channel editor, each row would have: `Force`, `Role`, `Assets`.  The `Assets` drop-down would contain a list of unassigned assets for this force.  It would be multi-select, and include `All` and `None`  entries.
- [x] change to `ChannelMapping` structure to support the above data model
- [x] change to `watuwargame.mock` object to reflect the above data model
- [x] new helper method to return the uniqid's of the assets that this role can control. Note: the method will take the whole `ForceData` object, since it may need to determine which assets are controlled by other roles
- [x] change to `Routes` object to include flags for if a route/asset can be controlled by the current player
- [x] change to `mapping` component for new `controls` logic. 
- [x] change to `handleForceDelta` to allow multiple roles to submit planned routes.
- [x] change to `world-state` panel to show which assets have submitted routes (ready for adjudication).

We should also come up with a way of showing the current player which asset(s) they can control.  Hmm, maybe wash-out assets that the player can't control?

** Update **
Change of plan. We have an outstanding feature requirement, to allow player(s) of one force to control assets of another force. The example for this is where `green` assets are actually controlled by `game control` of the `umpire` force. We're going to support this by allowing a `mapping participant` `role` to control assets of another force.  Or, to control all unclaimed assets of another force.

We'd support this through some special values in the `controls` column. It would be `controls-all` plus the `force['uniqid']` for the force in question.

In doing this, we'd have to look for existing instances of `controlled-by`, since we won't be _giving_ green force assets to `umpire`, we'll be indicating that `game control` can `control-all` for green force.

**Comment by ShendMikullovci** [comment]
>If no asset is. specified, then that role controls all un-controlled assets for that force.

Could this end up being problematic upon implementing? Any scenario where we end up with a user that is not supposed to control any assets, controlling all unassigned ones? If so, should we "force" GC to specify assets for every role, eventually selecting a "None" option for the roles that might not control an asset?

**Comment by ShendMikullovci** [comment]
I think it would also be smart to show the role controlling an asset in the force here: 

![Force SC](https://user-images.githubusercontent.com/85491794/165830413-c1361c97-988a-48ef-9a06-e545fd813d18.png)

**Comment by IanMayo** [comment]
I see the logic @ShendMikullovci  - but initially I only see a justification to have "asset-controller" in one place.  In the "Channels Tab" we're already giving roles different permission/access levels.  That seems the _more_ obvious place to make these changes.  From the `Channels tab` it's relatively quick/easy to let a player control multiple assets.  That would be cumbersome to do from the `Assets` tab.

**Comment by ShendMikullovci** [comment]
> That would be cumbersome to do from the `Assets` tab.

Absolutely. That's why I suggest it should only be shown there, and not editable. The value I see in that from an experience perspective is that the GC could need that information while reviewing assets.

**Comment by IanMayo** [comment]
Now sorted.
