### ISSUE TITLE
On new State of World animate markers to new location

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1538]
At the end of the adjudication phase, the new state of the world message is pushed out to all players.

In this message, each asset will have a new location, plus a history of steps from the location at the previous turn.

We should animate the passage of the asset along the last turn's history to the new location.  This will help players understand what has happened in the turn.

There's a plugin to do this here: https://gitlab.com/IvanSanchez/Leaflet.Marker.SlideTo

But, we're using react-leaflet, so we may not have access to the same object model.  Oh, and we may not be travelling in a direct path from start to end.  Aah, that's ok - we just animate the movement along the turn steps.  We can use the turn step speed to sort out how long the animation should take.

**Comment by ShendMikullovci** [comment]
> We should animate the passage of the asset along the last turn's history to the new location. This will help players understand what has happened in the turn.

I do agree in theory, but in practice it might be difficult to play out, especially if there's a large number of assets in movement. A solution would be to animate the assets one by one. The animation would take time, therefore we could provide them with a "skip current/all animation" button if necessary. 

Or, we could combine it with the slider feature you mentioned in #1540.
