### ISSUE TITLE
Umpire and Player annotations

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1539]
A lot of game context is passed by the map markers plus the supporting messages.

We've added map markers, which can represent events in the game at fixed locations.

Players and umpires could add more context to the map through the user of drawing features:
- text boxes
- lines
- polygons

These features would be stored on their own drawing layer in the game, and passed as part of `daily orders` and `state of world`.  

A library to support such a capability is here: https://github.com/geoman-io/leaflet-geoman

**Comment by ShendMikullovci** [comment]
Love the idea. We could add a visibility feature to it as well to allow the user to view the annotations whenever they choose to. Great addition.

**Comment by ShendMikullovci** [comment]
Icon ideas: 

![Compass Icon](https://user-images.githubusercontent.com/85491794/167951841-efe570e2-9a11-4349-bd2c-9c91affc1da4.png)

![Pen Swirl Icon](https://user-images.githubusercontent.com/85491794/167951853-f6e920b1-dfc0-4a31-940c-bb06a17c0bd3.png)

![Pen Ruler Icon](https://user-images.githubusercontent.com/85491794/167951865-27c25b1d-9436-4166-9565-23daf5cbd1ce.png)

![Shapes Icon](https://user-images.githubusercontent.com/85491794/167951884-5fe57ddb-a7b2-474a-bdc1-a7a39a31e9bc.png)

![Shapes Icon 2](https://user-images.githubusercontent.com/85491794/167952124-3d4c1cbf-8e23-4f1f-a058-3cc03f211dd4.png)

Depending on how we approach the feature, we could go for different keyword icons (tools, toolbox, etc.).

**Comment by ShendMikullovci** [comment]
Question: Would a feature such as a distance counter be of value? A tool that would measure the distance between, say, 2 assets (in time and/or miles/kilometers)? If I'm not mistaken, we do have the feature where we show the user how long an asset can take to get from point A to point B?

**Comment by IanMayo** [comment]
The triangle/circle/square icon looks great - though we're restricted to the icons in the free `font-awesome` package.

No we don't show the player how long a journey takes between two points. The closest to this is that we show them how far an asset can travel in a turn, according to its speed and the turn length.

The distance measuring tool would be of some modest value,  though no players have requested it.

**Comment by ShendMikullovci** [comment]
> The triangle/circle/square icon looks great - though we're restricted to the icons in the free `font-awesome` package.

This one is the closest I found on font-awesome:

![Shapes Icon](https://user-images.githubusercontent.com/85491794/168550260-620c305c-2b12-48e7-89dc-13588c09ccfc.png)

**Comment by ShendMikullovci** [comment]
Here's an idea:

If we go with the font-awesome icon, this is how it'd look.

![Drawing Feature Base](https://user-images.githubusercontent.com/85491794/168612086-dbfa8a3b-f1bd-421c-9a7a-255ad22fff17.png)

Clicking it would darken the button as the following drop-down appears:

![Drawing Feature Mapping](https://user-images.githubusercontent.com/85491794/168612388-07f8979f-baa4-438e-bd4d-02b0c5a2c09e.png)

If the user selects the line tool, then the line icon replaces the shapes icon in the general toolbar to emphasize its selection. The cursor turns to a cross:

![Drawing Feature Mapping 2](https://user-images.githubusercontent.com/85491794/168612628-407af523-14e9-4c87-99f0-5ece302911bd.png)

If the user is to click on the icon again, the drop-down shows the selected item in highlighted in grey alongside the 2 other tools:

![Drawing Feature Mapping 3](https://user-images.githubusercontent.com/85491794/168612942-7b9a39d2-2a22-455b-8b79-0d72d8542704.png)

Notes:
- I thought of adding a cursor button but we could also automatically revert to the cursor once an action with one of the tools is completed. Let me know if you'd like the cursor button in the design as well.
- I also like Google's line icon in Drawings if you'd like to use it instead:

![Line Icon](https://user-images.githubusercontent.com/85491794/168613982-f4f8009a-1705-42ef-b5eb-28e09011a048.png)

- If you'd like the feature to mimic the behavior of the feature in the leaflet you found above more closely, let me know. Didn't want to copy - paste it for security.
