### ISSUE TITLE
As a player (or umpire) I wish to replay turns

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1540]
It can be useful for players to replay previous turns, to remind them of what has happened.

Similarly, it can be useful for umpires to run through the current turn - double-checking where interactions could happen.

To do this, we'd need the following:
- an optionally visible slider control (see below)
- a specification of whether we're moving through the whole game, or just the current turn
- a label for the time of the current slider position
- new logic to position asset markers at the specified time, possibly including interpolation along the path followed.

Here is a leaflet slider control: https://github.com/Eclipse1979/leaflet-slider

**Comment by ShendMikullovci** [comment]
I've read studies proving that providing sliders (or other time control features) makes the users feel more invested and have a generally better experience using interactive media. I don't see why this wouldn't apply for SERGE.
