### ISSUE TITLE
Display legend for current assets/markers in use

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1541]
Hopefully the asset/marker icons are self-describing, but we may not be able to assume that.

So, we could introduce an optional `legend` panel.  A toggle in the toolbar would control whether the legend is displayed.

When displayed, Serge would run through the current assets and map-annotations, and display an icon/label for each one visible to the current player.  The component would be sensitive to `playerForce` - so it changes when the umpire does `view as` another force.

Here is a component that could provide the feature: https://github.com/ptma/Leaflet.Legend

**Comment by ShendMikullovci** [comment]
I like the idea. I'd suggest we present it in the top left panel containing the visibility/control features to avoid screen usage.

**Comment by IanMayo** [comment]
An alternative option is a question mark in the mapping toolbar at the top right.  Click the icon and the legend is shown. `x` to close it.  I don't think it will get used very often at all, but it may just save a player being confused.

**Comment by ShendMikullovci** [comment]
Here's how that could look: 

![Questionmark Icon Mapping](https://user-images.githubusercontent.com/85491794/167576638-e9dfe8fc-910e-4162-b464-790e63aff95f.png)

I found the question mark icon to give me more of a "Help" or "Tutorial" feeling to the feature, which is not what we're really looking for. So I went digging and found this icon on FontAwesome: 

![Map Location Pin Icon](https://user-images.githubusercontent.com/85491794/167576821-8b1855b1-a905-4fb7-a6f7-cd29949b7903.png)

I think it fits the description better for a legend feature. Here's how it looks on the toolbar:

![Map Location Icon Mapping](https://user-images.githubusercontent.com/85491794/167576949-eaad762c-bb33-4040-aa81-b4b053b415c6.png)

Let me know your thoughts on the icons.

Whichever direction we choose to go, clicking on the legend button leads to the following window: 

![Mapping Legend](https://user-images.githubusercontent.com/85491794/167577090-aff95561-2448-4938-a0ef-710fa8fdffd0.png)

Clean and simple legend with only the X to close it. I thought of adding a short description line as well if necessary and it refines the legend: 

![Mapping Legend with Descriptions](https://user-images.githubusercontent.com/85491794/167577329-a3d8e0a3-ab08-498a-8dee-a8a596216806.png)

Let me know what you think!

**Comment by ShendMikullovci** [comment]
Also, let me know if you'd like to see different locations for the button. I automatically put it on top of the toolbar since it pertains to the content of what the user sees in the mapping page at first glance.
