### ISSUE TITLE
Capture screenshot of assets in play

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1547]
For the mapping walk-through we intend to show an image of assets in play, to introduce players to them.

When we have a suitable map in usage, @IanMayo should grab a screenshot, and modify the mapping tour to include it.

**Comment by IanMayo** [comment]
Image attached.
![map_image](https://user-images.githubusercontent.com/1108513/178303445-7b638392-bcb6-46ef-9e1e-58ba9501fd0a.png)

**Comment by ShendMikullovci** [comment]
Image present in Small Wargame Laydown.
