### ISSUE TITLE
Need force indicator other than red/green colors

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1562]
I'm viewing a presentation on accessibility.  Apparently 20% of males are red/green color blind.

We use red and green colors frequently for red/green forces.  _Maybe_ we should consider some other visual clue, too.

We use color in these places: 
- map icons
- `visible to` in map forms
- "sender force" color strip on messages
- "my force" at bottom-right of screen

We should investigate places where we only use color to indicate force type.  In these instances, we should do something like putting the first letter of the Force Name in there somewhere.

**Comment by ShendMikullovci** [comment]
Love the focus on cognition & behavior! While it's a great idea, we should also consider asking the participants about color blindness and other possible conditions in our survey (dyslexia comes to mind for example, or disgraphia, etc.) since SERGE heavily relies on visual cues.

**Comment by IanMayo** [comment]
The set of players will change for each game - though the Game Designer may work on several games.

I think we're best off working with Industry Standard percentages of users with sight problems.
