### ISSUE TITLE
ID versus FROM

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1568]
What is the difference between the ID and From columns? 
I noticed that in Papafoxtrot, RFIs and COAs sent by Senior Blue all have different IDs. Is that on purpose?

![ID vs FROM](https://user-images.githubusercontent.com/85491794/170273612-12addc38-ae06-4cbf-aeeb-af8fe24cc37c.png)

![ID vs FROM 2](https://user-images.githubusercontent.com/85491794/170274168-6d2f5502-60ec-4d1c-8574-197c1506c3fb.png)

**Comment by IanMayo** [comment]
Sure, each RFI has a unique ID.  They are issued sequentially, per-force.  Note: a message may "evolve" as it gets managed through the collaborative working process, but it's ID will stay the same.

In the game, players refer to "Blue-4" as a way of ensuring they're dealing with the correct message. This is particularly important when several have similar titles.
