### ISSUE TITLE
UX for mapping constraints

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1579]
While it has been hard-coded in the games so far, we need to allow the Game Designer to specify the constraints on the mapping.

These are the fields we require for the mapping:
* **Bounds**: These are the top-left and bottom-right corners of the map to show. It should be two pairs of values, taking - say a number of degrees, with up to two decimal places (e.g. `12.25`)
* **H3 Resolution**: this is the hex cell grid size to use for the [H3 grid](https://h3geo.org/docs/core-library/restable/) (integer, from 1 to 10)
* **Tile Layer**: URL of path to where backdrop tile images may be found
* **minZoom**: the minimum zoom level, preventing the player from zooming out any further. (integer, from 1 to 12)
* **maxZoom**: the most a player can zoom in
* **maxNativeZoom**: the limit of zoom on the backdrop tiles. After this limit is reached, the smaller one will get zoomed appropriately
* **gridCellURL**:  path to file where grid cell styles can be retrieved.  So, for each cell there will be a style such as "1 - Land", "4 - Storm Areas", "12 - Fishing Area"
* **polygonAreasURL**:  for areas covering huge areas, plotting a simple set of polygons for each terrain type (land, deep-water, etc) is quicker than plotting all of the discrete hexes.  A scientist was able to do the clustering for his hex cells, and provide it here - which made the task of rendering such a large area much easier.

We have some existing thoughts on this, and the overall layout of "Overview" in #991 & #1425. We should consolidate the existing designs controls with new controls for the above set of fields.

**Comment by ShendMikullovci** [comment]
I'm afraid I'm not sure what all of these controls represent in the game. Could you clarify further please?

I do have an idea on how to present them though. I thought of adapting the "Platform Types" display to minimize space consumption. Since this is mostly about controls relative to proportion, we can use icons that are self-explanatory. 
Here's an idea: 

![Mapping Constraints](https://user-images.githubusercontent.com/85491794/171236393-682ed632-a079-4c48-9dd7-b2cd5f8007d5.png)

The bounds represented by the corner icons, the 3 zoom types and H3 resolution (?) next to their own value integers. 

Upon hovering, we'd show a small description of the icons.

Let me know your thoughts.

**Comment by IanMayo** [comment]
aah, good point. I did imagine these controls going on the overview tab. But, since they only apply to mapping, they could go in the top half of the mapping channel editor.

For collaborative editing, we have controls at the top of the page - so we would follow that model.

**Comment by ShendMikullovci** [comment]
It does look better: 

![Mapping Constraints](https://user-images.githubusercontent.com/85491794/171262774-929c426d-5790-4e60-998f-4e6aa1488a62.png)

Could you explain these please?: 

- H3 Resolution: this is the hex cell grid size to use for the [H3 grid](https://h3geo.org/docs/core-library/restable/) (integer, from 1 to 10)

- Tile Layer: URL of path to where backdrop tile images may be found

- gridCellURL: path to file where grid cell styles can be retrieved. So, for each cell there will be a style such as "1 - Land", "4 - Storm Areas", "12 - Fishing Area"

- polygonAreasURL: for areas covering huge areas, plotting a simple set of polygons for each terrain type (land, deep-water, etc) is quicker than plotting all of the discrete hexes. A scientist was able to do the clustering for his hex cells, and provide it here - which made the task of rendering such a large area much easier.

What is their use concretely, so I know how to think of and design them?

**Comment by IanMayo** [comment]
> H3 Resolution: this is the hex cell grid size to use for the [H3 grid](https://h3geo.org/docs/core-library/restable/) (integer, from 1 to 10)

The Game Designer chooses the size of hexagonal cell for the game.  This will be decided on the level of detail for the game.  In a past wargame they were 36 mile (50km?) cells, with each turn taking one week.  In another game they were 8km cells, with each turn taking 30 minutes. In the next game they may be 1km cells, with a 5 minute time step.  These are all decisions for the Game Designer.  Hmm, I guess that instead of a drop-down of 1 to 12, the label could include the cell radius, so like `5 (4.5km radius)`.  More background on H3 mapping [here](https://eng.uber.com/h3/)

> Tile Layer: URL of path to where backdrop tile images may be found

This is a path to the folder containing the pyramid of images that make up the backdrop. Read more [here](https://www.researchgate.net/figure/Sketch-map-of-image-pyramid-structure_fig2_311423420).  These get created outside Serge. The Game Designer will follow instructions to copy them into a specific folder in the SErge installation, then provide the path in this box, like "data\atlantic_2022`

> gridCellURL: path to file where grid cell styles can be retrieved. So, for each cell there will be a style such as "1 - Land", "4 - Storm Areas", "12 - Fishing Area"

Depending on the wargame, the Game Designer may want to provide different types of cells. They will certainly want to provide "land" or "sea" - to allow proper routing of ships. But, they may also want to highlight areas of deep/shallow water, areas with high levels of fishing activity, or others.  This will be developed in a data-file containing a list of "a22342adfdsff" H3 cell references, then showing the cell-type for that cell.

> polygonAreasURL: for areas covering huge areas, plotting a simple set of polygons for each terrain type (land, deep-water, etc) is quicker than plotting all of the discrete hexes. A scientist was able to do the clustering for his hex cells, and provide it here - which made the task of rendering such a large area much easier.

This is another Game Designer provided datafile. It allows quicker plotting of large areas of ocean.  The Game Designer runs some maths on the "gridCellURL" datafile (above), and comes up with a simpler set of regions.  For example, there may be a polygon around the edge of a patch of dark water, or land.  Serge can plot this much quicker than shading lots of individual hexagons.  As we zoom in, we may switch to shading individual hexes instead (since there are fewer of them).

I hope the above guidance helps.

**Comment by IanMayo** [comment]
Here are the types of control I think we need:

* **Bounds**: 4 text boxes, in two pairs.  Will allow for 5-6 digits  (e.g. `12.25`)
* **H3 Resolution**: text box, with up/down buttons, 1 to 12
* **minZoom**: text box, with up/down buttons, 1 to 12
* **maxZoom**: text box, with up/down buttons, 1 to 12
* **maxNativeZoom**: text box, with up/down buttons, 1 to 12
* **Tile Layer**: text box
* **gridCellURL**:  text box
* **polygonAreasURL**: text box

**Comment by ShendMikullovci** [comment]
Here's an idea:

![Mapping Constraints](https://user-images.githubusercontent.com/85491794/171499705-4a99435c-7f57-450f-9c42-69e6ab7850ad.png)

- Bounds: Four corner icons on the left. All on the same cloud. Text boxes next to each.
- H3: Hexagon icon, next to a text box with Up/Down buttons for the values.
- Zooms: Empty Spyglass is Max Native, Plus Spyglass (Zoom In) is Max Zoom, Minus Spyglass (Zoom Out) is Min Zoom. 
- Tile Layer: Triangle icon. Looked up a free Pyramid icon to match the description in the article you sent but they're only pro version. 
- GridCell: Grid icon, with a longer text box to contain the entire URL (suppose it's a longer text?)
- Polygon: Polygon icon, with text box.

We can also opt for a more vertical look: 

![Mapping Constraints Vertical](https://user-images.githubusercontent.com/85491794/171501845-3a20ba27-4ea9-4758-a5ce-304e1322a769.png)

Small preference over the vertical one. Let me know your thoughts.

**Comment by IanMayo** [comment]
Thanks for that work @ShendMikullovci .

For the top-left and bottom-right coordinates, they are naturally grouped into top-left / bottom-right pairs of latitude/longitude text boxes.   My guess is that we could represent this in a grid layout.  The rows start with the top-left and bottom-right icons you found.  Above the columns would be  icons (or text-labels) for latitude and longitude:
```
        [Lat] [Long]
[TL]    [   ]  [   ]
[BR]    [   ]  [   ]
```

For the other shape labels - I'm afraid that even though the "Game Designer" is a "Power-user", I don't think they will guess what the fields represent. I think we need the full text label. The extra icon could be provided _aswell_, if you think that will still help.

Tile / Grid / Polygon text boxes would all be a similar length. Here are examples of _real_ values in these fields:
![image](https://user-images.githubusercontent.com/1108513/172198112-f88c8707-3293-4631-a3dc-8935df7ba78e.png)

**Comment by ShendMikullovci** [comment]
Thanks for the feedback.

The reasoning behind the icons was to limit space consumption. Here's one with the icons and respective title labels.

![Mapping Constraints](https://user-images.githubusercontent.com/85491794/173245187-ce8ea901-3b02-4e43-bede-9bdafbb926af.png)

Here, the user would be forced to scroll down for Participants and Messages.

**Comment by IanMayo** [comment]
Hello @lebaphi - I'd like to get you started on this, please.

The new UI (above) will be in the `Mapping Channel` editor, and provide the data necessary for `MappingConstraints` object in `ChannelMapping`.  The `Proportions and Constraints` section should be collapsible.  So, once the constraints are sorted the Game Designer can choose to collapse it, and concentrate on the participants.

Hmm, actually - by default let's have this new panel collapsed. But, when collapsed it should show some summary text. If you include the 3 `Zoom levels` in the summary, I will work on a way to show as much info as possible, while still being legible.

The `Small wargame` game can be used for testing it.

**Comment by lebaphi** [comment]
okay @IanMayo 👍🏻

**Comment by ShendMikullovci** [comment]
Hi guys! Thanks for your work here.

![New Proportions](https://user-images.githubusercontent.com/85491794/178759636-9bf18cfe-ec80-4267-9640-4d537d90e226.png)

Couple of things: 

1. Why are "Bounds, Tiles, Cells" mentioned in the collapsible tab for Proportions and Constraints? Seems to me it overcrowds the tab a little and makes the title hard to read.
2. Can we stick to outlined, instead of filled icons? I believe it would look smoother. The pitch black is a little tough on the eyes and is not a color we usually use. I suggest our usual grey for neutrality.
3. Can we increase the size of the zoom icons (all three) to match the sizes of the other icons. They're a little tougher to spot than the others.
4. None of the sentences in the info panels shown when clicking on the (!) marker have periods at the end. I suggest we add periods.
5. Can one of you explain what the @ (Tile layer attribution string) is? 

Thanks!

**Comment by IanMayo** [comment]
I can answer some :-)

1 - these are ticks to show if the essential items have been provided. The Game Designer can check the mapping is in order without expanding to view the contents.
4 - sure
5. For some sets of background mapping (OpenStreetMap or Google Maps) the original providers want users to give an attribution string, to acknowledge (or _give credit to_) the provider.

**Comment by ShendMikullovci** [comment]
> 1 - these are ticks to show if the essential items have been provided. The Game Designer can check the mapping is in order without expanding to view the contents. 

Oh, OK. Can we have it shown like this? :

![Bounds tiles and cells](https://user-images.githubusercontent.com/85491794/178762850-b60f4836-fd8a-49c2-b9f5-5b5184c99e61.png)

Easily accessible information, without interferring with the tab title. Leveling them together also puts them on the same eye-line making it easy to spot both.

> 5. For some sets of background mapping (OpenStreetMap or Google Maps) the original providers want users to give an attribution string, to acknowledge (or _give credit to_) the provider.

OK. Thanks!

**Comment by IanMayo** [comment]
> Oh, OK. Can we have it shown like this? :

Yes, good suggestion.

**Comment by IanMayo** [comment]
One small task for @lebaphi , please.

Could you please change the collapsible item in the "Mapping" channel so the tick boxes are right-aligned, like this:
![image](https://user-images.githubusercontent.com/1108513/180819569-67fe54ff-5ab3-4b83-9d6f-10e868b0094c.png)
