### ISSUE TITLE
Rename Objectives Tab

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1580]
Considering most forces have their color name in the force name, as well as the fact that we color code the forces and show icons, I suggest we rename the tab on the bottom right to Objectives: 

![Rename tab to Objectives](https://user-images.githubusercontent.com/85491794/171163999-7aaf2e26-6f87-40a2-a3ff-4bc1ca04c69a.png)

This shouldn't lead to any confusion towards what force the user belongs to, and should emphasize where the objectives tab actually is, which is currently a little hidden.

An alternative solution could be including force name and objectives label in the button, if we think it's necessary to mention force name.

**Comment by IanMayo** [comment]
For our mock data, forces names tend to focus on the color. But, in real wargames they have taken the names of nations.   A player (particularly an umpire/facilitator) may have multiple Serge tabs open - and will rely on the Force Name label to know if this is the tab for "France" - "Logistics", or "Belgium" - "Logistics".

Even with our dummy data, we can have "Red-1" and "Red-2" forces.  WE need the `1` and `2` to be clear which force it is.

**Comment by ShendMikullovci** [comment]
We've decided to let this be.
