### ISSUE TITLE
Composite Markers

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1582]
Me and Ian noticed that when there are multiple markers in the same cell, they stack up on top of each other, and the ones below get no visibility. Unfortunately I can't post a screenshot here, since I only have access to the old version of the game, but basically we thought of introducing a composite marker in the shape of a black (dark grey?) square with the number of the markers in the cell displayed in its center. It would look something like this: 

![Composite Marker Only](https://user-images.githubusercontent.com/85491794/171262054-993e762a-fc9b-4f29-ae0a-53cd5fcfe75f.png)

![Composite Markers](https://user-images.githubusercontent.com/85491794/171262098-96ad6944-7189-455c-be00-16a774477976.png)

I suggest we make the circle slightly smaller than the asset icons, to further distinguish between them. 

Note from Ian: I think we agreed that if all the assets are from one force, then we should shade the composite counter in the color for that force.

**Comment by IanMayo** [comment]
Another option is to adopt a Leaflet clustering plugin, such as qCluster

**Comment by ShendMikullovci** [comment]
![Leaflet](https://user-images.githubusercontent.com/85491794/184919728-c23768d8-1c5d-44a8-9d1f-e0ed3a3cb1d4.png)

Something like this?

**Comment by ShendMikullovci** [comment]
> ![Leaflet](https://user-images.githubusercontent.com/85491794/184919728-c23768d8-1c5d-44a8-9d1f-e0ed3a3cb1d4.png)
> 
> Something like this?

The advantage of this design is that color and size would combine to show number of assets and clutter size. The disadvantage would be that we already have quite a little bit of color on the map, so we'd have to adapt. What do you think @IanMayo ?
