### ISSUE TITLE
Windows & Linux executables failing

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1592]
I've run `yarn pkg-build` on the `develop` branch.  I then copied the Windows executable to a `Windows 11` Virtual machine.

When I run the executable from `Windows Explorer` it silently fails.

When I run it from Command Prompt, it fails with this error:
![image](https://user-images.githubusercontent.com/1108513/172627836-c488a566-1613-4335-94d0-bbf6bd9a04e8.png)

The users are planning on running a wargame next week, and are keen on getting a test-able version on their network.

Ooops, it's also failing on Linuex:
![image](https://user-images.githubusercontent.com/1108513/172630857-6381c215-e44a-460a-aaf0-a25d9a59e0cb.png)

Note: I also downloaded a CI build from this PR, and it failed with the same error:
https://github.com/serge-web/serge/actions/runs/2455919188

Ok. I ran the CI build on an old Windows 10 PC, and got this error. It gives more detail:
![image](https://user-images.githubusercontent.com/1108513/172825342-5d2b77e4-4091-4c81-8edc-81fc4d0ad6f3.png)

**Comment by IanMayo** [comment]
Here's a recording of the issue on MS-Windows:
![screencast](https://i.gyazo.com/4f9b6365964da0742c1bdf8d8a8d7dc3.gif)

**Comment by IanMayo** [comment]
Ok, @lebaphi resolved it:

> I think the root cause is the node_sqlite3.node file is not consistent with node 16, 
> because it was build with node 14 (in executable/sqlite3.nodes)
> so we need to copy the new one which consistent with node 16 then it will work

Phi can produce `sqlite3.node` files for `macos` and `linux`, and hopefully @lilitkarapetyan will produce one for `windows`.

@lebaphi - if you zip up the `.node` files and attach them to this issue, then @lilitkarapetyan  can include them in a PR.

**Comment by lebaphi** [comment]
@IanMayo I just have the file for Macos, I think @lilitkarapetyan has files for windows and linux 👍 

[node_sqlite3.node_macos.zip](https://github.com/serge-web/serge/files/8896112/node_sqlite3.node_macos.zip)

**Comment by IanMayo** [comment]
Thanks @lebaphi - I'm just finishing the linux version.  I'll pass it to @lilitkarapetyan  in her Pull Request.
