### ISSUE TITLE
Notification Counter Responsive to Own Messages in General Chat

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1598]
I think it'd be best if the notification counter only responded to others messages to reduce cognitive load on users.
It feels redundant and counter-intuitive to have notifications for your own messages. 

https://user-images.githubusercontent.com/85491794/173696283-cb8f56b3-ce66-45b0-9abd-2c1c692a5df3.mp4

Side-note: I noticed that hitting enter sends you to a new line instead of sending the message, forcing the user to click on send by mouse. Is this necessary? What is the nature of the messages to be sent here? If the messages won't be long and complex, I'd suggest having Enter send the message.

**Comment by ShendMikullovci** [comment]
Same for RFIs, COAs and other messages I suppose.

**Comment by IanMayo** [comment]
Yes, wise decision.

**Comment by ShendMikullovci** [comment]
The message issue is still relevant:

[e1e122e8-a0ca-4643-abbd-96ad97708cb8.webm](https://user-images.githubusercontent.com/85491794/189439252-f9145565-e791-4def-9b94-c510b0bcb52f.webm)
