### ISSUE TITLE
Channel Intro Issues

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1599]
1. Step 1: The step refers to channels as "the game channels in the left" but they occupy a very central part of the screen, and I fear the dimming of the right hand side is not quite intuitive. I'd say we call it the center of the screen.

![Center Screen](https://user-images.githubusercontent.com/85491794/173698888-fce7c409-5859-4bcd-8c27-bfd5ff49e64c.png)

2. Did we want to include animation for step 3 (dragging and dropping channels/vertical bars to show users how to do it?)?

**Comment by ShendMikullovci** [comment]
I don't see how the fix for #1547 through #1665 closes this issue?

**Comment by IanMayo** [comment]
Aah.  The fix at #1665 amends the tour text.
![image](https://user-images.githubusercontent.com/1108513/178758930-aa982cda-81ba-44c6-93d8-6c2cd66e5246.png)


We don't (yet) have the animation for dragging bars. Re-opening.
