### ISSUE TITLE
Force Icons & Names

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1602]
![Force Icons](https://user-images.githubusercontent.com/85491794/173699790-c81c9aeb-3674-420c-aff2-a6ed4186873e.png)

Force icons under the channel tabs should show the name of the Force once hovered upon. 
What is their purpose in that position?

**Comment by IanMayo** [comment]
They are to show which forces are present in the channel.   So, if there isn't a Red icon, then Blue knows it can talk to White in there without Red knowing.

**Comment by IanMayo** [comment]
Fixed in #1641
