### ISSUE TITLE
Main Menu / Quit Button

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1609]
We currently don't have a "Quit" or "Go to Main Menu" button. On my end, I needed it to switch between war-games to test features and I was wondering if it could be a valuable addition to the game for the client? 
I've noticed that sometimes, hitting X and restarting the game brings you back to where you left off and other times, it forgets. By implementing a "Quit" or "Main Menu" button, we could make sure to ask the user if they want to quit and let them know they might lose progress (or suggest they save game). 
Would it be of any value?

**Comment by IanMayo** [comment]
Yes @ShendMikullovci - once we have the "restart wargame" functionality, we will want players to return to the Player Welcome page.

But the UI "affordance" for the home button isn't obvious. Here is our screen:
![image](https://user-images.githubusercontent.com/1108513/174643852-ab86cbbf-db4d-4849-9d5a-9cb79ae13394.png)

I can think of these possibilities:
1. A new (home) icon that goes at the top-left, next to the "VHF C16" tab.  But, when there are lots of tabs, this space becomes precious
2. The "Small Wargame" could become clickable - taking the player to the welcome page.
3. A "Home" icon to join the others to the right of the wargame title.
4. A "home" icon inside the Turn Description box ("Turn 3 - planning phase ...").
5. An "Exit" button at the bottom right, to the right of "White Force".

For all of the above, it's probably worth using a check-dialog to ensure they really want to drop out of the wargame. We don't really need to worry about losing any data - when something is sent, it is stored on server.  Only incomplete messages would be lost in going back to the welcome page.

**Comment by ShendMikullovci** [comment]
Here's two different variants: 

![Home Page Button Top Right](https://user-images.githubusercontent.com/85491794/174675815-b07e176f-4394-4428-9be3-02d57a650475.png)

Intuitive icon with an intuitive location. The only "problem" here is that a Home button is not necessarily a Quit/Restart button. 

![Quit Button](https://user-images.githubusercontent.com/85491794/174676079-e2ee1e02-292d-45ea-b4e6-c23ff7523773.png)

Also an intuitive button, less of an intuitive location for a button that is usually placed lower and somewhat hidden. Also, it has this connotation to exiting something, which we should discuss if it's pertinent for this issue. 

I think placing any of these next to the force label on the bottom right would be messy to say the least.
The Turn & Phase tab has important and distinct information in which the placement of these icons would be irrelevant.

I agree with your 1st point (that the space on the channel bar is precious). To offset that, we could place it next to the Maximize/Minimize feature but it would be less intuitive on the right hand side.

**Comment by ShendMikullovci** [comment]
> Yes @ShendMikullovci - once we have the "restart wargame" functionality, we will want players to return to the Player Welcome page.

Can you remind me which issue this functionality was again?

**Comment by IanMayo** [comment]
We don't have the concept of `Quit/Restart` for players.  They can go to the home page, but the current wargame will continue.  If they return to a wargame, it will have moved on without them.  Only the Game Control can stop or restart a game.

Aaah, so being in a game is like watching a broadcast TV channel.  You can turn the channel off, or switch to another channel, but the original channel will continue moving forward.

So, I guess the `Home` is the better metaphor.

> Can you remind me which issue this functionality was again?

Sure.  It's the (future) ability for the Game Control to suspend the current game, and restart it at a previous turn. They will do this by going back to a previous turn marker, and clicking on a "Restart from here" icon.  After a confirmation dialog, the game will restart at that turn (mechanics of this to be determined).

**Comment by ShendMikullovci** [comment]
> Aaah, so being in a game is like watching a broadcast TV channel. You can turn the channel off, or switch to another channel, but the original channel will continue moving forward.
> 
> So, I guess the `Home` is the better metaphor.

Nice analogy. I'll add the home button then.

> > Can you remind me which issue this functionality was again?
> 
> Sure. It's the (future) ability for the Game Control to suspend the current game, and restart it at a previous turn. They will do this by going back to a previous turn marker, and clicking on a "Restart from here" icon. After a confirmation dialog, the game will restart at that turn (mechanics of this to be determined).

Yes. What I meant is if there was an actual issue here on our GitHub that's been opened regarding this?

**Comment by IanMayo** [comment]
> Yes. What I meant is if there was an actual issue here on our GitHub that's been opened regarding this?

Have just created [one](https://github.com/serge-web/serge/issues/1639)

**Comment by IanMayo** [comment]
Fixed.
