### ISSUE TITLE
Blue Screen in Admin Page on Channels Tab

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1615]
The downloaded version of the game that I'm currently working with, crashes when I click on the "Channels" tab in the Admin Page. 

https://user-images.githubusercontent.com/85491794/174677091-74c79331-5ec8-48d0-abd0-50113792f30b.mp4

**Comment by ShendMikullovci** [comment]
Refer to #1433 for other encounters of the Blue Screen.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci - could you clarify which build version you're using? - via the build date at the bottom left.

**Comment by ShendMikullovci** [comment]
V:0.3.02022-04-29 09:58

**Comment by IanMayo** [comment]
Ok, there's a much newer Win64 build available for you to use here:
https://github.com/serge-web/serge/releases/tag/20220621b

**Comment by IanMayo** [comment]
Closing this issue, since it's using a build from April 22.
