### ISSUE TITLE
Editable vs Non-Editable Attributes

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1616]
Attributes in the Admin Page can be editable by players or not editable thanks to the toggle feature we've added. 
However, I noticed that in the Forces --> Assets tab, if an attribute has been made non-editable by players, the GC can't edit it either: 

https://user-images.githubusercontent.com/85491794/174677398-00555ad7-f69a-471c-98bc-4b3e3e436160.mp4

GC should be able to edit the attributes in both of the tabs (Force --> Assets and Platform Types), since they are not a "player" and have special access. This would also simplify GC's work process in the case where they might change attributes for a force. Much simpler to just go to Forces --> Assets and modify things there. This way, we give the GC versatility in doing this process.

**Comment by IanMayo** [comment]
Fixed in #1664
