### ISSUE TITLE
Attribute Editing to be Updated Across Tabs

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1617]
Editing attributes in the Forces --> Assets tab, should automatically update the attributes in the Platform Types page. Currently, this isn't the case: 

https://user-images.githubusercontent.com/85491794/174677820-2dfa9d5c-0670-4807-995c-f2364d74a8c2.mp4

If we are to keep this versatility on editing the attributes (which I'm pro of), the attribute edited on one tab, should be updated on the other.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci  - but I'm pretty sure this is handled, if I understand correctly.

If the master attribute is edited (in `platform-types`), then when we save the `force`, we check that asset attributes are still valid, and update/add/remove them accordingly:
![screencast](https://i.gyazo.com/b7482adf61111dfd9b882ad5eb5b04f9.gif)

**Comment by ShendMikullovci** [comment]
Closing until further notice.
