### ISSUE TITLE
Attribute Features out of Alignment

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1618]
In the downloadable version, the features of the attribute box seem to have left alignment with their respective text boxes/toggles:

![Attribute out of alignment](https://user-images.githubusercontent.com/85491794/174678068-794a229f-a56f-4991-b688-4f65cd132e3f.png)

It'd be nice if we could realign them.

**Comment by IanMayo** [comment]
@lebaphi  - could you center-align these icons on their columns please?
