### ISSUE TITLE
Client crash on creation of new channel

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1622]
A game is live.

The Game Designer just added a channel, into which he put all forces.  When he clicked on "Save channel", Serge blue-screened.  Other logged in clients also blue-screened.  A refresh cleared the issue.

But, I couldn't reproduce the issue on a development machine. Maybe I wasn't creating a channel with the same constraints.

For further investigation.

**Comment by IanMayo** [comment]
Was able to reproduce channel.

- Add channel (traditional/normal type)
- Add all forces to channel
- Save channel

This error shown on console:
```
TypeError: Cannot read properties of undefined (reading 'channel')
at t.default (handle-channel-updates.ts:317:47)
at er (handleWargameChanges.ts:20:34)
at dr (pllayerUI_reducer.ts:170:34) 
```

Note: the above handle-channel-updates may not match the current `develop` branch, since `develop` now includes the fix to avoid duplicate messages.

**Comment by IanMayo** [comment]
Line 317 doesn't relate to an obvious instance of `channel` in the source code.

The `channel` variable in this method is the index value in `allChannels.forEach`.  That suggests that _somehow_ there is an empty channel in the list of channels.  _Maybe_ we need to drop out of the loop if the channel is empty. _Maybe_ we need to understand how/why there is an empty channel in the listing.

So, output each `channel` as we process it, but don't fall over if it's empty.

**Comment by IanMayo** [comment]
Have learned some more. The game that was breaking was at "Turn 0 - Adjudication", and contained no messages at all so far.

Once I'd moved forward a single turn to "Turn 1 - Planning Phase", the crash didn't happen.

The issue was not related to messages.  In a game at turn 0, with a single message, the crash still happens.

**Comment by IanMayo** [comment]
Ok, steps to reproduce:
- create new wargame
- add a new force "Blue", leave it with default role "CO"
- add a new force "Red", leave it with default role "CO"
- add a new channel "All chat", put white and blue into it
- in player window, login as Blue
- in Admin window, remove Red from channel. Save channel. See blue screen appear

**Comment by ShendMikullovci** [comment]
> * add a new channel "All chat", put white and blue into it

It crashes for me when I click on the channel tab (#1615), so I can't reproduce this.

**Comment by ShendMikullovci** [comment]
Here's me doing the steps in Small Wargame: 

https://user-images.githubusercontent.com/85491794/175350374-828f8363-4100-4795-9bd0-b1aabc63bb20.mp4

Doesn't crash. Had to refresh the browser in order for the channel to appear.

**Comment by ShendMikullovci** [comment]
> Here's me doing the steps in Small Wargame:
> Shend.s.Channel.mp4
> 
> Doesn't crash. Had to refresh the browser in order for the channel to appear.

Update: Player tab crashed when I deleted the channel in the Admin tab. Cleared up after refreshing.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I've tested the "edit channel" functionality, and merged the PR.

But, I missed your feedback that something was crashing.

Earlier today it was crashing on update, but I fixed it.

Anyway - I welcome you trying to reproduce your steps on the current `develop` branch.

**Comment by ShendMikullovci** [comment]
> add a new channel "All chat", put white and blue into it

Here's me repeating these steps: 

https://user-images.githubusercontent.com/85491794/175810889-37c3aba2-d3d6-4184-b193-f22126b5b4d8.mp4

Notice how I encounter problems adding Forces to the Channels in the Channel Tab (original issue #1414).

Otherwise, the page doesn't seem to be crashing. The Force only disappears once the Channel has been saved in the Admin Page (which is good). 
One weird little thing is that when I created the wargame, it immediately landed on the Channel Tab, which has never happened before. You can see it in the beginning of the video.

**Comment by IanMayo** [comment]
Issue resolved, and tested.
