### ISSUE TITLE
Can't export forces

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1623]
There are two new issues. they are both  related to 'export' from the admin wargame listing. When I try to export Forces to xlsx, nothing happens, nor are any errors shown on console.  When I try to print exported force, the blue backdrop makes it illegible.

Note: I was unable to reproduce this on a dev machine. It _just worked_.

**Comment by IanMayo** [comment]
Ok. Have investigated.

The `xlsx` file does export, it's just a few seconds before it appears.  Plus, we're running in MS-Edge, which shows downloads in a different place.  Actually, network download speed seems slow. Maybe that's the delay that makes it look like it hasn't arrived.

Onto the issue about `print force`.   On Chrome on a develop machine, the tabular data is shown against a white background. On Edge on this user target machine, it's shown against the standard SERGE backdrop, which makes it difficult to read.

Aah, using Chrome on user target machine it also has dark blue backdrop.

Only difference I can think of is that user machines don't have Internet connection.  Could we be downloading white background image from Internet?

**Comment by lilitkarapetyan** [comment]
Yes, we can
