### ISSUE TITLE
Delete Marker Feature

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1628]
This is our current marker editor on the bottom left: 

![Map SC](https://user-images.githubusercontent.com/85491794/175015116-a04dfbca-c7ec-4baf-8a3f-e4ef402e5d51.png)

Currently, we do not support a delete feature, where GC can remove the marker from the game entirely. 

I suggest we do so by adding a red delete button at the bottom of the editor. 3 options

Option 1: 

![Marker Editor Option 1](https://user-images.githubusercontent.com/85491794/175015276-691a7402-6e21-4b28-95a9-95c2761a21ae.png)

Delete button on the far left since the action-ability of the editor is heavily located on the right hand side. It is also consensus for MacOS, iOS and Android to have the delete button immediately after the cancel button.

Option 2: 

![Marker Editor Option 2](https://user-images.githubusercontent.com/85491794/175015859-e5781377-e00a-4137-871d-9cffa182ba2e.png)

Bigger attentional impact given that 2 bright colors sit beside one another. 

Out of 1 and 2, I have a preference for option 1. 

Also, notice that I've rendered the cancel button transparent. That is to reduce visual pollution since we're adding a red color down there.

Option 3: There's also the option of having the bin placed instead of the delete button on the far left: 

![Marker Editor Option 3](https://user-images.githubusercontent.com/85491794/175017099-774cc8a1-edee-45d2-ad50-2dcac290c473.png)

Less invasive for the eyes and somewhat of a smoother look, but not very conventional. 

Let me know your thoughts.

**Comment by IanMayo** [comment]
Hmm, I don't expect the delete button to be used all that frequently.  So, I guess the unobtrusive trash can icon would be acceptable.

IMHO we don't have enough contrast on the `CANCEL` button.  Sometimes the sun is streaming through the office windows, and it's not that easy to read the text on the wall-mounted monitor.

**Comment by ShendMikullovci** [comment]
> Sometimes the sun is streaming through the office windows, and it's not that easy to read the text on the wall-mounted monitor.

What amazing information to know!

**Comment by ShendMikullovci** [comment]
Here's how that would look:

![Marker Editor Option 3](https://user-images.githubusercontent.com/85491794/175060917-22b1970c-f81c-47e0-a334-0c921668ad0a.png)

**Comment by ShendMikullovci** [comment]
Also, notice the typo on the cancel button ("canel") in our current display.

**Comment by IanMayo** [comment]
Re-open once #1642 is complete, so we can address the intermittent flicker when Game Control is dragging info markers
