### ISSUE TITLE
Admin Page Redesign

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1636]
I've done some touching up on the design of our admin pages. Here's what I've come up with: 

![Current Admin Page](https://user-images.githubusercontent.com/85491794/175607779-c1124606-9160-455a-91f5-16cffeb960db.png)

In our current layout, the admin page contains no logo, places too much emphasis on the menu on the left hand side, and when there are more wargames, the user has to scroll down to see them, despite having enough space on the screen to fit everything. The buttons are also inconsistent in color and action.

![Admin Page Games](https://user-images.githubusercontent.com/85491794/175608327-38aaed2a-9087-49fa-895f-b69d6835212c.png)

Here, we'd have the menu on the left contain all the necessary pages, without overbearing on the visual hierarchy of the page, right under the logo selected by GC. 
The title of the page would be indicated clearly and in more emphasis. Under it, we show the 3 main actions to perform on this page. 
The delete button is in red to distinguish between the two other actions due to the danger of accidentally deleting a wargame. The search spyglass after the buttons would expand to a search bar once clicked on (will design the UX for it if we proceed).

The wargames are displayed in a list and occupy a central part of the screen. 

Finally, I decided to add a "Contact Support" button where the user would be automatically redirected to our emails (or other means of connecting with us).

**Comment by ShendMikullovci** [comment]
For Message Templates: 

![Message Templates New](https://user-images.githubusercontent.com/85491794/175611333-6335b70f-b93d-4921-aa2e-b459b7d9fa59.png)


To maintain uniformity and consistency, we keep the navy blue background and display the templates similarly to the wargames (I added the scrollbar to insinuate there are more templates).

Create New Template button in light blue and on top of the screen to emphasize the action to be realized in this page.

Clicking on one of the templates would bold the title and collapse the adequate form.

![Message Templates New 2](https://user-images.githubusercontent.com/85491794/175611382-42fa7b66-4d51-48e4-a35a-b0bc2782a90a.png)

The Edit, Duplicate, Delete buttons are relocated next to the label of the template, similar to our platforms and forces pages.
Cancel and Save buttons at the bottom as usual.

**Comment by ShendMikullovci** [comment]
I noticed we don't support the Message Library feature anymore, but I designed these before I realized that: 

![Message Library New](https://user-images.githubusercontent.com/85491794/175611038-5a85c393-106e-4ef0-9b27-c4d531bb17b1.png)

![Message Library New 2](https://user-images.githubusercontent.com/85491794/175611062-2d7c2632-fd89-4860-a28c-c13e661ba40b.png)


Same thought-frame as the one behind the Message Templates.

**Comment by ShendMikullovci** [comment]
As for the Welcome Screen: 

![Welcome Screen New](https://user-images.githubusercontent.com/85491794/175610487-b3d8e833-c9f8-4986-bd6a-6d78a461926d.png)

Centered controls and text, with a smoother look. The icon occupies less space here and emphasis is put on the title and description. Finally, the save button goes at the bottom next to a cancel button instead of being on the top right.

**Comment by ShendMikullovci** [comment]
Finally, the landing page to the Admin Page itself: 

![Enter Admin Page](https://user-images.githubusercontent.com/85491794/175612112-a4f82afb-ed99-4f6f-96d9-1178f443fb7d.png)

Centered elements. We would switch from "Set Wargame" to "Select Wargame" since that is a more accurate description of the action realized in this page. The enter button in light blue, centered to the other elements of the page.

Let me know your thoughts.

**Comment by IanMayo** [comment]
Sure, ok. With these notes:
- I don't like the serif font - it only seems to be used when trying to be some old system/tool
- I think we need some clues that the items are in a list.  Once they player knows they're in a list, it highlights the fact that the next action is to click on (select) one of them
- Similarly, alternate light/dark backgrounds and permanently visible scroll bars can help highlight it's a list of items.
- It's rarely used, but I think we should keep the search box  above the wargame list

You're being consistent with adopting centred text, but it doesn't seem like the _normal_ way of presenting information.  When I do "new issue" here in Github, the pattern seems to be to push information out to left/right rather than stack it in the middle.

**Comment by ShendMikullovci** [comment]
> 
![New Admin Page Navigational Menu](https://user-images.githubusercontent.com/85491794/176211140-32ab3f8a-773e-4e04-a424-3f9731049396.png)

Nice point on highlighting the fact that it's a list. I added a "Menu" header and separated each each item. I also changed the font to Inter (Figma, can provide it). 

As for the centered text, I'm mostly emphasizing it on options where the actions to be taken are top-down. Here, that is the case since the user will naturally click right under the password text bar to log into the game.

**Comment by IanMayo** [comment]
> Nice point on highlighting the fact that it's a list.

No, I meant the list of wargames are a list :-D

**Comment by ShendMikullovci** [comment]
![New Admin Page ](https://user-images.githubusercontent.com/85491794/176272435-62e5adc7-380b-4e01-b2cd-b75de614c593.png)

How do you feel about this then? Slightly more complex visually. 

Also tried a gradient version: 

![Gradient Admin Page](https://user-images.githubusercontent.com/85491794/176275327-7d469e8c-2f2f-4d04-9274-f7d164d3897a.png)

 Brought back the search bar. I put the buttons under the list for two reasons: 
1. Most action buttons we have in the game are below the actionable feature.
2. Search bar and 3 buttons on top of the game list is a little too crowded.

Ideally, the buttons would be fixed.

The gradient is light at the top and bottom to emphasize title and buttons, and dark in the middle to bring out the wargame list.

**Comment by IanMayo** [comment]
Maybe the "Create wargame" buttons deserves more prominence - it's the trigger for the whole process. Maybe have just that one button near the search bar?

I _think_ the orange/green markers indicate if the wargame has been initiated (started) yet.  The game designers could probably do with a bit of clarification on that in the UI.

On occasion - a Game Designer may wish to have 2 windows open at once on the screen.  This is easier if the data is displayed in a more compact way.  I guess this would be supported by removing the white-space (well, blue-space) to the left of the wargame titles.

**Comment by ShendMikullovci** [comment]
> Maybe the "Create wargame" buttons deserves more prominence - it's the trigger for the whole process. Maybe have just that one button near the search bar?

I reduced the search bar size as well. Not necessary for it to be that long. 

![Games Page](https://user-images.githubusercontent.com/85491794/177160313-5298efbe-0904-49e0-8334-c057972397f9.png)

> 
> I _think_ the orange/green markers indicate if the wargame has been initiated (started) yet. The game designers could probably do with a bit of clarification on that in the UI.

Would you like an Intro to the Admin Page? A legend for the icons? Info upon hover?

> 
> On occasion - a Game Designer may wish to have 2 windows open at once on the screen. This is easier if the data is displayed in a more compact way. I guess this would be supported by removing the white-space (well, blue-space) to the left of the wargame titles.

We can't go too far on that because we still need the wargames to be visually distinct.

**Comment by IanMayo** [comment]
> legend

Great idea :-). It would cover both states, for both icons.

> We can't go too far on that because we still need the wargames to be visually distinct.

If we delete some of the unused "bar" to the left of the `eye` icon, I still think they would be visually distinct
![Screenshot 2022-07-04 at 14 11 27](https://user-images.githubusercontent.com/1108513/177162001-84445b9a-68e3-4280-852e-a84ea82ac7c2.png)
.

**Comment by ShendMikullovci** [comment]
![Game Page 2](https://user-images.githubusercontent.com/85491794/177167367-9d66b83e-4947-4dbe-9384-8a3cd5c4ba79.png)

How does this look to you?

**Comment by IanMayo** [comment]
Yes, great :-)

**Comment by IanMayo** [comment]
Oh, I'm afraid we have to delete `Contact support`.  Almost all "real" wargames will be run on networks without an Internet connection, so an email link won't work.

**Comment by ShendMikullovci** [comment]
![Game Page 3](https://user-images.githubusercontent.com/85491794/177174830-964b50a6-a98f-422f-8820-7d3afc3f5db3.png)

Let me know if there's anything else. I'll get on updating the remaining pages.

**Comment by ShendMikullovci** [comment]
Here are the remaining pages:

Message Templates:

![Message Templates 1](https://user-images.githubusercontent.com/85491794/177347278-7a5b827b-4b2c-4864-90a3-43c286e83593.png)

The template highlights upon hover. It doesn't necesarily have to be light blue. Just wanted to emphasize that. The highlighting disappears once it's collapsed.

![message templates 2](https://user-images.githubusercontent.com/85491794/177347325-fa35ee17-c43d-4ac5-a767-ecf5ba162583.png)

**Comment by ShendMikullovci** [comment]
Message Library:

Same idea.

![Message Library 1](https://user-images.githubusercontent.com/85491794/177347649-eda827cc-4cf0-40e6-88be-ef754ff9ee15.png)

![Message Library 2](https://user-images.githubusercontent.com/85491794/177347693-67b7808f-2446-4032-ae8c-785ccac384db.png)

**Comment by ShendMikullovci** [comment]
Welcome Screen: 

![Welcome Screen](https://user-images.githubusercontent.com/85491794/177347870-81ef449c-e478-42c5-8380-14929c3b98bb.png)

**Comment by ShendMikullovci** [comment]
Let me know if I should provide the color coding and gradients.

**Comment by IanMayo** [comment]
Thanks for the updates.

1. The "Message library" has been deleted. It was a good idea, but no Game Designer ever wanted to use it
2. For "Message Templates" I do believe it's more effective to keep the preview on the right-hand side.  This is because if the Game Designer is working their way down the list (reviewing the templates, or looking for one of interest), then the items in the list stay in a predictable position, and it's easier to move the mouse down the screen.

**Comment by ShendMikullovci** [comment]
Afternoon! I think that kind of defeats the point of the redesign in itself. We'd lose uniformity. Furthermore, I don't fully understand how the preview makes things easier? It's still on-click and the user gets to view the templates the same way. The new version is only more compact like you asked. You sure you want me to go back to the previous design?

**Comment by IanMayo** [comment]
Hello Shend :-)

> we'd lose the uniformity

Now that we've dropped the `message library` component, `message templates` would be the only component that shows previews embedded in the list.  That means there isn't any uniformity.  So, it doesn't that displaying the previews to the right of the list breaks uniformity.

>  Furthermore, I don't fully understand how the preview makes things easier

If I'm looking for a particular template, or a template that contains a particular feature (such as as drop-down list), I will want to work through the templates, having a look at each one.  With the previews shown to the right of the list, the items in the list stay in a predictable location - making it easy to mouse-click down the list.  But if the previews are "inline", the list of items is expanding/contracting as I view each preview, meaning the items in the list are moving up and down.  It also requires two clicks to check each item: once to expand, and once to contract before I move to the next item.  When displayed to the side, it's just one click for each template.

**Comment by ShendMikullovci** [comment]
Good afternoon!

>That means there isn't any uniformity. So, it doesn't that displaying the previews to the right of the list breaks uniformity.

Yes. I meant uniformity in design logic, not feature uniformity. My bad.

>  It also requires two clicks to check each item: once to expand, and once to contract before I move to the next item. When displayed to the side, it's just one click for each template.

Yes, good point. Here's how that could look: 

![New Message Templates](https://user-images.githubusercontent.com/85491794/178102872-98bec3cb-9091-4c84-91b6-502c2b4ff11f.png)

We would lose a little bit in text size, to fit everything in and keep them in a linear fashion. The Create New Template button goes on top of the list, instead of being on top of the page. The action buttons for the templates are on the template tab next ot its label, identical to what we have for forces, platforms etc. so we maintain logic with the rest of the admin pages.
