### ISSUE TITLE
Message Box Uniformity

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1638]
I suggest we make all message boxes collapsible. That would increase design uniformity and consistency, and give the user the option to reduce visual load across channels.

Essentially, I believe we should adopt this design for all channels: 

![Message Box Uniformity](https://user-images.githubusercontent.com/85491794/175827185-0f7d0458-e885-47ce-9e9c-702a8652cc54.png)

**Comment by IanMayo** [comment]
Hmm, chat channels are meant to support an interactive conversation - so having to expand each message could be a pain.

**Comment by ShendMikullovci** [comment]
No, what I mean is that the New Message button that opens up to the panel above, should be uniformly adopted accross channels. This is a great feature that is clear and easy to use. Having channels where the panel is open and fixed is a.) introducing a difference between channels that might not really rely on the message formats, b.) turning the display away from consistency/uniformity and c.) might lead the user to believe the channel message feature is a different feature from the other ones. As we know, the difference between channels is not message panel design, but message format and content. I'm afraid a different panel design might confuse the user into thinking formats/content are different.

Side benefit: Having uniformity accross message panel features forces the user's attention to the content of the channel since their eye will be used to the design. I think we'd want that.
