### ISSUE TITLE
5.3 Record player perception of other force

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#164]
As a < Player >, I want < to record/correct my perception of an asset from another force > so that < I can plan tactical strategies >.

A significant part of this wargame is that Red can hide its assets (typically fishing vessels) as a Green asset - and use stealth to get near to Blue assets.

Red can also do this picture management to try to track which are the Blue assets.

We include UI to support this.

Blue/Red can do this "picture management" in playing or planning phase.  But, since the players don't have much to do during the adjudication phase, we can start off by giving them this capability during that phase.

This functionality can completely replace the functionality in `MapAdjudicatingPlayerListener`

The list of available platform types come from the `wargame.platformTypes` element in state.  The platform-types block does contain the SVG filename of the relevant icon.  _if_ the icon is shown in the platform types drop-down, then _maybe_ we should use that icon path instead of the pre-defined CSS path we're currently using (this will mean new platform-types can be added added from the user-configured wargame document, rather than via code change.

The transmission/receipt of these messages should be similar to how we current handle these events:
* change platform visibility
* change vessel position (force laydown)

# Acceptance criteria

- [x] Logged into `MWARC Initialised` as Red force, any turn, game in adjudicating phase (switch to White force if you need to advance the game).  We can click on any non-red asset, and assign its Force/Perceived-type
- [ ] When we change the what our perception of that asset is and save, the screen should update to show the new force/icon type.  The icon will also update for another player logged into our force in a different browser.

# UX
https://www.figma.com/file/2qiEitO08s8jXamHWI3VpP/SERGE-mapping-tool?node-id=0%3A1

![screenshot](https://i.gyazo.com/d00ed2113d19ae50bb866b512788c243.png)

_Ideally_ we would show the icons in the platform-type dropdown, and shaded color blocks in the force drop-down.  But, we should start off with plain text for both, in order to test functionality/usability.

# Notes

**Comment by foxleigh81** [comment]
Putting @lilitkarapetyan's codesandbox link here for reference later: https://codesandbox.io/s/leaflet-with-react-qctv5
