### ISSUE TITLE
Possibly missing icon

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1647]
@lebaphi spotted a bug in PR #1642 

It relates to a missing icon:
![image](https://user-images.githubusercontent.com/1108513/176400943-1038c95f-d08b-4518-bc8d-61f1b7af307e.png)

The bug occurs when Game Admin selects an Info Marker in the planning phase.  Investigate.  It appears to be because of a missing `unknown` icon.  I _think_ we manually add `unknown` to the list of annotation icons available in the drop-down. 

Hmm, actually - the above icon (unknown) is currently displayed in the icon drop-down in the form:
![image](https://user-images.githubusercontent.com/1108513/176401448-161bca48-c892-4e44-97f4-f76eee8c9650.png)

**Comment by IanMayo** [comment]
Could you investigate this please @lilitkarapetyan ?

**Comment by lilitkarapetyan** [comment]
Yes, I will investigate.
