### ISSUE TITLE
New map messages produces wargame with wrong id

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1656]
When a wargame update happens, the admin pages pull out the most recent wargame with a particular`doc_id` (`initial-settings` if pre-initiated, and `settings` if after initiated).

But, when I submit a message from the map (umpire laydown in this case) the new document is stored with a date-time id.

Then, when I make a wargame change from the admin pages (such as initiate wargame), they actually retrieve and modify an earlier wargame.

Steps to reproduce:
1. checkout branch `1656_wargame_document_id`
2. open `wargame-l56yw0y5.sqlite` database in DB Browser. Verify there are 3 records. Newest one is `initial_wargame`
3. note that this wargame includes the phrase "Umpire laydown" 4 times.
4. enter game `Small wargame-laydown`
5. login as `Game Control`
6. move 4 assets from "laydown pen". Click once to select, and once to drag.  Move them anywhere.
7.  Once all 4 are moved, "Submit laydown" button will become enabled. Click it, and confirm "Submit laydown"
8.  Open wargame database.  There are now 5 records. The two new ones are "Umpire Laydown" message, then new wargame. Note that the `doc_id` for the new wargame is the date/time. Also note that the new wargame doesn't include the phrase "Umpire laydown" - since no assets are still waiting for "umpire laydown"
9.  Open admin pages, enter `Small wargame-laydown`
10.  Mark wargame as initiated
11.  Player UI fails, since `Error: Should not have umpire laydown for initiated wargame`
12.  Look at database. It now has 6  records. The newest wargame has date-time for `doc_id`, and includes the phrase "umpire laydown" - which shows it wasn't the most recent wargame that got updated.

**Comment by IanMayo** [comment]
I've been thinking about this @lilitkarapetyan 

I _think_ the first error is in line `#8` above - where we get the database record for the updated wargame with date-time for `doc_id`.

Fixing that may fix the _downstream_ error I get afterwards.

**Comment by IanMayo** [comment]
Startup condition.  Wargame not initiated, so wargame document stored in `initial_wargame`:
![image](https://user-images.githubusercontent.com/1108513/177980949-418c2e29-9af7-4e37-b964-a97c1d3f845a.png)

Log into `Small game - laydown`. Move `pending` assets.  Then submit laydown:
![image](https://user-images.githubusercontent.com/1108513/177981180-dec58635-72b0-4e74-9467-c5e06b498ace.png)

Note the two new documents. The one with `seq` of `11` is the `Submit laydown message` and the one at `12` is the new wargame.  It has the wrong name:
![image](https://user-images.githubusercontent.com/1108513/177981383-b440b01c-0ea8-4cb9-accf-01385ca0fc5d.png)

So, now if we make a change from the `Admin` pages (such as `initiate wargame`) Serge will pull out the document at `seq` value `10`, and modify that.  This is because the one at `12` has the wrong name.

**Comment by IanMayo** [comment]
@lilitkarapetyan - I'm pretty sure the issue is with this message:
![image](https://user-images.githubusercontent.com/1108513/178313805-9b3288e7-b175-45cc-91ae-0b39798d9815.png)


I _think_ that if the wargame is not initiated we need to overwrite the `initial_wargame` document, otherwise we create a new version of the `settings` document.  Here is where these are defined:
![image](https://user-images.githubusercontent.com/1108513/178314112-973c6dd5-2108-4bbf-92db-66fbfae5fbe0.png)

**Comment by lilitkarapetyan** [comment]
> @lilitkarapetyan - I'm pretty sure the issue is with this message: ![image](https://user-images.githubusercontent.com/1108513/178313805-9b3288e7-b175-45cc-91ae-0b39798d9815.png)
> 
> I _think_ that if the wargame is not initiated we need to overwrite the `initial_wargame` document, otherwise we create a new version of the `settings` document. Here is where these are defined: ![image](https://user-images.githubusercontent.com/1108513/178314112-973c6dd5-2108-4bbf-92db-66fbfae5fbe0.png)

Hi Ian, the issue is resolved, I will add today
