### ISSUE TITLE
New messages shown at top in all channels

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1663]
I invited a power user to give feedback on chat vs non-chat channels, and got this:

> I think it's probably worth harmonising at least in part - having one be most recent at top, and one most recent at bottom, could be counterintuitive - I suspect most would assume the newest message would appear at the bottom, like a text message chain.

Here is example of text message chain growing from the bottom:
![image](https://user-images.githubusercontent.com/1108513/178298953-dc1bc1cd-2b6d-4fa9-8020-344c98d0c5a4.png)

> Otherwise, I don't think it's problematic to have the chat channels showing the new message box constantly, it makes sense to have it available for free text but as a selectable option for template channels. I could go either way on that one, it would probably be down to how users felt about it!

Currently, chat channels display new messages at the top, and non-chat channels display new messages at the bottom.

This is inconsistent. New messages should appear at the bottom in all channels.

Hmm.  If a player doesn't have a message expanded, _maybe_ the channel should scroll down to the new message.

**Comment by ShendMikullovci** [comment]
Hi Ian! I think consistency is the way to go most of the time. We should just be mindful of the conceptual differences between the channels themselves!
