### ISSUE TITLE
Allow "forces in channel" to be hidden.

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1675]
For some channels, the Game Designer doesn't want channel members to see which forces are in channels.

This is because...

For this game, "Red" can position themselves so they can hear "Blue" conversations.  Game Control will move Red in and out of the Blue channel, depending on where they are.  But, they don't want "Blue" to know when this is happening.

We should handle this through a new setting in the "Channels" page, and the setting will apply to all channels.

This new attribute "hideForceMembers" will sit in "Player State", and will be used to determine whether to display the force icons in `ChatMessagesList` and `ChannelMessagesList`

We'll need a bit of design first, please @ShendMikullovci .  

Hmm, maybe a cog that's a drop-down menu to the right of the "Add Channel" button? The drop-down menu could show a toggle for "Hide Forces in Channels"

**Comment by ShendMikullovci** [comment]
https://user-images.githubusercontent.com/85491794/179421307-d1cf7256-e2ec-492f-a669-54cdf6f0af56.mp4

**Comment by ShendMikullovci** [comment]
Here's a screenshot of that for a better view: 

![Hide Forces In Channels](https://user-images.githubusercontent.com/85491794/179421364-d0e55377-bc6b-4a14-8693-801e37e7afd0.png)

You'll notice I deleted the "Actions" header. The buttons are quite self explanatory. 
You'll also notice I changed the "Restrict access to specific roles" to just "Roles". The latter header is also quite self explanatory. 
The hidden force in this case (Blue Force) is tinted grey.

**Comment by IanMayo** [comment]
Hello Shend, this requirement relates to the player pages.  In the admin pages, the Game Designer sees all roles.

The handle the changes in "visibility" while the game is playing, the Game Controller will delete the `Red Force` from the channel when they are dived, and add them again when they return to periscope death. This functionality is already quite mature.

All we need is the toggle for the whole wargame that indicates if forces should be shown in channels.  (we're coming to the end of the budget for this set of packages of work, and there isn't a requirement for per-channel control of visibiltiy).

**Comment by ShendMikullovci** [comment]
I thought of circular menus last night and tried it out. It could do the job well.

https://user-images.githubusercontent.com/85491794/179844494-a5d5aa8b-e478-47a0-a358-e73a323b83f7.mp4

**Comment by IanMayo** [comment]
Very stylish.  But, at the moment, it's just one toggle for the whole wargame: "Show forces in channels".

The Game Control uses the admin pages to add/remove a force (or role) from a channel.

**Comment by IanMayo** [comment]
Have added control to support this (bottom right). We'll have to include it in the updated admin pages overview:
![image](https://user-images.githubusercontent.com/1108513/179965841-31bae7d3-fdd7-4158-892e-b614e046d2f1.png)

**Comment by ShendMikullovci** [comment]
Hi Ian! 

So, in this case, nobody (no Force) sees anybody in channels? Meaning, everyone is invisible to everyone?

**Comment by IanMayo** [comment]
When ticked, no Force Icons will be shown at the top of channels.  So, Blue Force will not see Red Force entering or leaving the channel.  Red won't be posting into it, but while a member, it will be able to read messages.
