### ISSUE TITLE
Planning Board

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1682]
Here are a couple of ideas for the planning board we discussed on Slack: 

Considering that the planning board is going to be used to draw and doodle on the map, I think it should adopt the mapping page as it's background by default. 

![Planning Board 1](https://user-images.githubusercontent.com/85491794/180107788-22b2189a-5470-4edc-a217-2bc2d6613651.png)

An obvious location for the board would be on the top left panel in the mapping page. Opted for a Photoshop type of setup, where the tools are on the left hand side, and the title above. Once edited, the Save button would appear below the title. Notice that the background outside of the board has been dimmed.

![Planning Board 2](https://user-images.githubusercontent.com/85491794/180107893-d7934b00-56f3-4014-8a3d-f8ee7736bb6c.png)

We can also put the tools in the overhead panel, where the title and the Save button would be as well. This saves vertical space on the sides but takes up more space horizontally up top. 

I'm not sure how many tools and what type of tools the users would need here so there's need for further clarification on that end. 
In the case where the entire map would not be necessary, I thought we could use a "drag to select" feature where the user selects by dragging through an area of a certain size on the map, which would appear zoomed in as a background in the board. Let me know if you'd like an illustration, and what you think of the ideas!

**Comment by IanMayo** [comment]
The customers that want the planning board won't be using Serge mapping - so we can't base it on the mapping channel.

I'm pretty sure we'll represent the `Planning board` as another channel.  That means the Serge plumbing (to send/receive the updated plans) will _just work_.

As another channel, the board will be configured by the Game Designer to indicate which roles can produce plans, which roles can view plans, and which forces can see other force's plans (e.g. Umpire will see all plans, `Red` _may_ be able to see `Blue` plans for some wargames [*] ).

For the layout of the controls, we may be lead by the toolkit that we adopt.  But, your proposal looks fine.

[*] this may seem weird/unfair, but in some games it's the responsibility of Red to "drive" the Blue players into practicing certain tactics/strategies.

**Comment by ShendMikullovci** [comment]
Hi Ian! 

Couple of ideas:

1. In-Channel:

![Planning Board In Channel](https://user-images.githubusercontent.com/85491794/180609748-4b5fbd8c-e907-4e00-9f01-26170c8e3a43.png)

Here, we'd have New Plan instead of New Message in the bottom, with 2 other already submitted plans shown in the channel for GC to expand.

I thought it might be useful to include a grid in the board: 

![Planning Board In Channel 2](https://user-images.githubusercontent.com/85491794/180609794-7012809d-3f2e-4002-9362-b6cdecfe8a80.png)

The grid doesn't have to be this large, can be narrower boxes. I also included a cell size for reference, as we do in the mapping page as we zoom in and out.

Of course, we can also proceed without the grid: 

![Planning Board In Channel 3](https://user-images.githubusercontent.com/85491794/180609829-7cb63060-693b-4401-9b68-5af4afb6bc93.png)

As for the buttons, I assumed we would want the users to be able to save the board for later, in case they need further contemplation. So, I used Save vs Submit dynamic. Obviously, here color is important. So I tried the blue one above, as well as a green and red one: 

![Planning Board In Channel Green Button](https://user-images.githubusercontent.com/85491794/180610008-dd60d02f-b7a2-4c86-8fa1-bc537e32ab0f.png)

![Planning Board In Channel Red Button](https://user-images.githubusercontent.com/85491794/180610014-1cccf515-c48d-4b42-a215-341f40bc833c.png)

I think while red stands out a little more visually, it's generally got more serious/negative connotations (like close, error, etc.), whereas green is more generally associated to confirmations and success. 

2. Full Channel: 

Here, the entire channel would be a big planning board: 

![Planning Board Full Channel](https://user-images.githubusercontent.com/85491794/180610089-d3aedcdf-1c03-4adb-afab-3ffdfb1f5f88.png)

Also did a no-grid view:

![Planning Board Full Channel 2](https://user-images.githubusercontent.com/85491794/180610101-60addd24-debd-44e8-9179-f79558d18702.png)

It's a good solution if we want a bigger drawing space. However, a problem with this design would be that we'd have to figure out a way to show GC older plans somewhere else. 

Let me know your thoughts!

**Comment by IanMayo** [comment]
Oh dear - I've misled you.  The planning board will be a "channel" in that it will be represented as another tab on the left-hand side of Serge.  But, it will be an _illustration_ rather than a list of messages (just like the mapping component).

_Under the covers_, the drawings placed on the board will be transmitted around Serge as messages, but the content of the message will be "computer speak" to represent that feature, something loosely like this:
![image](https://user-images.githubusercontent.com/1108513/180747959-a003bfe6-d727-4a47-83f7-f5a4d6ce3ced.png)

So, to the user, the "Planning Board" will be a new tab in Serge, that shows a map with a number of text-boxes drawn on it.  Some players (probably the "CO" for each force) will have drawing controls that let them add those text-boxes.  These players will also have a `Save` (or similar) button that sends the text-boxes to other players.

**Comment by ShendMikullovci** [comment]
> The planning board will be a "channel" in that it will be represented as another tab on the left-hand side of Serge. But, it will be an _illustration_ rather than a list of messages (just like the mapping component).

So, similar to a mapping page except the entire screen is a drawing board?

**Comment by IanMayo** [comment]
Yes.  Once the task starts, and I have chance to talk to users, we _may_ identify the need to put shapes into layers, and for layers to be switched on and off.  Note: the concept of layers may just be one-layer-per-force.

**Comment by ShendMikullovci** [comment]
Here's an idea then: 

![Planning Board](https://user-images.githubusercontent.com/85491794/180829837-b696a62b-47bb-4586-aee5-24501d889506.png)

Let me know what happens.

**Comment by IanMayo** [comment]
Yes, that's the general idea.

**Comment by IanMayo** [comment]
Conversations with the clients have moved this issue on a long way . I have another meeting tomorrow, from which I hope to offer more firm requirements.

I propose we consider the new UX for those requirements in a new issue. Closing this one.
