### ISSUE TITLE
Consistent use of blue shade

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1683]
We appear to be using three shades of dark blue (`a`, `b`, `c` below):
![Screenshot 2022-07-21 at 12 02 34](https://user-images.githubusercontent.com/1108513/180199246-5bb869b3-df80-4e3e-affb-cf95eed3393a.png)

There could be benefit in switching to just one shade.

Or we could have one shade of dark-blue for _in-game_ (left) and another shade for _out-of-game_ (right) components.  If we do want different shades, to highlight different parts of the game, then I suspect we should:
1. increase the difference between the two shades
2. use the same shades for `b` and `c`.

What do you think, @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
I agree. I think a.) should stay, and c.) be turned into a.) to see how it looks. I think b.) should go, since it's not as widely used as a.) and c.) and it's more of a grey blue than navy blue.

**Comment by IanMayo** [comment]
Hmm, do you think there is logic in using styling to differentiate between "in-game" and "out-of-game" parts of Serge?

Using the same shade for A & C at the bottom of the screen loses this differentiation. But, if we are going to differentiate them, then we should probably make the color different greater.

**Comment by ShendMikullovci** [comment]
> Hmm, do you think there is logic in using styling to differentiate between "in-game" and "out-of-game" parts of Serge?

That could definitely be beneficial.

> Using the same shade for A & C at the bottom of the screen loses this differentiation. 

What we could do is remove B and apply C instead. That way we stick to navy blue, but the shade between A and C would still be sufficiently different (I believe).

**Comment by IanMayo** [comment]
Ok. That should be enough for @lebaphi .  Could shade of blue at `c` also be used for `b` please?
