### ISSUE TITLE
UX For polygon styles

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1693]
Analysts are able to provide set of data that describes what is in each cell.

The data looks a bit like this:
![image](https://user-images.githubusercontent.com/1108513/181007470-4924f361-9d6d-4875-b314-9cd7feefe167.png)

They provide a list of layer names, then for each cell on the map, they indicate if the cell is only of the named layers.

But, they do not provide styling for these layers.

So, once the Game Designer has specified the location of a "cell styles" file, we will introduce logic for Serge to scan that file, and give us a list of layers.  The Game Designer will then provide the styling for those layers.

Here is an initial mockup:
![image](https://user-images.githubusercontent.com/1108513/181006698-98542d4c-c85c-41bb-a55e-22bab40a660e.png)

Note: when the panel first loads the `Presentation` section will either be empty (if there is no cell refs file, or if the file has been changed`. On pressing `Rescan` - the list will be rebuilt.

The Game Designer then specifies the formatting for each layer, and can `Save` the settings.

When Serge is running, Serge is able to use cell references and color shades to plot data areas like this:
![image](https://user-images.githubusercontent.com/1108513/181007780-2f2ccc5c-7a56-4773-b8fa-a00882e0d9e4.png)

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - I had to produce a mockup of the "layer styling" for the analysts to review my intentions.

I'd appreciate you inspecting the mockup & seeing if it makes sense, please.

**Comment by ShendMikullovci** [comment]
Hi Ian!

Sure, the table looks decent. Wanted to ask you a couple of things:

1. What does "Rescan" mean, as a button" for Definitions here? Why that term specifically?
2. Are we sure Resolution doesn't go _inside_ the table, rather than above it? 

Did a quick redesign on this to match the looks and logic that we follow with Serge: 

![Cell Definitions](https://user-images.githubusercontent.com/85491794/182027429-3e731562-6665-4c4e-9ab6-3cc74133ef0d.png)

Left a larger cell for "Visible To" since Force Labels are usually longer.

**Comment by IanMayo** [comment]
For the table, there is one `row` for each data type defined in the provided data-file.  The resolution also comes from the data-file.

So, once the game designer has initially specified (or subsequently modified) the `cells/definitions/json` file, they must click on `Rescan` for SERGE to go through the file and pull out the cell styles (`Land`, `Depth-30`, `Depth-60`, `pKill-Low`), and the Resolution to be used.  

So, initially the `Resolution` value and the `Presentation` table will both be empty.  Someone will provide the Game Designer with the definitions file. The game designer will put the file into a sub-folder of Serge, type the path into `Definitions`, and then click `Rescan` - which will populate the `Resolution` box, and add rows to the `Presentation` table. The Game Designer will then specify how the cell-types are displayed by filling in the drop-down lists against each row.

**Comment by IanMayo** [comment]
Waiting on more test data to do this.
