### ISSUE TITLE
For some games the author of a message shouldn't be visible

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1706]
For one wargame we're simulating spoken radio comms via a chat channel.

In spoken comms the identity of the person sending the message will not be known to the recipients.

So, we should have a flag in game-admin over to "Hide identity of message authors" in some chat channels.  So, this will mean introducing a "options" panel at the top of "Chat" rooms - like we do for `mapping` and `collab status board`.

Start off with the backend data changes (Ian), then the admin page changes, then the chat channel itself.

**Comment by lebaphi** [comment]
do you have a design for it @IanMayo ?

**Comment by IanMayo** [comment]
I'm happy to do.the data changes first. 
I'll decide if we need UX in a couple of days.

**Comment by IanMayo** [comment]
Helle @lebaphi 
I've changed the TypeScript definition for a ChatChannel, and updated the UI to render messages accordingly.

![image](https://user-images.githubusercontent.com/1108513/182184854-5686432e-0212-4711-8214-eacc1e3cd9bb.png)


We just need to add a "Configuration" box at the top of the `setting-channels` admin page for chat channels, please.  This will be like the one for `mapping`, but will just have a text toggle (default off). The label will be `Hide message authors". A popup info box will say "Hide Force and Role for chat message authors".  In `setting-channels` we currently do _special processing_ for map channels using `renderMappingConstraints`. We'll have a similar method called `renderChatOptions`.

I hope that all makes sense :-)
