### ISSUE TITLE
Time Remaining Indicator is missing

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1709]
I've just realised that we aren't currently displaying the time remaining for a turn.

![image](https://user-images.githubusercontent.com/1108513/182129016-97e9f625-299c-4d76-b046-b0c579228844.png)

The wargame that ran at the end of last year didn't use SERGE timing/steps, so I hid it. I clearly forgot to reinstate it.

I can switch it back on, but it distorts the panel. At least it's working 🤣 

![gif](https://i.gyazo.com/6a33a1d6eed00ac0655cfd4b314ab1db.gif)

The time remaining helps players schedule their planning process - ensuring adjudication can happen on track.

The value counts down to zero in planning (which has fixed length), but increases up from zero in adjudication (since adjudication can take a greatly varying amount of time depending on the complexity of the game at that time).

The current "Turn Progression" panel looks great, but we also need to find a location for the time-remaining value. _Sorry_ 😉

**Comment by ShendMikullovci** [comment]
Hi Ian!

Nicely spotted! I'm afraid adding this new parameter breaks the integrity of the set up we came up with. I came up with some new looks that make more sense: 

![Time Remaining](https://user-images.githubusercontent.com/85491794/184926119-4e7466c1-df49-4200-8287-e2fcd3d73a5a.png)

On frame 10 (left), I kept the blue box we have, while rearranging the elements inside. Here, we have Labels on the left and their Values on the right (like we do in most of Serge). Emboldened values allow for a quicker spotting. 

On frame 11 (right), I got rid of the blue box to see how it looks through contrast only. If we're to add the "restart turn" feature, I have to say that the design on frame 11 would accomodate it better.

What do you think?

**Comment by IanMayo** [comment]
Thanks for that @ShendMikullovci .

Let's go for Frame 10 (left), since the dark block of blue pulls all this "overview" information together.

It will also re-arrange neatly in scenarios where we aren't showing "time remaining".

I'd like you to add it to your list of jobs, please @lebaphi
