### ISSUE TITLE
Possible issue with z-order for `<Select/>` control in Attribute Editor

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1728]
I'm in this game:
http://localhost:3000/?wargame=wargame-l63jlces&access=rl650chc3

I click on `R1` asset, and plan turn form opens.  I can then click on `Edit attributes`.  If I try to change `Depth` I don't see the values presented.  But, the direction of the triangle does change - so I think the items are visible, but beneath the popup.

![screencast](https://i.gyazo.com/b6c40368128bca1fa9259241ffc83d63.gif)

**Comment by lebaphi** [comment]
It seems I can not find this game in develop latest code @IanMayo

**Comment by IanMayo** [comment]
Hmm, it is in the game folder: 
![image](https://user-images.githubusercontent.com/1108513/183243916-89126c4c-1e48-476e-81aa-e9b9c88a15b1.png)

I did try to reproduce it from `storybook`, but the z-order for the `select` box works ok there:
![screencast](https://i.gyazo.com/91d8a24fc4946c46674220482f54caaa.gif)


(but - the z-order of the `Attributes Editor` is broken in storybook 🤣 )

**Comment by lebaphi** [comment]
> Hmm, it is in the game folder: ![image](https://user-images.githubusercontent.com/1108513/183243916-89126c4c-1e48-476e-81aa-e9b9c88a15b1.png)
> 
> I did try to reproduce it from `storybook`, but the z-order for the `select` box works ok there: ![screencast](https://camo.githubusercontent.com/e4e93d17383b9f3cf431ca36fe7b4e3d3544e27f49723f2b6aac1313e677ba9c/68747470733a2f2f692e6779617a6f2e636f6d2f39316438613234666334393436633436363734323230343832663534636161612e676966) [ ![screencast](https://camo.githubusercontent.com/e4e93d17383b9f3cf431ca36fe7b4e3d3544e27f49723f2b6aac1313e677ba9c/68747470733a2f2f692e6779617a6f2e636f6d2f39316438613234666334393436633436363734323230343832663534636161612e676966) ](https://camo.githubusercontent.com/e4e93d17383b9f3cf431ca36fe7b4e3d3544e27f49723f2b6aac1313e677ba9c/68747470733a2f2f692e6779617a6f2e636f6d2f39316438613234666334393436633436363734323230343832663534636161612e676966) [ ](https://camo.githubusercontent.com/e4e93d17383b9f3cf431ca36fe7b4e3d3544e27f49723f2b6aac1313e677ba9c/68747470733a2f2f692e6779617a6f2e636f6d2f39316438613234666334393436633436363734323230343832663534636161612e676966)
> 
> (but - the z-order of the `Attributes Editor` is broken in storybook 🤣 )

okay, I will take care of it 🤣
