### ISSUE TITLE
Allow Game Designer to set/update Perception of one asset by a force

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1743]
Players have perceptions of assets on other forces.

So, for each asset, Serge has a list of perceptions:
![image](https://user-images.githubusercontent.com/1108513/183704552-5d28f598-d00a-4555-a4b6-59e7505ed0ab.png)

Each entry is how another force perceives this asset.  The perception, may just be that there is "something" in a particular cell - so it's shown as a Grey Question-Mark. If force is known, then the icon is shaded. If the platform-type is known, then the relevant icon is shown. Note: these are perceptions, rather than facts - so the player may have the force or platform-type wrong.  Aah, lastly, they may perceive the name of the asset.

Currently, the Umpire only controls if a force an perceive an asset. If they can, it appears as a grey question mark - and the player must fill in the other details.  But, it would be good if the umpire could fill in the perception bits too.  It would also be good to be able to do this in the Game Design phase.

I _think_ the Game Design and Adjudication uses would be the same:  for each Asset in a force, there would be able a table with these columns:
- by (the force that is perceiving the asset)
- force (the perceived force of this asset)
- type (the perceived type of this asset)
- id (the perceived id (name/contact number) for this asset)

Game-Designer / umpire would be able to add rows to the bottom, or to edit individual rows, including deleting rows.

| By | Force | Type | ID |
|----|------|------|----|
|Blue-1| | | |
|Blue-2|Red|Yacht |
|Blue-3|Red|Tall Ship|MV Brigand|

The contents of "By", "Force" and "Type" would be drop-downs. The contents of "ID" would be free text, defaulting to the actual name of the Asset.

**Comment by IanMayo** [comment]
@ShendMikullovci - could you have a think about this please?

This is to allow the `Game Designer` to control how forces perceive assets from other forces.   Essentially, this would just happen in the game-design phase.  In the above design I describe a table to edit the other force perceptions of an asset. But, we do have an existing popup form that does the job.

![image](https://user-images.githubusercontent.com/1108513/189116566-a6317a67-ead2-40dc-8424-40c9d9c0b7c9.png)

Since this is in the admin pages we're _allowed_ to relax our UX standards a little.  

Any thoughts?

**Comment by ShendMikullovci** [comment]
I think it does the job. Couple of things we shouldn't forget:

1. Save button in light blue.
2. Cancel button in gray
3. The clouds are a little too dim. We usually use soft grayed blue like this one: 

![Panel](https://user-images.githubusercontent.com/85491794/189218868-406e8635-5612-4674-80c2-3bacccb3f042.png)

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci 

But, we do have a choice of whether to use a table, or this dedicated editor.  Since we'll be displaying all the perceptions anyway (to allow the Game Designer to review them), it seems simple enough to make the table editable (like all those other tables in the admin pages).

**Comment by ShendMikullovci** [comment]
> Thanks @ShendMikullovci
> 
> But, we do have a choice of whether to use a table, or this dedicated editor. Since we'll be displaying all the perceptions anyway (to allow the Game Designer to review them), it seems simple enough to make the table editable (like all those other tables in the admin pages).

My bad, I missed the part you said you wanted it in the admin pages. Have you considered adding it to the actual platform page? Something like this: 

![Platform Perception](https://user-images.githubusercontent.com/85491794/189446110-2b4e7f65-cd08-414d-b460-e41888beb7ff.png)

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - no, we can't put this into `platform-types`.   That is where "types" of platform are created, such as `fishing vessel` or `submarine`.  The perceptions relate to an `actual instance` of the fishing vessel or submarine.  So, it relates to a specific asset within a force.

I now the space seems constrained, but the implementation has to go in the right-hand column of this panel:
![image](https://user-images.githubusercontent.com/1108513/189885429-8dcce9cd-d748-473e-aa90-9fd5084276d0.png)

Hmm, the `list of assets` can certainly be made a little narrower.  I _guess_ the table would re-use the following component, with the columns/drop-downs as in the table I attempted at the top of the page here.
![image](https://user-images.githubusercontent.com/1108513/189885807-e2d14deb-4cda-4047-98fd-2e6dee96fde9.png)

**Comment by ShendMikullovci** [comment]
> Hello @ShendMikullovci - no, we can't put this into `platform-types`. That is where "types" of platform are created, such as `fishing vessel` or `submarine`. The perceptions relate to an `actual instance` of the fishing vessel or submarine. So, it relates to a specific asset within a force.
> 
> I now the space seems constrained, but the implementation has to go in the right-hand column of this panel: ![image](https://user-images.githubusercontent.com/1108513/189885429-8dcce9cd-d748-473e-aa90-9fd5084276d0.png)
> 
> Hmm, the `list of assets` can certainly be made a little narrower. I _guess_ the table would re-use the following component, with the columns/drop-downs as in the table I attempted at the top of the page here. ![image](https://user-images.githubusercontent.com/1108513/189885807-e2d14deb-4cda-4047-98fd-2e6dee96fde9.png)

In that case, I suggest we use it on the right-hand column you suggested. The list of assets can be narrower, but it contains quite a bit of information that is crucial to the gameplay, so I'd say let's avoid cluttering that page further. 

Here's how our column could look: 

![Perceptions idea](https://user-images.githubusercontent.com/85491794/191817458-6393e491-c9b8-4141-82f1-d31024807fdb.png)

Notice I've removed the chip display for the attributes and edit button. This buys us space and provides the user the ability to directly edit the attributes if necessary, without the extra steps of clicking on edit --> new editing window --> saving changes. Here, the user would directly edit and simply save channel. The arrows and Increase/Decrease would appear upon hover. 

One issue with this display is that if there are more attributes or more forces, there would be a need to scroll down.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci .  Each force will have its own perception of this asset.  So, `red` may think it's a `green`-`fishing boat`, but blue may think it's a `red`-`spy ship`.  The table I offered in the original description _seems_ the only way to represent this.

Hmm, dropping the `chips` for the atttributes hasn't gained space - the new version takes up more space.  Moving the editable version to the popup panel gained some space, IMHO.  Also, IMHO - the attributes will be read/reviewed more than they will be edited. So, having the editable version on a popup form seems a _fair_ compromise of space vs convenience.

**Comment by ShendMikullovci** [comment]
Hmmm... Maybe since we have two variables (perception _and_ perceiver), we should filter through perceiver first. We could use your first example: 
 
> ![image](https://user-images.githubusercontent.com/1108513/189116566-a6317a67-ead2-40dc-8424-40c9d9c0b7c9.png)

But instead have the user select each Force in a drop down list (like for "Perceived Type") to view how every Force perceives it? 

Problem with this is that it would add steps (each Force would have to be looked at individually...).

**Comment by IanMayo** [comment]
There are 4 variables (we may even be about to move to 5):
* who is perceiving it
* what force they think it is
* what platform-type they think it is
* what they think it's called (either the real name, or the contact Id (`C234`)

The new one for this wargame is:
* what condition they think it is (working, disabled, destroyed)

For the current wargame there's lots of blowing stuff up.  Sometimes players don't know if something has been destroyed or no - so they need to arrange for something to double-check it's condition before they decide to attack it again.

For the above - the table (with dropdowns) seems the only way of doing it.

**Comment by ShendMikullovci** [comment]
In that case, let's move ahead with the dropdown table for now.

**Comment by IanMayo** [comment]
Ok devs. Let's use this as an opportunity to use a `primereact` data table:

https://primefaces.org/primereact/datatable/
