### ISSUE TITLE
A. Create Support Panel

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1747]
Create child component that extends the mock `ChannelPlanning` developed in #1745 with following properties:
- Has tabs (similar to WorldState panel)
- Just have single "mock" tab to start with
- Occupies full height of page
- Drag bar to change width
- Clicking on tab collapses panel
- Has these props:
    - player role
    - player force
    - messages for this channel
    - current `forces` from wargame

Note: I've created a `PlanningChannel`, which itself contains a `PlanningMessagesList`.  This `PlanningChannel` will get extended with the above requirements, with `PlanningMessagesList` being the initial `My Orders` tab.

Hmm, I wonder if it's worth using `flexlayout-react` for the vertical tabs?  We're already using that component, after all.  The tabs won't need to be editable, but I think the implementation will be simpler than the way we did it with WorldState.

Here is a mockup:
![image](https://user-images.githubusercontent.com/1108513/184122471-919441a7-0486-4690-9f18-172b195169ab.png)

**Comment by lebaphi** [comment]
Hi @IanMayo @ShendMikullovci , do we have a mockup for the tab content?

**Comment by IanMayo** [comment]
No @lebaphi .  We're waiting to get more from the users - it could be a couple of weeks.  But, I'll try to mock data for now.

This component is just the "container" - it's the 3 children (two tables and a tree-table (#1748 and #1749) that I'll need to learn more about, and/or mock up.
