### ISSUE TITLE
C. Create orders component

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1748]
Use table component to display list of messages.  A _placeholder_ for this has been created as `Planning-Messages-List`.

Suggest this component: https://github.com/mbrn/material-table

Props (all from state):
* channel id (to be used when sending new message)
* messages for this channel (duh)
* player role (to be used when sending new message)
* player force (to filter messages)
* isUmpire (if true, include drop-down at top of channel to choose `view-as` force)
* templates for this wargame (used to render message _detail_, and for creating new messages).

Component will run "map" on messages to produced reduced array suitable for rendering.  The reduce function will extract the fields displayed below.

Display one row per message, initially (*) with these headers:
* id
* title
* from-role
* status
* start date
* finish date

(*) Users to provide exact fields in early Sept.

Page should have `sort` on id, title, start-date, finish-date. Page should have `filter` on `status`.

It should be possible for players to expand messages, to read the detail (presented using the JSON-Editor with the relevant template - like how we did for `COA Status Board`).

Have mocked up how a player may view their orders here:
![image](https://user-images.githubusercontent.com/1108513/187191841-8059b2f6-f16a-4c78-a180-8c5ea84b972f.png)

**Comment by lebaphi** [comment]
Hi @IanMayo , should I work on this ticket now or wait for the mockup to be available?

**Comment by IanMayo** [comment]
let's get started please. The columns are just a detail, let's learn about integrating the table component.
