### ISSUE TITLE
D. Create PlanningAssets component

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1749]
Create a component that shows a table of assets.

A `renderer` method (passed in as prop) will take an `Asset` object and return a `string[]` of table cells.

Props (all from state):
* ForceData[] (source data)
* PlayerForce - display data for that force
* isUmpire - if true, included drop-down for umpire to choose `view-as` force

The component should receive a `forces` object, `player-force` value and `renderer` method in `props`.

If `player-force` is provided, only show assets of that force.  If no `player-force` provided, show all assets.  The renderer method will either return the real values (when looking at own force) or `perceived` values (when looking at other forces).

Use this table component:
https://github.com/mbrn/material-table

Where an asset `comprises` other assets, the `children` assets should be grouped beneath the parent.

Test data is present in `p9.mock.ts`, developed in support of #1745 

Have attempted to mockup of how a player may see "own" and "other" assets:
![image](https://user-images.githubusercontent.com/1108513/187191691-dcdf8088-3fb3-4255-8824-caf8ef2c8a90.png)

**Comment by lebaphi** [comment]
Hi @IanMayo 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/26705621/186919225-70f01727-d8be-4370-b2e0-ca61bf59c44a.png">

This is an asset in the P9 mock data, so how do you think we will process data in render function? which fields to be displayed in the table?

**Comment by IanMayo** [comment]
Let's show these columns, please:
- ID (Contact Id)
- Name
- Condition
- Status
- Platform-Type
