### ISSUE TITLE
Contents of Chat message being written get lost on changing tab

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1757]
I'm writing a chat message. I switched tab to the mapping tab, then back to chat - and my text had disappeared!

Hmm, I guess that the event that triggered the "wipe" shouldn't cause a refresh.

I don't think there's an easy solution.   12 months ago we worked hard on performance with channels that have lots of messages - so we don't render channels that aren't visible.

Before we did that, I guess the draft contents of a new message would still be there when the player tabs back.  But, I don't think we can return to rendering all tabs (visible and non-visible).

Hmm, so what are the possible solutions?
* for a hidden tab, don't render the message list, but do render the edit form?
* monitor form changes, and put copies of the form contents into browser-memory?
* monitor tab going invisible, and persist any open editors to memory. Restore them on tab coming visible?

***Update:*** - we need a similar fix to this for when JSON-editor is editing a document in a "Custom Channel".  An example of a custom channel is the `Blue & SME` channel in `PAPA FOXTROT` wargame, when logged in as `Blue - Senior Blue`.   For long templates, is it worth trying to store all the JSON in one token?

***Update 2:***. I _like_ the idea of putting the full message into one token.  I was worried about the length of data we an fit into expired storage.  But, it has just stored and restored a 85,000 character message. That's 24 pages in a word document.  I think we'll be ok :-). The _great_ news is that it's persistent between sessions, so if I refresh the browser, it still remembers the text :-). Yes, let's store the whole message (as JSON) in expired storage.

**Comment by lilitkarapetyan** [comment]
Hi Ian, I write a chat message, then go to the mapping tab, go back to chat, the text doesn't disappear for me.

**Comment by lilitkarapetyan** [comment]
You get that  error every time you come back from mapping ?

**Comment by IanMayo** [comment]
Ok. Will write steps to reproduce.

**Comment by lilitkarapetyan** [comment]
Ok thank you.

**Comment by IanMayo** [comment]
![Screencast](https://i.gyazo.com/1d24c3d294b57cc853f665cbb72b4771.gif)

**Comment by lilitkarapetyan** [comment]
Thanks, I will investigate it.
