### ISSUE TITLE
Numeric Attribute Value Issue

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1790]
Hi everyone!

I encountered this issue while trying to change the default value to a numeric attribute:

https://user-images.githubusercontent.com/85491794/187743953-f31deb5b-9b0b-4f73-8aba-f1c7feccbab3.mp4

As you can see, clicking on the value and typing the number doesn't replace the default 0 and hitting backspace doesn't delete the default 0 either. The only way to delete the 0 is by selecting it via mouse. 

I think simply clicking on the value should select it, for the typing to insert and replace with a new value. The backspace should also work.

**Comment by IanMayo** [comment]
This is a niche part of the app, just used by the Game Designer.  The above behaviour is to ensure we always have a default value.  I think we can let it slip.
