### ISSUE TITLE
States info window bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1791]
Small bug in the states info window:

![Info window text bug](https://user-images.githubusercontent.com/85491794/187745131-4921b12a-0e23-4c7a-a63f-70af7bf7df98.png)

The whole word "planned" should either go down a line or stay up.

**Comment by IanMayo** [comment]
Hello @lebaphi - are you able to modify our `MoreInfo` component so that the text content wraps nicely please?

**Comment by lebaphi** [comment]
sure @IanMayo

**Comment by ShendMikullovci** [comment]
Thanks @lebaphi !
