### ISSUE TITLE
Weird message in the channels tab/admin page

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1794]
Do you guys recognize this? : 

![Message in Channels Tab](https://user-images.githubusercontent.com/85491794/187748945-5507ef9d-e5cf-4809-949c-8a72d8fc8393.png)

**Comment by IanMayo** [comment]
Sure. For some old wargames, we defined the channel in a way we don't now.  It's not worth maintaining the admin pages for these old wargames - so we don't.

But, I'll improve the message to include a more detailed explanation of why we aren't providing an editor.

Aah, hold on @ShendMikullovci - are you able to produce steps to reproduce this issue please?

**Comment by IanMayo** [comment]
Ok, sorted it. We now give better messaging for unrecognised channels.
Select the `Blue Planning` channel here:
https://serge-review.herokuapp.com/storybook/?path=/story/local-organisms-settingchannels--with-planning

**Comment by ShendMikullovci** [comment]
Still appears: 

![Weird message 2](https://user-images.githubusercontent.com/85491794/189219716-c1fac40c-ec3f-4f3d-98f5-4a3f4a7176ea.png)

**Comment by IanMayo** [comment]
Ok.  Once change #1830 is merged we'll give more diagnostics. That should explain why the chat channel isn't being rendered - we'll need a new screenshot showing the new diagnostic text, please @ShendMikullovci
