### ISSUE TITLE
Asset Control Issue

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1796]
I was asked to specify asset control in the Mapping channel for the first default force, but wasn't asked for the forces that I added myself: 

https://user-images.githubusercontent.com/85491794/187754516-b79c7037-005a-40c0-bc41-dd46e689c80c.mp4

When I tried to give control to all roles, it wouldn't let me: 

https://user-images.githubusercontent.com/85491794/187754316-77799194-4ae8-4731-a5dc-7ad29237b2cc.mp4

If only one role can control an asset, then we should make sure that every time a force is added, it is controlled automatically by one of the roles (CO, for example), and not by "All Roles".

**Comment by ShendMikullovci** [comment]
Specifying one role doesn't seem to work either: 

https://user-images.githubusercontent.com/85491794/187756927-38f64cdf-c5c7-4e3c-8683-8bc4951dca12.mp4

**Comment by IanMayo** [comment]
Aah, the PR does actually fix this.
