### ISSUE TITLE
Save Channel Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1797]
Saving the Mapping (or any other channel) seems to redirect to the top channel on the list, with its label shown on the list and in the window. The Mapping channel content remains however:

https://user-images.githubusercontent.com/85491794/187759546-49ac823a-b75a-4431-a52b-3632ef82b5f2.mp4

**Comment by IanMayo** [comment]
Closing this @ShendMikullovci  .  Recent updates appear to have fixed this.
