### ISSUE TITLE
Compiled Assets UI

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1800]
We had a similar issue with annotation markers (#1582), but I see that we need to apply the same solution to compiled assets as well: 

![Compiled Platforms](https://user-images.githubusercontent.com/85491794/187765441-eb5a470c-63a6-4d70-abf6-9afb4fe6e2b4.png)

**Comment by IanMayo** [comment]
Close. Related to #1852

**Comment by ShendMikullovci** [comment]
> Close. Related to #1852

1852 doesn't exist?

**Comment by IanMayo** [comment]
Oops, #1582 - as you indicated at start.
