### ISSUE TITLE
Submit New State Notification

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1801]
After submitting a new state, I got a notification on the mapping channel tab: 

![Submit State Notification](https://user-images.githubusercontent.com/85491794/187773750-4fae288a-a9c4-4dc8-87fa-076bead5282d.png)

What does this notification mean?

**Comment by IanMayo** [comment]
Correct.  We should remove the message counter from the Mapping tab. 

Maybe we need a _model_ for channels to indicate if they should have a message-read counter or not.

**Comment by ShendMikullovci** [comment]
Test Wargame still has the notification: 

![Mapping notification](https://user-images.githubusercontent.com/85491794/191792674-992abac9-862e-46d0-830a-21663e4e6c74.png)

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci .  I've tried a few wargames on `serge-review`, and none of them show the unread message count for `Mapping channel`:
![image](https://user-images.githubusercontent.com/1108513/191798576-cbbaf0d3-51b5-4f7b-87f9-480b52dc6b70.png)

Could you give me some specific steps to reproduce what you saw please ? (URL of Serge instance in use, name of wargame, role logged in as).
