### ISSUE TITLE
Unable to move asset in the map

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1802]
Can't seem to be able to plan out moves for the assets with any force. The bottom left panel won't appear when clicking on asset either: 

![SEA CO](https://user-images.githubusercontent.com/85491794/187775226-def13bbe-6666-4075-b53c-d9b66bba716e.png)

**Comment by IanMayo** [comment]
We'll need something more reproducible, please @ShendMikullovci 

That could be steps within an existing wargame (easiest to reproduce) or the steps to create the simplest wargame that experiences this issue.

**Comment by ShendMikullovci** [comment]
So this turns out to be an issue for new wargames (Test Wargame, in this example). 
However, I can't reproduce because I can't add the assets to the mapping channel: 

[5f961f40-6e5d-47a2-89b2-7ab30fb06816.webm](https://user-images.githubusercontent.com/85491794/189223387-4540ce80-b767-468d-9a6c-79145195d2a4.webm)

It seems like there's a problem with editing the channel. I can only add a role through the bottom of the channel. 

At the end, assets are not clickable in the mapping.

**Comment by IanMayo** [comment]
Sure - will look at this - starting with the Game Admin issue.

**Comment by IanMayo** [comment]
Aah, the issue is with the earlier two forces.  It's them that have `all roles` controlling an asset.  Will improve error messaging.

**Comment by IanMayo** [comment]
Ok @ShendMikullovci . Found (and fixed) the error in specifying who can control assets.  It was mistakenly throwing an error when one `role` was specified.  The review versions on Heroku should be ready soon. Done!

**Comment by ShendMikullovci** [comment]
I guess I'm not doing it right then. For some reason, I can't move them around during either phase. Could you show me how you do it?

**Comment by IanMayo** [comment]
Here is a working mapping component:
https://serge-review.herokuapp.com/storybook/?path=/story/local-mapping-smallscale--natural-earth&args=phase:planning;infoMarkers[0].position.lat:50.23249506295051;infoMarkers[0].position.lng:-19.528946616760432;infoMarkers[1].position.lat:50.24310600328171;infoMarkers[1].position.lng:-19.467288440193588;infoMarkers[2].position.lat:50.24692461728551;infoMarkers[2].position.lng:-19.570488735586327

You can select `TALN` then plan its turn. (you may have to switch to the `Blue1 - BlueCO player`, and switch Phase to `Planning`.

For the demo wargames, they may be in a state that doesn't allow planning (such as if the game isn't yet initiated).
