### ISSUE TITLE
Asset Panel Redesign

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1803]
Our current design of the asset panel in the map hasn't been updated to the color codes and general design feel we're going for. Here's how a new version could look: 

![Bottom Left Tab Redesign](https://user-images.githubusercontent.com/85491794/187775901-04f1fae5-78da-4886-a267-d7c13b79bc4e.png)

**Comment by IanMayo** [comment]
This largely seems cosmetic. Let's sweep it up if we are doing other `Adjudication form` modifications.
