### ISSUE TITLE
Message order bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1804]
It seems older messages are being put below recent ones, when it should be the opposite:

![Message Order](https://user-images.githubusercontent.com/85491794/187777501-27e1c19f-99b1-4d66-aaab-0d4c7d3bc914.png)

**Comment by IanMayo** [comment]
We should be consistent across the assorted types of channel (chat, custom, admin and feedback).

I can't remember which "standard" we agreed upon. We seem to have the GMAil model - where newest is at the top, or Instant-Messaging model, where newest are at the bottom.  Do you remember our previous decisions on this @ShendMikullovci ?

**Comment by IanMayo** [comment]
Closing. We covered this here:
#1663

**Comment by ShendMikullovci** [comment]
So, we're good with _New Messages_ at the _Bottom_?

**Comment by IanMayo** [comment]
@ShendMikullovci - it had to be one or the other 😉 

As stated above, we have to follow either the email model (new at top) or the instant messenger model (new at bottom).  Serge channels are closer to the instant messenger experience than the email one.

Unless you have any other perspective/thoughts...

**Comment by ShendMikullovci** [comment]
I'm good with new at bottom, since I do agree that the channels are closer to messenger experience.
