### ISSUE TITLE
Unusual behaviour with single channel

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1838]
With a blank wargame, or if we delete all channels, when we create the first channel it isn't selected, and clicking on it has no effect.

It's only when a second channel is added that either can be selected.

Also no: when we have channels, and the final one is deleted, the detail panel for that channel is still shown.

[screencast](https://i.gyazo.com/f7d19fa967869a5d806d9f08f64ba33a.mp4)

**Comment by lebaphi** [comment]
Hi @IanMayo, it seems that we can't reproduce it, I get the latest develop, build and run it on an incognito browser, you can see it in this video

https://user-images.githubusercontent.com/26705621/189651978-71b1c16e-ba60-4aa3-a233-261436a25468.mov

**Comment by IanMayo** [comment]
That looks like good news :-)

Maybe I need to update `develop`.

**Comment by IanMayo** [comment]
Yes, working perfectly @lebaphi :-)
