### ISSUE TITLE
Support Panel - create new orders

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1855]
The Support Panel has an orders tab:
![image](https://user-images.githubusercontent.com/1108513/190681556-8e6e3470-d758-4eaf-b450-648648a62d26.png)

The tab currently shows a list of templates for that set of orders.  We should allow players to create new orders.  The "New orders" will be shown as a drop-down list, that the user clicks to indicate what type of document to create. ( Hopefully we can re-use the implementation in "New Message", now that it has been refactored):
![image](https://user-images.githubusercontent.com/1108513/190681988-13636277-5b41-44d1-a170-b907bdba4aad.png)

See the `Blue & SME` tab here: https://serge-review.herokuapp.com/?wargame=wargame-kskl1i3t&access=pkskl17ti

**Comment by lebaphi** [comment]
it would be good if we place this component at the bottom of the support panel (in Order tab) ? @IanMayo

**Comment by IanMayo** [comment]
Thanks for that @lebaphi 

If NewMessage needs those props in order to send messages (with all the correct metadata), then I think we have to provide those props.

I'll try to have a look at the code this morning, and give you an answer.

**Comment by IanMayo** [comment]
Yes, at the bottom of the Orders tab in support.  We do have something similar at the bottom of the `CollabStatusPanel` - but I don't know if that allows multiple templates.
