### ISSUE TITLE
Delete Permission Bug

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1871]
Hi everyone! 

It seems the delete permission feature isn't working very efficiently: 

[7f1708cb-069c-4ca9-a353-8bc3f2061f2a.webm](https://user-images.githubusercontent.com/85491794/191802225-cf4519b2-51c1-47a9-a987-49d4e6cc2d9d.webm)

This was after I deleted 5 - 6 other permissions, and the feature started malfunctioning.

**Comment by IanMayo** [comment]
Sure, thanks for spotting it @ShendMikullovci .  Assigned to @lilitkarapetyan

**Comment by lilitkarapetyan** [comment]
Hello @all. I couldn't get this bug.

**Comment by IanMayo** [comment]
Could you check if it is still there please @ShendMikullovci ?

**Comment by ShendMikullovci** [comment]
> 

Just tested and re-tested. Looks like it's gone.
