### ISSUE TITLE
Select assets from the map

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1886]
We can currently only select assets from the table.

Players should be able to select assets from the map, too.

Note: currently the `Own Assets` and `OpFor Assets` tables are multi-select.

We should support this on the map, via the `ctrl` key.  So, if the player clicks on an asset - it should become the new single selected item.  If they hold down the `ctrl` key, the asset should be added to the current selection.

Note: we will also have to modify the `Own Forces` and `Opp Forces` tables - so that their items get marked as selected with triggered from the map.

I _suspect_ that `SupportMapping` will have to be modified to introduce `setSelectedItems()` and `selectedItems` props.  These will be passed down to `PlanningForces` in order that the onClick` handler for the markers can either replace the selected items with the new one, or to add the new item to the list (`ctrl` held down).

The `selectedItems` and `setSelectedItems` will sit in `PlanningChannel` - replacing `selectedItem` and `setSelectedItem`.

**Comment by lebaphi** [comment]
> We should support this on the map, via the ctrl key. So, if the player clicks on an asset - it should become the new single selected item. If they hold down the ctrl key, the asset should be added to the current selection.

for this requirement I update it with a different approach: click on the asset -> mark it selected, click it again -> deselect it. I think this way of working will be more convenient for users, just click instead of holding the ctrl key @IanMayo

**Comment by IanMayo** [comment]
> for this requirement I update it with a different approach: click on the asset -> mark it selected, click it again -> deselect it. I think this way of working will be more convenient for users, just click instead of holding the ctrl key @IanMayo

That's completely fine, let's give it a go :-)
