### ISSUE TITLE
Mark transit routes with arrows

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1890]
One day ( #1863 )  players will add lines to mark transit routes in orders.  But - the direction isn't clear:
![image](https://user-images.githubusercontent.com/1108513/192337254-1cc95f2e-dbf8-41b5-bd5b-be05719b2529.png)

[This](https://github.com/bbecquet/Leaflet.PolylineDecorator) library can decorate lines with icons or arrows:

![image](https://user-images.githubusercontent.com/1108513/192337365-46dacf1c-11a2-484d-a723-9631b19789cf.png)

Note: here is an article on a react implementation, but @IanMayo  couldn't get the code to work: https://stackoverflow.com/questions/57143284/how-to-use-leaflet-polylinedecorator-in-react-16-4-1

**Comment by lebaphi** [comment]
<img width="163" alt="image" src="https://user-images.githubusercontent.com/26705621/194715368-f6b573c9-531f-4dda-8ceb-6341b6575f7f.png">

I wonder how to active this drawing tool @IanMayo ?

**Comment by IanMayo** [comment]
There isn't a drawing tool in Serge at the moment.  That will be one of your next tasks, as we integrate `leaflet-geoman`

**Comment by lebaphi** [comment]
okay, so I think we should complete this task first 😄

**Comment by IanMayo** [comment]
Yes. The top screenshot was taken using the GeoMan demo page. 

If you can integrate the correct lib, and get a line on the map with arrows, I can integrate it with the relevant code.  I _Think_ that will be in plan mapping orders (or something like that).

**Comment by lebaphi** [comment]
I think it done by #1862
