### ISSUE TITLE
Cascading menu to trigger creation of new orders

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1895]
@IanMayo has produced the list of activities, now we need to create the menu.

Ok. The data is in there for the PlanningChannel story (#1907). `MapControl` is receiving the `actionItems` data (a tree of menu items).  We just need to make the menu popup, and pass the values to the `actionCallback` callback:
![image](https://user-images.githubusercontent.com/1108513/193230644-2ad11691-045f-4e7b-b596-0d1ab93fdcd8.png)

On Thursday I tried a number of different components to do this, but failed every time :-(. So, I don't really mind if we use an existing popup menu control or do it by hand.

Here is a control that provides a menu:
https://github.com/adammertel/Leaflet.Control.Select

**Comment by IanMayo** [comment]
This is the next one for you, please @lebaphi 

For the UX, we will just have a new button on the toolbar.  It will have the `file-plus` icon.  Clicking it will show a drop-down tree menu of the contents of the `actionItems` object.

**Comment by IanMayo** [comment]
Ok, @lebaphi - the data and control are ready for this.

My dodgy attempt (non-popup) is in `develop` in `NewOrderActions.tsx`.   You can view the control from this story: http://localhost:6611/?path=/story/local-organisms-planningchannel--default

**Comment by IanMayo** [comment]
This is the next one for you, please @lebaphi :-)

**Comment by lebaphi** [comment]
> This is the next one for you, please @lebaphi :-)

sure @IanMayo
