### ISSUE TITLE
Display geometry name on polygons

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1898]
For a selected set of orders [*], we should display the "geometry name" in the polygon, or next to the marker point.

[*] we don't have orders yet

**Comment by lebaphi** [comment]
could you provide some screenshots on this task @IanMayo ?

**Comment by IanMayo** [comment]
The `Orders` objects aren't being rendered, so I have a PR in that makes them render:
![image](https://user-images.githubusercontent.com/1108513/196205592-64b6f3e0-2d3f-42cc-978a-db290b01b924.png)

The issue here is that I wish the name of the polygon to be permanently visible at it's centre.  This is like how we display the name of the activity for polylines.

Once the `render orders ` [PR](https://github.com/serge-web/serge/pull/1932) is done, there will be at least two polygons on the screen (as shown above).  These polygons are generated in `SharedOrderRenderer.tsx` - in the `Polygon` block of `shapeFor`.

Here is a react component which shows. a div-icon.  I _think_ that DivIcon is the way of permanently showing a span of text on the map:
https://www.npmjs.com/package/react-leaflet-div-icon
