### ISSUE TITLE
Adopt MapContainer

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1910]
We're currently creating the map using `react-leaflet` `Map` control.  But, if we use `MapContainer` then we will be able to use `useMap()` hook in child components.

Plus, if we pass `children` into the map control using props, then we can create functionality outside the map container class.

So, step-1 is to switch `SupportMapping` to use `MapContainer`.

Step-2 is to move `SupportMapping` to `Map` - and remove any functionality that is specific to `PlanningChannel`.  To do this, we'll have to pass the two `LayerGroup` components in as `children`.

**Comment by lebaphi** [comment]
Hi @IanMayo, currently we are using v2, and `MapContainer` is supported from leaflet v3 with many changes in interface, components. I tried install leaflet v3 and it seems we need to refactor quite a lot of legacy code.

Should we do this thing in this ticket?

**Comment by IanMayo** [comment]
Leaflet has just moved to 1.9
![image](https://user-images.githubusercontent.com/1108513/193395645-246072c0-a424-42c9-8015-7ccf22765e6b.png)

Do you mean v3 of `react-leaflet`? 

> many changes in the interface.  

Hmm, how about this...

We adopt v3 (or even v4) for `SupportMapping` component - and leave `Mapping` running v2?  I can then come back and refactor `Mapping` to v3.

[This](https://stackoverflow.com/a/56495651/92441) seems to be how to install multiple versions of a package.

If we can't do two versions I'm happy to do the refactoring.

**Comment by lebaphi** [comment]
> Do you mean v3 of react-leaflet?

Yes.

> [This](https://stackoverflow.com/a/56495651/92441) seems to be how to install multiple versions of a package.

I will try with this approach

> If we can't do two versions I'm happy to do the refactoring.

The last solution that we must do I think lol
