### ISSUE TITLE
Upgrade TS to 4.5

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1918]
We're using `react-leaflet`, but it is generating TypeScript errors like those reported here:
https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat

It appears that `react-leaflet` is using a T/S "type specific import" construct that only arrived with TypeScript 4.4.

I tried upgrading the repo to that version, but Storybook broke (it couldn't find any stories).

So, I guess we need to upgrade TS (& maybe) storybook in `develop`, get the build working, then the `adopt MapContainer` branch can be updated with the new build setup.

I'm happy to help test-drive the branch once it has been updated, to check everything still builds/works.

**Comment by lebaphi** [comment]
I think it done @IanMayo

**Comment by IanMayo** [comment]
Yup:
![image](https://user-images.githubusercontent.com/1108513/195592046-0619860b-a672-4e68-8529-c33e4c5562f9.png)
