### ISSUE TITLE
Mismatch between wargame versions

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#194]
This seems to be Serge's **traditional** flow of wargame changes:
1. there is a wargame change to be made
2. request newest version from database
3. apply change to that version
4. push that version back to the database
5. other players then receive the new version, and render it

But, with our interactive mapping, we're making more frequent minor changes to the database:
1. there is a wargame change to be made
2. send change off as message
3. browsers receive message, use reducer to modify current local copy of wargame

But, with the newer flow of data, when admin clicks on "Next turn", the traditional flow happens, and the most recent wargame is pulled from the database, which overwrites the local one that we've applied our changes to.

So, each time the backend wargame is modified, any local game changes are overwritten.

I think we need to look at options:
* each time we need a wargame change, pull the newest version, apply the change, then push it back (creating lots of wargame increments).
_or_
* let white maintain the current 'master' version wargame.  On 'Next Turn', modify the current local master, and push that to the backend - which comes back for all to see.

Aah, I think I've got it.  We currently act on changes in the `playerUI_reducer`. That only makes changes to the PlayerUI (duh).  If we want to make database modifications, we should do it via the `wargames_api.js`.

**Comment by zukilover** [comment]
A quite tricky but I think is feasible, is by adding a kind of interceptor before applying changes from the backend, compare with the local changes, and apply only what's different between both.

**Comment by IanMayo** [comment]
Ok, I think I've got it.  Here's the solution:
![Serge DB Comms](https://user-images.githubusercontent.com/1108513/72887510-be973c00-3d03-11ea-98cb-365a917c355e.png)

We store new "orders" (or other) messages in the database, then we pull a new copy of the wargame, apply the orders to that wargame, then submit that wargame.

**Comment by IanMayo** [comment]
Closed in #197
