### ISSUE TITLE
Selected Asset in Map should appear in the Panel

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1962]
Once the user selects an asset through the panel on the left hand side, the screen adjusts and centers upon that asset, which is a great feature. I suggest we apply the same feature for a vice versa scenario: clicking on an asset in the map could automatically show the selected asset in the list, and scroll down until the selected asset is centered in the list or at least visible. 

The end result should show the asset clicked on the map and the centered list: 

![Map SC 2](https://user-images.githubusercontent.com/85491794/197833271-437a8814-9084-4c07-9e2d-b56f2a921dd4.png)

**Comment by IanMayo** [comment]
Ok @lebaphi let's do this please.

When a new asset is selected, and if that tab is visible, then we should scroll to show the newly selected asset.

So, this will be in the `PlanningAsset` component.  It gets `selectedAssets` from the context.  I guess we have to cache the `selectedAssets`. Then if the new `selectedAsset` has an item not in the cached `selectedAssets`, then we should scroll the table to that row.
