### ISSUE TITLE
Some activities don't trigger drawing editor

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1963]
@ShendMikullovci  is experimenting with the planning tab.

Some activities from the popup menu do not trigger the drawing editor.  Possibly `precision strikes` in Land domain.

The issue appears to be irrelevant of the asset selected.

**Comment by ShendMikullovci** [comment]
Here's another issue I accidentally stumbled upon while experimenting: 

![Orders Tab Overlaps New Message Box](https://user-images.githubusercontent.com/85491794/197871280-2bd881dc-0b31-4f6f-b11b-7acda7b2b0a6.png)

It appears that the Orders tab overlaps the New Message box, making it impossible for players to view the content. Inconsistent occurrence however.

**Comment by ShendMikullovci** [comment]
Here's what I got so far: 

https://user-images.githubusercontent.com/85491794/197875662-8ae84009-ab19-4f93-b7a1-bb5c9fb7ce43.mp4


Here are my notes during my experimentation: 

User: Mar-1 
Activities: Maritime 

Asset Type: Frigate and Frigate - TA

Blue 11: Frigate - TA; Working condition, Passive State, Air2 Ownership

Blue 11: After zooming out, I couldn't perform an Area Reconnaissance (the cursor doesn't appear).
P.S. I had already performed a Precision Strike, Area Strike and Transit beforehand.

Blue 11: Performing a Point Reconnaissance crashed the screen. Refreshed and re-tried, didn't crash. 

Blue 12: Frigate, Working Condition, Transiting Status, Mar-3 Ownership
Screen crashed performing a Precision Strike. Refreshed and re-tried, didn't crash. 

Screen crashed again. This time performing a Transit.

It appears the crashes happen when the action performed is completed upon the same point. It's not fully consistent, but it happened 4 times so far.

**Comment by ShendMikullovci** [comment]
Side-note: The activity button seems to have over-saturated:

![Activity Button](https://user-images.githubusercontent.com/85491794/197877242-95c686fb-9917-4c86-8927-f56498351eaa.png)

**Comment by ShendMikullovci** [comment]
Another occurrence pattern: 

https://user-images.githubusercontent.com/85491794/197881163-f16ced0c-3ea4-4e84-bad4-c4447d02003e.mp4

Here are my notes: 
Blue 4: Frigate - TA, Working Condition, Transiting Status, Air-1 Ownership
Screen crashed during a Transit, upon completion of the route. 
Refreshed and re-tried. Didn't crash.

Screen crashed doing an Point Reconnaissance, upon completion of the Out Route.

Screen also crashed doing an Area Reconnaissance. In 2 of these crashes, 
4 Route Out steps were taken. 

Tested the 4 Route Out steps and it crashed again.
Happens more consistently during Area Reconnaissance right after having
finished a Point Reconnaissance. 4-Route-Out-steps crashes happened 4 times.

**Comment by ShendMikullovci** [comment]
Update: 
https://user-images.githubusercontent.com/85491794/197880804-55449677-00ee-43e0-a424-ac25e64ab48f.mp4

**Comment by ShendMikullovci** [comment]
Update: 

https://user-images.githubusercontent.com/85491794/198135933-c606fd75-2d0d-4838-ac68-ddbb1b71b0f0.mp4

**Comment by ShendMikullovci** [comment]
Update: 

[877c07f3-1e17-4654-b0e1-d80d610f4dc3.webm](https://user-images.githubusercontent.com/85491794/198137485-e16bfa98-f3e8-4fc6-9f50-1e9d927b6afe.webm)

**Comment by ShendMikullovci** [comment]
Update: Missing marker/target area is a definitive indicator to the screen crashing. 

[fdca33cd-6cc7-446f-9ae1-6e31747bd39e.webm](https://user-images.githubusercontent.com/85491794/198140148-b943eba8-284c-4e91-af71-fb21fa448e7a.webm)

It also appears this phenomenon isn't asset-type or activity dependent, and happens most consistently on the 2nd trial of the same activity.

**Comment by ShendMikullovci** [comment]
Update: Tried it on Land activities. The crashes happen identically with the same methods deployed, so the crashes aren't category dependent.

They also crash the same way whether I use a different shape for the steps (i.e., triangular vs linear), so the crashes aren't shape dependent.

**Comment by IanMayo** [comment]
@ShendMikullovci - could you run through some more tests, please?

A number of the issues you've identified above have now been fixed.  It would be useful to find out what still isn't working.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - more issues in the "Plan orders" process have now been resolved.  There is still merit in you doing some more testing please, particularly if you can identify reproducible issues.

**Comment by IanMayo** [comment]
Done.
