### ISSUE TITLE
New Orders panel falling behind Orders List

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1970]
I'm in the real game (`yarn develop`), in `P9 Test`, playing as `Blue`, `Mar-1`.

I'm in the Planning Channel, with the `My Orders` tab open.

When I expand the `New Message` panel at the bottom of the `Support Panel`, the new-message box sits behind the table of orders.

It should either sit in front of the table, or take space away from the table.  Hmm, I think taking space from the table is best, so that players can still view the other Orders items.

![Screencast](https://i.gyazo.com/58fdf8631273d9a89cffaba0c911fd15.gif)

**Comment by lebaphi** [comment]
Strange, It works on my machine 😂 

https://user-images.githubusercontent.com/26705621/198638744-97088f9e-40bc-42a6-b472-e6ea3dfe1355.mov

**Comment by IanMayo** [comment]
Yeah @lebaphi , works for me, too.  Testing more widely.

Aah, there's no problem for `Game Control`. The issue arises when playing as `Mar-1`, `Mar-2`, etc.

**Comment by lebaphi** [comment]
okay, I'm checking it...

**Comment by lebaphi** [comment]
It still works @IanMayo  😂 

https://user-images.githubusercontent.com/26705621/198649237-fe31802a-ad37-477c-a72d-6225ff793a98.mov

**Comment by IanMayo** [comment]
Could you try this hosted URL please? https://serge-sql.herokuapp.com/?wargame=wargame-l6nngxlk&access=rk116f52

I'm on this Chrome build:
![image](https://user-images.githubusercontent.com/1108513/198651922-2391e35f-e078-4ad3-ab5a-0fb02847ce41.png)

**Comment by lebaphi** [comment]
I'm using the same version with you but different architecture (x86_64) but I don't think it's a root cause 🤔 

https://user-images.githubusercontent.com/26705621/198656049-d3be333a-eacd-4720-9cc4-9e370feeb400.mov

**Comment by IanMayo** [comment]
It's Chrome-specific, it's ok on Firefox on this mac.

Are you able to take steps to "force" the `New Message` panel to show on top?

**Comment by lebaphi** [comment]
yes I can update some steps to force `New Message` to show on the top but I can't verify if these steps work because I can't reproduce this issue on my machine 😂

**Comment by IanMayo** [comment]
I know. You'll have to push to a PR, and I'll check the `deployment` 🤣

**Comment by lebaphi** [comment]
okay 🤣

**Comment by IanMayo** [comment]
Fixed in #1978
