### ISSUE TITLE
Prevent assets being clickable when an activity is being planned

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#1976]
When the player is planning a route, the click-handling goes a bit screwy around existing items (assets or prior orders).

We either need to get an understanding of this, or maybe configure GeoMan to only `snap` to items it has drawn

Note: in `PlanningForce` we can set `snapIgnore={true}` for the `<Marker>` element.  That prevents snapping.  But, it still isn't possible to start a line on top of an existing asset.

Hmm, it needs another fix.

**Comment by lebaphi** [comment]
Hi @IanMayo , do you mean these assets the the image below can not be clicked when an activity is being planned?

<img width="333" alt="image" src="https://user-images.githubusercontent.com/26705621/198832962-c0725591-67b4-45ab-8412-441d6d9a4ec5.png">

I'll take a look at geoman to see if it offers an option to ignore the Marker 🤔

**Comment by IanMayo** [comment]
Here is the example I forgot to attach.

I want to start the line on an existing asset.  The mouse `snaps` to the asset, which is fine.  But, I cannot start the line by clicking on the asset - I have to click just to the side of the asset for the line to start.

![screencast](https://i.gyazo.com/c6d0aa9bc157e2be8c2a155cf0d20311.gif)

**Comment by lebaphi** [comment]
> Here is the example I forgot to attach.
> 
> I want to start the line on an existing asset. The mouse `snaps` to the asset, which is fine. But, I cannot start the line by clicking on the asset - I have to click just to the side of the asset for the line to start.
> 
> ![screencast](https://camo.githubusercontent.com/a612edbaa2d8f28a064020b63d86cc2574cbe450cb5dde563dccfb76b437bc04/68747470733a2f2f692e6779617a6f2e636f6d2f63366430616139626331353765326265386332613135356366306432303331312e676966) [ ![screencast](https://camo.githubusercontent.com/a612edbaa2d8f28a064020b63d86cc2574cbe450cb5dde563dccfb76b437bc04/68747470733a2f2f692e6779617a6f2e636f6d2f63366430616139626331353765326265386332613135356366306432303331312e676966) ](https://camo.githubusercontent.com/a612edbaa2d8f28a064020b63d86cc2574cbe450cb5dde563dccfb76b437bc04/68747470733a2f2f692e6779617a6f2e636f6d2f63366430616139626331353765326265386332613135356366306432303331312e676966) [ ](https://camo.githubusercontent.com/a612edbaa2d8f28a064020b63d86cc2574cbe450cb5dde563dccfb76b437bc04/68747470733a2f2f692e6779617a6f2e636f6d2f63366430616139626331353765326265386332613135356366306432303331312e676966)

yes I got your point, but it still has a problem that we cant start drawing on top of marker, I'm investigating to see if it's possible to do this
