### ISSUE TITLE
Maritime Activity displayed as Air Activity

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1984]
Is an area reconnaissance an air activity by default? I noticed we refer to the target area as "flight zone". It ultimately displayed as Air Activity on the New Message window: 

https://user-images.githubusercontent.com/85491794/198851596-05241b74-3f92-40d1-b921-580024b22551.mp4

**Comment by ShendMikullovci** [comment]
Side-note: Notice how it asked me to select a target area twice. Last time I ran crash pattern trials, it only asked me to select a target area once. Is that on purpose?

**Comment by IanMayo** [comment]
1. The set of activities are dummy data, and don't use the valid templates
2. `Air Reconnaisance` is deliberately an example of an activity that requires two polygons. Note one is called "flight box" and the other is "Target area".  This requirement came up in conversation, where an aircraft may fly over the sea next to a nation, but with its sensors (and eyes) focussing on an area on land.
