### ISSUE TITLE
Transit activity doesn't appear on New Message window

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1986]
[1be906c4-e6a9-4275-b4e4-66bfe9d0fbec.webm](https://user-images.githubusercontent.com/85491794/198851974-ccb2a83e-d72a-41c2-a0fe-f9b7a67b73b8.webm)

After the first successful transit, it doesn't seem to appear on the new message window, even if I hit cancel. Is this the desired outcome?

**Comment by IanMayo** [comment]
Well spotted, thanks :-)

**Comment by IanMayo** [comment]
I think I've found a pattern here.  The first new orders request triggers the creation of a new message. But any following orders don't trigger it to open.
