### ISSUE TITLE
Complex steps end up breaking activity (Precision Strike)

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1987]
The more steps I include in a Precision strike, the higher the chances of the feature missing the target pin and route out: 

[eef1e8da-497e-448e-9835-187a0ae8edd4.webm](https://user-images.githubusercontent.com/85491794/198852203-b67413e9-e244-463a-b87f-afab51a9700b.webm)

P.S. Notice that the Precision Strike shows as Land Activity.

**Comment by IanMayo** [comment]
Hello @ShendMikullovci - this is ready for re-test on `serge-sql`, please.  I'm pretty sure I've fixed it.

**Comment by ShendMikullovci** [comment]
Seems to work fine now. Thanks Ian!
