### ISSUE TITLE
Mark Read Button Doesn't Work

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1989]
It seems like the Mark Read button doesn't work for Blue RFI. Mark Unread works fine: 

[45fccf2f-36ae-43f2-a807-ad2f079a6a7e.webm](https://user-images.githubusercontent.com/85491794/198876509-c453ae92-6ec1-41fe-a295-ea479dece3d1.webm)

P.S. Notice how a small scrollbar appeared to the right of the button despite the button not working.

**Comment by IanMayo** [comment]
Hmm, I think it's expanding the message that marks it as read.  Clicking on the `closed` envelope isn't meant to mark it as read.

**Comment by ShendMikullovci** [comment]
When the envelope is closed and yellow, it means the message is unread. When it's open and white it means it's read.
The feature that doesn't work is when I click on a yellow envelope (closed, unread) to try to open it (make it read).

The other way around, marking it unread (a.k.a making it yellow) works great.

**Comment by IanMayo** [comment]
Thanks @ShendMikullovci 

But, for messages, the player hasn't `read` the message until he has expanded the item - and seen the contents.  We could allow the working practice of a player effectively choosing to `ignore` a message (by marking it as read without opening it), but I'm not aware of a business justification for doing that.
