### ISSUE TITLE
How did GC edit attributes on P9 test?

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1990]
Example: In the Platforms tab, merchant vessel has no attributes: 

![Merchant Vessel](https://user-images.githubusercontent.com/85491794/198876765-1b79c1f0-3d93-4183-8cc2-4d56b72abffc.png)

However, in the Forces set, under Assets, merchant vessel Blue 7 seems to have attributes assigned to it: 

![Merchant Vessel Blue 7](https://user-images.githubusercontent.com/85491794/198876805-2fe13b0f-8aed-409e-99d8-fbc23ec38b30.png)

How were these edited?

**Comment by IanMayo** [comment]
I think the platform-type for `merchant-vessel` was modified after the `Blue-7` instance was generated.

Aah, that's why Serge deletes the attributes on save.
