### ISSUE TITLE
"Roles" vs "Restrict Access to Specific Roles"

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1991]
I noticed that in the channels tab we use the term "Roles" for the mapping channel and "Restrict Access to Specific Roles" for other channels: 

![Roles](https://user-images.githubusercontent.com/85491794/198877213-ed4c1af5-221e-46c9-a898-b9cce7be10a7.png)

![RFI Channel Roles](https://user-images.githubusercontent.com/85491794/198877220-cbc59cd5-53cf-485e-8e57-bc8d1451c666.png)

While "Roles" fits best for the mapping channel since next to it we have "Controls" that indicate which assets are under said role control. Unfortunately, it forces us to add that information marker on top of it to explain what "Roles" means. 

I'm not a fan of the difference and would prefer to have the same label across channels. We could: 

- Use "Roles" across channels and add the information marker. "Controls" stays intact.
- Use "Restrict Access to Specific Roles" across channels. "Controls" turns into "Select Asset Under Control" or some similar variant. 

What do you think?

**Comment by IanMayo** [comment]
Sure.  I favour the second option.  We do have sufficient space.

**Comment by IanMayo** [comment]
Drop. We no longer have that mapping channel.
