### ISSUE TITLE
Dysfunctional Drag-n-Drop Feature for Annotation Markers

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1992]
[4b3a2da9-2407-4d2c-a5f3-7dc3d1ff4d61.webm](https://user-images.githubusercontent.com/85491794/198880120-82469a23-1ea0-4b95-86e7-37c5cd7d9b97.webm)

**Comment by IanMayo** [comment]
@ShendMikullovci - I can't quite understand the issue from the title/video.   I think the screen-recorder didn't capture all of the activity.

Could you provide a more detailed explanation of how what you experienced didn't match what you expected?

**Comment by ShendMikullovci** [comment]
Oh! It seems I only recorded a tab instead of the entire screen. My bad. 
Basically, the drag and drop feature doesn't seem to work for PNG files when selecting an icon for annotation markers.
