### ISSUE TITLE
Annotation Markers Don't Accept PNG Files

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1993]
It seems like the PNG files are not accepted as Annotation Marker icons: 

[b1f14fab-fb71-4371-a88f-caef736dd714.webm](https://user-images.githubusercontent.com/85491794/198880228-46d44fef-2902-418c-aa1d-99f8f23778ee.webm)

SVGs work fine.

**Comment by IanMayo** [comment]
ok, thanks @ShendMikullovci
