### ISSUE TITLE
Annotation Marker Shape & Size

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#1994]
Tried to upload a trash icon SVG file as an example for Annotation Marker icons and it zoomed in quite a bit: 

![Annotation Marker Crop](https://user-images.githubusercontent.com/85491794/198880328-39af4081-775a-423b-9171-e37bd66c213d.png)

It'd be nice to have a feature that allows the GC to resize, fill and crop the images uploaded for the marker. 

Canva has a nice one: 

[bf898e7c-0e4b-4703-b665-6bb0e90c4afb.webm](https://user-images.githubusercontent.com/85491794/198880704-4ebf3bf5-434c-431a-bcd8-41360dacf9e9.webm)

**Comment by IanMayo** [comment]
I'd rather not add this functionality to Serge.  It's a rarely used function, and we can expect the GC to have access to tools to crop/resize the image.
