### ISSUE TITLE
Bring Stylesheets in line with ruleset

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#20]
The current stylesheets fail the linting rules in multiple places. Most of the violations have been fixed but there are still quite a few remaining ones which will require fixing with care as they may affect the look of the application if done incorrectly.

The list of items which need to be fixed can be found in the code climate output or can be inferred from the coding guidelines which I will link below when they actually exist.

**Comment by foxleigh81** [comment]
Some of the fixes will require some additional work to be added. For example, the use of `!important` is not allowed but it is acceptable to use them in utility classes (e.g. `.button`) with this in mind, it would either make sense for the utility classes to be in their own (separately linted) package which allows for the use of `!important` or the utility classes are in a subfolder of the theme which has a `postcss` build step and adds `!important` where it is necessary without affecting the other styles. (This is a good plugin for that: https://github.com/crimx/postcss-safe-important) 

Either method is fine, adding the extra build step to the SCSS may seem wasteful but postcss is a very usesful tool to have running as other things can be added (such as autoprefixing and the use of `caniuse`

**Comment by IanMayo** [comment]
Close, OBE.
