### ISSUE TITLE
Create new reference messages server-side

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2009]
Currently, before we send a new message of any type other than chat, we do this in `checkReference`:
- get all docs
- filter for documents from this force, with a `.message.counter` field
- find the highest value of counter
- find all messages for this id

Retrieving all documents from the database seems an expensive process.

Is it possible to perform the above server-side?  

Something like:  `http://serge/wargame-23423/counter/force-red`

The processing would be almost the same, but it would happen in node.

**Comment by lilitkarapetyan** [comment]
Hello Ian, yes it is possible

**Comment by lilitkarapetyan** [comment]
I am working on it now.

**Comment by IanMayo** [comment]
Done.
