### ISSUE TITLE
Marker missing for edit orders

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2034]
@lebaphi created a fix for showing the geoman marker for drawing  new points.

When we edit an existing shape, it doesn't show an marker - the icon isn't found.

I've tried to [copy](https://github.com/serge-web/serge/pull/2033/commits/78f667a12ecbf87f2e7a78403d5d555099d8b56e) the code, but it still doesn't work.

https://user-images.githubusercontent.com/1108513/200938014-9b793104-4209-40e3-b505-76eeefd09068.mp4

Steps to reproduce:
* open storybook:  https://serge-sql.herokuapp.com/storybook/?path=/story/local-organisms-planningchannel--default
* open `orders` tab
* expand to view all rows
* find row with `point` in the `Activity`
* expand the row
* click on the `Edit` button in `Location`
* you'll see the marker isn't present

**Comment by lebaphi** [comment]
Hi @IanMayo , I can not reproduce this issue on this story, when I click the Edit button, it shows nothing

**Comment by IanMayo** [comment]
Hello @lebaphi - sorry.  The orders are still over Australia. If you drag the map you'll see them, but they get pushed back off the map.  I'll regenerate the orders for europe.
