### ISSUE TITLE
Generate P9 roles and channels

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2042]
We have a spreadsheet with the roles and channels.

There are 5 forces in the game:
* umpire
* blue
* red
* green
* white

In the umpire forces:
* Game Designer, with "umpire" permission
* two `Adjudicator` roles, that have `Observer` status

There are a range of chat channels, as described in this matrix diagram:
![roles](https://user-images.githubusercontent.com/1108513/201175419-775652fa-b199-4bbb-87ac-af35a0bdabfa.PNG)

**Comment by ShendMikullovci** [comment]
Game crashed during Force creation. The data was not lost.

**Comment by ShendMikullovci** [comment]
Created all the channels. When creating Red & SME, it duplicated the Blue & SME channel created beforehand.

**Comment by ShendMikullovci** [comment]
Launched game, channels are all good.

**Comment by ShendMikullovci** [comment]
Question: The timer started at roughly 20 minutes Adjudication Phase upon launching the game. How come? Did it count the time it take for me to create the game (25 min approx)?

**Comment by IanMayo** [comment]
This has now been incorporated. Thanks for your support @ShendMikullovci :-D
