### ISSUE TITLE
When we select an icon, any filters are lost

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2055]
In the PlanningChannel we have the two lists of forces.

We can filter for things, including platform-type.

But, the filter is lost when an asset is selected, either from the table or the map.

I _guess_ we need to cache the filter settings, then update the rows, then apply the settings again.

Hmm, the drop-downs probably only need to be generated once - since the assets essentially stay in the game.  So, may just declare the columns once - and just do the rows afterwards?

Yes THAT'S THE FIX!

**Comment by lebaphi** [comment]
Hi @IanMayo , does PR https://github.com/serge-web/serge/pull/2056 fix this problem? I tried to select an asset but the filter is still there

**Comment by IanMayo** [comment]
> Hi @IanMayo , does PR #2056 fix this problem? I tried to select an asset but the filter is still there

Yes.  While I was writing the issue, the  possible solution jumped into my head.  I gave it a go, and it worked.
