### ISSUE TITLE
UI Bug - Force Overview appears behind map

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#215]
**Describe the bug**
When we click on the Force Marker icon at the bottom-right of Serge, it opens a panel showing the `Force Overview` :

![image](https://user-images.githubusercontent.com/1108513/72989659-99c7c500-3de6-11ea-8fe2-64700ab34e86.png)

But, if there is a map present, the overview is shown behind the map:
![image](https://user-images.githubusercontent.com/1108513/72989696-b06e1c00-3de6-11ea-9eee-53f72764792c.png)

**To Reproduce**
1. Login as any force, in an `MWARC` game
2. Click on the force icon at the bottom-right
3. Observer the popup panel is displayed behind the map

**Expected behavior**
The popup panel should be in front of the map control

**Screenshots**
See above.

**Comment by zukilover** [comment]
I "accidentally" fixed this on https://github.com/serge-web/serge/pull/222/files#diff-40cb153b73bcd3b650cfe8c9e3aee34dR730

**Comment by IanMayo** [comment]
Closed, by @zukilover
