### ISSUE TITLE
Duplicate row feature in JSON-Editor

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2157]
For some type of "Own Asset" forms, we wish to be able to "duplicate" a row.

This is done with `enable_array_copy" in the JSON-Editor.

Test this, and verify we can see the button.  This is the only time when we want `copy` - so I guess a flag has to _somehow_  come from the template.

Hmm, in one editor (template) we want this `copy` button for some arrays, but not for others.  So, _maybe_ it's a case of a having a flag to enable it at the template level, then hiding the button for all arrays that don't have a particular flag.

**Comment by lebaphi** [comment]
Hi @IanMayo, https://github.com/jdorn/json-editor/pull/365, I checked this PR has not been merged into master that's why I can't find this option in the docs page official.

**Comment by IanMayo** [comment]
:-( that's not even the main repo for json-editor any more

Could you create a PR in the new repo please?

Let's see if they're interested in this feature.

**Comment by lebaphi** [comment]
ah sorry @IanMayo, I found it here https://github.com/json-editor/json-editor 🤣

**Comment by lebaphi** [comment]
Hi @IanMayo , with this option enabled, the `Copy Item` appears:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/26705621/206907235-b3cc505e-482b-4f77-845c-9d5477d00966.png">

<img width="919" alt="image" src="https://user-images.githubusercontent.com/26705621/206907219-03d2e6c4-511a-4d48-8875-916dc224a595.png">

**Comment by IanMayo** [comment]
Thanks @lebaphi , could you also investigate how we can switch it off for most arrays, but just leave it on for one array in a template?

**Comment by lebaphi** [comment]
Hi @IanMayo, I think we can not do this thing with the default editor at https://github.com/json-editor/json-editor/blob/master/src/editors/array.js except using DOM manipulation, so we can clone a new editor from this, then we easily enable/disable this button.

**Comment by IanMayo** [comment]
Hello @lebaphi - it _looks-like_ the property can be set at the `array` level, in addition to being set at the `json-editor` level:
https://github.com/json-editor/json-editor/blob/master/src/editors/array.js#L90

**Comment by lebaphi** [comment]
ah sure, it works @IanMayo 😂 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/26705621/207315444-b8386583-48ee-4963-8af8-0988dd824623.png">

**Comment by IanMayo** [comment]
Ooh, we're _nearly_ there.  I need the "Copy" to work when the array is `"format": "table"`.  The JS for `editors/table.js` _looks-like_ it supports `copy`, but it doesn't show on the screen.

Note: we have a reproducible example, by editing `Land--Transit` template in `p9-message-templates.mock.ts` in this story:
![image](https://user-images.githubusercontent.com/1108513/207317368-926d61b6-3964-4e95-88c5-c8cc0b0010d2.png)

For `OwnAssets`, if I switch the format off from `table`, then the `copy` button is shown, but not in `table` format.

**Comment by IanMayo** [comment]
Ok.  In an up-to-date release, it works:
https://is.gd/tEmnHk

Could you investigate a little further, please?

I _think_ we're on `1.3.5`, which was released 3.5 years ago:
![image](https://user-images.githubusercontent.com/1108513/207321220-0a8e0da1-21fd-4d7b-8dae-af88ea1f738d.png)

But, it _looks-like_ the copy button was added 3 years ago:
![image](https://user-images.githubusercontent.com/1108513/207321301-95afa048-8457-4bfc-819c-335d2ba4bf9a.png)

So, _maybe_ our first step is to update `json-editor`.  Would you be willing to take that one @lebaphi ?

**Comment by lebaphi** [comment]
Hi @IanMayo , it works on the latest version because of this https://github.com/json-editor/json-editor/blob/master/src/editors/table.js#L308, but it doesn't seem to support in our current version. So let me upgrade the json-editor to the latest version.

**Comment by IanMayo** [comment]
> So, maybe our first step is to update json-editor. Would you be willing to take on that one @lebaphi ?

**Comment by lebaphi** [comment]
Hi @IanMayo , it seems to work on the version 2.8.0. I tested on `yarn storybook`.

https://user-images.githubusercontent.com/26705621/207364673-2a071253-cfcc-4379-b20e-1a2a72c99d18.mov

It has a small issue on `yarn develop`, I'm working on this.
