### ISSUE TITLE
Need to handle new message coming in for interactions page

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2164]
This relates to PR #2149 

We aren't handling the `lose form` in the `Adjudication` channel.  I'm capturing the steps to reproduce here.

1. Login as `Adjudicator 1`. The game should be in `Adjudication Phase`
2. The `Adjudication` tab will be shown
3. There should be no Adjudication messages shown
4. Click on "Get Next Interaction".  When one is found, it's sent to the database, marked as "owned by" the current user. The page then refreshes, to show the new interaction form.
5. Scroll down the interaction form, and type something into "General feedback". Don't `Submit`
6. Open another browser tab, log in as `Adjudicator 2`. 
7. Click on `Get Next Interaction`.  As it finds the interaction, and submits it, the `Adjudicator 1` form will be wiped

So, I think we need a similar fix to the one done in #2149

**Comment by lilitkarapetyan** [comment]
Okay I will work on this when I finish #2149

**Comment by IanMayo** [comment]
Fixed in #2169
