### ISSUE TITLE
More fixes for LocationEditor

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2183]
Some steps to complete the location editor are recorded [here](https://twitter.com/RishiSunak/status/1605964002143522816)

Copied below:

Ok, but I _think_ we still need some processing like that.  We need to store the current GeoJSON data in the form (somewhere - maybe in the `location-editor`, or `DOM`), and we need to re-format the GeoJSON in human-readable form. 

We have these requirements. When the form contains a `location-editor`:
1. store the `PlannedActivityGeometry[]` JS array 
2. call a `render` function to convert the array to human readable `<ul>` list, display this as read-only in the `div`
3. provide an `Edit` button, when the form is editable
4. when the `Edit` button is clicked, provide the raw `PlannedActivityGeometry[]` array to the callback
5. when `Save` is clicked during location edit, store the new `PlannedActivityGeometry[]`, and re-do the `Render` function
6. when `Save` is clicked for the JSON-Editor, push the `current` value of of `PlannedActivityGeometry` back into the location field of the results object.

**Comment by lebaphi** [comment]
Hi @IanMayo, where is the `Save` button in the form, do you mean we will add new button?

**Comment by IanMayo** [comment]
"EDit location" is currently broken, since PlanningChannel is receiving a string of JSON instead of the JSON object.  When "EDit location" is working, and the player can drag/edit an existing location we show save/cancel buttons at the top-left of the map.  I think they're a save (floppy disk) and a airplane with a cross through it.

But, that's step 5 above.  If we get the previous steps working, it may just be ok.

**Comment by lebaphi** [comment]
Hi @IanMayo, I'm a bit confused about `when Save is clicked during location edit`(1) and `when Save is clicked for the JSON-Editor`(2), so I guess when click on the Edit button of the JSON editor, then make some changes on location editor then we handle save button as (1), if we click the Edit button but do not make any change -> handle save button as (2)?
