### ISSUE TITLE
JSON-Editor breaking map

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2187]
On `develop` most of SERGE is frozen when I log in as `MTG-1`.

I can't pan the map, and the map controls/buttons are effectively `disabled`.  I can't even click into the `Game-Admin` channel on the right-hand side.

The issue is down to `json-editor` falling over here:
![image](https://user-images.githubusercontent.com/1108513/209672474-5f3211db-9908-4288-aa21-dbb7643b8b4d.png)

It's not clear from the debug listing where the issue is, but it's the `enable` call in `json-editor\index.tsx` here:
![image](https://user-images.githubusercontent.com/1108513/209672576-2d39b93a-0b31-4668-b725-936393ebf775.png)

Commenting out that `enable()` line fixes the issue, but obvs that's not a real solution.  I don't see what the problem is with `enable()`

Lastly, this error happens on application-load, so I'm not expecting there to be a json-editor open at that point.  _Maybe_ that's a clue.

Note: this is Chrome only, not Safari or Firefox.  But, we need it to work on Chrome :-(

**Comment by IanMayo** [comment]
Note: this fix prevents the problem happening on startup, and SERGE runs ok, but I'd like to understand what's happening, and apply a proper fix, rather than a `sticking plaster`.
![image](https://user-images.githubusercontent.com/1108513/209677422-be55cc03-3393-49c5-a5b1-0ea70397a888.png)

**Comment by IanMayo** [comment]
Demoting this to technical debt, as we focus on getting across the finish line

**Comment by lilitkarapetyan** [comment]
The problem is fixed when you use (try catch), right ?

**Comment by IanMayo** [comment]
I see the try/catch as a workaround - I don't like it, and would like to avoid it, if we can.  Is there some status check we can do before calling `editor.enable()` ?

**Comment by lilitkarapetyan** [comment]
I remove the try/catch from the code but I don't get that error.

**Comment by lilitkarapetyan** [comment]
maybe the problem was fixed after the last change ? - https://github.com/serge-web/serge/commit/ad01fa0de493b47f6d164812df70b3dd683c7e61#diff-c9d461a0710ec430826247107f67a9527417e5b24b65a1f5be17494c75a829b0

**Comment by IanMayo** [comment]
Oh yeah - I don't see it any more 🥳 

Will keep the debug line in for a while, just to see if it comes back - but yes, current solution working :-)
