### ISSUE TITLE
Export wargame broken

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2202]
A user just reported that export to XLS is broken.

I've looked at an exported XLS.  Excel reported it as corrupted, but recovered it.

I'm pretty sure the issue is that SERGE is trying to export one or more wargame documents, which creates thousands of columns.

Hopefully it's a simple fix.

**Comment by lilitkarapetyan** [comment]
Hello Ian, the problem is in the old version `LibreOffice`, it is limited to `1024` columns, I have updated to `version 7.4.4` in my computer, the maximum number of columns in this version is `16284` - https://wiki.documentfoundation.org/Faq/Calc/022#:~:text=What%20is%20the%20maximum%20number,is%201%2C048%2C576%20(220)%3B.

**Comment by IanMayo** [comment]
Hey, thanks @lilitkarapetyan 

Aah, so our export is valid, it's just that the app can't open it.

When I try to export the current `P9 Test` messages, they only seem to export the InfoType messages, even though there are lots of others in there.

Hmm, I think we should probably exclude `InfoType` (wargame) messages from the export - they produce lots of columns, and the columns look nothing like those in normal messages.

**Comment by IanMayo** [comment]
Note: I hope to document a new requirement soon, for an alternative `export to CSV` - where it's a predictable set of CSV columns. I'll share it as soon as I can :-)

**Comment by lilitkarapetyan** [comment]
> Note: I hope to document a new requirement soon, for an alternative `export to CSV` - where it's a predictable set of CSV columns. I'll share it as soon as I can :-)

Ok Thanks, I will wait.
