### ISSUE TITLE
Dynamically regenerate `sub-type` based upon filtered `type` data

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2236]
In the `Assets` tab, we can now filter by `Platform Type` and `Sub-Type`.  Well, it's in #2235 

Both a currently drop-downs containing all of the values found in the data.  But, the sub-types column contains all values - even those which are no longer relevant.

We may/may-not wish to this for other columns in the future, but I'd like `sub-type` drop-down to only contain the relevant.

This could either be through:
1. When we load the data, store sub-types with the platform-type they're found under.  Then once we've filtered on platform-type, we can get the selected platform-type values, and filter sub-type to only show those
2. When a filter has been applied, run through the visible rows and collate a list of unique sub-types

Ok, I think the answer here is that the filters should be created from the current set of rows, not from the parent dataset (of assets).  So, in PlanningAssets we already have the callback for `onVisibleRowsChange`. I think this needs to trigger the update of the filter lists.

**Comment by IanMayo** [comment]
Hello @lebaphi - the Sqlite database for `P9 TEST` now includes the `a_Type` data:
![image](https://user-images.githubusercontent.com/1108513/212330990-f969bd72-1f6a-4883-a4c4-7d0fb6e9a4c5.png)

**Comment by lebaphi** [comment]
thank @IanMayo , could you add more details on this issue? I'm a bit confuse of "sub-types column contains all values" on this image, It seems the sub-type cell has the relevant value of the type cell value 🤔 
<img width="853" alt="image" src="https://user-images.githubusercontent.com/26705621/212340071-cf925af6-b97c-40b5-b1c7-88238e715951.png">

**Comment by IanMayo** [comment]
Sure - that's completely fine.  Part of the confusion is the dummy data I'm generating.  

For these assets, we have type and sub-type.

So, it's like we have `platform-type` of `car` and `truck`.

For `car` we have sub-types of `sedan`, `SUV`, `convertible`, `station wagon` and `minivan`.

For `truck` we have sub-types of `pickup`, `RV`, `18-wheeler`, `box van` and `flat-bed`

Serge is currently showing the full-list of all sub-types, regardless of what `type` filters have been applied.  

See how we're filtering for `Ship`.  Ideally - the sub-type would only show the sub-types of `Ship`:
![image](https://user-images.githubusercontent.com/1108513/212344522-64268213-bb5c-479b-8d55-5eafd0641758.png)


What the users would like, is that if a `Car` has been selected for `type`, then only the sub-types of car are shown in the `sub-type`.

If two `type` filters have been applied, then we show the `sub-types` for both of those two types.

We _could_ do this by analysing the type/sub-type data in advance.  But, a _possibly easier_ method could be to run an event after type-filters have been modified.  The event loops through all the current rows, finds the unique list of sub-types, and offers these as the choices.

Hope this helps :-)

(you're right that the sub-types currently contain the type name - that's just the way I generated the mock data).

**Comment by lebaphi** [comment]
Thank @IanMayo, how can I get this screen? 

![image](https://user-images.githubusercontent.com/26705621/212346109-41db154a-82b6-48ed-a173-d22267d78f88.png)

**Comment by IanMayo** [comment]
1. run `yarn develop`
2. go to this URL:  `http://localhost:3000/?wargame=wargame-l6nngxlk&access=blue-mtg-1`
3. switch to the `My Forces` tab in the `Planning` channel

**Comment by lebaphi** [comment]
that is what I'm confusing, I don't see these dropdowns in the table header 🤔 

https://user-images.githubusercontent.com/26705621/212347606-4a04bdff-1133-4193-a0a4-464137131c13.mov

**Comment by IanMayo** [comment]
Oh, you have to switch on the column filters -  using the `filters` icon at the top-right.

**Comment by lebaphi** [comment]
ahh I see, sorry I lost my memory on this 🤣

**Comment by IanMayo** [comment]
We seem to have lost this feature - possibly as a result of "don't lose filters on new data".  

It would really help users if when a filter is applied, the other drop-down lists were restricted to the displayed data. This _Shouldn't_ be a lot of processing - since there is already a filter applied. So, we need to listen for the "filter applied" event.  Aah, we already do that for the `selection changed` handling.
