### ISSUE TITLE
Issue with copy of Line Decorator

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2309]
We use the line decorator to put arrows on the polylines.

We use a `base` object for the formatting (`ArrowHeadPattern`), and modify it for each different colored line.

But, instead of copying the base object, we keep changing the original.

In this example, the yellow line arrows were the last to be drawn.  That means all of the line arrows get set to yellow:
![image](https://user-images.githubusercontent.com/1108513/215998811-d5555460-2843-443e-8367-62b1e2a03086.png)

Note: I tried switching from spread operator (`{...}`) to using deepCopy, but it appears there is (somehow) a function embedded in the object, which doesn't get copied properly.

**Comment by lebaphi** [comment]
Hi @IanMayo, how to reproduce this?

**Comment by IanMayo** [comment]
Hello @lebaphi, 
Open this story, then click on `Get Next` button:
http://localhost:6611/?path=/story/local-organisms-planningchannel--istar-interaction

Or, this story, then expand `umpire-3`:
http://localhost:6611/?path=/story/local-organisms-planningchannel--adjudication-form-open

![image](https://user-images.githubusercontent.com/1108513/216304002-f73420f7-e42a-446b-b39d-e8ebb1d40474.png)
Note how the blue order arrows are plotted in red.

**Comment by lebaphi** [comment]
> In this example, the yellow line arrows were the last to be drawn. That means all of the line arrows get set to yellow:

okay, so the issue is only the arrow gets yellow instead of all the line arrow gets yellow. We will get all the line arrow get yellow?

**Comment by IanMayo** [comment]
I don't think the issue is about the yellow line in particular. The issue is that the arrows get set to the last custom arrow-head color.

We generate a number of `ArrowHeadPattern` objects, and set the color to the color of the current line.  But, instead of creating new ones, each time we actually edit the previous one.  So, in the above diagram we:
1. generate the blue orders line, with a blue arrowhead
2. generate the red orders line, with a red arrowhead.

But, the second arrowhead actually also edits the first arrowhead - which makes the blue line in the image have red arrows.

**Comment by IanMayo** [comment]
Aah, I think I've just fixed it @lebaphi 

Let me push my changes.

**Comment by lebaphi** [comment]
yep, please push the changes and I can take a look on it 😄

**Comment by IanMayo** [comment]
> yep, please push the changes and I can take a look on it 😄

https://github.com/serge-web/serge/pull/2317

![image](https://user-images.githubusercontent.com/1108513/216338688-7626c4b7-0f24-4656-b246-78cc819c66cb.png)

**Comment by IanMayo** [comment]
Do you understand what the issue was?

**Comment by lebaphi** [comment]
yep, now it seems to work fine 😄

**Comment by IanMayo** [comment]
Yes - do you understand why our code kept using the same `ArrowHeadPattern` object?

I would be quite happy to carry on using the const instance, but we (somehow) needed a deeper copy of it, I guess.
![image](https://user-images.githubusercontent.com/1108513/216339664-0f05bcdf-2818-4f29-9957-1ef6d57040c9.png)

**Comment by lebaphi** [comment]
> Yes - do you understand why our code kept using the same `ArrowHeadPattern` object?
> 
> 
> 
> I would be quite happy to carry on using the const instance, but we (somehow) needed a deeper copy of it, I guess.
> 
> ![image](https://user-images.githubusercontent.com/1108513/216339664-0f05bcdf-2818-4f29-9957-1ef6d57040c9.png)
> 
> 

Hi @IanMayo, spread syntax effectively goes one level deep while copying an object. Therefore, it may be unsuitable for copying multidimensional object. I suggest we use cloneDeep of lodash.

**Comment by IanMayo** [comment]
> Hi @IanMayo, spread syntax effectively goes one level deep while copying an object. Therefore, it may be unsuitable for copying multidimensional object. I suggest we use cloneDeep of lodash.

Aah, I'd been using `deepCopy` - which threw a runtime error. `cloneDeep` works fine - thanks :-D
