### ISSUE TITLE
Allow longer list of orders

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2386]
The Order tab (Planning Messages List) shows at most 50 rows.  Allow 100 and 250 rows (check if performance of assets table is ok with 250 rows).

**Comment by IanMayo** [comment]
Related to #2384

**Comment by lebaphi** [comment]
Hi @IanMayo, I tried to add more 150, 200 and 250 rows and here is the result:

https://user-images.githubusercontent.com/26705621/219356389-e55a9912-897b-4fff-b7c0-b802529f39c4.mov


As you can see, the more rows on the table, the longer it takes to click on 1 content (200 content ~ 5-6 seconds). I think there might be a performance issue here 🤔

**Comment by IanMayo** [comment]
I'm pretty sure the delay is map-related.   If I switch off firing out the selection change, it's always under a second or so:
![image](https://user-images.githubusercontent.com/1108513/219367743-2f166d3b-a3b3-4319-ac90-44cdd1475a91.png)

Let's treat the map delay as a separate issue for now.  So could you please:
- (temporarily) stop firing the external `onSelectionChange`
- investigate if/where there is a performance delay in this table - see if we're unnecessarily calling something? getting icons from the network? 
- if the table is set to more rows than are present, empty <tr>` are created that appear as empty white-space.  So please (fancy css?) find a way of not displaying empty `<tr>`s.


![image](https://user-images.githubusercontent.com/1108513/219368170-b0abbd5d-ae13-4ebc-859e-f2d9abe341aa.png)

**Comment by IanMayo** [comment]
Done.
