### ISSUE TITLE
Assets disappear after 15 seconds (heartbeat)

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2390]
This is an intermittent error. It doesn't happen on some builds.

But, the issue is that every 15 seconds, the assets all disappear from the map.

This happens in response to the `heartbeat` message being sent.  It _looks-like_ new state is passed through to `factory.tsx`, which trigger state updates that mean the asset list gets cleared.

1. We should find a way of the heartbeat not clearing the assets
2. We should cancel the heartbeat functionality

I've just opened the heroku instance here, and it doesn't have the problem:
https://serge-sql.herokuapp.com/?wargame=wargame-l6nngxlk&access=blue-mtg-1

But, the same build on a different network does have the issue.

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo ,  any changes in the database make all all assets disappear from the map - https://gyazo.com/7ac51f8dc8fae431b500b2ed3fbe2640

**Comment by lilitkarapetyan** [comment]
I think the problem comes from the state update, when we make a change, the frontend listens to `soket ` change made by the server and updates the state.

**Comment by lilitkarapetyan** [comment]
I am working on a fix.

**Comment by IanMayo** [comment]
Aah, good work.

Separate question: how did you get all of these "view-as" toolbar buttons?
![image](https://user-images.githubusercontent.com/1108513/219330686-fc1ccb51-c615-4967-95c4-35ad8756dad5.png)

**Comment by lilitkarapetyan** [comment]
> Aah, good work.
> 
> Separate question: how did you get all of these "view-as" toolbar buttons? ![image](https://user-images.githubusercontent.com/1108513/219330686-fc1ccb51-c615-4967-95c4-35ad8756dad5.png)

I don't know, I will investigate now.

**Comment by lilitkarapetyan** [comment]
https://gyazo.com/fa6db67d6bb3b836d1ad895caadccdfe - here's how I got all the  "view-as" toolbar buttons.

**Comment by IanMayo** [comment]
> https://gyazo.com/fa6db67d6bb3b836d1ad895caadccdfe - here's how I got all the "view-as" toolbar buttons.

Oh fine  - you created lots of forces :-D

**Comment by lilitkarapetyan** [comment]
Yes :-D

**Comment by IanMayo** [comment]
Closed in #2425
