### ISSUE TITLE
Contents of chat in game-admin not persistent

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2409]
We have a chat box at the foot of the Game Admin panel.

The contents of the text area are lost if a new message is sent into the chat channel. We need to make this persistent - similar to how we do for our other channels.

**Comment by lilitkarapetyan** [comment]
I try it, it works for me without any problems, can you elebotate a bit how you get the problem ?

**Comment by IanMayo** [comment]
It's when a chat message is created from another Serge session.  I forgot to attach video. Capturing one now.

**Comment by IanMayo** [comment]
Aah, it's because @lebaphi replaced `json-editor` with a plain `text-area`.

Hmm, I think that shows the general weakness we have in `json-editor`.

Anyway - we can close this issue :-)
