### ISSUE TITLE
Persistent Planning Channel layout/status

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2416]
It would be great if we could make these aspects of the PlanningChannel persistent between browser reloads (via storing as cookies, like we do for page layout):
* [x] Current tab
* [x] Current width of support panel
* For tables:
    * [x] Currently visible columns
    * [x] Whether filters are shown
    * [x] Which filters are applied
    * [x] Sort on any columns
    * [x] Number of rows visible
    * [x] Current turn number (_think_ this is stored in `ChannelPlanning` - so it would probably be stored/retrieved from there)

Note: I'd like the key to start with `serge.planning` and be suffixed with the current role-id (`selectedRoleId` - passed down from `SupportPanel` if necessary)

**Comment by IanMayo** [comment]
Re-opening, it would be useful to remember the number of rows visible too, please.

Aah, and to include the role-name in the keys for filters.  We _may_ get an instance where the player switches to another role, and we try to restore filter settings that don't work for the new role - including trying to display a tab that the current user doesn't see (only umpires see the adjudication tab)

**Comment by IanMayo** [comment]
Aah, @lebaphi  - I think we still need to include the role-id in the filters, please, as described above.

**Comment by lebaphi** [comment]
Hi @IanMayo , about this item:
> Number of rows visible

Can you explain more about this scenario? when do we need to use it?

**Comment by IanMayo** [comment]
Hello @lebaphi - at the bottom of the material table, the players can use the drop-down to choose how many rows to view.  It would be useful if the value of this was persistent.

![image](https://user-images.githubusercontent.com/1108513/223103035-013adfe4-3882-4398-abf7-48eb0307a367.png)

**Comment by lebaphi** [comment]
Hi @IanMayo, the last item fixed 👍
