### ISSUE TITLE
Sticky Table Headers

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2447]
It would be good if the table headers were "sticky".

Actually, it would be good if the headers and footers (page details) and filter controls were always visible.

Details for making header sticky here: https://github.com/mbrn/material-table/issues/709#issuecomment-512876617

**Comment by lebaphi** [comment]
> Details for making header sticky here: https://github.com/mbrn/material-table/issues/709#issuecomment-512876617

Hi @IanMayo, it does not seems to work on our table, we are using https://material-table-core.com/docs, not mbrn/material-table 🤔

**Comment by IanMayo** [comment]
I think `material-table-core` started at the point when `material-table` had stopped development.  So, everything in the original _Shoud_ be in the `core` one. 

Here is a comment in `material-table-core`:
https://github.com/material-table-core/core/issues/256

**Comment by lebaphi** [comment]
yes, but it doesn't seem to work either, hmm what's so weird 🤔

**Comment by IanMayo** [comment]
Ok, let's drop this issue.  There are lots of other items for you to do :-D
