### ISSUE TITLE
Trouble with message filters

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2483]
We have two issues with the filters on the PlanningMessageList page.

1. When we reset the filters (via hide-filters, then view-filters), it is still showing the previous filters.
2. When we reload the page, it crashes

Video link [here](https://i.gyazo.com/e4c048ba9105d69c4b786fe48f34b81f.mp4)

Here is the error report:
![image](https://user-images.githubusercontent.com/1108513/220872377-780b212e-3784-4180-8499-3e6b60742d31.png)

Here is the stored filter:
![image](https://user-images.githubusercontent.com/1108513/220872751-c7ae8c21-23b7-4baa-9987-8236ae879505.png)

**Comment by lebaphi** [comment]
Hi @IanMayo , this is what i observed when running on the latest develop

https://user-images.githubusercontent.com/26705621/220922467-544d3b03-f5f3-4092-a580-a2a3ee3da080.mov

**Comment by IanMayo** [comment]
So, in that video we saw:
- close/reveal filters did reset them
- on page refresh, the filters were restored


Hmm, yes - it's all working fine :-)

**Comment by IanMayo** [comment]
Closing this - the filters seem fine.
