### ISSUE TITLE
3.0 Adjudication

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#249]
As a < umpire >, I want < to adjudicate the current turn > so that < I can move the game forward >.

This step covers the creation of the form  that is used by the Game Control to perform adjudication. That is, to accept the planned state (maybe including a route) for an asset, or provide an alternative outcome

Beyond providing the new state for the platform, the Game Control is also able to change who can see the asset, and what its condition is.

# Acceptance criteria

- [ ] Logged in as White, red and blue have provided planned routes, in Adjudication stage
- [ ] Click on an asset. The popup form appears.  Accept the planned state, and close the form.  The UI updates to show the asset at its new state/location, with the previous location shown faint.
- [ ] Click on another asset. The popup form appears.  Reject the state, select a new non-mobile state, and close the form.  The "new" marker will be shown over the previous markers (since it's a non-mobile state)
- [ ] Click on another asset. The popup form appears.  Reject the state, select a new mobile state, and close the form. The map will be in route-planning mode, with the umpire able to specify the route for a single turn. Once the route is planned, the umpire can click on the asset again, the form will popup, and he can "Accept" the planned route. The UI updates to show the asset at its new state/location, with the previous location shown faint.

Note: the above functionality is working in the game, but it is controlled by buttons rather than the form.

The popup form should be generated from within the `showAdjudicationAssetMenu`.  The UI popup form will replace the command buttons in the lower half of the method.

- [ ] Click on an asset, the form will popup.  If the route has been accepted, the top section is disabled (but with a 'revert' button).  But, the lower sections still allow the visibility and/or condition of the asset to be changed.  On changing these, the UI does not change, but the underlying datastore is modified to reflect the new selections.

Note: the visiblity/condition functionality is not working. I'm happy to provide support in creating the 'original' and 'edited' visibility and condition items.

# UX
https://www.figma.com/file/2qiEitO08s8jXamHWI3VpP/SERGE-mapping-tool?node-id=89%3A0

I suggest that @foxleigh81  has a Skype with @clenoble  to understand the flow of logic through this set of panels:
![image](https://user-images.githubusercontent.com/1108513/73269225-56010100-41d4-11ea-8afa-7a0ea39cec69.png)

# Notes
A wargame has been created that "arrives" in the correct state for this.

This link will bring you in as Umpire, with planned routes present for green, blue and red:
http://localhost:3000/?host=http://localhost:8080&wargame=wargame-k5xxsr4b&access=p2311

**Comment by clenoble** [comment]
@foxleigh81 I'm happy to guide you through the prototype and answer any question you might have. 
Here is an interactive prototype which should make it a bit easier to understand the interactions (even though all possible interactions and states are not mapped): https://www.figma.com/proto/2qiEitO08s8jXamHWI3VpP/SERGE-mapping-tool?node-id=89%3A177&scaling=scale-down

To open the popup, click on the green fishing vessel at the center of the screen.

**Comment by foxleigh81** [comment]
Add a way to select the child component of `MappingForm` by passing a prop instead of using if/then statements
