### ISSUE TITLE
Co-located markers don't show as selected

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2508]
When a marker is `selected`, we don't cluster it.

But, when markers are co-located, we do cluster them, to prevent them stacking.

This means we do see co-located selected assets.

We need to modify `planning-force` to make clusters pulse if they contain one or more selected assets.

In `planning-force`, this function generates cluster icons: `iconCreateFunction`.  It receives a set of markers.  So, we need to `inject` some field into a marker to show if they are selected.  We then need to check the set of markers in the above method, and decide if any are currently selected.  If they are - then we add styling to the marker cluster to make it pulse.

To test this we need data at exactly the same location. I'll investigate this.

**Comment by lebaphi** [comment]
> We need to modify planning-force to make clusters pulse if they contain one or more selected assets.

Hi @IanMayo, I have a problem here:
From initial phase, we have a cluster with 6 markers inside:

<img width="100" alt="before" src="https://user-images.githubusercontent.com/26705621/222942946-882e114e-aaf5-4fac-b311-05a156ead7b3.png">
Select 1 marker in this cluster, we add some styling to make this marker pulse, but this marker is separated and stands alone

<img width="137" alt="after" src="https://user-images.githubusercontent.com/26705621/222942956-0e85c77d-c95d-496b-9cab-9e28e1d73580.png">

I've tried to add some external attribute to determine if this cluster has some selected markers at line 55 and update style for html at line 60 but it does not seem to work, strange!

<img width="928" alt="image" src="https://user-images.githubusercontent.com/26705621/222945715-826727a2-86cd-4cd9-a1c0-0f8949511d78.png">

I'm still investigating it 🤔

**Comment by IanMayo** [comment]
I guess we can break it down:
1. see if you can get _all_ of the markers clusters to pulse by changing the above function
2. see if you can get _the relevant_ markers to pulse using some external attribute

**Comment by lebaphi** [comment]
yep I did
1. see if you can get all of the markers clusters to pulse by changing the above function: set isSelected = true, all markers clusters pulse
2. see if you can get the relevant markers to pulse using some external attribute: it does not work as expected 🤣
