### ISSUE TITLE
Filter changes (store tab and role details)

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2533]
1. When we remember our filters, we need to remember which tab they relate to.   

Steps to reproduce:
* log in as blue player
* leave the `Own forces` filters empty
* set a `Type` filter for `Other Forces`
* refresh the page.  See the filter is applied to own forces

I suspect we need to introduce multiple `filter` cookies, that include the name of the tab.  From within the `PlanningAssets` component, the `opFor` boolean flag can be used to determine if it is the `Own Forces` or `Other Forces` tab.

2.  When we remember Support Panel preferences, remember the role they related to.

Steps to reproduce:
* log in as `Adjudicator 1`
* select `Adjudiction` tab
* switch to `Blue` user
* note the app opens with the `Adjudication` tab open - which should not happen

**Comment by lebaphi** [comment]
> When we remember our filters, we need to remember which tab they relate to.
Steps to reproduce:
log in as blue player
leave the Own forces filters empty
set a Type filter for Other Forces
refresh the page. See the filter is applied to own forces
I suspect we need to introduce multiple filter cookies, that include the name of the tab. From within the PlanningAssets component, the opFor boolean flag can be used to determine if it is the Own Forces or Other Forces tab.

I already supported multiple filters, it seems there is a bug, I will check 😄
