### ISSUE TITLE
Mapping Improvements 

### ISSUE THREAD

**Issue by lm93547** [serge-web/serge#263]
**Idea 1: A mini map in the corner.**
**Why?** To allow faster navigation around the map, especially when in a highly zoomed state
**How?** Using the leaflet plugin [Leaflet-MiniMap](https://github.com/Norkart/Leaflet-MiniMap)
**Details:** The mini-map would be useful in a turn based game, as it would show context to where the user is on the map, especially at higher zoom levels, which are probably going to be used a lot in a small scale game, may even be more useful for larger scale games. The plugin is fully customisable, so both small scale and large scale games can have different mini-map zoom levels. The min-map can also be hidden, into a small triangle box in the corner
**Mock-up** 

![mini-map-serge](https://user-images.githubusercontent.com/49888000/73519818-ed7d8280-4466-11ea-90dc-692f8fa5ee93.png)
Hidden:

![mini-map-hidden-serge](https://user-images.githubusercontent.com/49888000/73520056-8ad8b680-4467-11ea-8515-178420731fb7.png)

**Idea 2: Text marker zoom level changes**
**Why?** As when the user zooms out, the marker text can often overlap with other features of the map such as markers or other text divs, such as this:

![Screenshot from 2020-01-31 20-25-43](https://user-images.githubusercontent.com/49888000/73520243-0d617600-4468-11ea-83a4-dc51133dd2de.png)

**How?** Using custom zoom listeners, much like the hexgrid listeners, which listen for changes in the zoom level and show or hide the hex labels accordingly
**Details:** While the full removal of the turn, or other text markers is probably not good for glance-able readability, I was thinking that the text could be concatenated at zoom levels greater than say 10. So for example the text: 
T03: Transiting @ 20kts 
Could become: 
T03: (icon) 20kts 
Where an icon represents the transiting state (the icon could be related to the platform type that is moving) A fishing vessel could have an icon like so: 
![boat-transit](https://user-images.githubusercontent.com/49888000/73520734-27e81f00-4469-11ea-847c-45bd29512e5b.png)

**Idea 3: Opacity controls for the drawn map**
**Why?** If the user wants to see both the base-map and the supplied map, to make more accurate movement decisions, an opacity control can be added.
**How?** Various methods, a plugin is available, or custom code can be written like on my site [here](https://experiments.lmmapping.com/projects/production-site-packed/index.html) (Press the sidebar, then press the 'New Mexico' button and it will snap to a Leaflet Image overlay of a wind speed raster of New Mexico, then the slider can be used to change the opacity. 
**Details:** Combined with perhaps an up to date satellite image, and the overlaid map, the users will get better immersion into the game, but with the option of changing the overlain layer opacity when needed. The opacity control could be a set of numbers, such as 0, 0.5, 1 (which represent three opacity levels) or a slider, but care will need to be taken where to put this. Prehaps @clenoble could help with some UX ideas. This may also be useful for seeing (as shown in the second screenshot below) the commercial shipping lanes, as long as this data is up to date, it would not need to be hardcoded in, and could provide another informative layer for the users of the wargame.
A screenshot here is provided using ESRI satellite imagery and an opacity of 0.5 for the overlain map:

![Screenshot from 2020-01-31 20-50-56](https://user-images.githubusercontent.com/49888000/73521638-67b00600-446b-11ea-8120-acbed3d75774.png)

Another screenshot of the regular Openstreet map and again an opacity of 0.5 for the overlain map:
![Screenshot from 2020-01-31 20-48-27](https://user-images.githubusercontent.com/49888000/73521650-6f6faa80-446b-11ea-898f-f3ba3a943bfd.png)

**Idea 4: Scale bars on the map**
**Why?** To show the users of the game roughly how far on map distances are
**How?** Leaflet has a built in scale function, but in my opinion, it is not very readable. I would propose a plugin such as [Leaflet.betterScale](https://daniellsu.github.io/leaflet-betterscale/), which uses black and white alternating bars, much like a traditional map, or the scale bars you find as default in enterprise level GIS softwares. 
**Details:** As an alternative to a static fixed scale bar, I found a handy [plugin](https://geof-osgl.github.io/Leaflet.EdgeScaleBar/) called Leaflet Edge Scale Bar, which adds scale graticules around the whole edge of the map, as shown in the second screenshot below, this could be more useful as it would be easier to discern distances than a fixed position scale bar
**Example:**
![scale-bar](https://user-images.githubusercontent.com/49888000/73522592-a21aa280-446d-11ea-847a-71dd43eaede6.png)

Edge Scale Bar:
![Screenshot from 2020-01-31 21-28-52](https://user-images.githubusercontent.com/49888000/73523960-e9eef900-4470-11ea-93ad-796d2cf81a89.png)

**Example** (no text on the screenshot here, but the production copy would show distance on the markers, and be the full size of the map)
![edge-scale-bar](https://user-images.githubusercontent.com/49888000/73524128-5538cb00-4471-11ea-8786-3cfd9370b9ef.png)

**Idea 5:** Making the popups always fit inside the map view
**Why?** On certain zoom levels and screen sizes, the marker popups can often be outside the bounds of the map (see below)

![Screenshot from 2020-01-31 21-51-32](https://user-images.githubusercontent.com/49888000/73525333-dee99800-4473-11ea-9af4-61ad3de6c271.png)

**How?** A handy plugin called [Leaflet Responsive Popup](https://github.com/yafred/leaflet-responsive-popup)
**Details:** This easy to use plugin simply replaces the `Leaflet Popup` method and using a single line of code, makes the popups always inside the map view
 
**Idea 6:** Box Zoom 
**Why?** Instead of the user having to manually click to zoom, and then manually pan, which can take time, the user just presses a 'Box Zoom' button, and selects a bounding box of the area they want to zoom to, for much faster and more efficient zooming.
**How?** A plugin called [L.Control.BoxZoom](https://github.com/gregallensworth/L.Control.BoxZoom)
**Details:** This can extend the leaflet home zoom functionality we added, with a single button added between the home button and the zoom out button that is a font-awesome [search icon](https://fontawesome.com/icons/search?style=solid). Upon click the user will draw a box on the map, and the map will zoom into the selected area. 

**Idea 7:** Bookmarking most used locations
**Why?** The map users may have certain locations they need to continually return back to, perhaps a certain vessel or certain location where lots of wargame events are happening. This functionality would allow the user to 'save' the most used locations, and with a single click return to that view and zoom level saved earlier.
**How?** [Leaflet.Bookmark](http://w8r.name/Leaflet.Bookmarks/) which is highly customisable, and can store data locally or in a database. 
**Details:** Alongside a plugin like [Leaflet.contextMenu](http://aratcliffe.github.io/Leaflet.contextmenu/examples/index.html) the user could right click on the map and press a button titled 'Save this map view' at which point the location, zoom level and a title for the view would be added to the 'Bookmarks' menu. The user would then be able to press the Bookmark button and select a previously saved bookmark, which then upon click the map would zoom to the location and zoom level saved earlier

**Example:**
Bookmark control open

![bookmarks](https://user-images.githubusercontent.com/49888000/73527053-40f7cc80-4477-11ea-8086-31d8d20a0a7d.png)

Bookmark control collapsed (this function can be added to the toolbar, not as a standalone button)

![bookmarks-collapsed](https://user-images.githubusercontent.com/49888000/73527085-4fde7f00-4477-11ea-8a9a-77f3688e6118.png)

**Comment by IanMayo** [comment]
Closing these - we have a clear list of mapping requirements from the last game.
