### ISSUE TITLE
Update stack (Heroku & node)

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2652]
We're currently running on Node-16

We should update to a more recent version.

Heroku is also complaining. (I've fixed Heroku)

**Comment by lilitkarapetyan** [comment]
Hello @IanMayo. I have updated the node version of my PC to 18.15.0 (recommended version) and I am now making changes to match this version.

**Comment by IanMayo** [comment]
Great, thanks @lilitkarapetyan
