### ISSUE TITLE
Serge doesn't work on windows 

### ISSUE THREAD

**Issue by DMTarmey** [serge-web/serge#2654]
## 🐞 Bug description

C:\Windows\System32>pip install serge
ERROR: Could not find a version that satisfies the requirement serge (from versions: none)
ERROR: No matching distribution found for serge

**Comment by IanMayo** [comment]
Good morning Darren,
I'm afraid you have the wrong `serge`.  This isn't a python app, it's nodejs.

I suspect you're looking for this one: https://github.com/nsarrazin/serge
