### ISSUE TITLE
Add `pouchdb-server`

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2665]
We have got into trouble by making edits to SQLite.  It appears that it's ok to delete rows, or change JSON,  but we're unable to insert rows.

An alternate way of doing this would be to make edits using PouchDb itself. It is possible for the fauxton UI to sit on a PouchDb database - which gives view/edit capabilities, plus mango queries.

_Maybe_ the best route is to integrate the express PouchDb wrapper in our app: https://github.com/pouchdb/pouchdb-server#express-pouchdb

Or _Maybe_ we wrap our existing PouchDb in the wrapper: https://github.com/pouchdb/pouchdb-server#using-your-own-pouchdb

**Comment by IanMayo** [comment]
Thanks for your research in #2669 @lilitkarapetyan 

Could you now produce a list of tasks that will have to be done for us to move over to `pouchdb-server`.  I'm would like to understand the size of the task.

**Comment by lilitkarapetyan** [comment]
To move over to `pouchdb-server`, the following tasks will need to be done.

1. Set up a server that will host line the `pouchDB-server` instance.

2.Install and configure the pouchdb-server package - This involves installing the pouchdb-server package on the server and configuring it based on the requirements of the application.

3. Replace the code that uses pouchDB in the application with code that uses pouchDB-server - This involves modifying the code that uses pouchDB in the application to use the pouchdb-server package instead.

4. Create databases on the `pouchdb-Server` instance that correspond to the databases used in the application.

5. Replicate the data from the existing databases to the newly created databases on the pouchdb-server instance. 

6. Test the application with the new pouchdb-server backend to ensure that it functions as expected - This involves testing the application with the new pouchdb-server backend to ensure that it works correctly and does not introduce any new issues.

> Thanks for your research in #2669 @lilitkarapetyan
> 
> Could you now produce a list of tasks that will have to be done for us to move over to `pouchdb-server`. I'm would like to understand the size of the task.

**Comment by lilitkarapetyan** [comment]
> Thanks for your research in #2669 @lilitkarapetyan
> 
> Could you now produce a list of tasks that will have to be done for us to move over to `pouchdb-server`. I'm would like to understand the size of the task.

To move over to pouchdb-server, the following tasks will need to be done.

1. Set up a server that will host line the pouchDB-server instance.

2.Install and configure the pouchdb-server package - This involves installing the pouchdb-server package on the server and configuring it based on the requirements of the application.

3. Replace the code that uses pouchDB in the application with code that uses pouchDB-server - This involves modifying the code that uses pouchDB in the application to use the pouchdb-server package instead.

4. Create databases on the pouchdb-Server instance that correspond to the databases used in the application.

5. Replicate the data from the existing databases to the newly created databases on the pouchdb-server instance.

6. Test the application with the new pouchdb-server backend to ensure that it functions as expected - This involves testing the application with the new pouchdb-server backend to ensure that it works correctly and does not introduce any new issues.

**Comment by lilitkarapetyan** [comment]
> Thanks for your research in #2669 @lilitkarapetyan
> 
> Could you now produce a list of tasks that will have to be done for us to move over to `pouchdb-server`. I'm would like to understand the size of the task.

To move over to `pouchdb-server`, the following tasks will need to be done.

1. Set up a server that will host line the `pouchDB-server` instance.

2.Install and configure the ` pouchdb-server` package - This involves installing the `pouchdb-server` package on the server and configuring it based on the requirements of the application.

3. Replace the code that uses ` pouchDB` in the application with code that uses` pouchDB-server` - This involves modifying the code that uses `pouchDB `in the application to use the `pouchdb-server` package instead.

4. Create databases on the `pouchdb-Server` instance that correspond to the databases used in the application.

5. Replicate the data from the existing databases to the newly created databases on the `pouchdb-server` instance.

6. Test the application with the new `pouchdb-server` backend to ensure that it functions as expected - This involves testing the application with the new `pouchdb-server` backend to ensure that it works correctly and does not introduce any new issues.

**Comment by IanMayo** [comment]
Thanks @lilitkarapetyan 

> 1. Set up a server that will host line the pouchDB-server instance.

No, we'll just be running it in the local instance, won't we?

> 2.Install and configure the  pouchdb-server package - This involves installing the pouchdb-server package on the server and configuring it based on the requirements of the application.

No, we'll either install and run `pouchdb-server` via `npm`, or we will add `express-pouchdb` to our existing server code.

> 3. Replace the code that uses  pouchDB in the application with code that uses pouchDB-server - This involves modifying the code that uses pouchDB in the application to use the pouchdb-server package instead.

Are you referring to server-side or client-side code here @lilitkarapetyan?   I'm sure we'll still need some serge-specific server-side code.

Hmm, since `pouchdb-server` is meant to be `couchdb` compliant, I wonder if this means we will be able to drop the `pouchdb.js` module, and just use the `couchdb` one for local and remote databases?

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I've just looked in `pouchdb.js`.  I see we are already using `express-pouchdb`:
![image](https://user-images.githubusercontent.com/1108513/234508161-215d83d7-6348-44d7-9cc9-d00a52419736.png)

Doesn't this mean we're already doing what I was proposing?

Hmm, if one `aim` of this issue is to be able to use `fauxton` for database maintenance, it looks like we just replace the above call with this:
![image](https://user-images.githubusercontent.com/1108513/234508897-53683a0e-3f5c-4bcf-b4ad-003eeb90e993.png)

**Comment by lilitkarapetyan** [comment]
> No, we'll just be running it in the local instance, won't we?

Yes, you're correct. If you're using pouchdb-server locally, you won't need to set up a separate server to host it. You can simply run it on your local machine.

**Comment by lilitkarapetyan** [comment]
> Hello @lilitkarapetyan - I've just looked in `pouchdb.js`. I see we are already using `express-pouchdb`: ![image](https://user-images.githubusercontent.com/1108513/234508161-215d83d7-6348-44d7-9cc9-d00a52419736.png)
> 
> Doesn't this mean we're already doing what I was proposing?
> 
> Hmm, if one `aim` of this issue is to be able to use `fauxton` for database maintenance, it looks like we just replace the above call with this: ![image](https://user-images.githubusercontent.com/1108513/234508897-53683a0e-3f5c-4bcf-b4ad-003eeb90e993.png)

Yes, that code sets up an instance of the PouchDB Server with the minimum configuration required to use Fauxton as a debugging tool. By setting the mode option to minimumForPouchDB and including the routes/fauxton route in the overrideMode option, it creates an HTTP API with a minimal interface and includes the Fauxton interface for database maintenance and debugging. 

However, it's important to note that SQLite is not a supported backend for PouchDB Server, so you won't be able to edit SQLite databases directly with this configuration.

**Comment by IanMayo** [comment]
> However, it's important to note that SQLite is not a supported backend for PouchDB Server, so you won't be able to edit SQLite databases directly with this configuration. Instead, you'll need to use a supported backend such as CouchDB or MemDOWN.

![image](https://user-images.githubusercontent.com/1108513/234521884-460ead86-fd61-49db-bc0a-ea6cf5487cba.png)

Is everythink ok with you @lilitkarapetyan ?

**Comment by IanMayo** [comment]
> > No, we'll just be running it in the local instance, won't we?
> 
> Yes, you're correct. If you're using pouchdb-server locally, you won't need to set up a separate server to host it. You can simply run it on your local machine.

You know the project currently already runs a PouchDb backend within node, don't you?  This issue is a minor change to our existing infrastructure.

**Comment by lilitkarapetyan** [comment]
> > > No, we'll just be running it in the local instance, won't we?
> > 
> > 
> > Yes, you're correct. If you're using pouchdb-server locally, you won't need to set up a separate server to host it. You can simply run it on your local machine.
> 
> You know the project currently already runs a PouchDb backend within node, don't you? This issue is a minor change to our existing infrastructure.

yes

**Comment by lilitkarapetyan** [comment]
> Hmm, since `pouchdb-server` is meant to be `couchdb` compliant, I wonder if this means we will be able to drop the `pouchdb.js` module, and just use the `couchdb` one for local and remote databases?

I think we can use the CouchDB module for local and remote databases

**Comment by IanMayo** [comment]
@lilitkarapetyan - do you agree that we can keep the SQLite backend?

**Comment by lilitkarapetyan** [comment]
ahh no, we still need to use PouchDB to work with local databases.

**Comment by IanMayo** [comment]
@lilitkarapetyan - do you agree that we can keep the SQLite backend in PouchDB?

**Comment by lilitkarapetyan** [comment]
@lilitkarapetyan - do you agree that we can keep the SQLite backend in PouchDB?

yes
![Screenshot (197)](https://user-images.githubusercontent.com/20753599/234542370-87fd3319-a38c-4d75-be9e-068083d4a392.png)

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - could you explain your point/issue please?

**Comment by lilitkarapetyan** [comment]
![234508897-53683a0e-3f5c-4bcf-b4ad-003eeb90e993](https://user-images.githubusercontent.com/20753599/234555082-82e3021d-91fe-4a2f-a2e0-dd9ad4235b21.png)
with the `pouchdb-adapter-node-websql` adapter, we be able to use a `SQLite `database with `PouchDB`, and therefore with the express-pouchdb module that you mentioned. However, keep in mind that the Fauxton debugging tool that comes with express-pouchdb is designed specifically for use with `PouchDB`, and may not be able to provide the same level of visibility and control over a `SQLite `database.

**Comment by lilitkarapetyan** [comment]
To use a SQLite database with express-pouchdb, would need to use the pouchdb-adapter-node-websql adapter. This adapter provides a WebSQL implementation that can be used with Node.js and PouchDB.

However, it's important to note that Fauxton, which comes with express-pouchdb, is a web-based user interface specifically designed for PouchDB. It provides tools for managing and querying PouchDB databases, but it may not be optimized for working with other types of databases, such as SQLite.

So while we should be able to use express-pouchdb and Fauxton with a SQLite database via the pouchdb-adapter-node-websql adapter, wemay not get the same level of visibility and control over the database as you would with a tool that is specifically designed for SQLite.

**Comment by IanMayo** [comment]
1. You've provided a screenshot of our current code.   
2. Our current code stores data in SQLite
3. Our current code uses `express-pouchdb`, which seems to be the main component of `pouchdb-server`
4. It should be a trivial change to add fauxton support to our current code

I didn't realise we were already using `express-pouchdb`.  Could you please have another attempt at creating a list of tasks required to add `fauxton` support to Serge?

**Comment by IanMayo** [comment]
Fixed in #2669

**Comment by IanMayo** [comment]
Done.
