### ISSUE TITLE
Serge Admin fixes

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2671]
I look forward to us having e2e testing of Serge admin, and Serge player.

We've got a new tester on the team.  To start with, he is doing some manual testing of Serge Admin.

To start off with, he is tracking his issues [here](https://docs.google.com/spreadsheets/d/11AcAhDh-aVzfzcLa0-WN3YcwDZGZPm7sm2_6q60ajQ4/edit#gid=0)

Could you start working through them please?

**Comment by lebaphi** [comment]
sure @IanMayo, I will fix it according to serverity from high to low.
