### ISSUE TITLE
Switch to non-tiled backdrop

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#268]
We need to introduce an area at the bottom-left of the map for "Organic Assets".

This is for things like helicopters or jet-skis that are currently on another platform.  Or, for aircraft that are actually at a distant airbase.

Anyway, for this, we need to portion off a large dark-grey area at the bottom left. 

This requires an edit to the underlying image.  It would be challenging to re-tile the underlying image, so let's have a look at the performance when we switch to a single image.

The changes required for this are documented under #254

**Comment by lm93547** [comment]
The performance seems comparable with a tiled backdrop, I notice no staggered loading, if anything its faster as the whole image is loaded at once. 

https://github.com/serge-web/serge/tree/image_backdrop

**Comment by IanMayo** [comment]
Done, via dynamic overlays.
