### ISSUE TITLE
MilSymbol renderer

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2702]
We have the MilSymbol renderer, but it's currently just showing a default marker.

We should copy some of [this](https://github.com/serge-web/serge/blob/3569785408f996e81169b04db5e58b9845f7ea41/client/src/Components/local/symbol-asset-icon/index.tsx#L4) code to make the renderer display a valid icon, using the `sidc` prop in `MilSymProperties`

**Comment by lebaphi** [comment]
Fixed in this commit https://github.com/serge-web/serge/pull/2701/commits/838638844c3fc04f93f4173ee71e966d4cfcfa8f

**Comment by IanMayo** [comment]
Fixed in #2701
