### ISSUE TITLE
Control panel for Core Mapping

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2704]
We require some general controls for the Core Mapping channel.

Here is a mockup:
https://docs.google.com/presentation/d/1LdTKv9BTrJdnfshJeEz6SpmMML8D_kbNc8emZ-Ugw6Q/edit#slide=id.g29d5206fb52_0_40

(more detail on following slide)

The aim here is for them not to be focussed on a particular wargame, style of data, or set of properties [*].  So, the UI will largely be build using retrospection from the current features on the map

* [x] create left-hand control panel. It's width (as a %age, I guess) should be persistent
* [x] create top `Filters` panel.  It should have a `filters` heading.  It should start with zero filters, but should have an `add` button to add a new filter.   The `add` button will popup a list of known properties (I don't yet know where these will come from. Either by doing a "live" scan of current data, or on each new update to `features`
* [x] create central `Items` panel. This will be a list of the currently visible items.  For `MilSymbol` it will show the symbol, for `CoreRenderer` item it will be a generic `shape` icon, shaded using the `color` for that item
* [x] create lower `properties` panel.   If one item is selected in the `items` listing, show it's properties here.  We're display text-boxes or drop-downs depending on what we can determine from the property.  We won't show properties with a leading underscore.

[*] - ok, we'll allow a _few_ predictable properties. `sidc` for MilSymbols and `color` for all features.

**Comment by lebaphi** [comment]
Hi @IanMayo , the core panel for core mapping was implemented in this commit https://github.com/serge-web/serge/pull/2708/commits/0846832539d77adc7ac5b15a7e5ea9a6a2476304.

https://github.com/serge-web/serge/assets/26705621/561032e4-39b7-4b19-8231-2e52b685924a


I think we can merge this PR https://github.com/serge-web/serge/pull/2708 into develop then I can create a new branch for this ticket?

**Comment by IanMayo** [comment]
> I think we can merge this PR https://github.com/serge-web/serge/pull/2708 into develop then I can create a new branch for this ticket?

Good plan.  PR now merged.

**Comment by lebaphi** [comment]
> create top Filters panel. It should have a filters heading. It should start with zero filters, but should have an add button to add a new filter. The add button will popup a list of known properties (I don't yet know where these will come from. Either by doing a "live" scan of current data, or on each new update to features

For this part, I'm thinking about the shape of the Filter component and the logic of how it works
- First we will have a text field to search for items by its properties
- The list of items will be changed based on the results of the filter value
- Clicking on add button opens a popup/modal, it shows all the properties of the current data (just for now), but when we select a property and add, what should it do next according to?

How do you think @IanMayo ?

**Comment by IanMayo** [comment]
Hello @lebaphi  - I tried to mock up the filter component here:
https://docs.google.com/presentation/d/1LdTKv9BTrJdnfshJeEz6SpmMML8D_kbNc8emZ-Ugw6Q/edit#slide=id.g29d5206fb52_0_64

When we select a property and add it, a new filter will be shown in the table.  It will have a text box or a drop-down list.  Initially, the text-box will be empty, or the drop-down list will have zero items selected.  That means that filter is currently inactive, and is ignored.  If the user enters some text, or selects an item from the drop-down, that filter becomes active, and we start filtering items accordingly (applying wildcard search if it's a text box)

**Comment by lebaphi** [comment]
I've implement the basic UI for the control panel @IanMayo 

https://github.com/serge-web/serge/assets/26705621/390f40cb-3115-47f1-b27e-d542ed86e500

**Comment by IanMayo** [comment]
Thanks @lebaphi  - that's looking great.

Note: I only used the color shades in the mock-up to make them easier to refer to in conversation.  I'm happy for the actual implementation to use standard color shades for the UI toolkit (presumably grey).

Note 2: The `+` markers for the drag handles seems non-standard.  Are you able to use drag markers?   I _think_ that several dots or parallel lines is the most common one.

![image](https://github.com/serge-web/serge/assets/1108513/ff35198c-721e-42f0-9268-555c65be385d)

**Comment by lebaphi** [comment]
Hi @IanMayo , I just implemented Add Filter modal and properties panel, can you review it? I'm not sure what should we do next with Add filter modal 😄 

https://github.com/serge-web/serge/assets/26705621/b5150c47-fcad-4ba3-b32b-5f0208c58629
