### ISSUE TITLE
Channel row are generated when switch channel

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2720]
## 🐞 Bug description
In Channels tab, some rows are auto generated when we switch from one channel to another channel

## 🔢 Steps to Reproduce
 
1. Login app as admin
2. Create a new game 
3. From 'Forces' tab, create some forces ( White, Blue, Red)
4. From 'Channels' tab, create channel 1 with some participant rows > Save Channel
5. Create channel 2 with some participant row > Save Channel
6. Switch from channel 1 and channel 2, notice the rows are auto generated

More details from below screencast : 

## ⚙️ Expected behavior
No more row is generated when switch from channels

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/3fd123c6-d655-4fde-93c0-54cd31b987ed

## 💻 System information

 - Operating System: [e.g. iOS, Windows, etc...]
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
This is an important one, please @lilitkarapetyan
