### ISSUE TITLE
Reload page from admin should keep the current place instead of the login admin page

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2727]
## 🐞 Bug description
From admin page, I reload page and notice it always direct to login admin page

## 🔢 Steps to Reproduce

1. Login app as admin
2. Go to 'Message Template page'
3. Refresh browser
4. Notice it always direct to login admin page and I have to login again

More details from below screencast.

## ⚙️ Expected behavior
Reload page from admin should keep the current place instead of the login admin page

## 🖥️ Screens

https://github.com/serge-web/serge/assets/107697044/cc6954b8-7590-4838-8ea1-95e009d32380

hots

## 💻 System information
Browser : Chrome
Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Thanks @Tristina1788 , but this is a behaviour I'm prepared to live with.
