### ISSUE TITLE
Can't play game with role 'Game control' with channel has config with template

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2728]
## 🐞 Bug description
Setup new game with channel using template. Notice play game with role 'Game Control' will show white screen and can't play game anymore

## 🔢 Steps to Reproduce
1. Login app as admin
2. Create a new game
3. From 'Forces' tab, create some forces ( White, Blue, Red)
4. From 'Channels' tab, create channel 1 with some participant rows which using template > Save Channel
5.  Go to 'game play' page
6. Select wargame is the game which is created above
7. Select role 'Game Control' 
8. Click 'Enter'
9. Notice it shows white screen and can not play game

Note: The issue is not happened when channels don't have any participants using template
See below screencast for more details

## ⚙️ Expected behavior
Should show the screen for playing game

## 🖥️ Screencasts

https://github.com/serge-web/serge/assets/107697044/e9ae606a-fab3-4829-a200-e76061dcbf8a

## 💻 System information
Browser : Chrome
Browser Version : Version 120.0.6099.111

## 📝 Additional context
@lilitkarapetyan - I suspect this is another "template not found" issue. Could it be related to the refactoring when we reduced the complexity of `participant states`?

**Comment by lilitkarapetyan** [comment]
Hello @Tristina1788 - No, I think it cannot be related to the changes made.
