### ISSUE TITLE
No input field for ' NEW MESSAGE' in game play page 

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2729]
## 🐞 Bug description
Play a game with White - Game Control, I don't see the input field for 'NEW MESSAGE' part

## 🔢 Steps to Reproduce
1. Create a basic game as this diagram

![image](https://github.com/serge-web/serge/assets/107697044/20433cf8-7b2c-467d-aab4-d94e22f2c87c)

2. Go to 'game play' page
4. Select wargame is the game which is created from step1
5. Select role White - Game Control
6. Click 'Enter'
7. Close the guide
8. Click 'NEW MESSAGE' to open this part
9. Notice no input field for input message

![image](https://github.com/serge-web/serge/assets/107697044/efb769f3-8ff7-4206-9496-e85d9944b8bd)

## ⚙️ Expected behavior
'NEW MESSAGE' should show the input field for input message

## 💻 System information

 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Is this still an issue @Tristina1788 ?

**Comment by Tristina1788** [comment]
> Is this still an issue @Tristina1788 ?

It works as expected now. So I close the ticket.

![image](https://github.com/serge-web/serge/assets/107697044/0baeb3d4-666c-4d2c-9db5-2da20b32d233)
