### ISSUE TITLE
The input of 'Text' in Welcome Screen should be larger

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2734]
## 🐞 Bug description
In 'Welcome screen' , the arear of 'Text' is smaller for input text

## 🔢 Steps to Reproduce
 
1. Login as admin
2. Go to 'Welcome Screen' page
3. Click 'Edit' at 'Text'
4. Notice the arear of input 'Text' is small

![image](https://github.com/serge-web/serge/assets/107697044/4fcbe23e-1a56-4169-8a98-1292eab8ff06)

## ⚙️ Expected behavior
The input of 'Text' in Welcome Screen should be larger or can be expanded 

## 💻 System information
 - Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Fixed in hotfix: https://github.com/serge-web/serge/commit/617eacc81286ea03dbd0b4b33251b0da5e8ec249
