### ISSUE TITLE
Message Templates screen should have only one 'Save' button

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2736]
## 🐞 Bug description
From 'Message Templates' screen, I click on one template. Notice we always see 2 'Save' button

## 🔢 Steps to Reproduce
1. Login as admin
2. Go to 'Welcome Screen' page
3. Click on a template
4. Notice 2 'Save' buttons always show although the template is short

![image](https://github.com/serge-web/serge/assets/107697044/a6cf94e0-11c0-495b-acd3-88e2a512eb1d)

## ⚙️ Expected behavior
- Should only show one 'Save' button on screen.

## 💻 System information

 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Low priority - I think it's a feature that's useful for really long templates.
