### ISSUE TITLE
Core Mapping - New shapes

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2744]
When a new shape is added to the CoreMapping map, we should send an updated `MappingMessage` to the server - so that other logged in users see the new shape.

This will be a `MappingMessage` where the `featureCollection` is the current set of features on the map.

We should check this works by being logged in twice, and verifying that new shapes get rendered on the map of other users.

**Comment by lebaphi** [comment]
I think it was fixed in https://github.com/serge-web/serge/pull/2753
