### ISSUE TITLE
Eliminate @ts-ignore in AdminGameSetup Component

### ISSUE THREAD

**Issue by lilitkarapetyan** [serge-web/serge#2769]
## 🐞 Amendment description
The `AdminGameSetup` component currently uses `@ts-ignore` in several places. This is not a recommended practice as it suppresses TypeScript errors without providing a proper solution. We need to refactor the code to eliminate the usage of `@ts-ignore` and implement TypeScript-friendly solutions.

## 🖥️ Screenshots
![393a98d96d2307b448cfedeecca32fa6](https://github.com/serge-web/serge/assets/20753599/b5ab9114-6836-4990-914d-fa75d5a9949e)

**Comment by IanMayo** [comment]
Well spotted, thanks @lilitkarapetyan 

**Update:** I've just had a look, and it looks like those `ts-ignore` flags are suppressing some issues that really need solving.
