### ISSUE TITLE
'Filter Out' button in Core mapping should not overlap the text

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2787]
## 🐞 Bug description
In 'Core Mapping', notice the 'Filter Out' button is overlap the text version and date time

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Notice the button 'Filter Out' is is overlap the text version and date time
![image](https://github.com/serge-web/serge/assets/107697044/f632cc8d-c093-49ac-8bf0-b7a841968458)

## ⚙️ Expected behavior
The button should not overlap the text. It's better to move up a little like this : 

![image](https://github.com/serge-web/serge/assets/107697044/84f76f03-b805-4060-ae76-d693a65b6145)

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Aah, now that we have moved the zoom in/out buttons to the bottom-right. we can move the `filter-out` button to the top-left, which will fix this.

Could you do that please @lebaphi ?
