### ISSUE TITLE
Can not zoom in/out for core mapping

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2788]
## 🐞 Bug description
From 'Core Mapping' channel, I can't zoom in/out the map

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Notice the button user can't zoom in/out on the map
4. Checking from https://www.geoman.io/demo, I can zoom in/out well

## ⚙️ Expected behavior
Our Core Mapping should work as https://www.geoman.io/demo. User should enable to zoo in/out on map

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
I think this is fixed now. Could you re-check please @Tristina1788 ?

**Comment by Tristina1788** [comment]
Check out latest code from branch 'Develop' and can zoom In/out well. It works as expected. So I close the ticket.
