### ISSUE TITLE
Core Mapping - custom editor control for lat/long

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2807]
We have a PR in progress that introduces lat/long as two new properties, shown on separate lines in the property editor.

But, these two properties are so closely associated with each other that I'd like them to be shown as two text fields side-by-side, with `tab` key moving from the first to the second.

**Comment by lebaphi** [comment]
Hi @IanMayo, fixes in this commit https://github.com/serge-web/serge/pull/2801/commits/524c76dc54d04eff520412d18cbc670fad332be5

**Comment by IanMayo** [comment]
> Hi @IanMayo, fixes in this commit [524c76d](https://github.com/serge-web/serge/commit/524c76dc54d04eff520412d18cbc670fad332be5)

Sure - I've updated the PR to record the fact that it `fixes` this issue (so this issue will get closed when that PR is merged)
