### ISSUE TITLE
Don't hard-code force colors

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2808]
In `core-renderer.tsx` we have hard-coded force ids and colors.

Instead, we should lookup the data from the `ForceStyle` object provided in the props.

**Comment by IanMayo** [comment]
Close. Duplicate of #2806

**Comment by IanMayo** [comment]
No, it's not a duplicate.

**Comment by lebaphi** [comment]
Hi @IanMayo, where can I find the force styles object?

**Comment by IanMayo** [comment]
Hello @lebaphi ,
`forces: ForceStyle[]` is in the props for `core-mapping`, though it isn't actually used within the component.
