### ISSUE TITLE
ID should not editable field 

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2817]
## 🐞 Bug description
ID should not editable field 

## 🔢 Steps to Reproduce
1.Play game with data wargame-l6nngxlk 
2. Click on channel 'Core Mapping'
3. Select any item 
4. Notice the 'Properties'  > 'ID' field is editable field and can edit to duplicate ID

![image](https://github.com/serge-web/serge/assets/107697044/52c5836a-6c9d-42a0-b4c0-596f6577cade)

## ⚙️ Expected behavior
ID should not editable field 

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Hello Tristina, could you give us a little more detail here please?

I'm not clear on where you are encountering the issue.

**Comment by Tristina1788** [comment]
> Hello Tristina, could you give us a little more detail here please?
> 
> I'm not clear on where you are encountering the issue.

@IanMayo  The character is redundant so it makes my detail is hidden. I remove it and now it shows well. Please help me check again

![image](https://github.com/serge-web/serge/assets/107697044/1e70faf8-2752-4633-80e7-fc6e50b182f5)

**Comment by IanMayo** [comment]
Aah, well done for spotting that Tristina.

We're still _learning_ about the role of id/label/name in this new mapping. The `id` _may_ end up as the name of the item, in which case we want users to be able to edit it.

We'll come back to this once our understanding has matured a little more.

**Comment by Tristina1788** [comment]
@IanMayo  Now the 'ID' field is disable as expected. Should we close it?

![image](https://github.com/serge-web/serge/assets/107697044/821add72-0723-4e1b-8068-d8b43627eaab)

**Comment by IanMayo** [comment]
Fixed in #2837
