### ISSUE TITLE
Unable to select created umpire

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2823]
## 🐞 Bug description
Unable to select created umpire

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Create new umpire
4. Try to select umpire to update properties
5. Notice user can't select umpire

## ⚙️ Expected behavior
Should enable to select created umpire

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/da0dea94-ec2b-4dd2-b27c-7ace1d8ed733

## 💻 System information
Browser : Chrome
Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Thanks @Tristina1788 - could you break down the steps to reproduce a little more please?  Or maybe try to include the whole process in the screencast?

(just to speed up the developer's time in fix it)

**Comment by Tristina1788** [comment]
> Thanks @Tristina1788 - could you break down the steps to reproduce a little more please? Or maybe try to include the whole process in the screencast?
> 
> (just to speed up the developer's time in fix it)

This is screen cast for create umpire and try to select it.  

https://github.com/serge-web/serge/assets/107697044/a4db21db-5ca0-4909-beb3-6359eb9a7173

**Comment by IanMayo** [comment]
Got it, thanks @Tristina1788

**Comment by lebaphi** [comment]
I think I have discussed with @IanMayo about this issue, and it was fixes in this PR https://github.com/serge-web/serge/pull/2820

**Comment by IanMayo** [comment]
Aah yes, thanks @lebaphi
