### ISSUE TITLE
Rectagle Item should has only 4 points when 'Edit Layers' 

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2826]
## 🐞 Bug description
Rectagle Item should has 4 points when 'Edit Layers' 

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Draw rectangle item
4. Click 'Edit Layers'
5. Notice the rectangle item has 8 points instead of 4 points and rectangle item can be changed to another shape

More details on below screencast
## ⚙️ Expected behavior
Rectangle item should has 4 points and 'Edit Layers' should not change rectangle shape.

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/817b77fa-aa04-4593-90f9-25ef2e726a8a

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Sure. This is intended behaviour @Tristina1788 . The user can click the corners to change the dimensions of the rectangle, or the corners in order to "grow" it.
