### ISSUE TITLE
3.1 Change entity visibility (via popup form)

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#284]
As a < umpire >, I want < to change platform visibility > so that < players have limited perception of the world >.

In the Adjudication Phase, the umpire builds up a set of platform visibilities, that are submitted at the end of the turn.

But, in the planning phase, the umpire may realise that one force should/should-not be able to see a particular platform, and is allowed to send an instant fix

# Acceptance criteria

- [ ] Logged in as game control, game in Planning phase
- [ ] Click on any marker. Popup menu appears, showing which forces can/can't see that asset
- [ ] Make some changes to these checkboxes
- [ ] Press submit.  Message sent with new visibility.  Note: I _think_ the existing processing can handle an array of visibility changes - so we should be able to send several at once.

Note: this popup dialog will replace the instances of calls to `getVisibilityButtonsFor` in `MapPlanningPlayerListener`, and the popup should be triggered from these locations.

Note: during the planning phase, the Umpire may have control of other forces. So, clicking on one of those assets will popup the Planning Dialog.  I _guess_ we have to extend the Planning Form to include the visible/not-visible flags.  Or, we could _maybe_ handle it in the `Orders Panel`.

# UX
Here's a similar form that was created for the adjudication phase.

For the planning phase, the form will only contain `Visibility`, and will have a `Submit` button - since the message goes instantly.  (It goes instantly because it could impact on this turn)

![image](https://user-images.githubusercontent.com/1108513/73615024-94dfee00-45fc-11ea-98cd-b7d8f579bc0b.png)

# Notes

**Comment by IanMayo** [comment]
@clenoble - we have a low priority UX issue here, please. 

In the Planning Phase, the umpire makes "live" changes to platform visibility.  For assets the umpire doesn't control, we can show a visibility popup.  But, for assets the umpire _does_ control, we currently show the `Planning` popup - where the umpire sets state/speed/etc for that platform.   

So, we _may_ need to introduce an `Umpire Planning` popup - that allow visibility to be modified, in addition to allowing the planned state to be set.

**Comment by clenoble** [comment]
@IanMayo The logic would be for white to log in as green or any color they control to do the planning. They could do so in another tab. And in white interface, they control the visibility for these ships as for all the other ships. That would make it more consistent.
How do we know which assets are controlled by white? Is it specified in the game design phase? 
If we keep visibility in white and route planning in each particular force, we don't need to specify which assets are controlled by white, and they can impersonate any color.

**Comment by IanMayo** [comment]
Nice logic.    At the wargame 2 weeks ago Paul already had 3 tabs open, one per wargame.  He wouldn't handle multiple tabs per wargame (actually, Chrome won't allow more than 5 connections to one server).

> How do we know which assets are controlled by white?

Yes, it's in the Game Design phase.  It will be edited in the Game Admin screen, but it's currently just in text as `controlledBy`:
```
  {
	"color": "#0F0",
	"controlledBy": ["umpire"],
	"icon": "default_img/umpireDefault.png",
	"name": "Green",
	"overview": "Green Shipping",
	"roles": [
		{
			"control": false,
			"isInsightViewer": false,
			"isObserver": false,
			"name": "CO",
			"password": "P9454"
		}
	],
	"umpire": false,
	"uniqid": "Green"
}
```

But, maybe can use the existing logic to fit what you described.  When in "Planning" mode, the umpire can click "View as Green" to view the plot as green. In this mode, clicking on Green will open the planning popup.    Clicking on a platform from any other force will open "Change visibility" dialog.  How does that sound?

**Comment by clenoble** [comment]
I thought you said that there will need to be 1 adjudicator per game in the future, because managing several games was too much. 
Anyway, the solution you suggest, using the map view, is even better! :)

**Comment by IanMayo** [comment]
Ok. Umpire will only get the "Planning Popup" when "View As" that force, and if that force is `controlledBy` the Umpire force.  Otherwise, the umpire will get "Visibility Popup"

**Comment by IanMayo** [comment]
In Sept 2020 this is partially broken.  As White, when I click on a Red asset in Planning mode, I should see the visibility flag. But, nothing happens.

![image](https://i.gyazo.com/11092cbe10f1ebf7c828d52328f63801.gif)

**Comment by IanMayo** [comment]
Issue no longer present.
