### ISSUE TITLE
The new shape umpire should not have black color as default

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2842]
## 🐞 Bug description
The new shape item should not have black color as default

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Create a new Shape item
4. Notice it 's created with default color is black although the force default is 'f-Red'

![image](https://github.com/serge-web/serge/assets/107697044/deb011cc-9220-4367-be5a-1c07e5f52fe7)

View  below screencast for more detail
## ⚙️ Expected behavior
The shape item should show default color same as default force color

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/3cbb6233-c07b-49bc-b2a7-251953cd3112

## 💻 System information
Browser : Chrome
Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
One for you, please @lebaphi .  I don't know if this associated with "highlight selected item" or some merge-issue introduced by me :-(

**Comment by lebaphi** [comment]
Hi @IanMayo, the shape icon color is getting from `color` property, we get it from playerForce prop. So I have 2 questions:
- Should we set the shape's color by force's color?
- If yes, what does the `playerForce.color` do?

<img width="248" alt="Screen Shot 2024-02-13 at 9 55 26 PM" src="https://github.com/serge-web/serge/assets/26705621/83e073b3-350b-4728-b5b6-afc98fcb826a">

<img width="241" alt="image" src="https://github.com/serge-web/serge/assets/26705621/8dac670f-82a9-44d6-966f-8bae7fc42cfb">

**Comment by IanMayo** [comment]
Aah yes, I see.  If we set the color according to the player force ,we no longer need the `color` prop.  Well spotted :-D
