### ISSUE TITLE
'Text' items should not show icon shape on 'Items' pannel

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2844]
## 🐞 Bug description
'Text' items should not show icon shape on 'Items' pannel

## 🔢 Steps to Reproduce
1.Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Create a new 'Text' item
4. Notice the 'Text' item show as shape item on 'Items' pannel

'Text' items should not show icon shape on 'Items' pannel

![image](https://github.com/serge-web/serge/assets/107697044/bb5d78ce-2135-45c2-834b-419f1c795304)

View more details on below screencast

## ⚙️ Expected behavior
'Text' items should not show icon shape on 'Items' pannel

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/22a0dce9-03c0-4168-85ba-340e41de0cb2

## 💻 System information
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
I don't see this as an issue @Tristina1788, I see "text-box" as a shape.
