### ISSUE TITLE
'Important' filter gets wrong result with default 'Yes' 

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2847]
## 🐞 Bug description
'Important' filter has default value is 'Yes' and the result of filter is all items. It should only show the result which match with default 

**Update from Ian:** the `important` boolean filter should have a third `Empty` state, which does not try to match anything.  When added, the filter component will be in this state.  The user then selects a boolean state, and the filter is applied.

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Add filter with 'Important'
4. Notice the default filter 'Important' is yes
5. Notice 'Items' panel shows all items instead of it shows the items which are matched with 'Important' = Yes

![image](https://github.com/serge-web/serge/assets/107697044/44c3bfa6-8612-4581-a41a-4d5fc7b53a36)

View below screencast for more details
## ⚙️ Expected behavior
'Important' filter has default value is 'Yes' and the result of filter is all items. It should only show the result which match with default 

## 🖥️ Screencasts

https://github.com/serge-web/serge/assets/107697044/7258d86a-7aba-4865-9438-ca9277c3e139

## 💻 System information

 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
@Tristina1788 -  if I change the value of the `important` filter, it seems to work correctly.  Could you try that?

Maybe all we require is for the filter to be applied as soon as it is added.

**Comment by Tristina1788** [comment]
> @Tristina1788 - if I change the value of the `important` filter, it seems to work correctly. Could you try that?
> 
> Maybe all we require is for the filter to be applied as soon as it is added.



> @Tristina1788 - if I change the value of the `important` filter, it seems to work correctly. Could you try that?
> 
> Maybe all we require is for the filter to be applied as soon as it is added.

@IanMayo   `if I change the value of the `important` filter, it seems to work correctly. Could you try that?` => Yes, it works fine when we change the value.  But I think it should show default value is Empty  in case we want to show all items. And if defaut is 'Yes', it should show only the items which has 'Important' is 'Yes'
`Maybe all we require is for the filter to be applied as soon as it is added.` => I think so.

**Comment by IanMayo** [comment]
Ok.  Yes, this is an issue. But, I'd like us to defer solving it for now.
