### ISSUE TITLE
'Wild card' is on Filter although it 's not in any properties of item

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2849]
## 🐞 Bug description
'Wild card' is on Filter although it 's not in any properties of item

**Update from Ian:** the wild-card filter searches through the `label` field.  We should change it so that it does a wildcard search through the `label` *and* `id` fields - since in use there can be some very similar labels, so id is the quickest route to finding an element.

## 🔢 Steps to Reproduce
1. Play game with data wargame-l6nngxlk
2. Click on channel 'Core Mapping'
3. Add filter 'Wild Cart'
4. Notice it can return some items
5. Click on item at step4
6. Notice no item has properties 'Wild Card', seem it gets from label

## ⚙️ Expected behavior
`Wild card' is not on Filter because of it 's not in any properties of item. 

## 🖥️ Screenshots
![image](https://github.com/serge-web/serge/assets/107697044/8df70888-2466-42fe-b070-dd760cc5cc18)

## 💻 System information
 - Browser : Chrome
 - Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
This is intended behaviour.  It is a full-text-search across all fields.

Ok @Tristina1788 ?

**Comment by Tristina1788** [comment]
> This is intended behaviour. It is a full-text-search across all fields.
> 
> Ok @Tristina1788 ?

@IanMayo  Seem filter 'Wildcard' is only searched for 'Label' properties. I try to search 'Id' of an item but filter 'WildCard' doen't return any item.

![image](https://github.com/serge-web/serge/assets/107697044/674e9011-1f0c-42eb-aa25-12d96a86431e)

![image](https://github.com/serge-web/serge/assets/107697044/67a5b6ae-7b1f-4463-8cad-145d22ee4681)

**Comment by lebaphi** [comment]
Hi @IanMayo and @Tristina1788, so do you want the Wildcard to search on all fields instead of `label` and `id`? If so, does it overlap in functionality with other filters?

**Comment by IanMayo** [comment]
Hmm, I'm ok with `id` and `label`.  The other text fields tend to be drop-downs, so it's easier to search using the specific filter for that field.

Aah, but maybe there's a ux improvement.  Can we name it a bit better?  Any thoughts @Tristina1788 

It's a wildcard search, and it covers the `id` and `label` fields.

**Comment by Tristina1788** [comment]
> Hmm, I'm ok with `id` and `label`. The other text fields tend to be drop-downs, so it's easier to search using the specific filter for that field.
> 
> Aah, but maybe there's a ux improvement. Can we name it a bit better? Any thoughts @Tristina1788
> 
> It's a wildcard search, and it covers the `id` and `label` fields.

How do you think about 'ID/Label' ?

**Comment by Tristina1788** [comment]
@IanMayo , @lebaphi  but I don't see it filter for `Id` 

![image](https://github.com/serge-web/serge/assets/107697044/44e0ca21-d062-4089-8d83-8d3901d20511)

![image](https://github.com/serge-web/serge/assets/107697044/bde9b25d-812e-43df-aa0f-b6fb188977d8)

**Comment by IanMayo** [comment]
> How do you think about 'ID/Label' 

@lebaphi - do you know if it's possible to have `ID/Label` plus a search icon as the label?  I think we need some extra _clue_ that it's a wildcard/regexp search.
