### ISSUE TITLE
Core Mapping - Measuring Tool (basic)

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2868]
The core mapping could do with these two features:
- ScaleBar - to show the current scale (in km).
- Measuring Tool - switch on to allow the user to measure a single or poly line. We should add this as a control to the geoman toolbar

We've used both in the past, we can probably use similar solutions this time.

**Comment by lebaphi** [comment]
Hello @IanMayo, about the measurement tool, I can't remember which plugin we used, can you remind me?

I found this one https://www.geoman.io/docs/options/measurement but only Leaflet-Geoman Pro supports this.
I found another one: https://ptma.github.io/Leaflet.Measure/examples/measure.html
