### ISSUE TITLE
Allow de-select of mapping feature

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2873]
A user selected a feature, and it started pulsing.

He wanted to de-select it, but it wasn't possible. It was only possible to select something else instead.

If a user clicks on `nothing`, clear the selection.

**Comment by lebaphi** [comment]
I think user can click the Cancel button @IanMayo

**Comment by IanMayo** [comment]
Aah yes. This user wanted to clear the selection using the map.  He _expected_ the selection to clear by clicking on _nothing_ on the map.

Could you investigate it please?
