### ISSUE TITLE
Can not build local from branch '2892_Edit_templates_in_admin_pages'

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2907]
## 🐞 Bug description
I get white screen on http://localhost:8080/, http://localhost:3000/ after build from my machine

## 🔢 Steps to Reproduce
1.  Checkout code from branch '2892_Edit_templates_in_admin_pages'
2. Build server with these command
  yarn install
  yarn build 
 yarn develop
4. Get white screen on localhost url

![image](https://github.com/serge-web/serge/assets/107697044/fb76d2e0-341e-4453-a8ca-5f7e8d4e92bc)

Note : 
- I recorded the error from console on the below screencast
- I tried on 2 machine,  clear cache, restart machine, reinstall npm. But nothing help for me.

## ⚙️ Expected behavior
I can build and run server well without issue

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/f5965b75-f6a6-4c58-a2ec-5e9c01f61502

## 💻 System information
 - Windows 10 Pro
 - Browser : Chrome, IE, firefox
 - Node : 18.x, 20.x

**Comment by IanMayo** [comment]
Thanks @Tristina1788 - could you also do a screen recording of you running "git status" (to confirm which branch you are on), then "yarn install" and then "yarn develop"?

**Comment by IanMayo** [comment]
Note: I also get this issue when running locally (macos / chrome):
![image](https://github.com/serge-web/serge/assets/1108513/a0834ea2-18be-4737-b0f4-ff2b45de4938)

Here is a video of my build process: no errors reported:
https://i.gyazo.com/7b25ba96400dbea53f5311ac4c1d191a.mp4

**Comment by Tristina1788** [comment]
> Thanks @Tristina1788 - could you also do a screen recording of you running "git status" (to confirm which branch you are on), then "yarn install" and then "yarn develop"?

Here screen recording for git and build server : 

https://github.com/serge-web/serge/assets/107697044/1bdcc3c7-b94b-471c-934c-048542a3ed63

**Comment by Tristina1788** [comment]
Another error on console localhost :8080

![image](https://github.com/serge-web/serge/assets/107697044/13b2a08c-dba8-49f7-a0f6-3f6c205cda13)

![image](https://github.com/serge-web/serge/assets/107697044/4fbb682b-e4a9-46ad-9eea-6fdf648e07d5)

**Comment by lilitkarapetyan** [comment]
Hello all, I think I resolved that issue in PR  - https://github.com/serge-web/serge/pull/2897

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan - I still have that issue in branch `2892_Edit_templates_in_admin_pages` for PR #2897

**Comment by lilitkarapetyan** [comment]
Have you attempted clearing the chache or remove node_module folder, followes by a fresh reinstallation ?( `node rm -rf, yarn  ` )

**Comment by lilitkarapetyan** [comment]
I had the same error, but it was resolved for me  after updating the `"@mui/material" `library.

**Comment by Tristina1788** [comment]
> Hello @lilitkarapetyan - I still have that issue in branch `2892_Edit_templates_in_admin_pages` for PR #2897

Can you try my way https://github.com/serge-web/serge/pull/2897#issuecomment-2011792883 ?
It works for me now.

**Comment by lilitkarapetyan** [comment]
> > Hello @lilitkarapetyan - I still have that issue in branch `2892_Edit_templates_in_admin_pages` for PR #2897
> 
> Can you try my way [#2897 (comment)](https://github.com/serge-web/serge/pull/2897#issuecomment-2011792883) ? It works for me now.

Yes I will try.

**Comment by IanMayo** [comment]
Ok. Deleting the repo and cloning, installing, building worked for me.
