### ISSUE TITLE
Get white screen when send feedback or send message and send message from admin

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2921]
## 🐞 Bug description
- Get white screen when send feedback or send message and send message from admin

## 🔢 Steps to Reproduce

1. Go to https://serge-inet.herokuapp.com/
2. Create a basic game
3. Try to send feedback / send message from channel and send message from admin
4. Notice the white screen shows and user need to refresh page and login again

Note: this bug is not present when run on `develop`

![image](https://github.com/serge-web/serge/assets/107697044/d4ea0640-db78-4cf7-a7db-b0ff9a325d97)

## ⚙️ Expected behavior
User can send message or send feedback without issue

## 🖥️ Screenscast

https://github.com/serge-web/serge/assets/107697044/b0c822e1-dbae-48e7-a841-d798a49a68d2

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by Tristina1788** [comment]
Testing from https://serge-inet.herokuapp.com/

Now I can send message and send feedback well


https://github.com/serge-web/serge/assets/107697044/ce4b105c-f2bf-4dc5-a1e9-712daced6bab

**Comment by IanMayo** [comment]
> Testing from https://serge-inet.herokuapp.com/
> 
> Now I can send message and send feedback well
> 
>  enable_send_msg_feedback.mp4

Great - thanks @Tristina1788
