### ISSUE TITLE
'New Channel' a game some times jump in to another game

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2937]
## 🐞 Bug description
From admin page, click 'New Channel' sometimes jump in to the latest channel which is open before.

## 🔢 Steps to Reproduce
1. Go to admin page
2. Create a simple wargame1 with some forces and some channels
3. Create a simple wargame2 with some forces and some channels
4. From tab 'Channel' of wargame2, back to all game
5. Douple click wargame1, click 'New Channel'
6. Notice it shows as it's on wargame2 instead of wargame1

## ⚙️ Expected behavior
Editing wargame should shows data on that wargame and not jump to another wargame

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/44755403-a944-4619-8ca8-b39762cdac28

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
@Tristina1788 - can you check if this is still an issue please?

**Comment by Tristina1788** [comment]
> @Tristina1788 - can you check if this is still an issue please?

@IanMayo Checking on 'Develop' branch, the issue is still happened 

https://github.com/serge-web/serge/assets/107697044/1443d98d-32f0-46ff-baeb-36b9db59d4de

**Comment by Tristina1788** [comment]
@IanMayo  Checking on `develop` branch, Now the issue is not happened any more. I think it may be fixed on this branch `2938_Open_a_wargame_should_show_Overview_tab_at_begining_from_admin_page` .

https://github.com/user-attachments/assets/0aca8541-10c2-4a0e-8071-4d16eb3a7916



So we can close ticket.
