### ISSUE TITLE
No input message field for Collab channel 

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2940]
## 🐞 Bug description
No input message field for Collab channel 

## 🔢 Steps to Reproduce
1. Create a basic game with some force and some channels
2. Login from admin page
3. Click on dropdown of button 'Add Channel'
4. Select 'Collab Edit'
5. Notice Permission has default is Red - All - CannotCollaborate

![image](https://github.com/serge-web/serge/assets/107697044/c2372afd-050d-4f8e-a6cd-cfa6711c159c)

6. Play game with Red - CO
7. Select 'Collab' channel
8. Notice no input message field 

![image](https://github.com/serge-web/serge/assets/107697044/ab518134-815a-4452-bbfb-4a5c7998a232)

## ⚙️ Expected behavior
If user can't send message, we should not show the 'New Message' on the bottom. If user can send message, we should have the input field for it

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/c3ed8c06-930f-490f-bd6b-abea99ec8a38

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Works as expected.
