### ISSUE TITLE
After send message from Collab Channel, I don't see message shows on board or anywhere else

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2941]
## 🐞 Bug description
After send message from Collab Channel, I don't see message shows on board or anywhere else

## 🔢 Steps to Reproduce
1. Create a basic game with some force and some channels
2. Login from admin page
3. Click on dropdown of button 'Add Channel'
4. Select 'Collab Edit'
5. Add New permission : Blue - All - Edit Collab

![image](https://github.com/serge-web/serge/assets/107697044/2eefccb9-3377-4270-a78a-e32aaef45a0e)

6. Play game with Blue - CO
7. Select 'Collab' Channel, send a message
8. Notice the new message is not showed on the board or anywhere

## ⚙️ Expected behavior
- Should have anywhere to see new message. Maybe the board of 'Collab' channel.

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/68f3cff0-2496-4c78-a761-84a2555ff204

## 💻 System information
- Browser : Chrome
- Browser Version : Version 120.0.6099.111

**Comment by IanMayo** [comment]
Hello @Tristina1788 - it appears you have now been able to send a message. Does that mean that #2940 is not now an issue?

**Comment by Tristina1788** [comment]
> Hello @Tristina1788 - it appears you have now been able to send a message. Does that mean that #2940 is not now an issue?

I think it's better if we don't show the panel message for the user with permisssion 'Cannot collaborate' . So user will not confuse why they can see the message panel and 'Send' button. @IanMayo  How do you think?

**Comment by IanMayo** [comment]
Hello @lilitkarapetyan 

I've created a branch with demo data to test this, it's in PR #2942 

If you login as blue player you will see the channel, and create a message.  But, when you press [`Send`], the `network` tab in Dev-Tools does not show a new message being sent.

**Comment by IanMayo** [comment]
> I think it's better if we don't show the panel message for the user with permisssion 'Cannot collaborate' . So user will not confuse why they can see the message panel and 'Send' button. @IanMayo How do you think?

No, there is logic in it - some roles can submit messages, but not interact with them afterwards.

**Comment by Tristina1788** [comment]
> > I think it's better if we don't show the panel message for the user with permisssion 'Cannot collaborate' . So user will not confuse why they can see the message panel and 'Send' button. @IanMayo How do you think?
> 
> No, there is logic in it - some roles can submit messages, but not interact with them afterwards.

If it works as our expected. I think we can close #2940

**Comment by IanMayo** [comment]
This is fixed in the PR for #2942

**Comment by Tristina1788** [comment]
> This is fixed in the PR for #2942

Checked on '2941_send_collab_message', I can see the message on the board of Collab channel as expected.

![image](https://github.com/serge-web/serge/assets/107697044/6f2b95ed-58dd-4f4b-8f2b-892e4353c33f)

**Comment by IanMayo** [comment]
Fixed in #2942
