### ISSUE TITLE
Shape is disappeared after changes force to 'f-green' or 'Umpire'

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2953]
## 🐞 Bug description
Shape is dissapeared after changes force to 'f-green' or 'Umpire'

## 🔢 Steps to Reproduce
1. Play game 'TestHat' with role Red - Red2
2. Update property 'Force' of a shape item to 'f-green' or 'Umpire'
3. Notice the item is disappeared

![image](https://github.com/serge-web/serge/assets/107697044/1de5b8a9-3837-4796-9632-a1a09314c0e7)

## ⚙️ Expected behavior
- Change force will change color of item and the item still show on game play

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/a48e5438-3b81-41df-8125-4dbea91f9082

## 💻 System information
- Browser : Chrome

**Comment by IanMayo** [comment]
I'm pretty sure this is expected behaviour @Tristina1788 

The way the wargame has been configured, red players can't see green or umpire features:
![image](https://github.com/serge-web/serge/assets/1108513/9af365e8-0a8a-421b-8e72-20bc0b935cbf)

**Comment by Tristina1788** [comment]
> I'm pretty sure this is expected behaviour @Tristina1788
> 
> The way the wargame has been configured, red players can't see green or umpire features: ![image](https://private-user-images.githubusercontent.com/1108513/333223187-9af365e8-0a8a-421b-8e72-20bc0b935cbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDI3NTAsIm5iZiI6MTcxNjU0MjQ1MCwicGF0aCI6Ii8xMTA4NTEzLzMzMzIyMzE4Ny05YWYzNjVlOC0wYThhLTQyMWItOGU3Mi0yMGJjMGI5MzVjYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMDkyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI0ZGMxNTIwMzBiZThkZmZlOTBjNzdkNTYyNzZiNjQ1NDYyMzM1ZmJjN2E2YmFkOTYxMTczZmZlMWI1Yjk3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c0ejvMjNktMHFI9ddobLvZfvfeD_4v3l2YMzipcyMoc)

As your explanation, I think it's not issue any more. So we can close it.
