### ISSUE TITLE
TestHat : user 'Umpire' should not see collab channel 'BlueWA'

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2959]
## 🐞 Bug description
TestHat : user 'Umpire' should not see collab channel 'BlueWA'

## 🔢 Steps to Reproduce
1. Go to admin page of 'TestHat' game
2. Click on channel and select 'BlueWA'
3. Notice no permission for 'Umpire' user 
![image](https://github.com/serge-web/serge/assets/107697044/5f17e6c3-c4ec-4526-bf78-4ef1ab962680)

5. Login gam play with user Umpire - Game Designer
6. Notice this user still can see all infors on channel 'BlueWA'

![image](https://github.com/serge-web/serge/assets/107697044/5f24351c-2dcf-4c10-b0e8-c3f1273a550a)

## ⚙️ Expected behavior
User don't have permission on Collab channel should not enable to see this channel

## 💻 System information

 - Browser : Chrome

**Comment by IanMayo** [comment]
This is intended behaviour @Tristina1788 , since in the Admin Pages, the `Game Designer` role has `Game Designer` ticked, so they see all data, everywhere:
![image](https://github.com/serge-web/serge/assets/1108513/adfcaa23-e84d-46cc-afe1-947487405f2c)
