### ISSUE TITLE
Message is auto clear after some seconds

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2962]
## 🐞 Bug description
Message is auto clear after some seconds.   

**Note:** this issue only occurs in branches with the new template strategy, such as for PR #2897 

## 🔢 Steps to Reproduce
1. Go to admin page
2. Create new template

![image](https://github.com/serge-web/serge/assets/107697044/9b63c6be-9034-46b2-aca7-006415b47d3d)

3. Using this template for a channel

![image](https://github.com/serge-web/serge/assets/107697044/7224100f-8228-4dc4-9294-c2d3371716c4)

4. Playgame on new channel
5. Input content on the input form and wait some seconds
6. Notice the content is auto clear

https://github.com/serge-web/serge/assets/107697044/1106b6bd-f6e4-4c27-ab25-def3ecd2f4e3

## ⚙️ Expected behavior
Message is not auto clear 

## 💻 System information
 - Browser : Chrome

**Comment by IanMayo** [comment]
Note: while I saw this happen (I _think_ it was on the heartbeat), it wasn't always reproducible. 

Aah, I was able to make the form clear itself by saving the wargame from admin pages in a different tab.

**Comment by Tristina1788** [comment]
> to make the form clear itself by saving the wargame from admin pages in a different t

Currently I only reproduce it on branch '2892_Edit_templates_in_admin_pages' . And It happens when the first time input on text message. (It means when the text is clear, you input again and the issue will not happen, you have to send the message and try to input on new message to reproduce it, or logout and login then input on new message again)

**Comment by IanMayo** [comment]
This is resolved, isn't it @Tristina1788 ?

**Comment by Tristina1788** [comment]
> This is resolved, isn't it @Tristina1788 ?

Yes, that's correct. The issue is fixed.
