### ISSUE TITLE
BlueWA channel should has column 'Sent Date' instead of 'ID'

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2968]
## 🐞 Bug description
BlueWA channel should has column 'Sent Date' instead of 'ID'

## 🔢 Steps to Reproduce
1. Playing game with any role ( ex : Umpire - Game designer)
2. Click on 'Blue WA' channel
3. Notice the column 'ID', it should be 'Sent Date'

![image](https://github.com/serge-web/serge/assets/107697044/3a86f6a1-0427-4c88-9a5b-093d07ebb27b)

## ⚙️ Expected behavior
BlueWA channel should has column 'Sent Date' instead of 'ID'

## 💻 System information
 - Browser : Chrome

**Comment by IanMayo** [comment]
Hello @Tristina1788 - I'm pretty sure CouchDb uses the current date-time to generate unique IDs.  That's what you're seeing, ok?

**Comment by Tristina1788** [comment]
> Hello @Tristina1788 - I'm pretty sure CouchDb uses the current date-time to generate unique IDs. That's what you're seeing, ok?

Yes, If you think it's working as your expected. So it's ok to me.
