### ISSUE TITLE
The message which is sent should not have 'Send Message' and 'Cancel' Button

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2972]
## 🐞 Bug description
The message which is sent ,have 'Send Message' and 'Cancel' Button. 
Note : This issue only happens on branch '2892_Edit_templates_in_admin_pages'

## 🔢 Steps to Reproduce
1. Playing game with any role ( ex : Umpire - Game designer)
2. Click on 'Blue WA' channel
3. Click on some message in collab board
4. Notice these message also have 'Send Message' and 'Cancel' Button although we can't use these button

![image](https://github.com/serge-web/serge/assets/107697044/26e2f51d-0b2e-46aa-ab2d-e23dad7ac47a)

## ⚙️ Expected behavior
The message which is sent should not have 'Send Message' and 'Cancel' Button

## 🖥️ Screencast

https://github.com/serge-web/serge/assets/107697044/21c5443d-5ef7-442e-8b28-b1bb0cc023cd

## 💻 System information
- Browser : Chrome

**Comment by IanMayo** [comment]
Is this still an issue @Tristina1788 ?

**Comment by Tristina1788** [comment]
> Is this still an issue @Tristina1788 ?

It's fixed.  'Cancel' and 'Send Message' is removed from admin and user play as expected.

![image](https://github.com/serge-web/serge/assets/107697044/6062eb08-4dab-4a7c-9f5e-a3428ddf692c)

![image](https://github.com/serge-web/serge/assets/107697044/e19eb48b-6c12-48a1-8f11-769d057c86e7)
