### ISSUE TITLE
Control which phases a collab participant can interact

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2979]
For most of the time, the collab channel participation will be during the Planning Phase.

Where collab channel messages are generated by adjudications  during the adjudication phase, we should be able to prevent players from editing/interacting with them.

Introduce new attribute to the Collab Participant record type, which lists the phases that this participant has the `action` buttons visible.  For backwards compatibility (and ease of use), if the fields is empty then the participant can interact in all phases.

* [x] Update data definitions
* [x] Reflect data definitions in Collab Channel UI for player
* [x] Verify implementation via StoryBook
* [x] Update admin page to reflect new attribute

**Update:** ok, I've done the early steps for this.  We now just need the  `admin` page for `collab channels` to allow zero or more phases to be specified for an participant.

Here is the current UI. This will require a new multi-select drop-down containing `planning` and `adjudication` (to the right of `See live updates` .  Zero or more can be selected.
![image](https://github.com/serge-web/serge/assets/1108513/19096802-9614-4218-93e9-a7446ca3357a)

Here is the data change that this control relates to:
![image](https://github.com/serge-web/serge/assets/1108513/cc249a86-4557-49b0-80e7-36f5250fc51f)

The PR for this issue contains a branch that can be used to complete development.

**Comment by lebaphi** [comment]
should we close it @IanMayo ?

**Comment by IanMayo** [comment]
Now complete.
