### ISSUE TITLE
Core mapping - the created items are disapeared after logout gameplay

### ISSUE THREAD

**Issue by Tristina1788** [serge-web/serge#2992]
## 🐞 Bug description
The created items are dissapeared after logout gameplay

## 🔢 Steps to Reproduce

1. Go to gameplay TestHAT
2. Login with user can create new item (Example : Red - Red2)
3. Go to  'Core Mapping' Channel 
4. Create some new items
5. Logout gameplay
6. Login again
7. From 'Core mapping' channel , notice the created items are dissapeared

Notice : I checked some merges to develop and found that it happens from the merge '[Sometimes_message_shows_in_wrong_turn](https://github.com/serge-web/serge/commit/a03e7148f6e332b025caa270b97c8d05f6f26a51)'

https://github.com/serge-web/serge/assets/107697044/8a3b76a1-baa2-47f4-9812-fdbfdc1814fe

## ⚙️ Expected behavior
the created items are disapeared after logout gameplay

## 💻 System information
 - Browser : Chrome

**Comment by IanMayo** [comment]
Great, thanks @Tristina1788

**Comment by Tristina1788** [comment]
@IanMayo  It works as expected now. So we can close this ticket.

**Comment by IanMayo** [comment]
Fixed in #2993
