### ISSUE TITLE
Separate MapControls `AddRemove` property into `Add` and `Remove`

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#2996]
We currently manage which controls to provide the player depending on the value of `canAddRemove`.

But, the value of this property is updated when an item is selected.

That logic is slightly wrong. The ability to `remove` is sensitive to the selected item.  But, the ability to `add` should not be.  That is probably why @Tristina1788 is finding she cannot add new `green` items, [here](https://github.com/serge-web/serge/pull/2970#issuecomment-2230622794)

So, we should separate the `MapControls` prop titled `canAddRemove` into `canAdd` and `canRemove`.  The first just checks if this player has permission to `AddRemove` for their own force.  The second is updated on a new `selectedFeature` - as in the existing logic.

This work should be done in a branch off `core-mapping-admin`

**Comment by lebaphi** [comment]
I think we can close it @IanMayo
