### ISSUE TITLE
Cannot delete shapes

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#3000]
In our current test wargame, the Game Designer has lots of mapping permissions.

When playing as Game Designer, with the map in `Remove Layers` mode it is possible to delete MilSymbols, but not Shapes.

Instead of being deleted, the shapes become `selected`:

Hmm,  I've just tried to record a video, but the error seems intermittent.  Could you please investigate further @Tristina1788 ?

![screencast](https://i.gyazo.com/47f50dd00e12ec0b1dedb0ac58ca30e0.gif)

**Comment by Tristina1788** [comment]
@IanMayo Currently we only enable to delete one item for one time although the 'Remove' tool is still highlight as ticket ['Delete Layer' function should enable to delete multi layers](https://github.com/serge-web/serge/issues/2794)

**Comment by IanMayo** [comment]
Close. Duplicate of #2794
