### ISSUE TITLE
Bring existing SCSS in line with new linting rules

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#319]
# The issue

In the refactor, we have started following the guidelines provided by [Sass Guidelines](https://sass-guidelin.es/). These rules will enable us to build a stable application regardless of scale. Our current SCSS does not conform to these standards.

# Working through the errors

To get a list of the current failures, you can `cd` into the `themes` package and run `yarn lint`. I would also recommend installing a `stylelint` extension for your code editor.

Many of the rules are self-explanatory, but if you see a rule that isn't obvious, you can search for it here: https://github.com/bjankord/stylelint-config-sass-guidelines, that will tell you how what the actual problem is.

There will be a few occasions where a rule isn't valid in some circumstances, if so then you can disable the rule checking in that block using this:

```css
 /* stylelint-disable */
  color: red; 
  /* stylelint-enable */
```

Please use this very sparingly though.

If you require any additional help, please don't hesitate to contact me.

# 🚨🚨Important information🚨🚨

Please do not branch from (or merge back into) `develop` for this ticket, all work must be branched from `feature/serge-refactor`

**Comment by IanMayo** [comment]
Heri sorted this earlier in the year in #320 and #321
