### ISSUE TITLE
Refactor game admin channel component into component library

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#333]
* [ ] Pull Serge GameAdmin styles into StoryBook component
* [ ] User StoryBook GameAdmin component in main Serge app

**Comment by IanMayo** [comment]
@foxleigh81 provided a first version of this control in PR #429 

But, it lacks Serge styling.  See here: https://serge-review.herokuapp.com/storybook/?path=/story/local-gameadmin--default

@Lilit - are you able to think of a way to pull the Serge styles into StoryBook?  

There are a couple of instances where the storybook styling is different to Serge, which makes things more difficult to review.

But, if this isn't easy - just say, and we can work around it.

**Comment by IanMayo** [comment]
Aah, @lilitkarapetyan - I've found another remaining part of this issue.

The Serge client is still using the legacy (original) Game Admin control, not the new component.

Could you switch the Serge client to use the new Component please?

**Comment by IanMayo** [comment]
Handled separately.
