### ISSUE TITLE
Build component: Forces list

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#355]
## 💬 Brief description of feature

Build the organism component 'Forces list'

This task includes the creation of an new version of the `Planning Orders` panel. Here's the existing version:
![image](https://user-images.githubusercontent.com/1108513/82218122-505e3100-9913-11ea-9b45-fdf519cd2f3b.png)

The new panel should receive/listen for data in the same way as the existing one.

The "planned routes" data can be found in the new `RouteStore` state object within `Mapping` context (as being developed in this branch: `feature/426_route_management` .

To access this mapping context, it _appears_ that the Outline form will have to be a child element within the `Mapping` react element.

## ☑️ Acceptance criteria

- [ ] Component UI built
- [ ] Component accepts data
- [ ] Icons shown for platforms, with icon matching the one display in `mapping\with marker` story. Clicking on an icon opens the `Plan Route` form. The icons listed are for all `Forces` that the player can control (this is all the contents of the `RouteStore` object)
- [ ] Second tab shows icons for other visible platforms. Clicking on a icon opens the `Perceptions` form
- [ ] Story exists in storybook for just this panel (still under `mapping` block of Storybook)
- [ ] `stories` includes button that submits a new planned route, to show panel updating
- [ ] Tests pass

## 📐 Designs / Wireframes

Design visible here: https://docs.google.com/document/d/1lKQ_aZof6vNNm8atmxnqDoW6m76FVrdLvxA7DzlyuGw/edit

More detailed designs here:

![SERGE-player view - SOW - platform details panel](https://user-images.githubusercontent.com/1108513/83125568-9ebbbe80-a0cf-11ea-9879-90da68bcc952.png)

![SERGE-player view - other visible platforms panel](https://user-images.githubusercontent.com/1108513/83125584-a2e7dc00-a0cf-11ea-9272-165fb609fcd7.png)

**Comment by IanMayo** [comment]
Done.
