### ISSUE TITLE
Build component: Hex-grid

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#357]
## 💬 Brief description of feature

Build the organism component 'Hex grid'

## ☑️ Acceptance criteria

- [ ] Integrates with `mapping` component
- [ ] Component UI built
- [ ] Component accepts data
- [ ] Story exists in storybook
- [ ] Tests pass

## 📐 Designs / Wireframes

Design visible here: https://docs.google.com/document/d/1lKQ_aZof6vNNm8atmxnqDoW6m76FVrdLvxA7DzlyuGw/edit

**Comment by IanMayo** [comment]
Ok. Some early progress in the PR.  I could do with some more help please.  Here's an example of creating Leaflet polygons:
https://github.com/fullhdpixel/react-leaflet-distance-marker/blob/master/src/DistanceMarkers.js

I could do with support in how I get the `map` element down into my component (pass the `this` from the `Mapping` parent class?).  

I could also do with support in if/how/where I would call `L.polyline` as done at line 10 in the above example/

**Comment by foxleigh81** [comment]
Do you need to actually reference the `Map` element or do you just want something to happen inside it? If it's the latter, take a look at the story file inside the `Mapping` component for an example.

If it's the former, I *think* this example will help: https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/events.js

I think this line is what you are possibly looking for: `mapRef = createRef<Map>()` Only use `Mapping` instead of `Map` as that's where the map is initialised, you may need to extend the mapping component by passing extra parameters in.

**Comment by IanMayo** [comment]
Fixed in #364
