### ISSUE TITLE
TypeScript config not working as expected

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#363]
## 🐞 Bug description
The TypeScript configuration is causing errors, here is an example of the error:

```
TS6059: File '/Users/foxleigh81/dev/serge/packages/config/routes.ts' is not under 'rootDir' '/Users/foxleigh81/dev/serge/packages/components/src'. 'rootDir' is expected to contain all source files.
```

I believe I've set up the `tsconfig.json` files incorrectly but I cannot find an obvious answer to this. My lack of experience with TypeScript means that this is probably a problem better suited to someone else with more knowledge.

*Update:* I've implemented a workaround which prevents this error from occurring, however, that workaround causes the `build` folder in `packages/components/` to no longer be correct. 

It currently outputs like this:

![Screenshot 2020-04-17 10 02 59](https://user-images.githubusercontent.com/151028/79552279-bcd6dd80-8092-11ea-9bcb-c91f50c88735.png)

It should look like this:

![Screenshot 2020-04-17 10 03 22](https://user-images.githubusercontent.com/151028/79552321-c8c29f80-8092-11ea-8b35-665d8ac83771.png)

Each folder in the `local` directory should contain the generated typescript files and all of the static assets (`scss` files, etc...)

## 🔢 Steps to Reproduce

1. Open command line
2. Checkout a copy of the branch: `feature/328-mapping-refactor`
3. Run `yarn install` in the root
4. Run `cd packages/components && yarn storybook`

## ⚙️ Expected behaviour

The storybook project will build and open in your browser and the project will build successfully when typing `yarn build`

## 💻 System information

 - Operating System: Mac OS 10.15.4
 - Command-line tool: iTerm3

## Notes

- Once a fix is made, please PR it back into `feature/328-mapping-refactor` and NOT `develop`

**Comment by IanMayo** [comment]
@foxleigh81 - is this still an issue?

**Comment by IanMayo** [comment]
Closing. Create new issue if it returns.
