### ISSUE TITLE
Common MapControls in new ReactComponents

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#388]
## 📖 User Story

As a Serge player I wish to control the map via the MappingToolbar

In the _legacy_ mapping system, the toolbar elements are created in `\packages\client\src\Components\Mapping\index.jsx`

We need to refactor them into our new declarative approach.

For the basic controls (zoom-in, zoom-out, home) these can be declared as permanent children of the `Mapping` control.

Note: this issue does not include the `View as` buttons that are displayed for White Force: https://serge-review.herokuapp.com/?wargame=wargame-k5xyxas9&access=p2311

### Controls to use
@foxleigh81 has requested that the controls use the ButtonGroup controls we have in StoryBook:
https://deploy-preview-387--serge-storybook.netlify.app/?path=/story/vendor-buttongroup--icons

But, @lilitkarapetyan - if you find yourself fighting against Leaflet, then it's acceptable to use Leaflet controls.

## ☑️ Acceptance criteria

A toolbar is displayed for the map control which includes: zoom-in, home (fit-to-window) and zoom-out.

The toolbar should be present in all of the StoryBook Mapping components.

## 📐 Designs / Wireframes

![image](https://user-images.githubusercontent.com/1108513/80089932-a16a4780-8556-11ea-94cb-b460376c00a3.png)

**Comment by foxleigh81** [comment]
> But, @lilitkarapetyan - if you find yourself fighting against Leaflet, then it's acceptable to use Leaflet controls.

Yup, the `ButtonGroup` component is preferred but it's not essential. If it is too hard to implement using this then the leaflet defaults is fine.

**Comment by IanMayo** [comment]
Closed in #448
