### ISSUE TITLE
Admin Page - only show observer/insights for White forces

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#456]
When editing a Role in the Game Admin pages, we should only show "Observer" or "Can view insights" checkboxes for members of Umpire force.

**Comment by IanMayo** [comment]
Heena asked:
> We need to show only one checkbox either it can be observer/insights for White forces but on which base we need to show one checkbox currently there is not any condition applied

This is how the `edit role` dialog looks for a member of `White` force:
![image](https://user-images.githubusercontent.com/1108513/95432701-ea685980-0946-11eb-9ee4-e04742b73cd1.png)

Here is how it looks for a member of `Blue` force:
![image](https://user-images.githubusercontent.com/1108513/95432763-fd7b2980-0946-11eb-874f-3b8b64e95406.png)

But, those two check-boxes only apply to members of `White` force.  

So, the relevant check-boxes should only be displayed if `selectedForce === UMPIRE_FORCE`

**Comment by loveheenavasu** [comment]
@IanMayo we need to show those two checkboxes only if selectedForce === White and those
checkboxes remain hidden for other options right ?

**Comment by IanMayo** [comment]
Yes, that's correct.

**Comment by loveheenavasu** [comment]
If we need to show those checkboxes if selectedForce === White then what does this line means
"So, the relevant check-boxes should only be displayed if selectedForce === UMPIRE_FORCE"

**Comment by IanMayo** [comment]
Sorry, my mistake.  The constant has the value of `umpire`, not `white`.

![image](https://user-images.githubusercontent.com/1108513/95578158-515f3e80-0a2b-11eb-91e2-86397bbfda0a.png)

It's the constant that you should be referring to in the code. (in `consts.js`)

So, you need `selectedForce === UMPIRE_FORCE`

The confusion is that in wargames, the UMPIRE force is also called the WHITE force, they're interchangeable.

**Comment by loveheenavasu** [comment]
so we need to change UMPIRE_FORCE = "White" in cont.js file right ?

**Comment by IanMayo** [comment]
No, we don't need to change the constant. You just need to use the constant in your React code.

**Comment by loveheenavasu** [comment]
okay got it

**Comment by IanMayo** [comment]
Great. Please submit a separate Pull Request for each issue you're working on.

**Comment by IanMayo** [comment]
Done.
