### ISSUE TITLE
Task Group interactions

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#459]
As a ***player*** I wish to ***adjust membership of a group*** in order to ***control my assets***.

Céline has come up with the interactions for groups of assets.  There are two types of group:
* **Comprising** this is a set of assets that are behaving as a group (also called a Task Group)
* **Hosting** this is a set of assets that are carried by another asset (such as helicopter & UAV on a ship)

These interactions are all within the "My Forces" view of the WorldState panel. There are interactions that apply to both types of group.

We need to add these interactions:
1. If an asset is in either type of group, it can be dragged/dropped to the top level in the WorldState panel, meaning it has left that grouping.
2. If an asset anywhere is drag/dropped onto a group, they become a child of that group
3. If an asset anywhere is drag/dropped onto an asset at the top level, they will become children of a new `Task Group` asset.
4. When a Task Group with zero children is selected, a `Delete` button is shown at the top of the the `Plan Orders` panel.

@lilitkarapetyan - I'm happy to implement the backend processing for the above, I just need a callback to `mapping` with the event.  I suggest these callbacks:

* detach(groupid, assetid) `for when an asset is dragged out of a group`
* join(groupid, assetid) `for when an asset is dragged into a group`
* combine(uniqid, uniqid) `for when one asset is dropped onto another`

**Note:** there is a complication to interaction 3) above.  When one asset is dragged onto another, we don't actually know if player is trying to combine them into a group (comprising), or if the player wants to put the dragged asset onto the drop target (hosting).  We will solve this problem in this way:
* if the drop target is a Task Group (platform-type) we know it is "Comprising", and we just let asset get dropped onto it.
* if the drop target is not a task group, we will insert a blank line beneath it, to act as the "landing pad" for "hosting", but dropping it onto the asset itself will be interpreted as "create new task group".  Sample below:
![image](https://user-images.githubusercontent.com/1108513/86247195-0a4bec80-bba4-11ea-8802-088562d2a817.png)

**Comment by clenoble** [comment]
@IanMayo I made 2 short clips to show the difference between join and combine interactions: 
[Join interaction](https://youtu.be/chbBCxbtp1c)
[Combine interaction](https://youtu.be/aqxnV_acRjU)

**Comment by clenoble** [comment]
Here is the mockup to delete an empty task group: 
![Empty task group](https://user-images.githubusercontent.com/22282418/86367751-a34e3680-bc7c-11ea-8a87-5a93a5e5cd9f.png)

**Comment by IanMayo** [comment]
Done.
