### ISSUE TITLE
UX - should planning form disappear during planning?

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#467]
Here is the planning form, as used for planning the route of an aircraft:
![screencast](https://i.gyazo.com/8f57704bb3c5e789002b8297dfcd856e.gif)

Note: the map is zoomed out further than normal, so that planning marker isn't obscured by the planning form.

There would be more space available for the planning to happen if the planning dialog disappeared once "Plan Route" was clicked.

But, we need some interaction to make the form return, in case the player wants to switch to another state (mobile or static).

It doesn't seem right for the form to appear once the next leg has been dragged, since the form may obscure the planning marker.

I guess we could open it up if the user clicked on the planning marker (but not the asset icon, since that would un-select the asset).

**Comment by clenoble** [comment]
@IanMayo I played with it a little and here is what I suggest: 

- to un-select the asset after planning a number of legs, the player clicks anywhere else on the map but the marker.
- to open the planning form again while the asset is selected, the players clicks on the marker.
- to re-select the asset after un-selecting it, the player can click on the marker or on the asset name in the ORDERS panel, in both cases, the planning form opens again.

**Comment by clenoble** [comment]
When I say marker, I mean the pin that marks future locations. To re-open the planning form, the player could also click on the platform symbol itself at the current location.

**Comment by IanMayo** [comment]
> to un-select the asset after planning a number of legs, the player clicks anywhere else on the map but the marker.

Currently, the planning for an asset is stopped when another asset is selected.  I'm nervous that the player may get "caught out" by clicking on another area of the map.

I'll try to make a trial.

Oh, and @clenoble  - preview available here (without click on map to clear)

**Comment by IanMayo** [comment]
@clenoble  - I've implemented the "click on clear space to deselect current asset", and it works quite well:
https://serge-review-feature-46-du2iu1.herokuapp.com/?wargame=wargame-kc226hoa&access=p5543

(contrary to what I predicted 🤣  )

**Comment by clenoble** [comment]
@IanMayo Great! 
A small graphic change would help: only the selected platform should have a shadow. Platforms that are not selected should not have a shadow, or a very limited, barely visible one. That would help also differentiate the selected platform from the other ones.

**Comment by IanMayo** [comment]
I hadn't even noticed the shadow.  I'll ping you when it's updated.

**Comment by IanMayo** [comment]
Yes, tit disappears.
