### ISSUE TITLE
Make allowable cells more vivid

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#471]
The allowable cells don't stand out very much.

The legacy mapping version stood out more.

Talk to @celine about look & feel.

**Comment by clenoble** [comment]
@IanMayo What about using the platform color slightly transparent?
This would also help the user make sure they are moving the right platform when several platform are stacked in the same cell
![Screenshot_2020-07-09 Figma](https://user-images.githubusercontent.com/22282418/87042190-9dfc6900-c1f3-11ea-9241-a18e45e53b2c.png)

**Comment by IanMayo** [comment]
Done.
