### ISSUE TITLE
Transition to Mono Repo

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#5]
## User Story
As a _maintainer_ I wish to _adopt a MonoRepo architecture_ in order to  _have a reliable and robust repo, and introduce opportunities for a micro-services architecture._

## Background
We've actually got two applications in our repo:  a NodeJS backend, and a ReactJS front-end.  In production, the latter is statically served by the former.

This requires us to have two npm libraries, and two build processes.

Adoption of a MonoRepo should simplify the above architecture.

It is expected that this task will use a snapshot of the current Serge code.

**Comment by foxleigh81** [comment]
This is done but I'm leaving it in progress for now as I consider tickets #6 and #7 to be children of this one.

**Comment by foxleigh81** [comment]
Glo autoclosed it with the PR which is fine I guess. It's just spiritually still 'in progress' :)

**Comment by IanMayo** [comment]
Interesting. The GitHub issue is still open.

**Comment by IanMayo** [comment]
Done.
