### ISSUE TITLE
Compact display of visible forces

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#552]
The Adjudication panel is quite large.   The list of forces that an asset is visible to takes up more space than necessary.

![image](https://user-images.githubusercontent.com/1108513/97318612-f53a4e00-1863-11eb-8089-5ac68ece488f.png)

The list of checkboxes is built from the `RCB` component.

I've introduced a `compact` boolean prop that ties to display the choices in a more compact layout.  I've managed to remove the text labels, but wasn't able to get the optional `row` prop to show the radio buttons in a horizontal line.  This is as far as I got:

![image](https://user-images.githubusercontent.com/1108513/97318819-2d419100-1864-11eb-971e-f8fbc8684f65.png)

This issue is to modify the `RCB` component so that the checkboxes are displayed in a horizontal line when the `compact` flag is true.

It's probably best to fix the issue in this branch: feature/518_submit_adjudicate_plans

**Comment by zukilover** [comment]
It looks like the bug has been fixed.
