### ISSUE TITLE
Minor - UI to add "Special" channels.

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#605]
Steps to reproduce:
- at home page, go into Admin pages (see below)
- select any wargame
- go to `channels` tab
- here we need UI to create a new `channel` with one of two specific titles

Here is an example of a set of channels: https://github.com/serge-web/serge/blob/develop/packages/mocks/game-channels.mock.ts

Note: Admin pages is accessed via "person" icon near top-right:
![image](https://user-images.githubusercontent.com/1108513/116691508-c9cf2200-a9b2-11eb-8476-1d5e87ee6ae5.png)

We have two "Special" channels:
- Mapping - for players that see/use the mapping control
- RFI Status - for players that will be managing/tracking RFIs.

The Serge application gives specific UI for these channels when it the current role is in that channel.  It does this by checking if the name matches one of these two strings:
![image](https://user-images.githubusercontent.com/1108513/117003513-dae2a080-acdc-11eb-846e-3a1f8b01e48a.png)

Note: constants for the two special channels are in `consts.js` file.

These channels are currently generated by creating a Channel with the exact correct title.  But, it is fragile to expect the Game Designer to enter those specific strings for the new channel.

It would be more robust for Game Designers to be able to indicate if they're creating a "normal" channel or one of these "special" ones.  

Just like with "normal" channels, in these "Special" channels Roles get added (to indicate who sees them). But, for the "special" channels but the Game Designer does not indicate which messages (templates) get sent - so the Admin page for these channels could be slightly simpler.
![image](https://user-images.githubusercontent.com/1108513/117004631-2f3a5000-acde-11eb-89eb-e75097148b91.png)

Somehow - if we have one of these special channels we should hide the `templates` column.

_Maybe_ the `Add Channel` would become button with drop-down that lets the designer add a "Special" channel instead of a standard channel.
![image](https://user-images.githubusercontent.com/1108513/108085011-c6432480-706c-11eb-949f-1df91170f6b8.png)

**Comment by sandro768** [comment]
`These channels are currently generated by creating a Channel with the exact correct title.`
This sentence confuses me. Channels are created from the admin page by clicking `ADD CHANNEL`, aren't they?

You've mentioned that `Roles` distinguish special channels from regular ones.
I see 3 channels and all of them seem to have roles. Are they all special?
![image](https://user-images.githubusercontent.com/24352108/116874381-c6cd6f00-ac08-11eb-8d51-261af3bc1451.png)

**Comment by IanMayo** [comment]
(it's a holiday here today, I'll get back to you tomorrow, @sandro768 )

**Comment by IanMayo** [comment]
>> These channels are currently generated by creating a Channel with the exact correct title.
> This sentence confuses me. Channels are created from the admin page by clicking ADD CHANNEL, aren't they?

Yes. 'ADD CHANNEL', then proviide a specific channel name to get the special channel displayed.

> You've mentioned that Roles distinguish special channels from regular ones.
> I see 3 channels and all of them seem to have roles. Are they all special?

No, it's the specific channel name/title that distinguishes them from regular ones.

@sandro768 - I've also updated the original description.  Hopefully it all makes sense - but I'm happy to help out further if necessary.

**Comment by sanjayradadiya** [comment]
Do we need to maintain specific flag for channel type or something ?

**Comment by IanMayo** [comment]
No. The game looks out for channels called 'RFIs' or 'Mapping' (as in the above code).  But, I don't want to rely on the Game Designer remembering to enter the correct string.  So, we're just providing command buttons to create channels - using these specific names
