### ISSUE TITLE
Errors during `yarn develop`

### ISSUE THREAD

**Issue by sandro768** [serge-web/serge#678]
🐞 The development server fails to compile

 🖥️ Screenshots
![image](https://user-images.githubusercontent.com/24352108/115278494-9096e680-a156-11eb-87c3-6c99d97fa006.png)

**Comment by IanMayo** [comment]
That's a strange one. 

Will be on it in the morning.

**Comment by IanMayo** [comment]
@sandro768  - could you remind me/us of the command you're running which produces that error, and branch that you're in please?

**Comment by sandro768** [comment]
Branch - develop
Command - yarn develop

**Comment by IanMayo** [comment]
Aah, sorry - I didn't spot this earlier.  Could you re-run `yarn build` first?

We need to run that before `yarn develop` (says the man who barely understands the build process ;-) ).

**Comment by sandro768** [comment]
`yarn build` fixes it. Maybe we need to update the readme

**Comment by IanMayo** [comment]
Sure - how about submitting a PR that fixes the readme? (you can do it from GitHub website - just open the `readme.md` and click on the `edit` toolbar button).  You can include `fixes #678` in the PR description.  When we close it, it will close this too.

**Comment by IanMayo** [comment]
Readme updated.
![image](https://user-images.githubusercontent.com/1108513/115541879-8a5c5380-a297-11eb-8e7a-04dc7746c7e1.png)
