### ISSUE TITLE
Re-install pre-commit hook

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#692]
When I moved to a new PC I lost the pre-commit hook.

The pre-commit hook introduced a delay of a few minutes while the full test-suite ran, but it did help to ensure quality.

I _think_ it has to be installed per-user.

We should document how to install it.

Hmm, alternatively, we could run the full suite it as a test in the PR, then it's running on GitHub hardware, not ours.

Aah, running the test in the PR via GitHub actions is a good step. We could also run pkg-build, and attach the executables to the PR.

**Comment by sanjayradadiya** [comment]
Yeah, github action would be nice

**Comment by IanMayo** [comment]
The `Git Actions` part of this is complete.

For now, I propose we just have the post-commit unit tests in Git Actions. This means the `git push` runs more quickly.  The Git-Action is now `required` for `develop` and `master` - which will ensure code quality.
