### ISSUE TITLE
Adopt serge favicon

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#693]
We have a logo for Serge: 
![image](https://user-images.githubusercontent.com/1108513/116117069-c0dd0880-a6b3-11eb-850d-ba3f7a54eb51.png)

We should use it for the favicon. I guess we're currently using the one from `create-react-app`.

We need to convert this png to a 16px favicon:
https://github.com/serge-web/serge/blob/develop/packages/client/public/serge-logo.png

**Comment by sanjayradadiya** [comment]
Please review this PR
https://github.com/serge-web/serge/pull/699

**Comment by IanMayo** [comment]
Fixed in #699
