### ISSUE TITLE
Packaged serge needs to expose `data` folder at runtime

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#698]
The `data` package contains files that the users may wish to edit/overwrite at runtime.

That's easy enough in a cloned repo where the `packages\data` folder can be easily found. But, it's not possible for an Serge deployment that has been packaged into an executable with `pkg`.

So, when the packaged Serge is run for the first time it should create (and use) the `data` sub-folder.

When run on other occasions, it should not overwrite this folder, since it may contain user data.

**Comment by lebaphi** [comment]
done

**Comment by IanMayo** [comment]
Tested by opening `TG-Initialised` wargame & verifying presence of large body of Type:3 (deep) cells.  Then, change all `type:3` to  `type:2` in 6k-cells json datafile.  Quit serge & restart.  No deep water cells present - indicating the modified file is being used, and that the it isn't being overwritten for the new game.
