### ISSUE TITLE
Introduce coding standards & build pipeline

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#7]
- [x] Introduce coding standards (including config instructions for IDEs in use)
- [x] Implement GitHub PR process (with automated reviews)
- [x] Implement CI/deploy to Heroku (or other)

**Comment by foxleigh81** [comment]
Splitting deployment out into separate ticket as this should be done after we have the builds passing correctly.

**Comment by IanMayo** [comment]
Done.
