### ISSUE TITLE
Produce list of roles & passwords

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#748]
During development, we allow anyone to log into any role, by clicking on the list of roles on the left-hand side, which injects the password.

But, during game-play, this list of roles is hidden, and users have to enter a password/passcode to get in.

The game organisers need to give each team a list of roles & passwords.

This is a pain to create.  It would be easier if they could get a list of names/passwords from the admin page.

Add a new item to the context menu on the wargame list.  This will be `Export passcodes`. 

![image](https://user-images.githubusercontent.com/1108513/119265509-f1df2900-bbde-11eb-8ae1-2e8abc412e0f.png)

It will produce a CSV file breaking down the roles & passcodes by force. The roles in a force will be in alphabetical order.  The output will be something like:

| Force | Role | Passcode |
|-------|------|----------|
| White | Game Control | P2342 |
| White | RFI Mgr | P132 |
| Blue | CO | P34543 |

Note: there is already an `export wargame` item in the menu. It may offer tips on how to do this.

**Comment by sanjayradadiya** [comment]
Export wargame contains same list of passcodes and roles but in different different tabs so that would be helpful.

**Comment by IanMayo** [comment]
This functionality is already present in `Export Forces`, under `Export Wargame`.

**Comment by IanMayo** [comment]
I've just run through this @sanjayradadiya  Here is a sample export:
![image](https://user-images.githubusercontent.com/1108513/119472176-e9ebca00-bd41-11eb-8c6d-97d1ed0b666d.png)


I'm not sure of the order of the columns, but it would be more useful to the users if `Name` and `Password` were the first two columns.
Are you able to re-arrange the order please?

**Comment by sanjayradadiya** [comment]
> I've just run through this @sanjayradadiya Here is a sample export:
> ![image](https://user-images.githubusercontent.com/1108513/119472176-e9ebca00-bd41-11eb-8c6d-97d1ed0b666d.png)
> 
> I'm not sure of the order of the columns, but it would be more useful to the users if `Name` and `Password` were the first two columns.
> Are you able to re-arrange the order please?

Yes, Sure
