### ISSUE TITLE
Make Game Admin panel resizable

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#792]
The Game Control was using a twin monitor setup to view/control the game.

We were able to stretch the window to fill both screens.  But, then the Game Admin panel consumed around 40% of the right-hand screen.

So, we should either switch the Game Admin panel from using a  %age to using a fixed number of pixels, or we should make the Game Admin panel resizable by the user.

The first option is probably the least disruptive.

**Comment by IanMayo** [comment]
For this phase - let's make the Game Admin panel fixed width. For now let's make it 350px wide.

**Comment by sanjayradadiya** [comment]
can you just show me the actual issue In the screenshot here ? @IanMayo

**Comment by IanMayo** [comment]
Sorry Sanjay - I'm on Macox, and I can't make browser span both screens.

I can describe it though.  Since the GameAdmin area on the right-hand of the screen is configured to take a %age of the horizontal space, as we expanded the browser to fill both screens, the GameAdmin wasted a lot of horizontal space. But, if we make it fixed width, then that won't happen.
