### ISSUE TITLE
Introduce uniqid for Role

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#812]
We currently use the role title as the identifier when referred to from channel definitions.

But, the role title can be renamed, which would break the logic.

Instead, when creating a role a persistent uniqid should be generated, which would handle role name changes.

**Update:** Aah, actually we already create a unique id with each role - the passcode/password. So, we could rename `password` to `roleId`

* [x] Change `Role` type by renaming `password` to introduce `RoleId` (`role.d.ts`)
* [x] Change to `Channels` page, to store roleId for channel participations, rather than role name (but still display human-readable name in UI).  
* [x] Change to welcome page, to work with role-id values rather than role name 
* [x] Identify locations where `role-name` still used, and work through them.   One will be the `reducer` than handles new wargame.  It will have to retrieve the role data for the current user, then set `observer`, `canSubmitOrders`, `isRFIManager`.

**Comment by IanMayo** [comment]
@lebaphi  said:
> so how can we deal with the legacy roles?
> it does not include the roleId

@ian said:
> Sure. I suggest we use a method: getRole(). We pass it the forces plus the force and role-name and
>  role-id. If there > is a role-id, we retrieve the Role from Forces. If there isn't, we use force and 
> role-name and use them to get the Role from `Forces.
> The method would sit in helpers package.
> Note: for the second scenario, we need to use force and role, since CO may be present in multiple forces.

But, we would not use the helper each time we needed to get the role details.   I suggest it's neater to update the `PlayerUIState` when the wargame/force/role are updated.  Then we only handle it in onnce.

Does that sound right @sanjayradadiya .  Can you identify where we should put this logic please?

**Comment by sanjayradadiya** [comment]
Sure, I will check and update here

**Comment by IanMayo** [comment]
@lebaphi  said:
> currently, the selectedRole is the role name, and we use it to find the role (in the selected forces) somewhere in the code, I just wonder why we don't store the selectedRole as the role object from the beginning, so we will reduce to find the role by role name or role id also?

Yes - that's exactly what I was thinking of.  Is that right @sanjayradadiya ?

**Comment by lebaphi** [comment]
> @lebaphi said:
> 
> > currently, the selectedRole is the role name, and we use it to find the role (in the selected forces) somewhere in the code, I just wonder why we don't store the selectedRole as the role object from the beginning, so we will reduce to find the role by role name or role id also?
> 
> Yes - that's exactly what I was thinking of. Is that right @sanjayradadiya ?

if this is okay, I will go with it. Because of adding the `roleId`, we need to change a lot of files and need a solution to deal with the legacy roles. By storing a role object from the begining, I think we don't need to add a roleId 🤔

**Comment by sanjayradadiya** [comment]
> > @lebaphi said:
> > > currently, the selectedRole is the role name, and we use it to find the role (in the selected forces) somewhere in the code, I just wonder why we don't store the selectedRole as the role object from the beginning, so we will reduce to find the role by role name or role id also?
> > 
> > 
> > Yes - that's exactly what I was thinking of. Is that right @sanjayradadiya ?
> 
> if this is okay, I will go with it. Because of adding the `roleId`, we need to change a lot of files and need a solution to deal with the legacy roles. By storing a role object from the begining, I think we don't need to add a roleId 🤔

I did this same thing before like whenever game loaded i was checking for role id and if not exists then creating id and save that id inside db and after all dispatch update wargame will replace roleid everywhere.

**Comment by IanMayo** [comment]
Yes, thanks @sanjayradadiya 

This task extends further than the player UI.   I want us to create and store a unique Role-Id right from when the role is created in the game admin pages into the wargame document.   Also, when we define channels, I want us to store the role role-id in the channel, not the whole role object.  We currently store the whole role in there, which doesn't allow for role name or permissions to change.

![image](https://user-images.githubusercontent.com/1108513/123943675-4cb13080-d994-11eb-9b65-26bdb3b91cae.png)

Should be:
![image](https://user-images.githubusercontent.com/1108513/123943847-6eaab300-d994-11eb-99e0-5073a2ad508a.png)

**Comment by IanMayo** [comment]
This is done.
