### ISSUE TITLE
Walkthrough Experiece

### ISSUE THREAD

**Issue by ShendMikullovci** [serge-web/serge#823]
🐞 Some minor issues on the Walkthrough part that should be addressed. 

![INTRO TIP - DRAG AND DROP](https://user-images.githubusercontent.com/85491794/121206861-17c02b00-c879-11eb-9497-5cff1f8057cd.png)

In this screen, for a new user like myself, it was difficult to understand what tab I'm supposed to drag and where I'm supposed to drop it. It would help if, similar to the other Intro tips, the surrounding irrelevant area would dim in color and brightness, and the relevant tab that can be dragged & dropped be lit up to capture the players' attention.  

**From Ian:** we won't know the name/label of the top-left tab, since they can change for each game.  But, we could try to find the first displayed tab, and highlight that.

![INTRO TIP - GAME PHASE PANEL](https://user-images.githubusercontent.com/85491794/121207506-9fa63500-c879-11eb-8c4e-d90b2319e0c3.png)

In this screen, the tip suggests that the panel on the top right indicates the phases of the game, but the panel itself is dim. Brightening the right-hand panel while maintaining the surrounding area dark would efficiently direct the players' attention to the relevant area.

**From Ian:** Yes - we should try to highlight the Game Control panel at the top-right.  The tutorial is _probably_ trying to do that, but the control ID may have changed when we switched to _components_.

![INTRO TIP - OUT OF GAME MESSAGES AND QUESTIONS](https://user-images.githubusercontent.com/85491794/121207962-ff9cdb80-c879-11eb-9a11-e9c1c36fb48b.png)

In this screen, I didn't understand where to actually type the out-of-game message/questions. Indicate the area where the message is to be typed by brightening that area.

**From Ian:** Again - we just need to highlight the Game-Admin channel on the right-hand side.

![INTRO TIP - TARGET ICON](https://user-images.githubusercontent.com/85491794/121208200-2d822000-c87a-11eb-91e5-d82cecc614ab.png)

In this screen, it would be better to show the target icons using the same brightness technique as for the previous screens.

**From Ian:** Yes, we should highlight the area at the bottom-right of the screen.

I'm at your disposal for any further information or clarifications.

**Comment by IanMayo** [comment]
Ian > check issue is self-describing
