### ISSUE TITLE
UI element to trigger new walkthrough

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#840]
Brand new users of Serge are invited to do a walkthrough of the UI.

There isn't a way of triggering this walkthrough at a later date.

We should add some button/element to the player interface to trigger the walkthrough to restart.

We should describe this button in the walkthrough, probably near the start.

Which icon?  We could extend the concept of `walking` the `walkthrough` with these walking icons:
![image](https://user-images.githubusercontent.com/1108513/122238747-49a84180-ceb8-11eb-81cc-dc55595c709a.png)

[Here](https://fontawesome.com/v5.15/icons?d=gallery&p=2) is the full library of icons that are available to us.

Hmm, where would icon go?  Here is link into game: https://serge-review.herokuapp.com/?wargame=wargame-koiquada&access=pkoiqu5ev

It _could_ go near the top-right, where we have `feedback` and `heart` icons.  If we're adding a third icon, we should probably put all three into a panel.

![image](https://user-images.githubusercontent.com/1108513/122239199-a99ee800-ceb8-11eb-938e-b05698821847.png)

**Comment by ShendMikullovci** [comment]
A great feature to add to the game. It’s important to know whether our target audience identifies and understands the word “walk-through” the same way we do.

Thesaurus definition of “walk-through”: "a step-by-step demonstration of a procedure or process or a step-by-step explanation of it as a novice attempts it." (Source: https://www.dictionary.com/browse/walk-through, 18/06/2021).

The following icons fit the definition: 
![Step Icon](https://user-images.githubusercontent.com/85491794/122536937-58f8cd80-d025-11eb-9de6-89172ca6f5af.png)

A clear indication of the “step-by-step” fragment of the definition. The last icon specifically implies a movement as well, further emphasizing the term “walk-through”.


![Walking Icon](https://user-images.githubusercontent.com/85491794/122537089-7fb70400-d025-11eb-9f29-5ce8442e1d14.png)

These icons also visually match the term “walk-through”, however, they are used in rather different scenarios in daily life, which might lead to confusion (i.e., pedestrian traffic lights, public restrooms, etc.). 


It’s also important to note that in video game design and game-play, the terms often synonymous for walk-through are  “training”, “practice”. These terms are more direct and objective. However, they give a sense of agency and control: When one clicks on the “Training” button, one expects to train actively. Our walk-through is mostly a passive experience where the user is guided through the important information. 

Another term used in video game design and game-play is “tutorial” which would also fit our requirements. The term “tutorial” implies learning and guidance, similar to “walk-through” and unlike “training” or “practice”, it doesn’t present a sense of agency/control. It could be a potential replacement or plan B for the term “walk-through”.

THESAURUS: “a manual explaining how to use a particular software package or computer system.” (Source: https://www.dictionary.com/browse/tutorial, 18/06/2021).

In this case, the following icons would apply:
![Education icons](https://user-images.githubusercontent.com/85491794/122537368-c73d9000-d025-11eb-811f-ecb71a77e06c.png)

This set of icons especially applies if we decide to move forward with the “manual” definition of “tutorial”.

![Teach icons](https://user-images.githubusercontent.com/85491794/122537437-d91f3300-d025-11eb-85f4-0485bd580db9.png)

This set of icons applies if we decide to imply a definition based upon instructing, educating or guiding the players.

As for the location of the icon, two possibilities:

1. We put the icon next to the feedback and heartbeat icons. Could create clutter so like you said, we would have to create a panel or tab, which is extra work. We also don't know how adding an extra tab would look like for the players, given that the display has plenty of tabs already. The screen would have to look simple and approachable.
2. We replace the heartbeat icon with the walk-through icon, IF the heartbeat icon is placed at the bottom end of the screen, next to "App: Serge/Client". Eliminates clutter and is easily accessible.

**Comment by IanMayo** [comment]
That's all great, thanks @ShendMikullovci 

* Yes for **Tutorial**
* Yes for **Replace heartbeat with walk-through (tutorial) and move heartbeat to bottom-left**

**Comment by IanMayo** [comment]
Covered by #846
