### ISSUE TITLE
Avoid deprecated library

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#854]
When the app runs in the dev mode (:3000), we get this warning:
![image](https://user-images.githubusercontent.com/1108513/122639994-dd665180-d0f4-11eb-8222-04c9bc51e799.png)

Here's the link: https://developer.chrome.com/blog/enabling-shared-array-buffer/

I don't really understand it, but am concerned something may break next month.

We should investigate the issue, and see if it's in our code (and we fix it), or an upstream dependancy (so we update dependency).

**Comment by sanjayradadiya** [comment]
@IanMayo I just see this solution and its working after upgrade react and react-dom version.

https://stackoverflow.com/a/66763874/6536418

![image](https://user-images.githubusercontent.com/16476120/123419609-0ba5ce80-d5d8-11eb-8c17-027ee86bf239.png)
