### ISSUE TITLE
Looks like server pings are too frequent

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#858]
The app is set to ping the server every 5 seconds (5000 millis).

But, the console log shows the server being pinged much frequently, though not at an apparent regular interval.

For this logging, I'm not making any UI interactions, we're just seeing the server pings.

![screencast](https://i.gyazo.com/9bc073a354a489b0982e04e2dd876dbf.gif)

**Comment by sanjayradadiya** [comment]
Currently, i am not able to recreate it on my side so just try again with steps so i can try accordingly.

Please test #861 as well may this issue would be fixed along with

**Comment by IanMayo** [comment]
This behaviour no longer happens on my browser. Closing.
