### ISSUE TITLE
Display formatted messages in read-only editor

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#868]
Templates are provided for some messages:
![image](https://user-images.githubusercontent.com/1108513/123266775-3c143c80-d4f4-11eb-809a-0f7fe097d1b5.png)

These structure the information, and lead the player through what to enter.

But, when we display the message for other players, it's just `word-soup`.  The JSON is sorted in alphabetical order, rather than the original order:
![image](https://user-images.githubusercontent.com/1108513/123267112-8d243080-d4f4-11eb-8777-120c35bd0330.png)

We may have a better way of presenting the information.  If we presented it in a read-only version of the original editor then it will keep the original information layout.

So, for `ChannelMessageDetail` - we'll look for the message type. Then we'll create an instance of the editor form, insert the message payload, and mark the editor as read-only.

**Comment by lebaphi** [comment]
![image](https://user-images.githubusercontent.com/26705621/124211229-f6202f80-db16-11eb-9663-49f29381178d.png)

Hi @IanMayo , I'm working on this, I can load the editor with the message 🤔

**Comment by IanMayo** [comment]
Great - well done. Can you do it in a branch/PR, so we can have a look?

I think we need to work on:
* simplification: remove UI elements that aren't required in read-only mode - via options or CSS
* compactness: try to take steps to reduce whitespace - so users see more of message on screen at once.

**Comment by IanMayo** [comment]
Done.
