### ISSUE TITLE
Make icon for overflow menu more vivid

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#907]
Some (older) users didn't spot the tab overflow menu (`>>`). 

It's dark-grey on dark-blue.
![image](https://user-images.githubusercontent.com/1108513/124175705-d56bc180-daa5-11eb-9f74-e84e9421e773.png)

We should probably make it a bit larger, and a lighter shade of grey.

**Comment by IanMayo** [comment]
Re-opening.

@lebaphi - actually, could you make the maximise button more vivid too.

As I discussed in #920  - there could be situations when maximise could be useful.  Plus, the issue that #920 fixes may not have happened if the maximise button was more visible.

**Comment by lebaphi** [comment]
oka @IanMayo 👌

**Comment by IanMayo** [comment]
Sorted, in #926
