### ISSUE TITLE
Message opened/read indicator

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#911]
"It would be useful to have an indication that messages that have been sent have been opened/read"

This is _technically_ possible.  It may introduce clutter if we're adding the names of lots of roles for messages that are seen by many players.

To be considered.

**Comment by IanMayo** [comment]
Closed in #933

**Comment by IanMayo** [comment]
Oops, wasn't closed. That was a separate issue.

**Comment by ShendMikullovci** [comment]
Great feature idea! It’s also important to know a few things beforehand:
Privacy: Will Game Control want the players to know that they (GC) have viewed their (Players) messages and vice-versa?

Who absolutely needs to see what and in which channels? 

For me, as a player, do I need to know that everybody has seen my messages? Or do I only need to know about a specific group of people? 

Answering these correctly would help with clutter avoidance and improve design.

**Comment by IanMayo** [comment]
Thanks for the contribution Shend. For the current wargame(s), the cost of adding this support does not match the benefit to the players.  But, we'll retain the issue, in case it becomes of greater value in the future.
