### ISSUE TITLE
As a Game Designer I need to be able to specify a start time for a wargame

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#952]
The admin pages have an overview tab:
![image](https://user-images.githubusercontent.com/1108513/126645354-e1b50d7f-d918-426d-9ef7-e98fb0607684.png)

This should allow the designer to specify the start date-time, to be stored in field `overview.gameDate`

**Comment by lebaphi** [comment]
Hi @IanMayo, I see currently we allow the designer to input the wargame turn time as a format `DD HH MM SS`, right?

**Comment by IanMayo** [comment]
That is the size of each step/turn.

In this issue we need to set the date/time for the start of the game.   @sanjayradadiya added a date-time control in his recent [PR](https://github.com/serge-web/serge/pull/940/files#diff-5aae42db3cea01fa29e6c3b68c3c08098e2be259835da190d09dd573f1107d82R14) - we should probably re-use that control.

Note: you may have to re-use the ["trick"](https://github.com/serge-web/serge/pull/940/files#r672264190)he did for flatpickr.
