### ISSUE TITLE
As Game Manager I want to control how turns are presented

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#955]
Past games have used a `natural` turn numbering system: `0, 1, 2, 3, 4` (where turn-zero is spent preparing to play).

For the next wargame, unusually the turns will be run in pairs, so it will be `0.1, 0.2, 1.1, 1.2, 2.1, 2.2`.

In the `Overview` tab of `Admin` pages, we should introduce an optional `Turn Presentation` drop-down list, with this values/labels:
* `natural`: `Natural (0, 1, 2, 3)`
* `turn-pair numbers`: `Turn-pair numbers (0.1, 0.2, 1.1, 1.2)`
* `turn-pair letters`: `Turn-pair letters (0.a, 0.b, 1.a, 1.b)`

The data will be stored in an optional `turnPresentation` element that takes one of the two above values.   I guess they should be enums in TS, so we can grow them in a controlled way in the future.

I don't think we will have to change the actual turn numbering, we just cosmetically change what is displayed if there is a value in `turnPresentation` that is not `natural`.

This logic will convert `i` from natural to turn-pair numbers: 
```
Math.floor(i / 2) + '.' + (i % 2 ? 1 : 0)
```

This logic will convert `i` from natural to turn-pair letters: 
```
Math.floor(i / 2) + '.' + (i % 2 ? b : a )
```

The number rendering will happen in these places:
* Status bar at top-right
* In-channel turn markers
* Wargame Export (check for non-'natural' value in `overview.turnPresentation`, and render turn number column if necessary).

**Note:** in this modification we should also allow the Game Manager to set the starting turn number. This functionality would also be used to set the _current_ turn number part-way through a game.  The turn number will use the `natural` numbering above.

**Comment by IanMayo** [comment]
@ShendMikullovci : if/when you work on the new layout for the `Game Overview` page, it would be useful to include the above two controls in the design please: 
* the current turn number
* the Turn Presentation option (just a drop-down with the above two labels.

**Comment by ShendMikullovci** [comment]
> @ShendMikullovci : if/when you work on the new layout for the `Game Overview` page, it would be useful to include the above two controls in the design please:
> 
> * the current turn number
> * the Turn Presentation option (just a drop-down with the above two labels.

Yes! I’ve added the required controls (i.e., Turn number & Turn Presentation) onto the overview page. Refer to issue #954.
