### ISSUE TITLE
Snapshot for RFI Status Board keeps changing

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge#972]
Our `yarn test:unit` is repeatedly failing due to the RFI-Status-Board snapshot file.  A numbered CSS class keeps changing.
https://github.com/serge-web/serge/pull/969/commits/47f646f89b19050596ecc6c1d0c3ba4f8ebc68bb

Can we configure this file/test to ignore the numbers in the `makestyles`?

**Comment by lebaphi** [comment]
Hi @IanMayo, yes we can customize the `generateClassName ` to make it does not include the `ruleCounter `, so the className will not include the number as well. I tried to reproduce this issue but the tests are always passed :D

**Comment by IanMayo** [comment]
Great - could you create a PR that does that please?

**Comment by lebaphi** [comment]
I will create it soon, can you show me how to make the `rfi-status-board` snapshot failed on the `yarn test-unit`, It's always passed on my machine :D

**Comment by IanMayo** [comment]
This history of changes to the snapshot shows how many changes it has been through:
https://github.com/serge-web/serge/commits/develop/packages/components/src/local/rfi-status-board/__snapshots__

**Comment by lebaphi** [comment]
We have a PR @IanMayo
